"""Oracle-fidelity regression for Holtslag-Boville turbulence.

Locks in the match between ``hb_diffusivities`` (the faithful JAX port) and
the E3SM/CAM ``hb_diff.F90`` (``eddy_scheme='HB'``) + ``pbl_utils.F90``
Fortran oracle.  The oracle reference values below were produced by
compiling the UNMODIFIED E3SM Fortran into a standalone driver and feeding
it the identical column + prescribed kinematic surface fluxes; the build +
comparison harness lives in
``.physics-validator/holtslag_boville/`` (oracle/build.sh, compare.py).

We drive the diffusivity core with the SAME prescribed surface fluxes the
oracle receives (so this tests the PBL-height + K-profile + countergradient
algorithm, not the bulk-flux closure).  Columns:

* convective  -- Wangara-style: ~1 km mixed layer, strong upward heat flux.
* stable      -- GABLS1-style: surface cooling, stable lapse, low-level jet.
* neutral     -- well-mixed theta, zero surface buoyancy flux.

Tolerances absorb the documented smooth-blend-vs-hard-switch gap (the
oracle's hard ``if`` switches are replaced by sigmoid blends; PBLH matches
to <1 %, K-profile peaks to ~5 % in the neutral edge case where a 0.6 %
PBLH offset is cubed into the ``fak1 = u*·h·vk`` amplitude).
"""

from __future__ import annotations

import numpy as np
import pytest

import jax
import jax.numpy as jnp

from legoesm import constants
from legoesm.atmosphere.physics._shared import virtual_temperature
from legoesm.atmosphere.physics.turbulence.config import HoltslagBovilleConfig
from legoesm.atmosphere.physics.turbulence.holtslag_boville import (
    hb_diffusivities,
    holtslag_boville_turbulence,
)

G = constants.g
CPAIR = constants.c_pd
VK = constants.kappa_vk
RAIR = constants.R_d
ZVIR = 1.0 / constants.epsilon - 1.0
USTAR_MIN = 0.01
NLEV = 48

# E3SM hb_diff.F90 (eddy_scheme='HB') oracle reference values, per column.
# Generated by .physics-validator/holtslag_boville/compare.py.
ORACLE = {
    "convective": dict(pblh=1009.48, km_peak=83.486, kh_peak=118.110, cgs_peak=0.00605),
    "stable":     dict(pblh=216.73,  km_peak=0.084,  kh_peak=0.084,   cgs_peak=0.0),
    "neutral":    dict(pblh=7092.72, km_peak=108.754, kh_peak=108.754, cgs_peak=0.0),
}


def _build_column(kind):
    sig_half = np.linspace(0.01, 1.0, NLEV + 1)
    p_s = 1.0e5
    p_half = sig_half * p_s
    p_mid = 0.5 * (p_half[:-1] + p_half[1:])
    z_half = -8000.0 * np.log(np.clip(sig_half, 1e-6, None))
    z_mid = 0.5 * (z_half[:-1] + z_half[1:])
    exner = (p_mid / 1e5) ** (RAIR / CPAIR)

    if kind == "convective":
        theta = np.where(z_mid < 1000.0, 301.0,
                         np.where(z_mid < 1100.0, 301.0 + 0.03 * (z_mid - 1000.0),
                                  304.0 + 0.003 * (z_mid - 1100.0)))
        q = np.full(NLEV, 0.006)
        u = np.full(NLEV, 5.0); v = np.zeros(NLEV)
        shflx, qflx, taux, tauy = 150.0, 5.0e-5, 0.04, 0.0
    elif kind == "stable":
        theta = 265.0 + 0.01 * z_mid
        q = np.full(NLEV, 0.001)
        u = np.full(NLEV, 8.0); v = np.zeros(NLEV)
        shflx, qflx, taux, tauy = -20.0, 0.0, 0.06, 0.0
    elif kind == "neutral":
        theta = np.full(NLEV, 290.0)
        q = np.full(NLEV, 0.004)
        u = np.full(NLEV, 10.0); v = np.zeros(NLEV)
        shflx, qflx, taux, tauy = 0.0, 0.0, 0.08, 0.0
    else:
        raise ValueError(kind)
    T = theta * exner
    return dict(p_mid=p_mid, p_half=p_half, z_mid=z_mid, z_half=z_half,
                theta=theta, T=T, q=q, u=u, v=v,
                shflx=shflx, qflx=qflx, taux=taux, tauy=tauy)


def _surface_scalars(col):
    T = col["T"]; theta = col["theta"]; q = col["q"]; p_mid = col["p_mid"]
    rho_bot = p_mid[-1] / (RAIR * T[-1])
    rrho = 1.0 / rho_bot
    ustar = max(np.sqrt(np.sqrt(col["taux"] ** 2 + col["tauy"] ** 2) * rrho), USTAR_MIN)
    khfs = col["shflx"] * rrho / CPAIR
    kqfs = col["qflx"] * rrho
    ths = theta[-1]
    thvs = ths * (1.0 + ZVIR * q[-1])
    kbfs = khfs + ZVIR * ths * kqfs
    kbfs_signed = kbfs + np.sign(kbfs) * 1e-10 + (kbfs == 0) * 1e-10
    obklen = -thvs * ustar ** 3 / (G * VK * kbfs_signed)
    return dict(ustar=ustar, khfs=khfs, kbfs=kbfs, obklen=obklen)


def _run_core(col, sfc):
    u = jnp.array(col["u"][None, :]); v = jnp.array(col["v"][None, :])
    theta = jnp.array(col["theta"][None, :]); q = jnp.array(col["q"][None, :])
    thv = virtual_temperature(theta, q)
    z_full = jnp.array(col["z_mid"][None, :])
    z_half = jnp.array(col["z_half"][None, :])
    p_full = jnp.array(col["p_mid"][None, :])
    dz_half = jnp.clip(jnp.abs(z_full[:, :-1] - z_full[:, 1:]), 1.0, None)
    dvdz2 = jnp.maximum((u[:, :-1] - u[:, 1:]) ** 2 + (v[:, :-1] - v[:, 1:]) ** 2, 1e-36)
    s2 = dvdz2 / dz_half ** 2
    thv_sum = thv[:, :-1] + thv[:, 1:]
    n2 = G * 2.0 * (thv[:, :-1] - thv[:, 1:]) / (jnp.clip(thv_sum, 1.0, None) * dz_half)
    Ri = n2 / s2
    Km, Kh, gamma, h_pbl, wstar, wm = hb_diffusivities(
        u, v, thv, z_full, z_half, p_full, s2, Ri,
        jnp.array([sfc["ustar"]]), jnp.array([sfc["khfs"]]),
        jnp.array([sfc["kbfs"]]), jnp.array([sfc["obklen"]]),
        HoltslagBovilleConfig(),
    )
    khfs = float(sfc["khfs"])
    cgs = np.array(gamma[0]) / khfs if abs(khfs) > 1e-12 else np.zeros_like(np.array(gamma[0]))
    return dict(h_pbl=float(h_pbl[0]), km=np.array(Km[0]), kh=np.array(Kh[0]), cgs=cgs)


@pytest.mark.parametrize("kind", ["convective", "stable", "neutral"])
def test_pblh_matches_oracle(kind):
    col = _build_column(kind)
    sfc = _surface_scalars(col)
    out = _run_core(col, sfc)
    ref = ORACLE[kind]["pblh"]
    rel = abs(out["h_pbl"] - ref) / max(ref, 1.0)
    assert rel < 0.02, (
        f"HB PBLH ({kind}) = {out['h_pbl']:.2f} m vs E3SM oracle {ref:.2f} m "
        f"(rel.err {rel:.3f} > 0.02)"
    )


@pytest.mark.parametrize("kind", ["convective", "stable", "neutral"])
def test_k_profile_peak_matches_oracle(kind):
    col = _build_column(kind)
    sfc = _surface_scalars(col)
    out = _run_core(col, sfc)
    km_ref = ORACLE[kind]["km_peak"]
    kh_ref = ORACLE[kind]["kh_peak"]
    # 6% band: the neutral edge case amplifies a 0.6% PBLH offset into the
    # K amplitude via fak1 = u*·h·vk; convective/stable match to <0.1%.
    assert abs(out["km"].max() - km_ref) / max(km_ref, 1e-3) < 0.06, (
        f"HB Km peak ({kind}) = {out['km'].max():.3f} vs oracle {km_ref:.3f}"
    )
    assert abs(out["kh"].max() - kh_ref) / max(kh_ref, 1e-3) < 0.08, (
        f"HB Kh peak ({kind}) = {out['kh'].max():.3f} vs oracle {kh_ref:.3f}"
    )


def test_countergradient_matches_oracle_convective():
    col = _build_column("convective")
    sfc = _surface_scalars(col)
    out = _run_core(col, sfc)
    ref = ORACLE["convective"]["cgs_peak"]
    assert abs(out["cgs"].max() - ref) / ref < 0.02, (
        f"HB countergradient cgs peak = {out['cgs'].max():.5f} vs oracle {ref:.5f}"
    )


def test_countergradient_zero_in_stable():
    """No nonlocal countergradient when the surface buoyancy flux is <= 0."""
    col = _build_column("stable")
    sfc = _surface_scalars(col)
    out = _run_core(col, sfc)
    assert np.max(np.abs(out["cgs"])) < 1e-6


def test_full_scheme_runs_and_is_finite():
    """End-to-end scheme (bulk-flux closure + diffusion) stays finite."""
    col = _build_column("convective")
    ncol = 1
    args = [
        jnp.array(col["u"][None, :]), jnp.array(col["v"][None, :]),
        jnp.array(col["T"][None, :]), jnp.array(col["q"][None, :]),
        jnp.array(col["p_mid"][None, :]), jnp.array(col["p_half"][None, :]),
        jnp.array(col["z_mid"][None, :]), jnp.array(col["z_half"][None, :]),
        jnp.array([col["T"][-1] + 4.0]), jnp.array([col["q"][-1] + 0.01]),
        jnp.array((col["p_mid"] / (RAIR * col["T"]))[None, :]),
    ]
    out = holtslag_boville_turbulence(*args, 300.0, HoltslagBovilleConfig())
    for arr in (out.du_dt, out.dv_dt, out.dT_dt, out.dq_v_dt, out.Km, out.Kh, out.h_pbl):
        assert jnp.all(jnp.isfinite(arr))
    assert 100.0 < float(out.h_pbl[0]) < 4000.0  # physical convective PBL


def test_grad_finite_through_full_scheme():
    """jax.grad of a scalar loss is finite for all stratification inputs."""
    col = _build_column("stable")  # stable -> exercises the cube-root / sqrt edges
    base = [
        jnp.array(col["u"][None, :]), jnp.array(col["v"][None, :]),
        jnp.array(col["T"][None, :]), jnp.array(col["q"][None, :]),
        jnp.array(col["p_mid"][None, :]), jnp.array(col["p_half"][None, :]),
        jnp.array(col["z_mid"][None, :]), jnp.array(col["z_half"][None, :]),
        jnp.array([col["T"][-1] - 2.0]), jnp.array([col["q"][-1]]),
        jnp.array((col["p_mid"] / (RAIR * col["T"]))[None, :]),
    ]

    def loss(T):
        a = list(base); a[2] = T
        o = holtslag_boville_turbulence(*a, 300.0, HoltslagBovilleConfig())
        return jnp.sum(o.dT_dt ** 2) + jnp.sum(o.h_pbl)

    g = jax.grad(loss)(base[2])
    assert jnp.all(jnp.isfinite(g))


def test_grad_matches_finite_difference():
    """AD gradient w.r.t. surface T matches a centered finite difference.

    Verifies gradient CORRECTNESS (not just finiteness) where the scheme has
    a broad, non-trivial sensitivity: the surface temperature drives the
    bulk fluxes -> kbfs -> the whole convective K-profile + PBL height.
    """
    col = _build_column("convective")
    base = [
        jnp.array(col["u"][None, :]), jnp.array(col["v"][None, :]),
        jnp.array(col["T"][None, :]), jnp.array(col["q"][None, :]),
        jnp.array(col["p_mid"][None, :]), jnp.array(col["p_half"][None, :]),
        jnp.array(col["z_mid"][None, :]), jnp.array(col["z_half"][None, :]),
        jnp.array([col["T"][-1] + 4.0]), jnp.array([col["q"][-1] + 0.01]),
        jnp.array((col["p_mid"] / (RAIR * col["T"]))[None, :]),
    ]

    def loss(T_sfc):
        a = list(base); a[8] = T_sfc
        o = holtslag_boville_turbulence(*a, 300.0, HoltslagBovilleConfig())
        return jnp.sum(o.dT_dt ** 2) * 1e6 + jnp.sum(o.h_pbl)

    T_sfc = base[8]
    g_ad = float(jax.grad(loss)(T_sfc)[0])
    eps = 1e-3
    g_fd = float((loss(T_sfc + eps) - loss(T_sfc - eps)) / (2 * eps))
    rel = abs(g_ad - g_fd) / (abs(g_fd) + 1e-8)
    assert rel < 1e-4, f"AD grad {g_ad:.6e} vs FD {g_fd:.6e} (rel {rel:.2e})"
