#!/usr/bin/env python
"""Feature-degraded MPAS baseline for the global overturning experiment.

A first-cut MPAS counterpart to the lat-lon
``run_global_overturning_implicit_spinup.py`` working run, with three
explicit feature gaps relative to the lat-lon reference:

  - **No GM/Redi.**  The MPAS port of ``gm_redi_latlon_cgrid.py`` does
    not yet exist; ``MPASOceanConfig`` has no ``gm_redi`` field.  This
    means the deep stratification and MOC will be set by spurious
    numerical mixing at this resolution rather than by the
    parameterized eddy transfer, so this run is **not** a quantitative
    comparison to the lat-lon ``50yr_implicit`` MOC.
  - **No implicit Crank-Nicolson barotropic solver.**  ``MPASOceanConfig``
    has no ``barotropic_solver`` field; the MPAS path uses the explicit
    forward-backward subcycling barotropic substeps.  Whether that
    produces an analogue of the lat-lon C-grid Coriolis null-mode noise
    is precisely one of the things this run is meant to reveal.
  - **No convective adjustment.**  ``make_mpas_ocean_physics`` does not
    yet route the ``convection='enhanced_diffusion'`` scheme; it is
    silently dropped (with a RuntimeWarning) when the OceanPhysicsConfig
    is fed to the MPAS physics factory.  The lat-lon reference relies
    on ``K_conv=1.0`` to sink cold surface water generated by SST
    restoring at high latitudes.  Without this on MPAS, statically
    unstable columns are not relieved by the physics; expect different
    deep-water behaviour and possibly inverted stratification at high
    latitudes.  Only the constant background ``A_v`` / ``K_v`` are
    applied (these go through ``MPASOceanConfig`` directly, not the
    physics factory, and are unaffected).

Goal: confirm the MPAS dycore + global wind + SST restoring chain
stands up at multi-year timescales, on a global ico4 mesh (~4°, 2562
cells), with sensible gyre + Drake-band response.  Once stable, the
follow-on ports (GM/Redi on MPAS; implicit barotropic on MPAS) can use
this as the baseline against which the parameterizations are added.

Inner stepping uses the same ``lax.scan`` + JIT block pattern as the
lat-lon spinup driver.

Outputs (results/ocean/global_overturning_mpas_baseline/):
  - restart_day{000000,000365,...}.npz — every 1 sim-yr
  - run.log — captured by the runner

Usage:
    JAX_ENABLE_X64=1 python scripts/run/global_overturning/run_global_overturning_mpas_baseline.py
"""

from __future__ import annotations

import argparse
import os
import sys
import time
from functools import partial
from pathlib import Path

import numpy as np
import jax
import jax.numpy as jnp

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "matrix"))
os.environ.setdefault("JAX_ENABLE_X64", "1")

from legoesm.ocean.vertical import create_ocean_z_star
from legoesm.grids.voronoi import create_voronoi_mesh
from legoesm.ocean.dynamics.ocean_model_mpas import MPASOceanModel
from legoesm.ocean.experiments.global_overturning import (
    GlobalOverturningConfig, create_initial_conditions, create_forcings,
    create_eos_config, global_overturning_mpas_model_config,
)


OUTPUT_DIR = Path("results/ocean/global_overturning_mpas_baseline")

# ico4 is the closest match to lat-lon 36×72 (5°): ~4° spacing, 2562 cells.
MPAS_SUBDIVISION_LEVEL = 4

# Lesson from scripts/matrix/ocean_test_matrix/experiments.py:run_global_barotropic_wind:
# "MPAS ico3 needs higher viscosity than lat-lon at comparable resolution —
#  the TRiSK discretization on irregular cells requires more dissipation
#  to remain stable with correct bottom drag."  Apply the same floor here.
MPAS_A_H_FLOOR = 5.0e5

# CFL: matrix uses dt=300s on ico3 (~8°).  ico4 halves cell size, so halve dt.
DT = 200.0


def _save_restart(state, day, output_dir):
    npz = {"step": int(round(day * 86400 / DT)), "time_days": float(day),
           "grid_type": "mpas",
           "mpas_subdivision_level": MPAS_SUBDIVISION_LEVEL}
    for f in state._fields:
        obj = getattr(state, f)
        if obj is None or not hasattr(obj, "data"):
            continue
        npz[f] = np.asarray(obj.data)
    fname = output_dir / f"restart_day{int(round(day)):06d}.npz"
    np.savez_compressed(fname, **npz)
    print(f"    Restart saved: {fname.name}")


def _make_step_block(model, dt):
    """JIT-compiled n-step scan of model.step (no diagnostic capture)."""
    def scan_body(state, _):
        return model.step(state, dt), None

    @partial(jax.jit, static_argnames=("n_inner",))
    def block_fn(state, n_inner: int):
        state, _ = jax.lax.scan(scan_body, state, None, length=n_inner)
        return state

    return block_fn


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--years", type=float, default=5.0,
                        help="Total simulation years (default: 5)")
    parser.add_argument("--restart-every-years", type=float, default=1.0,
                        help="Restart save cadence (default: 1 yr)")
    parser.add_argument("--baro-u-viscosity", type=float, default=0.0,
                        help="Barotropic-mode lateral viscosity on u_bar "
                             "[m^2/s].  Damps the TRiSK rotational null "
                             "branch (Thuburn 2008; Ringler et al. 2010).  "
                             "Default 0 (disabled, baseline behavior).  "
                             "Try 1e3-1e4 on ico4 (~460 km cells) to test "
                             "whether the null-branch noise is responsible "
                             "for the diagnosed ⟨v_t(u_bar)⟩ residual.")
    parser.add_argument("--barotropic-solver", default="explicit_substep",
                        choices=("explicit_substep", "implicit_cn"),
                        help="Barotropic solver. ``explicit_substep`` "
                             "(default) uses forward-backward subcycling "
                             "with cosine filter — the baseline that "
                             "exhibits the TRiSK null-branch noise.  "
                             "``implicit_cn`` uses single-step Crank-"
                             "Nicolson with PCG Helmholtz solve, "
                             "eliminating the chequerboard mode by "
                             "construction (issue: barotropic_mode_noise).")
    args = parser.parse_args()

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # ---- Configuration ----
    total_years = args.years
    dt = DT
    n_steps = int(total_years * 365.0 * 86400 / dt)
    block_size = 1000
    restart_every_years = args.restart_every_years
    n_steps_per_restart = int(restart_every_years * 365.0 * 86400 / dt)

    # use_gm_redi defaults to False; we leave it at the default and do
    # NOT call create_gm_redi_config — MPAS has no gm_redi support yet.
    config = GlobalOverturningConfig()
    z_coord = create_ocean_z_star(
        n_levels=config.n_levels, H_max=config.H_max,
        dz_surface=config.dz_surface, dz_deep=config.dz_deep,
    )
    mesh = create_voronoi_mesh(MPAS_SUBDIVISION_LEVEL)
    physics = create_forcings("mpas", mesh, config)
    eos_config = create_eos_config(config)

    # A_h: lift to MPAS floor; report both values so the deviation from
    # the lat-lon reference (config.A_h = 2e5) is visible in the log.
    a_h_used = max(config.A_h, MPAS_A_H_FLOOR)

    ocean_config = global_overturning_mpas_model_config(
        config, physics=physics, eos_config=eos_config,
        A_h=a_h_used,                                   # lifted to MPAS A_h floor
        barotropic_u_viscosity=args.baro_u_viscosity,
        barotropic_solver=args.barotropic_solver,
    )

    print(f"=== MPAS baseline: {total_years:g}-year fresh spinup (no GM/Redi) ===")
    print(f"  Output: {OUTPUT_DIR}")
    print(f"  Mesh: ico{MPAS_SUBDIVISION_LEVEL} "
          f"(nCells={int(mesh.lonCell.shape[0])}, ~4° equivalent)")
    print(f"  Vertical: {config.n_levels} levels, H_max={config.H_max} m")
    print(f"  dt = {dt} s, n_steps = {n_steps:,}")
    print(f"  Block size: {block_size}  ({n_steps // block_size} blocks)")
    print(f"  A_h = {a_h_used:.1e} m²/s "
          f"(lat-lon ref uses {config.A_h:.1e}; MPAS floor={MPAS_A_H_FLOOR:.0e})")
    print(f"  A_v = {config.A_v:.1e}, K_v = {config.K_v:.1e}, "
          f"bottom_drag_r = {config.bottom_drag_coeff:.4f}")
    print(f"  GM/Redi: DISABLED (no MPAS port yet)")
    if ocean_config.barotropic_solver == "implicit_cn":
        print(f"  Barotropic solver: implicit Crank-Nicolson "
              f"(θ_eta=θ_pgf={ocean_config.barotropic_implicit_theta_eta}, "
              f"PCG tol={ocean_config.barotropic_implicit_pcg_tol:.0e})")
    else:
        print(f"  Barotropic solver: explicit subcycle "
              f"(n_barotropic_substeps={ocean_config.n_barotropic_substeps})")
    print(f"  Barotropic u_bar viscosity: "
          f"{ocean_config.barotropic_u_viscosity:.1e} m²/s "
          f"({'enabled' if ocean_config.barotropic_u_viscosity > 0 else 'disabled'})")
    print(f"  Restart cadence: every {restart_every_years:g} yr "
          f"({n_steps // n_steps_per_restart} mid-run + 1 final)")
    print()

    model = MPASOceanModel(mesh, z_coord, ocean_config)
    state = create_initial_conditions("mpas", mesh, z_coord, config)
    print(f"Initial state (rest, stratified):")
    print(f"  T range: [{float(jnp.min(state.T.data)):.2f}, "
          f"{float(jnp.max(state.T.data)):.2f}] °C")
    print(f"  S uniform: {float(jnp.mean(state.S.data)):.2f} PSU")
    print(f"  |η|max: {float(jnp.max(jnp.abs(state.eta.data))):.3e} m  (rest)")
    print()

    block_fn = _make_step_block(model, dt)

    # Day-0 reference restart
    _save_restart(state, 0.0, OUTPUT_DIR)

    n_blocks = n_steps // block_size
    n_remainder = n_steps - n_blocks * block_size
    print(f"Starting integration ({n_blocks} blocks × {block_size} "
          f"+ {n_remainder} remainder)")
    t0 = time.time()
    last_print = t0

    steps_done = 0
    last_restart_step = 0
    progress_every = max(1, n_blocks // 30)

    for b in range(n_blocks):
        state = block_fn(state, block_size)
        steps_done += block_size

        # Periodic restart
        if (steps_done - last_restart_step) >= n_steps_per_restart:
            jax.block_until_ready(state.eta.data)
            day = steps_done * dt / 86400.0
            _save_restart(state, day, OUTPUT_DIR)
            last_restart_step = steps_done

        # Progress + blowup guard
        if (b + 1) % progress_every == 0 or (b + 1) == n_blocks:
            now = time.time()
            if now - last_print > 30 or (b + 1) == n_blocks:
                jax.block_until_ready(state.eta.data)
                yr = steps_done * dt / 86400.0 / 365.0
                eta_max = float(jnp.max(jnp.abs(state.eta.data)))
                T_max = float(jnp.max(state.T.data))
                T_min = float(jnp.min(state.T.data))
                u_max = float(jnp.max(jnp.abs(state.u.data)))
                elapsed = now - t0
                eta_s = elapsed / yr * total_years - elapsed if yr > 0 else 0
                eta_str = (f"{eta_s/60:.1f} min" if eta_s < 3600
                           else f"{eta_s/3600:.2f} h")
                print(f"  Yr {yr:5.2f}/{total_years:.1f} | "
                      f"|η|max={eta_max:.2e} | "
                      f"T∈[{T_min:.1f},{T_max:.1f}] | "
                      f"|u|max={u_max:.3f} | ETA {eta_str}", flush=True)
                last_print = now

                if not np.isfinite(eta_max) or eta_max > 100.0:
                    print(f"\n  BLOWUP at year {yr:.2f} (|η|max={eta_max}) "
                          f"— saving restart and aborting", flush=True)
                    final_day = steps_done * dt / 86400.0
                    _save_restart(state, final_day, OUTPUT_DIR)
                    return

    if n_remainder > 0:
        state = block_fn(state, n_remainder)
        steps_done += n_remainder

    jax.block_until_ready(state.eta.data)
    wall = time.time() - t0
    final_day = steps_done * dt / 86400.0
    print(f"\nMPAS baseline spinup complete in {wall:.0f}s "
          f"({wall/60:.1f} min, {wall/3600:.2f} h)")
    print(f"  Final state at sim day {final_day:.0f} (year {final_day/365:.2f})")
    print(f"  |η|max = {float(jnp.max(jnp.abs(state.eta.data))):.4e} m")
    print(f"  T range: [{float(jnp.min(state.T.data)):.2f}, "
          f"{float(jnp.max(state.T.data)):.2f}] °C")
    print(f"  |u|max = {float(jnp.max(jnp.abs(state.u.data))):.4e} m/s")

    _save_restart(state, final_day, OUTPUT_DIR)


if __name__ == "__main__":
    main()
