"""Voronoi (MPAS-style) mesh for legoESM.

Implements icosahedral SCVT mesh generation and all required
connectivity/geometry arrays for the TRiSK discretization.

The mesh is a centroidal Voronoi tessellation on the sphere,
generated by recursive bisection of an icosahedron followed by
Lloyd relaxation.

References
----------
- Ringler, T. D., Thuburn, J., Klemp, J. B., & Skamarock, W. C. (2010).
  A unified approach to energy conservation and potential vorticity dynamics
  for arbitrarily-structured C-grids. J. Comput. Phys., 229(9), 3065-3090.
- Thuburn, J., Ringler, T. D., Skamarock, W. C., & Klemp, J. B. (2009).
  Numerical representation of geostrophic modes on arbitrarily structured
  C-grids. J. Comput. Phys., 228(22), 8321-8335.
- Du, Q., Faber, V., & Gunzburger, M. (1999). Centroidal Voronoi
  tessellations. SIAM Review, 41(4), 637-676.
"""

from __future__ import annotations

from typing import NamedTuple

import numpy as np
import jax.numpy as jnp
from scipy.spatial import ConvexHull, SphericalVoronoi

from legoesm import constants


class VoronoiMesh(NamedTuple):
    """MPAS-style Voronoi mesh for TRiSK discretization.

    All arrays use 0-based indexing. Unused entries in variable-length
    connectivity arrays are padded with -1 (integers) or 0.0 (floats).
    """
    # --- Dimensions ---
    nCells: int
    nEdges: int
    nVertices: int
    maxEdges: int       # max edges per cell (6 for hex, 5 for pent)
    vertexDegree: int   # edges per vertex (always 3 for Delaunay dual)
    radius: float

    # --- Cell coordinates (Voronoi generators) ---
    latCell: jnp.ndarray    # (nCells,)
    lonCell: jnp.ndarray    # (nCells,)
    xCell: jnp.ndarray      # (nCells,) Cartesian
    yCell: jnp.ndarray
    zCell: jnp.ndarray

    # --- Edge coordinates (midpoints of Voronoi boundaries) ---
    latEdge: jnp.ndarray    # (nEdges,)
    lonEdge: jnp.ndarray    # (nEdges,)
    xEdge: jnp.ndarray
    yEdge: jnp.ndarray
    zEdge: jnp.ndarray

    # --- Vertex coordinates (Delaunay circumcenters) ---
    latVertex: jnp.ndarray  # (nVertices,)
    lonVertex: jnp.ndarray  # (nVertices,)
    xVertex: jnp.ndarray
    yVertex: jnp.ndarray
    zVertex: jnp.ndarray

    # --- Connectivity (0-indexed, padded with -1) ---
    cellsOnEdge: jnp.ndarray       # (2, nEdges)
    edgesOnCell: jnp.ndarray       # (maxEdges, nCells)
    verticesOnCell: jnp.ndarray    # (maxEdges, nCells)
    verticesOnEdge: jnp.ndarray    # (2, nEdges)
    edgesOnVertex: jnp.ndarray     # (vertexDegree, nVertices)
    cellsOnVertex: jnp.ndarray     # (vertexDegree, nVertices)
    cellsOnCell: jnp.ndarray       # (maxEdges, nCells)
    edgesOnEdge: jnp.ndarray       # (maxEdges2, nEdges)
    nEdgesOnCell: jnp.ndarray      # (nCells,)
    nEdgesOnEdge: jnp.ndarray      # (nEdges,)

    # --- Geometry ---
    areaCell: jnp.ndarray           # (nCells,)
    areaTriangle: jnp.ndarray       # (nVertices,)
    dcEdge: jnp.ndarray             # (nEdges,) dist between cell centers
    dvEdge: jnp.ndarray             # (nEdges,) dist between vertices
    angleEdge: jnp.ndarray          # (nEdges,) angle of normal from east

    # --- Weights and signs ---
    weightsOnEdge: jnp.ndarray      # (maxEdges2, nEdges)
    kiteAreasOnVertex: jnp.ndarray  # (vertexDegree, nVertices)
    fEdge: jnp.ndarray              # (nEdges,) Coriolis at edges
    fVertex: jnp.ndarray            # (nVertices,) Coriolis at vertices
    edgeSignOnCell: jnp.ndarray     # (maxEdges, nCells) ±1
    edgeSignOnVertex: jnp.ndarray   # (vertexDegree, nVertices) ±1
    meshDensity: jnp.ndarray        # (nCells,)

    # ------------------------------------------------------------------
    # GridProtocol properties
    # ------------------------------------------------------------------

    @property
    def grid_lat(self) -> jnp.ndarray:
        return self.latCell

    @property
    def grid_lon(self) -> jnp.ndarray:
        return self.lonCell

    @property
    def grid_area(self) -> jnp.ndarray:
        return self.areaCell

    @property
    def grid_total_area(self):
        return jnp.sum(self.areaCell)

    @property
    def grid_coriolis(self) -> jnp.ndarray:
        return 2.0 * 7.292e-5 * jnp.sin(self.latCell)

    @property
    def grid_radius(self) -> float:
        return self.radius

    @property
    def grid_n_columns(self) -> int:
        return self.nCells

    @property
    def grid_shape_2d(self) -> tuple[int, ...]:
        return (self.nCells,)

    def to_columns(self, field):
        return field

    def from_columns(self, cols):
        return cols


# ============================================================================
# Icosahedral mesh generation
# ============================================================================

def _icosahedral_base():
    """12 vertices, 20 triangles of a regular icosahedron on the unit sphere."""
    phi = (1.0 + np.sqrt(5.0)) / 2.0
    verts = np.array([
        [-1, phi, 0], [1, phi, 0], [-1, -phi, 0], [1, -phi, 0],
        [0, -1, phi], [0, 1, phi], [0, -1, -phi], [0, 1, -phi],
        [phi, 0, -1], [phi, 0, 1], [-phi, 0, -1], [-phi, 0, 1],
    ], dtype=np.float64)
    verts /= np.linalg.norm(verts, axis=1, keepdims=True)
    hull = ConvexHull(verts)
    triangles = hull.simplices.copy()
    # Orient all triangles outward (normal pointing away from origin)
    for i, tri in enumerate(triangles):
        a, b, c = verts[tri[0]], verts[tri[1]], verts[tri[2]]
        normal = np.cross(b - a, c - a)
        if np.dot(normal, a) < 0:
            triangles[i] = [tri[0], tri[2], tri[1]]
    return verts, triangles


def _bisect_mesh(vertices, triangles, level):
    """Recursive edge-midpoint bisection of a triangular mesh on the sphere."""
    verts_list = list(vertices)
    for _ in range(level):
        edge_midpoints = {}
        new_triangles = []

        def get_midpoint(i, j):
            key = (min(i, j), max(i, j))
            if key in edge_midpoints:
                return edge_midpoints[key]
            mid = (verts_list[i] + verts_list[j]) * 0.5
            mid /= np.linalg.norm(mid)
            idx = len(verts_list)
            verts_list.append(mid)
            edge_midpoints[key] = idx
            return idx

        for tri in triangles:
            a, b, c = int(tri[0]), int(tri[1]), int(tri[2])
            ab = get_midpoint(a, b)
            bc = get_midpoint(b, c)
            ca = get_midpoint(c, a)
            new_triangles.extend([
                [a, ab, ca],
                [b, bc, ab],
                [c, ca, bc],
                [ab, bc, ca],
            ])
        triangles = np.array(new_triangles, dtype=np.int64)
    return np.array(verts_list, dtype=np.float64), triangles


def _lloyd_relaxation(points, n_iter=50):
    """Lloyd relaxation to produce a centroidal Voronoi tessellation (SCVT)."""
    pts = points.copy()
    for _ in range(n_iter):
        try:
            sv = SphericalVoronoi(pts, radius=1.0, center=np.zeros(3))
            sv.sort_vertices_of_regions()
        except Exception:
            break
        new_pts = np.empty_like(pts)
        for i, region in enumerate(sv.regions):
            if len(region) == 0:
                new_pts[i] = pts[i]
                continue
            poly_verts = sv.vertices[region]
            # Spherical centroid: area-weighted mean projected to sphere
            centroid = _spherical_polygon_centroid(poly_verts)
            new_pts[i] = centroid
        pts = new_pts
    return pts


def _spherical_polygon_centroid(vertices):
    """Centroid of a spherical polygon on the unit sphere."""
    n = len(vertices)
    if n < 3:
        c = vertices.mean(axis=0)
        return c / np.linalg.norm(c)
    # Decompose into triangles from v0 and compute area-weighted centroid
    v0 = vertices[0]
    total_area = 0.0
    centroid = np.zeros(3)
    for i in range(1, n - 1):
        v1, v2 = vertices[i], vertices[i + 1]
        # True spherical triangle area via spherical excess
        area = _spherical_triangle_area(v0, v1, v2, radius=1.0)
        tri_center = (v0 + v1 + v2) / 3.0
        centroid += area * tri_center
        total_area += area
    if total_area > 0:
        centroid /= total_area
    else:
        centroid = vertices.mean(axis=0)
    norm = np.linalg.norm(centroid)
    if norm > 1e-15:
        centroid /= norm
    return centroid


# ============================================================================
# Geometry helpers
# ============================================================================

def _xyz_to_latlon(x, y, z):
    """Convert Cartesian (unit sphere) to (lat, lon) in radians."""
    lat = np.arcsin(np.clip(z, -1.0, 1.0))
    lon = np.arctan2(y, x)
    lon = np.mod(lon, 2.0 * np.pi)  # [0, 2pi)
    return lat, lon


def _great_circle_distance(p1, p2, radius=1.0):
    """Great-circle distance between two 3D points on a sphere."""
    dot = np.clip(np.sum(p1 * p2, axis=-1), -1.0, 1.0)
    return radius * np.arccos(dot)


def _spherical_triangle_area(a, b, c, radius=1.0):
    """Area of a spherical triangle using the scalar triple product."""
    # E = 2 * arctan(|a·(b×c)| / (1 + a·b + b·c + a·c)) on unit sphere
    ab = np.dot(a, b)
    bc = np.dot(b, c)
    ac = np.dot(a, c)
    cross_bc = np.cross(b, c)
    triple = np.dot(a, cross_bc)
    denom = 1.0 + ab + bc + ac
    if abs(denom) < 1e-15:
        return 0.0
    E = 2.0 * np.arctan2(abs(triple), denom)
    return E * radius**2


def _angle_from_east(x, y, z, dx, dy, dz):
    """Angle of direction vector (dx,dy,dz) relative to local east at (x,y,z).

    Returns angle in radians, measured counterclockwise from east.
    """
    # Local east: (-sin(lon), cos(lon), 0)
    r_horiz = np.sqrt(x**2 + y**2)
    if r_horiz < 1e-15:
        return 0.0
    east = np.array([-y / r_horiz, x / r_horiz, 0.0])
    # Local north: (-sin(lat)*cos(lon), -sin(lat)*sin(lon), cos(lat))
    lat = np.arcsin(np.clip(z, -1.0, 1.0))
    lon = np.arctan2(y, x)
    north = np.array([
        -np.sin(lat) * np.cos(lon),
        -np.sin(lat) * np.sin(lon),
        np.cos(lat),
    ])
    # Project direction onto tangent plane
    de = np.dot(dx * np.array([1, 0, 0]) + dy * np.array([0, 1, 0]) +
                dz * np.array([0, 0, 1]), east)
    dn = np.dot(dx * np.array([1, 0, 0]) + dy * np.array([0, 1, 0]) +
                dz * np.array([0, 0, 1]), north)
    d_vec = np.array([dx, dy, dz])
    de = np.dot(d_vec, east)
    dn = np.dot(d_vec, north)
    return np.arctan2(dn, de)


def _order_indices_ccw(center_xyz, neighbor_xyz):
    """Order neighbor indices counterclockwise around center on the sphere."""
    # Build local tangent plane basis
    c = center_xyz / np.linalg.norm(center_xyz)
    # Choose an arbitrary perpendicular direction
    if abs(c[2]) < 0.9:
        up = np.array([0.0, 0.0, 1.0])
    else:
        up = np.array([1.0, 0.0, 0.0])
    east = np.cross(up, c)
    east /= np.linalg.norm(east)
    north = np.cross(c, east)

    # Project neighbors to tangent plane and compute angles
    offsets = neighbor_xyz - c[None, :]
    x_proj = np.dot(offsets, east)
    y_proj = np.dot(offsets, north)
    angles = np.arctan2(y_proj, x_proj)
    return np.argsort(angles)


# ============================================================================
# Mesh connectivity and geometry building
# ============================================================================

def _build_mesh_from_generators(cell_xyz, radius, omega=constants.Omega):
    """Build complete MPAS mesh from generator points on the unit sphere.

    Parameters
    ----------
    cell_xyz : ndarray, shape (nCells, 3)
        Generator points on the unit sphere.
    radius : float
        Sphere radius [m].
    omega : float
        Rotation rate [rad/s].

    Returns
    -------
    dict : All mesh arrays needed for VoronoiMesh.
    """
    nCells = len(cell_xyz)

    # --- Delaunay triangulation via ConvexHull ---
    hull = ConvexHull(cell_xyz)
    triangles = hull.simplices.copy()

    # Orient triangles outward
    for i, tri in enumerate(triangles):
        a, b, c = cell_xyz[tri[0]], cell_xyz[tri[1]], cell_xyz[tri[2]]
        normal = np.cross(b - a, c - a)
        if np.dot(normal, a) < 0:
            triangles[i] = [tri[0], tri[2], tri[1]]

    nVertices = len(triangles)

    # --- Compute vertex positions (circumcenters of Delaunay triangles) ---
    vertex_xyz = np.zeros((nVertices, 3), dtype=np.float64)
    for v, tri in enumerate(triangles):
        a, b, c = cell_xyz[tri[0]], cell_xyz[tri[1]], cell_xyz[tri[2]]
        # Circumcenter: point equidistant from a, b, c on the sphere
        # cc · (a-b) = 0 and cc · (b-c) = 0 => cc = cross(a-b, b-c)
        n1 = a - b
        n2 = b - c
        cc_vec = np.cross(n1, n2)
        norm = np.linalg.norm(cc_vec)
        if norm < 1e-15:
            cc_vec = (a + b + c) / 3.0
            norm = np.linalg.norm(cc_vec)
        cc_vec /= norm
        # Ensure circumcenter is on the same side as the triangle
        if np.dot(cc_vec, a) < 0:
            cc_vec = -cc_vec
        vertex_xyz[v] = cc_vec

    # --- Build edge list from triangles ---
    edge_dict = {}  # (min_cell, max_cell) -> edge_index
    edge_to_triangles = {}  # edge_index -> [tri1, tri2]
    edge_list = []  # list of (cell1, cell2)

    for t_idx, tri in enumerate(triangles):
        for i in range(3):
            c1, c2 = int(tri[i]), int(tri[(i + 1) % 3])
            key = (min(c1, c2), max(c1, c2))
            if key not in edge_dict:
                e_idx = len(edge_list)
                edge_dict[key] = e_idx
                edge_list.append(key)
                edge_to_triangles[e_idx] = []
            edge_to_triangles[edge_dict[key]].append(t_idx)

    nEdges = len(edge_list)

    # --- cellsOnEdge: orient normal so cross product points outward ---
    cellsOnEdge = np.zeros((2, nEdges), dtype=np.int32)
    for e_idx, (c1, c2) in enumerate(edge_list):
        # Normal direction: from c1 to c2
        # Choose orientation so that the cross product of (c2-c1) with (v1-v2)
        # points outward (same as cell_xyz average direction)
        cellsOnEdge[0, e_idx] = c1
        cellsOnEdge[1, e_idx] = c2

    # --- verticesOnEdge: the two triangles sharing this edge ---
    verticesOnEdge = np.full((2, nEdges), -1, dtype=np.int32)
    for e_idx in range(nEdges):
        tris = edge_to_triangles[e_idx]
        if len(tris) >= 1:
            verticesOnEdge[0, e_idx] = tris[0]
        if len(tris) >= 2:
            verticesOnEdge[1, e_idx] = tris[1]

    # Orient verticesOnEdge so that (v0→v1) is consistent with tangent = k × normal
    for e_idx in range(nEdges):
        c1, c2 = cellsOnEdge[0, e_idx], cellsOnEdge[1, e_idx]
        v0, v1 = verticesOnEdge[0, e_idx], verticesOnEdge[1, e_idx]
        if v0 < 0 or v1 < 0:
            continue
        # Normal direction: c1 → c2
        n_vec = cell_xyz[c2] - cell_xyz[c1]
        # Tangent: k × n (where k is radial at edge midpoint)
        edge_mid = (cell_xyz[c1] + cell_xyz[c2])
        edge_mid /= np.linalg.norm(edge_mid)
        t_vec = np.cross(edge_mid, n_vec)
        # v0→v1 direction
        v_dir = vertex_xyz[v1] - vertex_xyz[v0]
        if np.dot(v_dir, t_vec) < 0:
            verticesOnEdge[0, e_idx] = v1
            verticesOnEdge[1, e_idx] = v0

    # --- Edge coordinates (midpoint of the two cell centers, projected to sphere) ---
    edge_xyz = np.zeros((nEdges, 3), dtype=np.float64)
    for e_idx in range(nEdges):
        c1, c2 = cellsOnEdge[0, e_idx], cellsOnEdge[1, e_idx]
        mid = (cell_xyz[c1] + cell_xyz[c2]) * 0.5
        norm = np.linalg.norm(mid)
        if norm > 1e-15:
            mid /= norm
        edge_xyz[e_idx] = mid

    # --- Cell-level connectivity: find edges and vertices for each cell ---
    cell_edges = [[] for _ in range(nCells)]
    cell_vertices = [[] for _ in range(nCells)]
    cell_neighbors = [[] for _ in range(nCells)]

    for e_idx in range(nEdges):
        c1, c2 = cellsOnEdge[0, e_idx], cellsOnEdge[1, e_idx]
        cell_edges[c1].append(e_idx)
        cell_edges[c2].append(e_idx)
        cell_neighbors[c1].append(c2)
        cell_neighbors[c2].append(c1)

    # For each vertex (triangle), which cells meet there
    vertex_cells = [[] for _ in range(nVertices)]
    vertex_edges_list = [[] for _ in range(nVertices)]
    for v_idx, tri in enumerate(triangles):
        for c in tri:
            vertex_cells[v_idx].append(int(c))
            cell_vertices[int(c)].append(v_idx)

    # For each vertex, find its edges (edges of the Delaunay triangle)
    for v_idx, tri in enumerate(triangles):
        for i in range(3):
            c1, c2 = int(tri[i]), int(tri[(i + 1) % 3])
            key = (min(c1, c2), max(c1, c2))
            e_idx = edge_dict[key]
            vertex_edges_list[v_idx].append(e_idx)

    # --- Determine maxEdges and build padded arrays ---
    nEdgesOnCell_arr = np.array([len(cell_edges[c]) for c in range(nCells)],
                                dtype=np.int32)
    maxEdges = int(np.max(nEdgesOnCell_arr))
    vertexDegree = 3  # Delaunay triangles always have 3 vertices

    # Order edges and vertices CCW around each cell
    edgesOnCell = np.full((maxEdges, nCells), -1, dtype=np.int32)
    verticesOnCell = np.full((maxEdges, nCells), -1, dtype=np.int32)
    cellsOnCell = np.full((maxEdges, nCells), -1, dtype=np.int32)

    for c in range(nCells):
        n = nEdgesOnCell_arr[c]
        if n == 0:
            continue
        # Get vertex positions and order CCW
        v_indices = list(set(cell_vertices[c]))
        v_xyz = vertex_xyz[v_indices]
        order = _order_indices_ccw(cell_xyz[c], v_xyz)
        ordered_verts = [v_indices[i] for i in order]

        # Build ordered edges: edge between consecutive vertices
        ordered_edges = []
        ordered_neighbors = []
        for i in range(len(ordered_verts)):
            v_curr = ordered_verts[i]
            v_next = ordered_verts[(i + 1) % len(ordered_verts)]
            # Find edge connecting cells that share both v_curr and v_next
            found = False
            for e_idx in cell_edges[c]:
                ev0, ev1 = verticesOnEdge[0, e_idx], verticesOnEdge[1, e_idx]
                if set([ev0, ev1]) == set([v_curr, v_next]):
                    ordered_edges.append(e_idx)
                    # Neighbor is the other cell on this edge
                    oc1, oc2 = cellsOnEdge[0, e_idx], cellsOnEdge[1, e_idx]
                    nbr = oc2 if oc1 == c else oc1
                    ordered_neighbors.append(nbr)
                    found = True
                    break
            if not found:
                # Fallback: use any unassigned edge
                for e_idx in cell_edges[c]:
                    if e_idx not in ordered_edges:
                        ordered_edges.append(e_idx)
                        oc1, oc2 = cellsOnEdge[0, e_idx], cellsOnEdge[1, e_idx]
                        nbr = oc2 if oc1 == c else oc1
                        ordered_neighbors.append(nbr)
                        break

        for i in range(min(len(ordered_verts), maxEdges)):
            verticesOnCell[i, c] = ordered_verts[i]
        for i in range(min(len(ordered_edges), maxEdges)):
            edgesOnCell[i, c] = ordered_edges[i]
            cellsOnCell[i, c] = ordered_neighbors[i]

    # --- Vertex-level connectivity (ordered) ---
    cellsOnVertex = np.full((vertexDegree, nVertices), -1, dtype=np.int32)
    edgesOnVertex = np.full((vertexDegree, nVertices), -1, dtype=np.int32)

    for v_idx in range(nVertices):
        tri = triangles[v_idx]
        # Order cells CCW around vertex
        c_indices = [int(tri[0]), int(tri[1]), int(tri[2])]
        c_xyz = cell_xyz[c_indices]
        order = _order_indices_ccw(vertex_xyz[v_idx], c_xyz)
        ordered_cells = [c_indices[i] for i in order]

        for k in range(3):
            cellsOnVertex[k, v_idx] = ordered_cells[k]

        # Edges: edge between consecutive cells in the ordered list
        for k in range(3):
            c1_v = ordered_cells[k]
            c2_v = ordered_cells[(k + 1) % 3]
            key = (min(c1_v, c2_v), max(c1_v, c2_v))
            if key in edge_dict:
                edgesOnVertex[k, v_idx] = edge_dict[key]

    # --- Compute geometric quantities ---
    # dcEdge: great-circle distance between cell centers
    dcEdge = np.zeros(nEdges, dtype=np.float64)
    for e in range(nEdges):
        c1, c2 = cellsOnEdge[0, e], cellsOnEdge[1, e]
        dcEdge[e] = _great_circle_distance(cell_xyz[c1], cell_xyz[c2], radius)

    # dvEdge: great-circle distance between vertices
    dvEdge = np.zeros(nEdges, dtype=np.float64)
    for e in range(nEdges):
        v0, v1 = verticesOnEdge[0, e], verticesOnEdge[1, e]
        if v0 >= 0 and v1 >= 0:
            dvEdge[e] = _great_circle_distance(vertex_xyz[v0], vertex_xyz[v1],
                                                radius)

    # angleEdge: angle of edge normal (c1→c2 direction) relative to local east
    angleEdge = np.zeros(nEdges, dtype=np.float64)
    for e in range(nEdges):
        c1, c2 = cellsOnEdge[0, e], cellsOnEdge[1, e]
        dx = cell_xyz[c2, 0] - cell_xyz[c1, 0]
        dy = cell_xyz[c2, 1] - cell_xyz[c1, 1]
        dz = cell_xyz[c2, 2] - cell_xyz[c1, 2]
        ex, ey, ez = edge_xyz[e]
        angleEdge[e] = _angle_from_east(ex, ey, ez, dx, dy, dz)

    # areaTriangle: spherical triangle area for each vertex (Delaunay triangle)
    areaTriangle = np.zeros(nVertices, dtype=np.float64)
    for v in range(nVertices):
        tri = triangles[v]
        a = cell_xyz[tri[0]] * radius
        b = cell_xyz[tri[1]] * radius
        c = cell_xyz[tri[2]] * radius
        areaTriangle[v] = _spherical_triangle_area(
            a / radius, b / radius, c / radius, radius)

    # --- Kite areas ---
    kiteAreasOnVertex = _compute_kite_areas(
        nVertices, vertexDegree, cellsOnVertex, vertex_xyz, cell_xyz,
        verticesOnEdge, edgesOnVertex, edge_xyz, radius)

    # areaCell: sum of kite areas for each cell
    areaCell = np.zeros(nCells, dtype=np.float64)
    for v in range(nVertices):
        for k in range(vertexDegree):
            c = cellsOnVertex[k, v]
            if c >= 0:
                areaCell[c] += kiteAreasOnVertex[k, v]

    # --- Edge sign arrays ---
    edgeSignOnCell = _compute_edge_sign_on_cell(
        nCells, maxEdges, nEdgesOnCell_arr, edgesOnCell, cellsOnEdge)
    edgeSignOnVertex = _compute_edge_sign_on_vertex(
        nVertices, vertexDegree, edgesOnVertex, cellsOnVertex, cellsOnEdge,
        vertex_xyz, cell_xyz)

    # --- edgesOnEdge and weightsOnEdge ---
    maxEdges2 = 2 * maxEdges - 2
    edgesOnEdge, weightsOnEdge, nEdgesOnEdge_arr = _compute_weights_on_edge(
        nEdges, nCells, maxEdges, maxEdges2, nEdgesOnCell_arr,
        cellsOnEdge, verticesOnEdge, edgesOnCell, verticesOnCell,
        edgeSignOnCell, kiteAreasOnVertex, cellsOnVertex, areaCell,
        vertex_xyz, cell_xyz, edge_xyz, angleEdge, dvEdge, dcEdge, radius)

    # --- Coriolis parameters ---
    latEdge, lonEdge = _xyz_to_latlon(edge_xyz[:, 0], edge_xyz[:, 1],
                                       edge_xyz[:, 2])
    latVertex, lonVertex = _xyz_to_latlon(vertex_xyz[:, 0], vertex_xyz[:, 1],
                                           vertex_xyz[:, 2])
    latCell, lonCell = _xyz_to_latlon(cell_xyz[:, 0], cell_xyz[:, 1],
                                       cell_xyz[:, 2])
    fEdge = 2.0 * omega * np.sin(latEdge)
    fVertex = 2.0 * omega * np.sin(latVertex)

    # --- Convert all arrays to JAX ---
    # Use float64 when x64 is enabled for geometry precision, float32 otherwise.
    import jax
    try:
        from legoesm.core.precision import get_policy
        _fdtype = get_policy().storage
    except Exception:
        _fdtype = jnp.float64 if jax.config.jax_enable_x64 else jnp.float32

    def to_jax_f(arr):
        return jnp.array(arr, dtype=_fdtype)

    def to_jax_i(arr):
        return jnp.array(arr, dtype=jnp.int32)

    return VoronoiMesh(
        nCells=nCells, nEdges=nEdges, nVertices=nVertices,
        maxEdges=maxEdges, vertexDegree=vertexDegree, radius=radius,
        latCell=to_jax_f(latCell), lonCell=to_jax_f(lonCell),
        xCell=to_jax_f(cell_xyz[:, 0] * radius),
        yCell=to_jax_f(cell_xyz[:, 1] * radius),
        zCell=to_jax_f(cell_xyz[:, 2] * radius),
        latEdge=to_jax_f(latEdge), lonEdge=to_jax_f(lonEdge),
        xEdge=to_jax_f(edge_xyz[:, 0] * radius),
        yEdge=to_jax_f(edge_xyz[:, 1] * radius),
        zEdge=to_jax_f(edge_xyz[:, 2] * radius),
        latVertex=to_jax_f(latVertex), lonVertex=to_jax_f(lonVertex),
        xVertex=to_jax_f(vertex_xyz[:, 0] * radius),
        yVertex=to_jax_f(vertex_xyz[:, 1] * radius),
        zVertex=to_jax_f(vertex_xyz[:, 2] * radius),
        cellsOnEdge=to_jax_i(cellsOnEdge),
        edgesOnCell=to_jax_i(edgesOnCell),
        verticesOnCell=to_jax_i(verticesOnCell),
        verticesOnEdge=to_jax_i(verticesOnEdge),
        edgesOnVertex=to_jax_i(edgesOnVertex),
        cellsOnVertex=to_jax_i(cellsOnVertex),
        cellsOnCell=to_jax_i(cellsOnCell),
        edgesOnEdge=to_jax_i(edgesOnEdge),
        nEdgesOnCell=to_jax_i(nEdgesOnCell_arr),
        nEdgesOnEdge=to_jax_i(nEdgesOnEdge_arr),
        areaCell=to_jax_f(areaCell),
        areaTriangle=to_jax_f(areaTriangle),
        dcEdge=to_jax_f(dcEdge),
        dvEdge=to_jax_f(dvEdge),
        angleEdge=to_jax_f(angleEdge),
        weightsOnEdge=to_jax_f(weightsOnEdge),
        kiteAreasOnVertex=to_jax_f(kiteAreasOnVertex),
        fEdge=to_jax_f(fEdge),
        fVertex=to_jax_f(fVertex),
        edgeSignOnCell=to_jax_f(edgeSignOnCell),
        edgeSignOnVertex=to_jax_f(edgeSignOnVertex),
        meshDensity=to_jax_f(np.ones(nCells)),
    )


def _compute_kite_areas(nVertices, vertexDegree, cellsOnVertex,
                         vertex_xyz, cell_xyz, verticesOnEdge,
                         edgesOnVertex, edge_xyz, radius):
    """Compute kite areas at each vertex for each adjacent cell.

    A kite at vertex v for cell c is the quadrilateral formed by:
    vertex v, midpoint of edge between v and next cell, cell center c,
    midpoint of edge between v and prev cell.
    """
    kiteAreas = np.zeros((vertexDegree, nVertices), dtype=np.float64)

    for v in range(nVertices):
        for k in range(vertexDegree):
            c = cellsOnVertex[k, v]
            if c < 0:
                continue
            # Find the two edges of this vertex that bound cell c
            # These are the edges between (c, prev_cell) and (c, next_cell)
            e_prev = edgesOnVertex[(k - 1) % vertexDegree, v]
            e_curr = edgesOnVertex[k, v]

            if e_prev < 0 or e_curr < 0:
                continue

            # Kite: vertex_v, edge_midpoint_prev, cell_center_c, edge_midpoint_curr
            p_v = vertex_xyz[v] * radius
            p_eprev = edge_xyz[e_prev] * radius
            p_c = cell_xyz[c] * radius
            p_ecurr = edge_xyz[e_curr] * radius

            # Area as sum of two spherical triangles
            a1 = _spherical_triangle_area(
                p_v / radius, p_eprev / radius, p_c / radius, radius)
            a2 = _spherical_triangle_area(
                p_v / radius, p_c / radius, p_ecurr / radius, radius)
            kiteAreas[k, v] = a1 + a2

    return kiteAreas


def _compute_edge_sign_on_cell(nCells, maxEdges, nEdgesOnCell, edgesOnCell,
                                cellsOnEdge):
    """Compute edgeSignOnCell: +1 if edge normal points outward from cell."""
    edgeSignOnCell = np.zeros((maxEdges, nCells), dtype=np.float64)
    for c in range(nCells):
        n = nEdgesOnCell[c]
        for k in range(n):
            e = edgesOnCell[k, c]
            if e < 0:
                continue
            if cellsOnEdge[0, e] == c:
                edgeSignOnCell[k, c] = 1.0   # normal points outward
            else:
                edgeSignOnCell[k, c] = -1.0  # normal points inward
    return edgeSignOnCell


def _compute_edge_sign_on_vertex(nVertices, vertexDegree, edgesOnVertex,
                                  cellsOnVertex, cellsOnEdge,
                                  vertex_xyz, cell_xyz):
    """Compute edgeSignOnVertex for curl computation.

    edgeSignOnVertex(k, v) = +1 if the edge contributes positively to
    the counterclockwise circulation around vertex v, -1 otherwise.

    The sign is +1 if the edge normal (c1→c2) is oriented such that
    traversing from c1 to c2 is counterclockwise around vertex v.
    """
    edgeSignOnVertex = np.zeros((vertexDegree, nVertices), dtype=np.float64)
    for v in range(nVertices):
        for k in range(vertexDegree):
            e = edgesOnVertex[k, v]
            if e < 0:
                continue
            c1 = cellsOnEdge[0, e]
            c2 = cellsOnEdge[1, e]
            # Check if c1→c2 is CCW around v
            # Use cross product: (c1 - v) × (c2 - v) should be same direction as v
            v_pos = vertex_xyz[v]
            vec1 = cell_xyz[c1] - v_pos
            vec2 = cell_xyz[c2] - v_pos
            cross = np.cross(vec1, vec2)
            if np.dot(cross, v_pos) > 0:
                edgeSignOnVertex[k, v] = 1.0   # c1→c2 is CCW
            else:
                edgeSignOnVertex[k, v] = -1.0  # c1→c2 is CW
    return edgeSignOnVertex


def _compute_weights_on_edge(nEdges, nCells, maxEdges, maxEdges2,
                              nEdgesOnCell, cellsOnEdge, verticesOnEdge,
                              edgesOnCell, verticesOnCell, edgeSignOnCell,
                              kiteAreasOnVertex, cellsOnVertex,
                              areaCell, vertex_xyz, cell_xyz, edge_xyz,
                              angleEdge, dvEdge, dcEdge, radius):
    """Compute weights for tangential velocity reconstruction.

    Uses a Perot-style least-squares approach: for each edge e, the
    weights are chosen so that a uniform vector field is reconstructed
    exactly. This is the minimum-norm solution of:
        Σ w_k cos(α_k) = -sin(α_e)
        Σ w_k sin(α_k) =  cos(α_e)
    where α_k = angleEdge[e_k].
    """
    edgesOnEdge = np.full((maxEdges2, nEdges), -1, dtype=np.int32)
    weightsOnEdge = np.zeros((maxEdges2, nEdges), dtype=np.float64)
    nEdgesOnEdge_arr = np.zeros(nEdges, dtype=np.int32)

    for iEdge in range(nEdges):
        c1 = cellsOnEdge[0, iEdge]
        c2 = cellsOnEdge[1, iEdge]

        # Build stencil: all edges of c1 and c2, excluding iEdge
        stencil_set = set()
        for k in range(nEdgesOnCell[c1]):
            e = edgesOnCell[k, c1]
            if e >= 0 and e != iEdge:
                stencil_set.add(int(e))
        for k in range(nEdgesOnCell[c2]):
            e = edgesOnCell[k, c2]
            if e >= 0 and e != iEdge:
                stencil_set.add(int(e))
        stencil_edges = sorted(stencil_set)
        m = len(stencil_edges)
        if m == 0:
            continue

        # Build least-squares system:
        # A w = b where A is 2×m, b is 2×1
        # A[0,k] = cos(angle_k), A[1,k] = sin(angle_k)
        # b = [-sin(angle_e), cos(angle_e)]
        A = np.zeros((2, m), dtype=np.float64)
        for k, ek in enumerate(stencil_edges):
            A[0, k] = np.cos(angleEdge[ek])
            A[1, k] = np.sin(angleEdge[ek])

        b = np.array([-np.sin(angleEdge[iEdge]),
                       np.cos(angleEdge[iEdge])], dtype=np.float64)

        # Minimum-norm solution: w = A^T (A A^T)^{-1} b
        AAT = A @ A.T  # 2x2
        det = AAT[0, 0] * AAT[1, 1] - AAT[0, 1] * AAT[1, 0]
        if abs(det) < 1e-30:
            continue
        AAT_inv = np.array([[AAT[1, 1], -AAT[0, 1]],
                            [-AAT[1, 0], AAT[0, 0]]]) / det
        w = A.T @ (AAT_inv @ b)

        # Store
        nEdgesOnEdge_arr[iEdge] = m
        for k, ek in enumerate(stencil_edges):
            if k < maxEdges2:
                edgesOnEdge[k, iEdge] = ek
                weightsOnEdge[k, iEdge] = w[k]

    return edgesOnEdge, weightsOnEdge, nEdgesOnEdge_arr


# ============================================================================
# Public API
# ============================================================================

def create_voronoi_mesh(
    subdivision_level: int,
    radius: float = constants.R_earth,
    lloyd_iterations: int = 50,
    omega: float = constants.Omega,
) -> VoronoiMesh:
    """Create a centroidal Voronoi tessellation (SCVT) on the sphere.

    Starts from an icosahedral triangulation, bisects to the desired
    level, applies Lloyd relaxation, then builds the full MPAS-compatible
    mesh with all connectivity and geometric arrays.

    Parameters
    ----------
    subdivision_level : int
        Number of bisection levels. nCells = 10*4^level + 2.
        level=3: 642 cells, level=4: 2562, level=5: 10242.
    radius : float
        Sphere radius [m]. Default: Earth radius.
    lloyd_iterations : int
        Number of Lloyd relaxation iterations. Default: 50.
    omega : float
        Rotation rate [rad/s]. Default: Earth rotation.

    Returns
    -------
    VoronoiMesh
    """
    if subdivision_level > 8:
        n_cells = 10 * 4 ** subdivision_level + 2
        raise ValueError(
            f"subdivision_level={subdivision_level} would create {n_cells:.2e} cells. "
            f"Maximum supported level is 8 (655,362 cells). "
            f"For higher resolutions, use load_mpas_mesh() with a pre-built mesh file."
        )

    # Step 1: Icosahedral base
    verts, triangles = _icosahedral_base()

    # Step 2: Bisect to desired resolution
    if subdivision_level > 0:
        verts, triangles = _bisect_mesh(verts, triangles, subdivision_level)

    # Step 3: Lloyd relaxation for SCVT
    if lloyd_iterations > 0 and subdivision_level > 0:
        cell_points = _lloyd_relaxation(verts, n_iter=lloyd_iterations)
    else:
        cell_points = verts

    # Step 4: Build complete mesh
    mesh = _build_mesh_from_generators(cell_points, radius, omega)
    return mesh


def load_mpas_mesh(path: str) -> VoronoiMesh:
    """Load an MPAS mesh from a NetCDF file.

    Parameters
    ----------
    path : str
        Path to MPAS mesh NetCDF file.

    Returns
    -------
    VoronoiMesh
    """
    import netCDF4 as nc

    ds = nc.Dataset(path, 'r')

    def read_var(name):
        return np.array(ds.variables[name][:])

    nCells = len(ds.dimensions['nCells'])
    nEdges = len(ds.dimensions['nEdges'])
    nVertices = len(ds.dimensions['nVertices'])
    maxEdges = len(ds.dimensions['maxEdges'])
    vertexDegree = len(ds.dimensions['vertexDegree'])

    # Read and convert from 1-indexed to 0-indexed
    def read_int_var(name):
        return np.array(ds.variables[name][:], dtype=np.int32) - 1

    radius = float(ds.sphere_radius) if hasattr(ds, 'sphere_radius') else 6371229.0

    import jax
    try:
        from legoesm.core.precision import get_policy
        _fdtype = get_policy().storage
    except Exception:
        _fdtype = jnp.float64 if jax.config.jax_enable_x64 else jnp.float32

    mesh_data = {
        'nCells': nCells, 'nEdges': nEdges, 'nVertices': nVertices,
        'maxEdges': maxEdges, 'vertexDegree': vertexDegree, 'radius': radius,
    }

    # Coordinates
    for name in ['latCell', 'lonCell', 'latEdge', 'lonEdge',
                 'latVertex', 'lonVertex']:
        mesh_data[name] = jnp.array(read_var(name), dtype=_fdtype)

    for prefix in ['Cell', 'Edge', 'Vertex']:
        for coord in ['x', 'y', 'z']:
            name = f'{coord}{prefix}'
            mesh_data[name] = jnp.array(read_var(name), dtype=_fdtype)

    # Connectivity (transpose to match our (maxEdges, nCells) convention)
    conn_names = {
        'cellsOnEdge': (2, nEdges),
        'verticesOnEdge': (2, nEdges),
        'edgesOnCell': (maxEdges, nCells),
        'verticesOnCell': (maxEdges, nCells),
        'cellsOnVertex': (vertexDegree, nVertices),
        'edgesOnVertex': (vertexDegree, nVertices),
        'cellsOnCell': (maxEdges, nCells),
    }
    for name, shape in conn_names.items():
        data = read_int_var(name)
        if data.ndim == 2:
            data = data.T if data.shape[0] != shape[0] else data
        mesh_data[name] = jnp.array(data, dtype=jnp.int32)

    # Geometry
    for name in ['areaCell', 'areaTriangle', 'dcEdge', 'dvEdge', 'angleEdge',
                 'fEdge', 'fVertex', 'meshDensity']:
        if name in ds.variables:
            mesh_data[name] = jnp.array(read_var(name), dtype=_fdtype)

    # Weights
    maxEdges2 = 2 * maxEdges - 2
    if 'weightsOnEdge' in ds.variables:
        woe = read_var('weightsOnEdge')
        eoe = read_int_var('edgesOnEdge')
        if woe.ndim == 2:
            woe = woe.T if woe.shape[0] != maxEdges2 else woe
            eoe = eoe.T if eoe.shape[0] != maxEdges2 else eoe
        mesh_data['weightsOnEdge'] = jnp.array(woe, dtype=_fdtype)
        mesh_data['edgesOnEdge'] = jnp.array(eoe, dtype=jnp.int32)
    else:
        mesh_data['weightsOnEdge'] = jnp.zeros((maxEdges2, nEdges))
        mesh_data['edgesOnEdge'] = jnp.full((maxEdges2, nEdges), -1,
                                             dtype=jnp.int32)

    if 'kiteAreasOnVertex' in ds.variables:
        ka = read_var('kiteAreasOnVertex')
        if ka.ndim == 2:
            ka = ka.T if ka.shape[0] != vertexDegree else ka
        mesh_data['kiteAreasOnVertex'] = jnp.array(ka, dtype=_fdtype)
    else:
        mesh_data['kiteAreasOnVertex'] = jnp.zeros((vertexDegree, nVertices))

    if 'edgeSignOnCell' not in mesh_data:
        mesh_data['edgeSignOnCell'] = jnp.zeros((maxEdges, nCells))
    if 'edgeSignOnVertex' not in mesh_data:
        mesh_data['edgeSignOnVertex'] = jnp.zeros((vertexDegree, nVertices))

    mesh_data['nEdgesOnCell'] = jnp.array(
        read_var('nEdgesOnCell'), dtype=jnp.int32)
    if 'nEdgesOnEdge' in ds.variables:
        mesh_data['nEdgesOnEdge'] = jnp.array(
            read_var('nEdgesOnEdge'), dtype=jnp.int32)
    else:
        mesh_data['nEdgesOnEdge'] = jnp.zeros(nEdges, dtype=jnp.int32)

    ds.close()
    return VoronoiMesh(**mesh_data)
