"""Grid and vertical coordinate protocols for legoESM.

Protocols define a uniform interface for all grid types, eliminating
isinstance/hasattr dispatch in physics code.
"""
from __future__ import annotations
from typing import Protocol, runtime_checkable
import jax


@runtime_checkable
class GridProtocol(Protocol):
    """Uniform interface for all horizontal grids."""

    @property
    def grid_lat(self) -> jax.Array: ...
    @property
    def grid_lon(self) -> jax.Array: ...
    @property
    def grid_area(self) -> jax.Array: ...
    @property
    def grid_total_area(self) -> jax.Array: ...
    @property
    def grid_coriolis(self) -> jax.Array: ...
    @property
    def grid_radius(self) -> float: ...
    @property
    def grid_n_columns(self) -> int: ...
    @property
    def grid_shape_2d(self) -> tuple[int, ...]: ...
    def to_columns(self, field: jax.Array) -> jax.Array: ...
    def from_columns(self, cols: jax.Array, /) -> jax.Array: ...


@runtime_checkable
class VerticalCoordProtocol(Protocol):
    """Uniform interface for vertical coordinates."""

    @property
    def n_levels(self) -> int: ...
    def pressure_at_full(self, p_s: jax.Array) -> jax.Array: ...
    def pressure_at_half(self, p_s: jax.Array) -> jax.Array: ...
    def layer_thickness_dp(self, p_s: jax.Array) -> jax.Array: ...
