"""Voronoi (MPAS-style) mesh for legoESM.

Implements icosahedral SCVT mesh generation and all required
connectivity/geometry arrays for the TRiSK discretization.

The mesh is a centroidal Voronoi tessellation on the sphere,
generated by recursive bisection of an icosahedron followed by
Lloyd relaxation.

References
----------
- Ringler, T. D., Thuburn, J., Klemp, J. B., & Skamarock, W. C. (2010).
  A unified approach to energy conservation and potential vorticity dynamics
  for arbitrarily-structured C-grids. J. Comput. Phys., 229(9), 3065-3090.
- Thuburn, J., Ringler, T. D., Skamarock, W. C., & Klemp, J. B. (2009).
  Numerical representation of geostrophic modes on arbitrarily structured
  C-grids. J. Comput. Phys., 228(22), 8321-8335.
- Du, Q., Faber, V., & Gunzburger, M. (1999). Centroidal Voronoi
  tessellations. SIAM Review, 41(4), 637-676.
"""

from __future__ import annotations

import os
import warnings
from typing import NamedTuple

import numpy as np
import jax
import jax.numpy as jnp
from scipy.spatial import ConvexHull, Delaunay, SphericalVoronoi

from legoesm import constants


class VoronoiMesh(NamedTuple):
    """MPAS-style Voronoi mesh for TRiSK discretization.

    All arrays use 0-based indexing. Unused entries in variable-length
    connectivity arrays are padded with -1 (integers) or 0.0 (floats).
    """
    # --- Dimensions ---
    nCells: int
    nEdges: int
    nVertices: int
    maxEdges: int       # max edges per cell (6 for hex, 5 for pent)
    vertexDegree: int   # edges per vertex (always 3 for Delaunay dual)
    radius: float

    # --- Cell coordinates (Voronoi generators) ---
    latCell: jnp.ndarray    # (nCells,)
    lonCell: jnp.ndarray    # (nCells,)
    xCell: jnp.ndarray      # (nCells,) Cartesian
    yCell: jnp.ndarray
    zCell: jnp.ndarray

    # --- Edge coordinates (midpoints of Voronoi boundaries) ---
    latEdge: jnp.ndarray    # (nEdges,)
    lonEdge: jnp.ndarray    # (nEdges,)
    xEdge: jnp.ndarray
    yEdge: jnp.ndarray
    zEdge: jnp.ndarray

    # --- Vertex coordinates (Delaunay circumcenters) ---
    latVertex: jnp.ndarray  # (nVertices,)
    lonVertex: jnp.ndarray  # (nVertices,)
    xVertex: jnp.ndarray
    yVertex: jnp.ndarray
    zVertex: jnp.ndarray

    # --- Connectivity (0-indexed, padded with -1) ---
    cellsOnEdge: jnp.ndarray       # (2, nEdges)
    edgesOnCell: jnp.ndarray       # (maxEdges, nCells)
    verticesOnCell: jnp.ndarray    # (maxEdges, nCells)
    verticesOnEdge: jnp.ndarray    # (2, nEdges)
    edgesOnVertex: jnp.ndarray     # (vertexDegree, nVertices)
    cellsOnVertex: jnp.ndarray     # (vertexDegree, nVertices)
    cellsOnCell: jnp.ndarray       # (maxEdges, nCells)
    edgesOnEdge: jnp.ndarray       # (maxEdges2, nEdges)
    nEdgesOnCell: jnp.ndarray      # (nCells,)
    nEdgesOnEdge: jnp.ndarray      # (nEdges,)

    # --- Geometry ---
    areaCell: jnp.ndarray           # (nCells,)
    areaTriangle: jnp.ndarray       # (nVertices,)
    dcEdge: jnp.ndarray             # (nEdges,) dist between cell centers
    dvEdge: jnp.ndarray             # (nEdges,) dist between vertices
    angleEdge: jnp.ndarray          # (nEdges,) angle of normal from east

    # --- Weights and signs ---
    weightsOnEdge: jnp.ndarray      # (maxEdges2, nEdges)
    kiteAreasOnVertex: jnp.ndarray  # (vertexDegree, nVertices)
    fEdge: jnp.ndarray              # (nEdges,) Coriolis at edges
    fVertex: jnp.ndarray            # (nVertices,) Coriolis at vertices
    edgeSignOnCell: jnp.ndarray     # (maxEdges, nCells) ±1
    edgeSignOnVertex: jnp.ndarray   # (vertexDegree, nVertices) ±1
    meshDensity: jnp.ndarray        # (nCells,)

    # ------------------------------------------------------------------
    # GridProtocol properties
    # ------------------------------------------------------------------

    @property
    def grid_lat(self) -> jnp.ndarray:
        return self.latCell

    @property
    def grid_lon(self) -> jnp.ndarray:
        return self.lonCell

    @property
    def grid_area(self) -> jnp.ndarray:
        return self.areaCell

    @property
    def grid_total_area(self):
        return jnp.sum(self.areaCell)

    @property
    def grid_coriolis(self) -> jnp.ndarray:
        return 2.0 * constants.Omega * jnp.sin(self.latCell)

    @property
    def grid_radius(self) -> float:
        return self.radius

    @property
    def grid_n_columns(self) -> int:
        return self.nCells

    @property
    def grid_shape_2d(self) -> tuple[int, ...]:
        return (self.nCells,)

    def to_columns(self, field):
        return field

    def from_columns(self, cols):
        return cols


# ============================================================================
# Icosahedral mesh generation
# ============================================================================

def _icosahedral_base():
    """12 vertices, 20 triangles of a regular icosahedron on the unit sphere."""
    phi = (1.0 + np.sqrt(5.0)) / 2.0
    verts = np.array([
        [-1, phi, 0], [1, phi, 0], [-1, -phi, 0], [1, -phi, 0],
        [0, -1, phi], [0, 1, phi], [0, -1, -phi], [0, 1, -phi],
        [phi, 0, -1], [phi, 0, 1], [-phi, 0, -1], [-phi, 0, 1],
    ], dtype=np.float64)
    verts /= np.linalg.norm(verts, axis=1, keepdims=True)
    hull = ConvexHull(verts)
    triangles = hull.simplices.copy()
    # Orient all triangles outward (normal pointing away from origin)
    for i, tri in enumerate(triangles):
        a, b, c = verts[tri[0]], verts[tri[1]], verts[tri[2]]
        normal = np.cross(b - a, c - a)
        if np.dot(normal, a) < 0:
            triangles[i] = [tri[0], tri[2], tri[1]]
    return verts, triangles


def _bisect_mesh(vertices, triangles, level):
    """Recursive edge-midpoint bisection of a triangular mesh on the sphere."""
    verts_list = list(vertices)
    for _ in range(level):
        edge_midpoints = {}
        new_triangles = []

        def get_midpoint(i, j):
            key = (min(i, j), max(i, j))
            if key in edge_midpoints:
                return edge_midpoints[key]
            mid = (verts_list[i] + verts_list[j]) * 0.5
            mid /= np.linalg.norm(mid)
            idx = len(verts_list)
            verts_list.append(mid)
            edge_midpoints[key] = idx
            return idx

        for tri in triangles:
            a, b, c = int(tri[0]), int(tri[1]), int(tri[2])
            ab = get_midpoint(a, b)
            bc = get_midpoint(b, c)
            ca = get_midpoint(c, a)
            new_triangles.extend([
                [a, ab, ca],
                [b, bc, ab],
                [c, ca, bc],
                [ab, bc, ca],
            ])
        triangles = np.array(new_triangles, dtype=np.int64)
    return np.array(verts_list, dtype=np.float64), triangles


def _lloyd_relaxation(points, n_iter=50, density_fn=None):
    """Lloyd relaxation to produce a centroidal Voronoi tessellation (SCVT).

    With ``density_fn`` the centroid of each Voronoi cell is **density-weighted**
    (Du–Faber–Gunzburger), so generators drift toward the high-density region and
    the converged mesh is refined there.  ``density_fn=None`` reproduces the
    uniform area-weighted SCVT exactly.
    """
    pts = points.copy()
    for _ in range(n_iter):
        try:
            sv = SphericalVoronoi(pts, radius=1.0, center=np.zeros(3))
            sv.sort_vertices_of_regions()
        except Exception:
            break
        new_pts = np.empty_like(pts)
        for i, region in enumerate(sv.regions):
            if len(region) == 0:
                new_pts[i] = pts[i]
                continue
            poly_verts = sv.vertices[region]
            # Spherical centroid: (density-weighted) area mean projected to sphere
            centroid = _spherical_polygon_centroid(poly_verts, density_fn=density_fn)
            new_pts[i] = centroid
        pts = new_pts
    return pts


def _density_at(point_xyz, density_fn):
    """Evaluate a (lat, lon)[rad] density function at a unit-sphere xyz point."""
    p = point_xyz / np.linalg.norm(point_xyz)
    lat = np.arcsin(np.clip(p[2], -1.0, 1.0))
    lon = np.arctan2(p[1], p[0])
    rho = float(density_fn(lat, lon))
    if not np.isfinite(rho) or rho <= 0.0:
        raise ValueError(
            f"density_fn must return a finite positive value; got {rho} at "
            f"(lat={lat:.3f}, lon={lon:.3f}) rad"
        )
    return rho


def _spherical_polygon_centroid(vertices, density_fn=None):
    """Centroid of a spherical polygon on the unit sphere.

    When ``density_fn`` is given each sub-triangle is weighted by
    ``area * density(centre)`` instead of ``area`` alone (density-weighted SCVT).
    """
    n = len(vertices)
    if n < 3:
        c = vertices.mean(axis=0)
        return c / np.linalg.norm(c)
    # Decompose into triangles from v0 and compute (density-)area-weighted centroid
    v0 = vertices[0]
    total_area = 0.0
    centroid = np.zeros(3)
    for i in range(1, n - 1):
        v1, v2 = vertices[i], vertices[i + 1]
        # True spherical triangle area via spherical excess
        area = _spherical_triangle_area(v0, v1, v2, radius=1.0)
        tri_center = (v0 + v1 + v2) / 3.0
        weight = area
        if density_fn is not None:
            # A density-weighted CVT relaxes cell area ~ weight**(-1/2); weighting by
            # density**2 therefore drives cell AREA ~ 1/density, i.e. a region with
            # density d gets ~d x smaller cells (the intuitive resolution control).
            weight = area * _density_at(tri_center, density_fn) ** 2
        centroid += weight * tri_center
        total_area += weight
    if total_area > 0:
        centroid /= total_area
    else:
        centroid = vertices.mean(axis=0)
    norm = np.linalg.norm(centroid)
    if norm > 1e-15:
        centroid /= norm
    return centroid


# ============================================================================
# Geometry helpers
# ============================================================================

def _xyz_to_latlon(x, y, z):
    """Convert Cartesian (unit sphere) to (lat, lon) in radians."""
    lat = np.arcsin(np.clip(z, -1.0, 1.0))
    lon = np.arctan2(y, x)
    lon = np.mod(lon, 2.0 * np.pi)  # [0, 2pi)
    return lat, lon


def _wrap_dlon(dlon, L_rad):
    """Wrap a longitude difference into the interval (-L_rad/2, L_rad/2]."""
    if L_rad is None:
        return dlon
    half = 0.5 * L_rad
    # Avoid Python-level while loops for speed — use modular arithmetic.
    return ((dlon + half) % L_rad) - half


def _shift_near(ref_xyz, other_xyz, L_rad):
    """Return ``other_xyz`` shifted zonally so it lies within ±L_rad/2 of
    the longitude of ``ref_xyz``.

    Used for sub-360° periodic meshes where seam edges and seam triangles
    involve cells whose true 3D positions sit on opposite sides of the
    periodic zonal extent. After shifting, the usual 3D great-circle,
    midpoint, and cross-product formulas give the correct *through-the-
    seam* geometry instead of the *the-long-way-around* geometry.

    For non-periodic meshes or full 360° meshes (L_rad None or ~2π), the
    input is returned unchanged.
    """
    if L_rad is None or abs(L_rad - 2.0 * np.pi) < 1e-10:
        return other_xyz
    np.arcsin(np.clip(ref_xyz[2], -1.0, 1.0))
    lon_r = np.arctan2(ref_xyz[1], ref_xyz[0])
    lat_o = np.arcsin(np.clip(other_xyz[2], -1.0, 1.0))
    lon_o = np.arctan2(other_xyz[1], other_xyz[0])
    dlon = _wrap_dlon(lon_o - lon_r, L_rad)
    lon_shifted = lon_r + dlon
    cos_lat_o = np.cos(lat_o)
    return np.array([
        cos_lat_o * np.cos(lon_shifted),
        cos_lat_o * np.sin(lon_shifted),
        np.sin(lat_o),
    ])


def _great_circle_distance(p1, p2, radius=1.0):
    """Great-circle distance between two 3D points on a sphere."""
    dot = np.clip(np.sum(p1 * p2, axis=-1), -1.0, 1.0)
    return radius * np.arccos(dot)


def _spherical_triangle_area(a, b, c, radius=1.0):
    """Area of a spherical triangle using the scalar triple product."""
    # E = 2 * arctan(|a·(b×c)| / (1 + a·b + b·c + a·c)) on unit sphere
    ab = np.dot(a, b)
    bc = np.dot(b, c)
    ac = np.dot(a, c)
    cross_bc = np.cross(b, c)
    triple = np.dot(a, cross_bc)
    denom = 1.0 + ab + bc + ac
    if abs(denom) < 1e-15:
        return 0.0
    E = 2.0 * np.arctan2(abs(triple), denom)
    return E * radius**2


# Public names for the spherical-geometry primitives reused by the unstructured
# conservative-remap weight generator (grids.conservative_regrid_unstructured).
# Promotion only — identical implementations, no behaviour change — so cross-
# module callers do not import the underscore-private symbols.
spherical_triangle_area = _spherical_triangle_area
shift_near = _shift_near


def _angle_from_east(x, y, z, dx, dy, dz):
    """Angle of direction vector (dx,dy,dz) relative to local east at (x,y,z).

    Returns angle in radians, measured counterclockwise from east.
    """
    # Local east: (-sin(lon), cos(lon), 0)
    r_horiz = np.sqrt(x**2 + y**2)
    if r_horiz < 1e-15:
        return 0.0
    east = np.array([-y / r_horiz, x / r_horiz, 0.0])
    # Local north: (-sin(lat)*cos(lon), -sin(lat)*sin(lon), cos(lat))
    lat = np.arcsin(np.clip(z, -1.0, 1.0))
    lon = np.arctan2(y, x)
    north = np.array([
        -np.sin(lat) * np.cos(lon),
        -np.sin(lat) * np.sin(lon),
        np.cos(lat),
    ])
    # Project direction onto tangent plane
    de = np.dot(dx * np.array([1, 0, 0]) + dy * np.array([0, 1, 0]) +
                dz * np.array([0, 0, 1]), east)
    dn = np.dot(dx * np.array([1, 0, 0]) + dy * np.array([0, 1, 0]) +
                dz * np.array([0, 0, 1]), north)
    d_vec = np.array([dx, dy, dz])
    de = np.dot(d_vec, east)
    dn = np.dot(d_vec, north)
    return np.arctan2(dn, de)


def _order_indices_ccw(center_xyz, neighbor_xyz):
    """Order neighbor indices counterclockwise around center on the sphere."""
    # Build local tangent plane basis
    c = center_xyz / np.linalg.norm(center_xyz)
    # Choose an arbitrary perpendicular direction
    if abs(c[2]) < 0.9:
        up = np.array([0.0, 0.0, 1.0])
    else:
        up = np.array([1.0, 0.0, 0.0])
    east = np.cross(up, c)
    east /= np.linalg.norm(east)
    north = np.cross(c, east)

    # Project neighbors to tangent plane and compute angles
    offsets = neighbor_xyz - c[None, :]
    x_proj = np.dot(offsets, east)
    y_proj = np.dot(offsets, north)
    angles = np.arctan2(y_proj, x_proj)
    return np.argsort(angles)


# ============================================================================
# Mesh connectivity and geometry building
# ============================================================================

def _build_mesh_from_generators(cell_xyz, radius, omega=constants.Omega,
                                triangles=None, periodic_L_rad=None):
    """Build complete MPAS mesh from generator points on the unit sphere.

    Parameters
    ----------
    cell_xyz : ndarray, shape (nCells, 3)
        Generator points on the unit sphere.
    radius : float
        Sphere radius [m].
    omega : float
        Rotation rate [rad/s].
    triangles : ndarray or None
        Pre-computed Delaunay triangles (nTriangles, 3). If ``None``,
        uses ``ConvexHull`` (only valid for global meshes covering the
        full sphere).
    periodic_L_rad : float or None
        When provided (and not equal to 2π), the mesh is treated as
        a zonally-periodic channel with periodic extent ``L_rad``. All
        per-edge, per-triangle, and per-vertex geometric computations
        shift neighbouring points across the seam so the resulting
        lengths, midpoints, angles, and areas reflect the correct
        through-the-seam geometry rather than the long-way-around
        great-circle on the full sphere. Leave as None for closed
        basins or full-sphere meshes.

    Returns
    -------
    dict : All mesh arrays needed for VoronoiMesh.
    """
    nCells = len(cell_xyz)
    # Seam-shift flag; None disables all periodic corrections.
    _L = periodic_L_rad if (
        periodic_L_rad is not None
        and abs(periodic_L_rad - 2.0 * np.pi) > 1e-6
    ) else None

    if triangles is None:
        # --- Delaunay triangulation via ConvexHull ---
        hull = ConvexHull(cell_xyz)
        triangles = hull.simplices.copy()

    # Orient triangles outward (uses seam-shifted positions when needed so
    # the outward normal of a seam triangle is correct).
    for i, tri in enumerate(triangles):
        a = cell_xyz[tri[0]]
        b = _shift_near(a, cell_xyz[tri[1]], _L)
        c = _shift_near(a, cell_xyz[tri[2]], _L)
        normal = np.cross(b - a, c - a)
        if np.dot(normal, a) < 0:
            triangles[i] = [tri[0], tri[2], tri[1]]

    nVertices = len(triangles)

    # --- Compute vertex positions (circumcenters of Delaunay triangles) ---
    vertex_xyz = np.zeros((nVertices, 3), dtype=np.float64)
    for v, tri in enumerate(triangles):
        a = cell_xyz[tri[0]]
        b = _shift_near(a, cell_xyz[tri[1]], _L)
        c = _shift_near(a, cell_xyz[tri[2]], _L)
        # Circumcenter: point equidistant from a, b, c on the sphere
        # cc · (a-b) = 0 and cc · (b-c) = 0 => cc = cross(a-b, b-c)
        n1 = a - b
        n2 = b - c
        cc_vec = np.cross(n1, n2)
        norm = np.linalg.norm(cc_vec)
        if norm < 1e-15:
            cc_vec = (a + b + c) / 3.0
            norm = np.linalg.norm(cc_vec)
        cc_vec /= norm
        # Ensure circumcenter is on the same side as the triangle
        if np.dot(cc_vec, a) < 0:
            cc_vec = -cc_vec
        vertex_xyz[v] = cc_vec

    # --- Build edge list from triangles ---
    edge_dict = {}  # (min_cell, max_cell) -> edge_index
    edge_to_triangles = {}  # edge_index -> [tri1, tri2]
    edge_list = []  # list of (cell1, cell2)

    for t_idx, tri in enumerate(triangles):
        for i in range(3):
            c1, c2 = int(tri[i]), int(tri[(i + 1) % 3])
            key = (min(c1, c2), max(c1, c2))
            if key not in edge_dict:
                e_idx = len(edge_list)
                edge_dict[key] = e_idx
                edge_list.append(key)
                edge_to_triangles[e_idx] = []
            edge_to_triangles[edge_dict[key]].append(t_idx)

    nEdges = len(edge_list)

    # --- cellsOnEdge: orient normal so cross product points outward ---
    cellsOnEdge = np.zeros((2, nEdges), dtype=np.int32)
    for e_idx, (c1, c2) in enumerate(edge_list):
        # Normal direction: from c1 to c2
        # Choose orientation so that the cross product of (c2-c1) with (v1-v2)
        # points outward (same as cell_xyz average direction)
        cellsOnEdge[0, e_idx] = c1
        cellsOnEdge[1, e_idx] = c2

    # --- verticesOnEdge: the two triangles sharing this edge ---
    verticesOnEdge = np.full((2, nEdges), -1, dtype=np.int32)
    for e_idx in range(nEdges):
        tris = edge_to_triangles[e_idx]
        if len(tris) >= 1:
            verticesOnEdge[0, e_idx] = tris[0]
        if len(tris) >= 2:
            verticesOnEdge[1, e_idx] = tris[1]

    # Orient verticesOnEdge so that (v0→v1) is consistent with tangent = k × normal
    for e_idx in range(nEdges):
        c1, c2 = cellsOnEdge[0, e_idx], cellsOnEdge[1, e_idx]
        v0, v1 = verticesOnEdge[0, e_idx], verticesOnEdge[1, e_idx]
        if v0 < 0 or v1 < 0:
            continue
        c1_pos = cell_xyz[c1]
        c2_pos = _shift_near(c1_pos, cell_xyz[c2], _L)
        # Normal direction: c1 → c2
        n_vec = c2_pos - c1_pos
        # Tangent: k × n (where k is radial at edge midpoint)
        edge_mid = (c1_pos + c2_pos)
        edge_mid /= np.linalg.norm(edge_mid)
        t_vec = np.cross(edge_mid, n_vec)
        # v0→v1 direction, with v1 shifted near v0 if on opposite sides of seam
        v0_pos = vertex_xyz[v0]
        v1_pos = _shift_near(v0_pos, vertex_xyz[v1], _L)
        v_dir = v1_pos - v0_pos
        if np.dot(v_dir, t_vec) < 0:
            verticesOnEdge[0, e_idx] = v1
            verticesOnEdge[1, e_idx] = v0

    # --- Edge coordinates (midpoint of the two cell centers, projected to sphere) ---
    edge_xyz = np.zeros((nEdges, 3), dtype=np.float64)
    for e_idx in range(nEdges):
        c1, c2 = cellsOnEdge[0, e_idx], cellsOnEdge[1, e_idx]
        c1_pos = cell_xyz[c1]
        c2_pos = _shift_near(c1_pos, cell_xyz[c2], _L)
        mid = (c1_pos + c2_pos) * 0.5
        norm = np.linalg.norm(mid)
        if norm > 1e-15:
            mid /= norm
        edge_xyz[e_idx] = mid

    # --- Cell-level connectivity: find edges and vertices for each cell ---
    cell_edges = [[] for _ in range(nCells)]
    cell_vertices = [[] for _ in range(nCells)]
    cell_neighbors = [[] for _ in range(nCells)]

    for e_idx in range(nEdges):
        c1, c2 = cellsOnEdge[0, e_idx], cellsOnEdge[1, e_idx]
        cell_edges[c1].append(e_idx)
        cell_edges[c2].append(e_idx)
        cell_neighbors[c1].append(c2)
        cell_neighbors[c2].append(c1)

    # For each vertex (triangle), which cells meet there
    vertex_cells = [[] for _ in range(nVertices)]
    vertex_edges_list = [[] for _ in range(nVertices)]
    for v_idx, tri in enumerate(triangles):
        for c in tri:
            vertex_cells[v_idx].append(int(c))
            cell_vertices[int(c)].append(v_idx)

    # For each vertex, find its edges (edges of the Delaunay triangle).
    # A triangle's edge may have been dropped from edge_dict as a periodic
    # half-edge; skip it here (the final edgesOnVertex is rebuilt later
    # with the same `if key in edge_dict` guard at line ~645).
    for v_idx, tri in enumerate(triangles):
        for i in range(3):
            c1, c2 = int(tri[i]), int(tri[(i + 1) % 3])
            key = (min(c1, c2), max(c1, c2))
            e_idx = edge_dict.get(key, -1)
            if e_idx >= 0:
                vertex_edges_list[v_idx].append(e_idx)

    # --- Rebuild cell_edges and cell_vertices from cellsOnEdge / triangles ---
    # cellsOnEdge is the source of truth for edge→cell adjacency; derive
    # per-cell edge/vertex sets from it.  The original upstream graph
    # construction could add the same edge twice to a cell (periodic
    # unroll-and-ghost) or miss edges whose vertex pair did not align
    # with triangle membership.  The LSQ weight code hid both bugs via
    # `stencil_set = set(...)`, but TRiSK walks the ordered edge list
    # around the cell and must have a clean, unique, CCW ordering.
    cell_edges = [[] for _ in range(nCells)]
    for e in range(nEdges):
        c1 = int(cellsOnEdge[0, e])
        c2 = int(cellsOnEdge[1, e])
        if c1 >= 0:
            cell_edges[c1].append(e)
        if c2 >= 0 and c2 != c1:
            cell_edges[c2].append(e)
    # Rebuild cell_vertices from the edge list (each edge contributes
    # up to two vertices to the cell).
    cell_vertices = [set() for _ in range(nCells)]
    for c in range(nCells):
        for e in cell_edges[c]:
            for a in range(2):
                v = int(verticesOnEdge[a, e])
                if v >= 0:
                    cell_vertices[c].add(v)
    cell_vertices = [sorted(cv) for cv in cell_vertices]

    # --- Determine maxEdges and build padded arrays ---
    nEdgesOnCell_arr = np.array([len(cell_edges[c]) for c in range(nCells)],
                                dtype=np.int32)
    maxEdges = int(np.max(nEdgesOnCell_arr))
    vertexDegree = 3  # Delaunay triangles always have 3 vertices

    # Order edges and vertices CCW around each cell
    edgesOnCell = np.full((maxEdges, nCells), -1, dtype=np.int32)
    verticesOnCell = np.full((maxEdges, nCells), -1, dtype=np.int32)
    cellsOnCell = np.full((maxEdges, nCells), -1, dtype=np.int32)

    for c in range(nCells):
        n = int(nEdgesOnCell_arr[c])
        if n == 0:
            continue

        # Order edges of cell c CCW by the angle of their midpoint
        # about the cell center (seam-shifted).
        edges_c = cell_edges[c]
        if _L is None:
            e_xyz = edge_xyz[edges_c]
        else:
            e_xyz = np.array([_shift_near(cell_xyz[c], edge_xyz[e], _L)
                               for e in edges_c])
        e_order = _order_indices_ccw(cell_xyz[c], e_xyz)
        ordered_edges = [edges_c[i] for i in e_order]

        # Order vertices CCW as well.
        verts_c = cell_vertices[c]
        if _L is None:
            v_xyz = vertex_xyz[verts_c]
        else:
            v_xyz = np.array([_shift_near(cell_xyz[c], vertex_xyz[v], _L)
                               for v in verts_c])
        v_order = _order_indices_ccw(cell_xyz[c], v_xyz)
        ordered_verts = [verts_c[i] for i in v_order]

        # Neighbors: the "other" cell across each ordered edge.
        ordered_neighbors = []
        for e_idx in ordered_edges:
            oc1 = int(cellsOnEdge[0, e_idx])
            oc2 = int(cellsOnEdge[1, e_idx])
            ordered_neighbors.append(oc2 if oc1 == c else oc1)

        ne = len(ordered_edges)
        for i in range(min(len(ordered_verts), maxEdges)):
            verticesOnCell[i, c] = ordered_verts[i]
        for i in range(min(ne, maxEdges)):
            edgesOnCell[i, c] = ordered_edges[i]
            cellsOnCell[i, c] = ordered_neighbors[i]

    # --- Vertex-level connectivity (ordered) ---
    cellsOnVertex = np.full((vertexDegree, nVertices), -1, dtype=np.int32)
    edgesOnVertex = np.full((vertexDegree, nVertices), -1, dtype=np.int32)

    for v_idx in range(nVertices):
        tri = triangles[v_idx]
        # Order cells CCW around vertex (seam-shift cells near the vertex)
        c_indices = [int(tri[0]), int(tri[1]), int(tri[2])]
        if _L is None:
            c_xyz = cell_xyz[c_indices]
        else:
            c_xyz = np.array([_shift_near(vertex_xyz[v_idx], cell_xyz[ci], _L)
                               for ci in c_indices])
        order = _order_indices_ccw(vertex_xyz[v_idx], c_xyz)
        ordered_cells = [c_indices[i] for i in order]

        for k in range(3):
            cellsOnVertex[k, v_idx] = ordered_cells[k]

        # Edges: edge between consecutive cells in the ordered list
        for k in range(3):
            c1_v = ordered_cells[k]
            c2_v = ordered_cells[(k + 1) % 3]
            key = (min(c1_v, c2_v), max(c1_v, c2_v))
            if key in edge_dict:
                edgesOnVertex[k, v_idx] = edge_dict[key]

    # --- Compute geometric quantities ---
    # dcEdge: great-circle distance between cell centers (seam-shifted)
    dcEdge = np.zeros(nEdges, dtype=np.float64)
    for e in range(nEdges):
        c1, c2 = cellsOnEdge[0, e], cellsOnEdge[1, e]
        c1_pos = cell_xyz[c1]
        c2_pos = _shift_near(c1_pos, cell_xyz[c2], _L)
        dcEdge[e] = _great_circle_distance(c1_pos, c2_pos, radius)

    # dvEdge: great-circle distance between vertices (seam-shifted)
    dvEdge = np.zeros(nEdges, dtype=np.float64)
    for e in range(nEdges):
        v0, v1 = verticesOnEdge[0, e], verticesOnEdge[1, e]
        if v0 >= 0 and v1 >= 0:
            v0_pos = vertex_xyz[v0]
            v1_pos = _shift_near(v0_pos, vertex_xyz[v1], _L)
            dvEdge[e] = _great_circle_distance(v0_pos, v1_pos, radius)

    # angleEdge: angle of edge normal (c1→c2 direction) relative to local east
    # At the edge midpoint the local frame is well-defined; the direction
    # vector uses the seam-shifted c2 so it points the short way across
    # the seam rather than the long way around the sphere.
    angleEdge = np.zeros(nEdges, dtype=np.float64)
    for e in range(nEdges):
        c1, c2 = cellsOnEdge[0, e], cellsOnEdge[1, e]
        c1_pos = cell_xyz[c1]
        c2_pos = _shift_near(c1_pos, cell_xyz[c2], _L)
        dx = c2_pos[0] - c1_pos[0]
        dy = c2_pos[1] - c1_pos[1]
        dz = c2_pos[2] - c1_pos[2]
        ex, ey, ez = edge_xyz[e]
        angleEdge[e] = _angle_from_east(ex, ey, ez, dx, dy, dz)

    # areaTriangle: spherical triangle area for each vertex (seam-shifted)
    areaTriangle = np.zeros(nVertices, dtype=np.float64)
    for v in range(nVertices):
        tri = triangles[v]
        a = cell_xyz[tri[0]]
        b = _shift_near(a, cell_xyz[tri[1]], _L)
        c = _shift_near(a, cell_xyz[tri[2]], _L)
        areaTriangle[v] = _spherical_triangle_area(a, b, c, radius)

    # --- Kite areas ---
    kiteAreasOnVertex = _compute_kite_areas(
        nVertices, vertexDegree, cellsOnVertex, vertex_xyz, cell_xyz,
        verticesOnEdge, edgesOnVertex, edge_xyz, radius, periodic_L_rad=_L)

    # areaCell: sum of kite areas for each cell
    areaCell = np.zeros(nCells, dtype=np.float64)
    for v in range(nVertices):
        for k in range(vertexDegree):
            c = cellsOnVertex[k, v]
            if c >= 0:
                areaCell[c] += kiteAreasOnVertex[k, v]

    # --- Edge sign arrays ---
    edgeSignOnCell = _compute_edge_sign_on_cell(
        nCells, maxEdges, nEdgesOnCell_arr, edgesOnCell, cellsOnEdge)
    edgeSignOnVertex = _compute_edge_sign_on_vertex(
        nVertices, vertexDegree, edgesOnVertex, cellsOnVertex, cellsOnEdge,
        vertex_xyz, cell_xyz, periodic_L_rad=_L)

    # --- edgesOnEdge and weightsOnEdge ---
    maxEdges2 = 2 * maxEdges - 2
    edgesOnEdge, weightsOnEdge, nEdgesOnEdge_arr = _compute_weights_on_edge(
        nEdges, maxEdges2, vertexDegree, nEdgesOnCell_arr,
        cellsOnEdge, verticesOnEdge, edgesOnCell,
        kiteAreasOnVertex, cellsOnVertex, areaCell, dvEdge, dcEdge)

    # --- Coriolis parameters ---
    latEdge, lonEdge = _xyz_to_latlon(edge_xyz[:, 0], edge_xyz[:, 1],
                                       edge_xyz[:, 2])
    latVertex, lonVertex = _xyz_to_latlon(vertex_xyz[:, 0], vertex_xyz[:, 1],
                                           vertex_xyz[:, 2])
    latCell, lonCell = _xyz_to_latlon(cell_xyz[:, 0], cell_xyz[:, 1],
                                       cell_xyz[:, 2])
    fEdge = 2.0 * omega * np.sin(latEdge)
    fVertex = 2.0 * omega * np.sin(latVertex)

    # --- Convert all arrays to JAX ---
    # Use float64 when x64 is enabled for geometry precision, float32 otherwise.
    import jax
    try:
        from legoesm.core.precision import get_policy
        _fdtype = get_policy().storage
    except Exception:
        _fdtype = jnp.float64 if jax.config.jax_enable_x64 else jnp.float32

    def to_jax_f(arr):
        return jnp.array(arr, dtype=_fdtype)

    def to_jax_i(arr):
        return jnp.array(arr, dtype=jnp.int32)

    return VoronoiMesh(
        nCells=nCells, nEdges=nEdges, nVertices=nVertices,
        maxEdges=maxEdges, vertexDegree=vertexDegree, radius=radius,
        latCell=to_jax_f(latCell), lonCell=to_jax_f(lonCell),
        xCell=to_jax_f(cell_xyz[:, 0] * radius),
        yCell=to_jax_f(cell_xyz[:, 1] * radius),
        zCell=to_jax_f(cell_xyz[:, 2] * radius),
        latEdge=to_jax_f(latEdge), lonEdge=to_jax_f(lonEdge),
        xEdge=to_jax_f(edge_xyz[:, 0] * radius),
        yEdge=to_jax_f(edge_xyz[:, 1] * radius),
        zEdge=to_jax_f(edge_xyz[:, 2] * radius),
        latVertex=to_jax_f(latVertex), lonVertex=to_jax_f(lonVertex),
        xVertex=to_jax_f(vertex_xyz[:, 0] * radius),
        yVertex=to_jax_f(vertex_xyz[:, 1] * radius),
        zVertex=to_jax_f(vertex_xyz[:, 2] * radius),
        cellsOnEdge=to_jax_i(cellsOnEdge),
        edgesOnCell=to_jax_i(edgesOnCell),
        verticesOnCell=to_jax_i(verticesOnCell),
        verticesOnEdge=to_jax_i(verticesOnEdge),
        edgesOnVertex=to_jax_i(edgesOnVertex),
        cellsOnVertex=to_jax_i(cellsOnVertex),
        cellsOnCell=to_jax_i(cellsOnCell),
        edgesOnEdge=to_jax_i(edgesOnEdge),
        nEdgesOnCell=to_jax_i(nEdgesOnCell_arr),
        nEdgesOnEdge=to_jax_i(nEdgesOnEdge_arr),
        areaCell=to_jax_f(areaCell),
        areaTriangle=to_jax_f(areaTriangle),
        dcEdge=to_jax_f(dcEdge),
        dvEdge=to_jax_f(dvEdge),
        angleEdge=to_jax_f(angleEdge),
        weightsOnEdge=to_jax_f(weightsOnEdge),
        kiteAreasOnVertex=to_jax_f(kiteAreasOnVertex),
        fEdge=to_jax_f(fEdge),
        fVertex=to_jax_f(fVertex),
        edgeSignOnCell=to_jax_f(edgeSignOnCell),
        edgeSignOnVertex=to_jax_f(edgeSignOnVertex),
        meshDensity=to_jax_f(np.ones(nCells)),
    )


def _compute_kite_areas(nVertices, vertexDegree, cellsOnVertex,
                         vertex_xyz, cell_xyz, verticesOnEdge,
                         edgesOnVertex, edge_xyz, radius,
                         periodic_L_rad=None):
    """Compute kite areas at each vertex for each adjacent cell.

    A kite at vertex v for cell c is the quadrilateral formed by:
    vertex v, midpoint of edge between v and next cell, cell center c,
    midpoint of edge between v and prev cell.

    When ``periodic_L_rad`` is set, kites near the seam have their four
    corners (vertex, two edge midpoints, cell center) seam-shifted
    relative to the vertex so the two spherical-triangle sub-areas
    reflect the true through-the-seam geometry.
    """
    kiteAreas = np.zeros((vertexDegree, nVertices), dtype=np.float64)

    for v in range(nVertices):
        for k in range(vertexDegree):
            c = cellsOnVertex[k, v]
            if c < 0:
                continue
            # Find the two edges of this vertex that bound cell c
            # These are the edges between (c, prev_cell) and (c, next_cell)
            e_prev = edgesOnVertex[(k - 1) % vertexDegree, v]
            e_curr = edgesOnVertex[k, v]

            if e_prev < 0 or e_curr < 0:
                continue

            # Kite: vertex_v, edge_midpoint_prev, cell_center_c, edge_midpoint_curr.
            # Anchor on the vertex; shift the other three points into the
            # vertex's longitude window so the great-circle geometry is
            # correct for seam kites.
            p_v = vertex_xyz[v]
            p_eprev = _shift_near(p_v, edge_xyz[e_prev], periodic_L_rad)
            p_c = _shift_near(p_v, cell_xyz[c], periodic_L_rad)
            p_ecurr = _shift_near(p_v, edge_xyz[e_curr], periodic_L_rad)

            # Area as sum of two spherical triangles
            a1 = _spherical_triangle_area(p_v, p_eprev, p_c, radius)
            a2 = _spherical_triangle_area(p_v, p_c, p_ecurr, radius)
            kiteAreas[k, v] = a1 + a2

    return kiteAreas


def _compute_edge_sign_on_cell(nCells, maxEdges, nEdgesOnCell, edgesOnCell,
                                cellsOnEdge):
    """Compute edgeSignOnCell: +1 if edge normal points outward from cell."""
    edgeSignOnCell = np.zeros((maxEdges, nCells), dtype=np.float64)
    for c in range(nCells):
        n = nEdgesOnCell[c]
        for k in range(n):
            e = edgesOnCell[k, c]
            if e < 0:
                continue
            if cellsOnEdge[0, e] == c:
                edgeSignOnCell[k, c] = 1.0   # normal points outward
            else:
                edgeSignOnCell[k, c] = -1.0  # normal points inward
    return edgeSignOnCell


def _compute_edge_sign_on_vertex(nVertices, vertexDegree, edgesOnVertex,
                                  cellsOnVertex, cellsOnEdge,
                                  vertex_xyz, cell_xyz, periodic_L_rad=None):
    """Compute edgeSignOnVertex for curl computation.

    edgeSignOnVertex(k, v) = +1 if the edge contributes positively to
    the counterclockwise circulation around vertex v, -1 otherwise.

    The sign is +1 if the edge normal (c1→c2) is oriented such that
    traversing from c1 to c2 is counterclockwise around vertex v.

    When ``periodic_L_rad`` is set, seam vertices shift their two
    bounding cells into the vertex's longitude window before the
    cross-product sign test.
    """
    edgeSignOnVertex = np.zeros((vertexDegree, nVertices), dtype=np.float64)
    for v in range(nVertices):
        v_pos = vertex_xyz[v]
        for k in range(vertexDegree):
            e = edgesOnVertex[k, v]
            if e < 0:
                continue
            c1 = cellsOnEdge[0, e]
            c2 = cellsOnEdge[1, e]
            # Shift cells near this vertex so (c - v) vectors are correct
            # across the seam.
            c1_pos = _shift_near(v_pos, cell_xyz[c1], periodic_L_rad)
            c2_pos = _shift_near(v_pos, cell_xyz[c2], periodic_L_rad)
            vec1 = c1_pos - v_pos
            vec2 = c2_pos - v_pos
            cross = np.cross(vec1, vec2)
            if np.dot(cross, v_pos) > 0:
                edgeSignOnVertex[k, v] = 1.0   # c1→c2 is CCW
            else:
                edgeSignOnVertex[k, v] = -1.0  # c1→c2 is CW
    return edgeSignOnVertex


def _compute_weights_on_edge(nEdges, maxEdges2, vertexDegree,
                              nEdgesOnCell, cellsOnEdge, verticesOnEdge,
                              edgesOnCell, kiteAreasOnVertex, cellsOnVertex,
                              areaCell, dvEdge, dcEdge):
    """Compute weights for tangential velocity reconstruction (TRiSK).

    Implements the Thuburn-Ringler kite-area formula
    (Ringler et al. 2010, J. Comput. Phys. 229, Eq. 24;
     Thuburn et al. 2009, J. Comput. Phys. 228, Eq. 33).

    The stored weight satisfies

        v_t(e) = Σ_k weightsOnEdge[k, e] · u(edgesOnEdge[k, e])

    with

        weightsOnEdge[e, e']  =  w_T(e, e') · dvEdge[e'] / dcEdge[e]

    where the dimensionless `w_T` is antisymmetric
    (w_T(e,e') + w_T(e',e) = 0) — this guarantees discrete energy
    conservation of the tangential reconstruction.  Unlike the Perot
    minimum-norm LSQ, this formula additionally preserves Thuburn's
    stationary geostrophic mode, which is required to avoid spurious
    baroclinic-instability growth on non-uniform Voronoi meshes.

    The algorithm mirrors the canonical MPAS-Tools
    `buildEdgesOnEdgeArrays` (mpas_mesh_converter.cpp):  for each
    iEdge, walk CCW around each adjacent cell starting from iEdge,
    accumulating kite-area fractions at each shared vertex, and
    push one stencil entry per edge encountered.
    """
    edgesOnEdge = np.full((maxEdges2, nEdges), -1, dtype=np.int32)
    weightsOnEdge = np.zeros((maxEdges2, nEdges), dtype=np.float64)
    nEdgesOnEdge_arr = np.zeros(nEdges, dtype=np.int32)

    for iEdge in range(nEdges):
        c1 = int(cellsOnEdge[0, iEdge])
        c2 = int(cellsOnEdge[1, iEdge])
        dc_iE = dcEdge[iEdge]
        if dc_iE <= 0.0:
            continue
        k_slot = 0

        # Cell c1 pass: global sign +1 (n_{iEdge} points out of c1).
        if c1 >= 0:
            k_slot = _trisk_walk(
                iEdge, c1, +1.0, k_slot,
                nEdgesOnCell, edgesOnCell, verticesOnEdge, cellsOnEdge,
                cellsOnVertex, kiteAreasOnVertex, areaCell,
                dvEdge, dc_iE, vertexDegree, maxEdges2,
                edgesOnEdge, weightsOnEdge,
            )

        # Cell c2 pass: global sign -1 (n_{iEdge} points into c2).
        if c2 >= 0:
            k_slot = _trisk_walk(
                iEdge, c2, -1.0, k_slot,
                nEdgesOnCell, edgesOnCell, verticesOnEdge, cellsOnEdge,
                cellsOnVertex, kiteAreasOnVertex, areaCell,
                dvEdge, dc_iE, vertexDegree, maxEdges2,
                edgesOnEdge, weightsOnEdge,
            )

        nEdgesOnEdge_arr[iEdge] = k_slot

    return edgesOnEdge, weightsOnEdge, nEdgesOnEdge_arr


def _trisk_walk(iEdge, c, global_sign, k_slot,
                nEdgesOnCell, edgesOnCell, verticesOnEdge, cellsOnEdge,
                cellsOnVertex, kiteAreasOnVertex, areaCell,
                dvEdge, dc_iE, vertexDegree, maxEdges2,
                edgesOnEdge, weightsOnEdge):
    """Walk CCW around cell c starting from iEdge, emitting TRiSK weights.

    For each subsequent edge `cur_edge` of c in CCW order:
      - find the vertex shared with `last_edge` (the previous edge on
        the walk; initially iEdge)
      - accumulate kite_area(shared_vertex, c) / areaCell[c] into area_sum
      - push  global_sign · n(cur_edge, c) · (0.5 - area_sum) · dv[cur] / dc[iEdge]
        into weightsOnEdge, where n(cur_edge, c) = +1 if
        cellsOnEdge[0, cur_edge] == c (normal points out of c), else -1.

    Returns the updated `k_slot` cursor.
    """
    ne = int(nEdgesOnCell[c])
    if ne <= 0:
        return k_slot

    # Find position of iEdge in edgesOnCell[:, c].
    pos = -1
    for i in range(ne):
        if int(edgesOnCell[i, c]) == iEdge:
            pos = i
            break
    if pos < 0:
        return k_slot  # malformed mesh: iEdge not in its own cell's list

    area_c = areaCell[c]
    if area_c <= 0.0:
        return k_slot

    last_edge = iEdge
    area_sum = 0.0
    for step in range(1, ne):
        i = (pos + step) % ne
        cur_edge = int(edgesOnCell[i, c])
        if cur_edge < 0 or cur_edge == iEdge:
            break

        # Shared vertex between last_edge and cur_edge.
        va0 = int(verticesOnEdge[0, last_edge])
        va1 = int(verticesOnEdge[1, last_edge])
        vb0 = int(verticesOnEdge[0, cur_edge])
        vb1 = int(verticesOnEdge[1, cur_edge])
        shared = -1
        if va0 >= 0 and (va0 == vb0 or va0 == vb1):
            shared = va0
        elif va1 >= 0 and (va1 == vb0 or va1 == vb1):
            shared = va1
        if shared < 0:
            break

        # Accumulate kite-area fraction of cell c at the shared vertex.
        for j in range(vertexDegree):
            if int(cellsOnVertex[j, shared]) == c:
                area_sum += kiteAreasOnVertex[j, shared] / area_c
                break

        # Edge-orientation sign: +1 if cur_edge normal points out of c.
        edge_sign = 1.0 if int(cellsOnEdge[0, cur_edge]) == c else -1.0
        w_dimless = global_sign * edge_sign * (0.5 - area_sum)
        w_store = w_dimless * dvEdge[cur_edge] / dc_iE

        if k_slot < maxEdges2:
            edgesOnEdge[k_slot, iEdge] = cur_edge
            weightsOnEdge[k_slot, iEdge] = w_store
            k_slot += 1
        last_edge = cur_edge

    return k_slot


# ============================================================================
# Public API
# ============================================================================

# ============================================================================
# Mesh disk cache (avoids redundant per-rank SCVT rebuild under MPI)
# ============================================================================
#
# create_voronoi_mesh runs Lloyd relaxation (scipy SphericalVoronoi) which is
# DETERMINISTIC in (subdivision_level, radius, lloyd_iterations, omega) when
# density_fn is None, and slow (~10^2 s at level>=6).  Under MPI every rank
# rebuilds the SAME mesh; at 32 ranks/node the redundant builds contend for
# cores and exceed the job walltime (the multi-node "hang" was this, not an MPI
# fault: a surviving rank reported mesh=105.4 s while its peers timed out).
# Caching the built mesh to a shared-filesystem .npz lets the first process
# build once and every other process (this run or a later one) load it in
# O(1 s).  Pre-warm once before an MPI launch (prewarm_voronoi_cache) so all
# ranks only load.

_MESH_CACHE_ENV = "LEGOESM_MESH_CACHE_DIR"
_MESH_CACHE_DISABLE_ENV = "LEGOESM_MESH_CACHE_DISABLE"

# Big-mesh policy (codex round-19, issue: subdiv-8 cap blocked 128-GPU MPAS).
# Levels <= ROUTINE build freely (cheap). ROUTINE+1 .. MAX are
# cache-or-prewarm ONLY: a hit loads; a miss raises unless this process is
# the designated single builder (env below + exclusive lockfile — the
# opt-in alone would be a thundering herd across an MPI launch). > MAX is
# hard-refused (42M+ cells; the scipy SphericalVoronoi path does not scale
# there). Build cost measured 2026-07-29: one Lloyd iteration = 21.6 s at
# subdiv-7, 87.1 s at subdiv-8 (~4x per level).
_BIG_MESH_ROUTINE_LEVEL = 8
_BIG_MESH_MAX_LEVEL = 10
_BIG_MESH_BUILD_ENV = "LEGOESM_ALLOW_BIG_MESH_BUILD"
_BIG_MESH_LOCK_STALE_S = 7200.0   # lloyd=50 at subdiv-9 ~ 5 h; lloyd=0 ~ min
# Bump whenever the SCVT/connectivity/geometry construction changes VALUES for
# unchanged args (e.g. edits to _lloyd_relaxation / _build_mesh_from_generators).
# The schema check below only catches FIELD changes; a value-changing algorithm
# edit must invalidate old caches via this token.
_MESH_CACHE_VERSION = 1


def _voronoi_cache_disabled() -> bool:
    """True when LEGOESM_MESH_CACHE_DISABLE is set to a truthy value."""
    return os.environ.get(_MESH_CACHE_DISABLE_ENV, "").strip().lower() in (
        "1", "true", "yes", "on")


def _voronoi_cache_dir() -> str:
    """Cache directory (LEGOESM_MESH_CACHE_DIR or ~/.cache/legoesm/voronoi)."""
    d = os.environ.get(_MESH_CACHE_ENV, "").strip()
    if not d:
        d = os.path.join(
            os.path.expanduser("~"), ".cache", "legoesm", "voronoi")
    return d


def _voronoi_cache_path(
    subdivision_level: int, radius: float, lloyd_iterations: int, omega: float
) -> str:
    """Deterministic cache filename keyed on every parameter that changes the mesh.

    Includes the active x64 flag because the stored dtypes (and a fresh rebuild)
    depend on it — a float32-built mesh must never be served to an x64 run.
    ``radius``/``omega`` use ``repr`` (round-trippable for Python floats).
    """
    x64 = bool(jax.config.read("jax_enable_x64"))
    name = (
        f"scvt_v{_MESH_CACHE_VERSION}_lvl{subdivision_level}"
        f"_r{radius!r}_omega{omega!r}_lloyd{lloyd_iterations}"
        f"_x64{int(x64)}.npz"
    )
    return os.path.join(_voronoi_cache_dir(), name)


def _load_voronoi_cache(path: str):
    """Reconstruct a VoronoiMesh from *path*, or None on miss/corruption/schema drift."""
    if not os.path.exists(path):
        return None
    try:
        with np.load(path) as data:
            if set(data.files) != set(VoronoiMesh._fields):
                # Stale schema (fields added/removed) -> ignore, rebuild.
                return None
            fields = {}
            for field_name in VoronoiMesh._fields:
                arr = data[field_name]
                if arr.ndim == 0:
                    fields[field_name] = arr.item()        # scalar (nCells, radius, ...)
                else:
                    fields[field_name] = jnp.asarray(arr)  # respects current x64
        return VoronoiMesh(**fields)
    except Exception as exc:  # corrupt / truncated cache file -> rebuild
        warnings.warn(
            f"Ignoring unreadable Voronoi mesh cache {path!r}: {exc}",
            RuntimeWarning, stacklevel=2)
        return None


def _save_voronoi_cache(path: str, mesh: "VoronoiMesh") -> None:
    """Atomically write *mesh* to *path* (tmp + os.replace; safe under the N-rank race)."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    arrays = {field_name: np.asarray(getattr(mesh, field_name))
              for field_name in mesh._fields}
    tmp = f"{path}.tmp.{os.getpid()}"
    try:
        with open(tmp, "wb") as f:
            np.savez(f, **arrays)  # file handle -> no .npz extension munging
        os.replace(tmp, path)      # atomic on same filesystem; last writer wins
    except Exception as exc:  # never let a cache-write failure break generation
        warnings.warn(
            f"Could not write Voronoi mesh cache {path!r}: {exc}",
            RuntimeWarning, stacklevel=2)
        try:
            if os.path.exists(tmp):
                os.remove(tmp)
        except OSError:
            pass


def prewarm_voronoi_cache(
    subdivision_level: int,
    radius: float = constants.R_earth,
    lloyd_iterations: int = 50,
    omega: float = constants.Omega,
) -> str:
    """Build (if absent) and cache the uniform SCVT mesh; return the cache path.

    Call ONCE from a single process before an MPI launch so every rank loads the
    mesh instead of redundantly rebuilding it.  Cheap no-op when already cached
    (create_voronoi_mesh returns the cached mesh without rebuilding).
    """
    if _voronoi_cache_disabled():
        raise RuntimeError(
            f"{_MESH_CACHE_DISABLE_ENV} is set; cannot pre-warm a disabled cache.")
    path = _voronoi_cache_path(subdivision_level, radius, lloyd_iterations, omega)
    create_voronoi_mesh(
        subdivision_level, radius=radius,
        lloyd_iterations=lloyd_iterations, omega=omega)
    return path


def create_voronoi_mesh(
    subdivision_level: int,
    radius: float = constants.R_earth,
    lloyd_iterations: int = 50,
    omega: float = constants.Omega,
    density_fn=None,
) -> VoronoiMesh:
    """Create a centroidal Voronoi tessellation (SCVT) on the sphere.

    Starts from an icosahedral triangulation, bisects to the desired
    level, applies Lloyd relaxation, then builds the full MPAS-compatible
    mesh with all connectivity and geometric arrays.

    Parameters
    ----------
    subdivision_level : int
        Number of bisection levels. nCells = 10*4^level + 2.
        level=3: 642 cells, level=4: 2562, level=5: 10242.
    radius : float
        Sphere radius [m]. Default: Earth radius.
    lloyd_iterations : int
        Number of Lloyd relaxation iterations. Default: 50.
    omega : float
        Rotation rate [rad/s]. Default: Earth rotation.
    density_fn : callable(lat, lon) -> float, optional
        Relative mesh-density function (``lat``, ``lon`` in radians; larger =>
        finer cells).  When provided, the Lloyd relaxation is **density-weighted**
        (Du–Faber–Gunzburger SCVT): generators concentrate where the density is
        high, yielding a VARIABLE-RESOLUTION mesh refined over the high-density
        region (the MPAS variable-resolution capability).  Cell area relaxes toward
        ``~ 1/density`` (weighting by ``density**2``), so a region with relative
        density ``d`` gets roughly ``d`` x smaller cells.  ``None`` (default) =>
        the uniform quasi-uniform SCVT (unchanged).  Host-side mesh generation —
        the callable is plain NumPy, never traced.  NOTE: Lloyd relaxation converges
        linearly, so the achieved refinement contrast grows with
        ``lloyd_iterations``; for strong/precise variable resolution prefer a
        JIGSAW-built mesh loaded via :func:`load_mpas_mesh`.

    Returns
    -------
    VoronoiMesh
    """
    if subdivision_level > _BIG_MESH_MAX_LEVEL:
        n_cells = 10 * 4 ** subdivision_level + 2
        raise ValueError(
            f"subdivision_level={subdivision_level} would create {n_cells:.2e} "
            f"cells — unsupported (hard cap {_BIG_MESH_MAX_LEVEL}; the scipy "
            f"SphericalVoronoi build path does not scale there). For higher "
            f"resolutions, use load_mpas_mesh() with a pre-built mesh file."
        )
    # Levels above the routine cap are CACHE-OR-PREWARM only (codex round-19
    # design): a valid cache hit is always admissible; a MISS is refused
    # unless this process is the designated prewarmer — otherwise an N-rank
    # MPI launch would have every rank silently rebuild for hours (build is
    # ~87 s/Lloyd-iteration at subdiv-8, ~4x that at 9). The prewarm path is
    # single-builder: an exclusive lockfile serialises concurrent opt-ins.
    _big = subdivision_level > _BIG_MESH_ROUTINE_LEVEL

    # Disk cache: a uniform SCVT mesh is deterministic in these args, so skip the
    # expensive rebuild on a hit.  density_fn meshes are NOT cached (a callable
    # has no stable key); the env switch lets a run force a fresh build.
    use_cache = density_fn is None and not _voronoi_cache_disabled()
    cache_path = None
    if use_cache:
        cache_path = _voronoi_cache_path(
            subdivision_level, radius, lloyd_iterations, omega)
        cached = _load_voronoi_cache(cache_path)
        if cached is not None:
            return cached

    _lock_path = None
    if _big:
        if not use_cache:
            raise ValueError(
                f"subdivision_level={subdivision_level} needs the mesh disk "
                f"cache (density_fn=None and {_MESH_CACHE_DISABLE_ENV} unset)"
                f" — an uncached big-mesh build would repeat per rank.")
        if os.environ.get(_BIG_MESH_BUILD_ENV, "") != "1":
            raise ValueError(
                f"subdivision_level={subdivision_level}: no cached mesh at "
                f"{cache_path} and this process is not the designated "
                f"prewarmer. Build the cache ONCE via scripts/data/"
                f"prewarm_voronoi_mesh.py (or set {_BIG_MESH_BUILD_ENV}=1 in "
                f"a SINGLE-process job), then rerun.")
        # Single-builder lock (codex round-19: the opt-in alone is a
        # thundering herd — N authorized ranks could all miss). O_EXCL
        # lockfile beside the cache; losers wait for the winner's atomic
        # os.replace to land and then load it. Stale locks (builder died)
        # are stolen after _BIG_MESH_LOCK_STALE_S with a warning.
        _lock_path = f"{cache_path}.lock"
        import time as _time
        while True:
            try:
                _fd = os.open(_lock_path, os.O_CREAT | os.O_EXCL | os.O_WRONLY)
                os.write(_fd, str(os.getpid()).encode())
                os.close(_fd)
                break                      # we are the builder
            except FileExistsError:
                for _ in range(int(_BIG_MESH_LOCK_STALE_S)):
                    _time.sleep(1.0)
                    cached = _load_voronoi_cache(cache_path)
                    if cached is not None:
                        return cached      # winner finished; use its mesh
                    if not os.path.exists(_lock_path):
                        break              # lock released without a cache?!
                else:
                    try:                   # stale: builder likely died
                        os.unlink(_lock_path)
                    except FileNotFoundError:
                        pass
                    import warnings
                    warnings.warn(
                        f"stale big-mesh lock {_lock_path} removed after "
                        f"{_BIG_MESH_LOCK_STALE_S}s; taking over the build.")

    # Step 1: Icosahedral base
    verts, triangles = _icosahedral_base()

    # Step 2: Bisect to desired resolution
    if subdivision_level > 0:
        verts, triangles = _bisect_mesh(verts, triangles, subdivision_level)

    # Step 3: Lloyd relaxation for SCVT (density-weighted when density_fn given)
    if lloyd_iterations > 0 and subdivision_level > 0:
        cell_points = _lloyd_relaxation(
            verts, n_iter=lloyd_iterations, density_fn=density_fn)
    elif density_fn is not None:
        raise ValueError(
            "density_fn requires lloyd_iterations > 0 and subdivision_level > 0 "
            "(the variable-resolution mesh is produced by density-weighted Lloyd "
            "relaxation; with no relaxation the icosahedral seed stays uniform)."
        )
    else:
        cell_points = verts

    # Step 4: Build complete mesh
    mesh = _build_mesh_from_generators(cell_points, radius, omega)
    if use_cache and cache_path is not None:
        _save_voronoi_cache(cache_path, mesh)
    if _lock_path is not None:
        # Release AFTER the atomic cache save: waiters poll the cache, so
        # the lock's job is done once the mesh is loadable.
        try:
            os.unlink(_lock_path)
        except FileNotFoundError:
            pass
    return mesh


# ============================================================================
# Regional mesh generation
# ============================================================================

def _stereo_project(xyz, pole):
    """Stereographic projection from *pole* onto the tangent plane.

    Parameters
    ----------
    xyz : ndarray, shape (N, 3)
        Points on the unit sphere.
    pole : ndarray, shape (3,)
        Projection pole (unit vector). The tangent plane is at the
        antipodal point.

    Returns
    -------
    xy : ndarray, shape (N, 2)
        2-D projected coordinates.
    """
    p = pole / np.linalg.norm(pole)

    # Build ONB for the plane perpendicular to p
    if abs(p[2]) < 0.9:
        up = np.array([0.0, 0.0, 1.0])
    else:
        up = np.array([1.0, 0.0, 0.0])
    e1 = np.cross(up, p)
    e1 /= np.linalg.norm(e1)
    e2 = np.cross(p, e1)

    dot = xyz @ p  # (N,)
    denom = 1.0 + dot  # (N,)
    denom = np.maximum(denom, 1e-15)
    scale = 2.0 / denom

    diff = xyz - dot[:, None] * p[None, :]
    x_proj = np.sum(diff * e1[None, :], axis=1) * scale
    y_proj = np.sum(diff * e2[None, :], axis=1) * scale
    return np.stack([x_proj, y_proj], axis=1)


def _seed_regional_generators(lon_range, lat_range, resolution_km, radius,
                               periodic_x=False):
    """Seed quasi-uniform hex generators on the sphere in a regional domain.

    Uses uniform angular dlon spacing (same cell count per row) to avoid
    degenerate Voronoi edges at row boundaries. A buffer ring of ~1.5x
    resolution is added around the domain.

    When ``periodic_x=True`` with ``lon_range`` spanning the full 360°,
    longitude wraps around the sphere with no duplicate generators at the
    seam.  When ``periodic_x=True`` with a smaller zonal range, generators
    are seeded within ``lon_range`` and the east/west boundaries are
    identified (zonally-periodic regional channel on the sphere).  Only
    latitude gets a buffer ring in either periodic case.

    Parameters
    ----------
    lon_range : tuple[float, float]
        Longitude range in degrees [lon_min, lon_max]. When
        ``periodic_x=True`` this is the periodic zonal extent; generators
        live within [lon_min, lon_max) and lon_max is identified with
        lon_min.
    lat_range : tuple[float, float]
        Latitude range in degrees [lat_min, lat_max].
    resolution_km : float
        Target cell spacing in km.
    radius : float
        Sphere radius in m.
    periodic_x : bool
        If True, seed generators around the periodic zonal extent.

    Returns
    -------
    cell_xyz : ndarray, shape (nCells, 3)
        Generator points on the unit sphere.
    """
    lat_min = np.radians(lat_range[0])
    lat_max = np.radians(lat_range[1])

    d_rad = resolution_km * 1000.0 / radius

    # Latitude buffer (both periodic and closed cases)
    buffer = 3.0 * d_rad
    lat_min_buf = max(lat_min - buffer, -np.pi / 2 + 0.01)
    lat_max_buf = min(lat_max + buffer, np.pi / 2 - 0.01)

    lat_center = 0.5 * (lat_min_buf + lat_max_buf)
    dlon = d_rad / max(np.cos(lat_center), 0.1)
    dlat = d_rad

    lats = np.arange(lat_min_buf, lat_max_buf + 0.5 * dlat, dlat)

    if periodic_x:
        # Periodic in longitude. Full 360° or sub-360° zonal extent.
        lon_min_rad = np.radians(lon_range[0])
        lon_max_rad = np.radians(lon_range[1])
        L_rad = lon_max_rad - lon_min_rad
        if L_rad <= 0 or L_rad > 2.0 * np.pi + 1e-10:
            raise ValueError(
                f"periodic-x requires 0 < L_rad ≤ 2π, got {L_rad} rad "
                f"(lon_range={lon_range})"
            )
        # Exact integer number of cells around the periodic extent.
        # Force ``n_lon`` even so that the hex row-offset staggering
        # (lons shifted by dlon/2 on odd rows) closes consistently at
        # the seam.
        n_lon = max(2, int(np.round(L_rad / dlon)))
        if n_lon % 2 == 1:
            n_lon += 1
        dlon_exact = L_rad / n_lon

        generators = []
        for i_row, lat in enumerate(lats):
            offset = 0.5 * dlon_exact if (i_row % 2 == 1) else 0.0
            lons = lon_min_rad + offset + np.arange(n_lon) * dlon_exact
            for lon in lons:
                x = np.cos(lat) * np.cos(lon)
                y = np.cos(lat) * np.sin(lon)
                z = np.sin(lat)
                generators.append([x, y, z])
    else:
        # Closed basin: longitude buffer on both sides
        lon_min = np.radians(lon_range[0])
        lon_max = np.radians(lon_range[1])
        lon_min_buf = lon_min - buffer
        lon_max_buf = lon_max + buffer
        n_lon = max(1, int(np.ceil((lon_max_buf - lon_min_buf) / dlon)))

        generators = []
        for i_row, lat in enumerate(lats):
            offset = 0.5 * dlon if (i_row % 2 == 1) else 0.0
            lons = lon_min_buf + offset + np.arange(n_lon) * dlon
            for lon in lons:
                x = np.cos(lat) * np.cos(lon)
                y = np.cos(lat) * np.sin(lon)
                z = np.sin(lat)
                generators.append([x, y, z])

    cell_xyz = np.array(generators, dtype=np.float64)
    norms = np.linalg.norm(cell_xyz, axis=1, keepdims=True)
    cell_xyz /= norms
    return cell_xyz


def _regional_delaunay(cell_xyz, resolution_km, radius, periodic_x=False,
                       lon_range=None):
    """Compute Delaunay triangulation for regional points.

    For closed basins (``periodic_x=False``), uses stereographic projection
    from the centroid + 2D Delaunay.

    For a full 360° zonal band (``periodic_x=True`` with L ≈ 2π), uses
    stereographic projection through the centroid (which sits on the
    z-axis by zonal symmetry) to form an annulus in 2D; the annular
    Delaunay naturally connects the east-west seam.

    For a sub-360° zonal band (``periodic_x=True`` with L < 2π − ε), the
    centroid is not on the z-axis and the stereographic annulus does not
    close, so we use an **unroll-and-ghost** 2D triangulation: cells
    within ~3 Δx of each seam are duplicated on the opposite side as
    ghosts, a 2D Delaunay over the unrolled (u=lon−lon_min, lat)
    rectangle connects real cells to ghosts of their seam partners, and
    the resulting triangles are mapped back to originals and
    deduplicated.  This yields a triangulation that is Delaunay-correct
    on the periodic cylinder topology.

    Parameters
    ----------
    cell_xyz : ndarray, shape (N, 3)
        Points on the unit sphere.
    resolution_km : float
        Target resolution in km (used for degenerate-triangle filter).
    radius : float
        Sphere radius in m.
    periodic_x : bool
        If True, use an approach suited to zonal periodicity.
    lon_range : tuple[float, float] or None
        Required when ``periodic_x=True`` and L < 360°: the (lon_min,
        lon_max) of the periodic zonal extent in degrees. Ignored when
        L ≈ 360° or when ``periodic_x=False``.

    Returns
    -------
    triangles : ndarray, shape (M, 3)
        Filtered triangle vertex indices.
    """
    d_rad = resolution_km * 1000.0 / radius
    # Oversize-edge cutoff for Delaunay triangle acceptance.  The correct
    # value is path-dependent:
    #   - sub-360° periodic (unroll+ghost):  1.5·d_rad.  The unroll+ghost
    #     Delaunay in (u·cos(lat_c), lat) coordinates produces pathological
    #     seam triangles with a meridional third leg of exactly 2·d_rad
    #     (two rows at identical lon).  These pass a looser 3·d_rad
    #     threshold and poison TRiSK with phantom edges (issue #211).
    #     1.5·d_rad is a comfortable margin above legitimate edges
    #     (~1.0–1.15·d_rad) and well below the 2·d_rad pathology.
    #   - bounded / full-360°:  3·d_rad.  The stereographic-projection
    #     path produces legitimate convex-hull boundary triangles with
    #     edge lengths up to ~2·d_rad; tightening to 1.5·d_rad here
    #     filter-orphans them and breaks antisymmetry.
    _sub360_periodic = (
        periodic_x and lon_range is not None
        and abs(np.radians(lon_range[1] - lon_range[0]) - 2.0 * np.pi) > 1e-6
    )
    max_edge = (1.5 if _sub360_periodic else 3.0) * d_rad

    if periodic_x:
        # Decide between full-360° stereographic-annulus and sub-360°
        # unroll-and-ghost path based on the zonal extent.
        if lon_range is None:
            L_rad = 2.0 * np.pi  # legacy full-360° default
        else:
            L_rad = np.radians(lon_range[1] - lon_range[0])
        if abs(L_rad - 2.0 * np.pi) < 1e-6:
            # Full zonal band: stereographic from the centroid's antipode.
            centroid = cell_xyz.mean(axis=0)
            centroid /= np.linalg.norm(centroid)
            xy = _stereo_project(cell_xyz, centroid)
            tri = Delaunay(xy)
            triangles = tri.simplices.copy()
        else:
            triangles = _periodic_unroll_delaunay(
                cell_xyz, lon_range, resolution_km, radius
            )
    else:
        centroid = cell_xyz.mean(axis=0)
        centroid /= np.linalg.norm(centroid)
        # _stereo_project uses denom = 1 + dot(xyz, pole), which effectively
        # projects from -pole.  Setting pole = +centroid means the projection
        # is from -centroid (the true antipodal point), so data near +centroid
        # gets denom ≈ 2 and well-behaved projected coordinates.
        pole = centroid

        xy = _stereo_project(cell_xyz, pole)

        tri = Delaunay(xy)
        triangles = tri.simplices.copy()

    # Filter degenerate triangles: any edge > max_edge (1.5x for sub-360°
    # periodic, 3x otherwise — see max_edge definition above).
    # For sub-360° periodic, use seam-aware distances so valid seam
    # triangles are retained.
    L_for_shift = None
    if periodic_x and lon_range is not None:
        _L = np.radians(lon_range[1] - lon_range[0])
        if abs(_L - 2.0 * np.pi) > 1e-6:
            L_for_shift = _L

    keep = []
    for t in triangles:
        i0, i1, i2 = int(t[0]), int(t[1]), int(t[2])
        p0 = cell_xyz[i0]
        if L_for_shift is None:
            p1 = cell_xyz[i1]
            p2 = cell_xyz[i2]
        else:
            p1 = _shift_near(p0, cell_xyz[i1], L_for_shift)
            p2 = _shift_near(p0, cell_xyz[i2], L_for_shift)
        d01 = np.arccos(np.clip(np.dot(p0, p1), -1, 1))
        d12 = np.arccos(np.clip(np.dot(p1, p2), -1, 1))
        d20 = np.arccos(np.clip(np.dot(p2, p0), -1, 1))
        if d01 <= max_edge and d12 <= max_edge and d20 <= max_edge:
            keep.append(t)

    if len(keep) == 0:
        raise ValueError(
            "All Delaunay triangles were filtered as degenerate. "
            "Try increasing resolution_km or expanding the domain."
        )

    return np.array(keep, dtype=np.int64)


def _periodic_unroll_delaunay(cell_xyz, lon_range, resolution_km, radius):
    """Delaunay triangulation on a sub-360° periodic-x zonal band.

    Unrolls the cells into a 2D rectangle ``(u, lat)`` with
    ``u = lon − lon_min ∈ [0, L)``, duplicates cells within a buffer of
    each seam on the opposite side (ghost cells at u ± L), and
    triangulates the combined point set using scipy's 2D Delaunay. The
    resulting triangles are mapped back from ghost indices to their
    original cell indices and deduplicated.

    The returned triangle list is Delaunay-correct on the periodic
    cylinder topology — cells near the east seam connect to cells near
    the west seam through the ghost copies. The caller still performs
    an oversize-edge filter using seam-aware great-circle distances.

    Parameters
    ----------
    cell_xyz : ndarray, shape (N, 3)
        Points on the unit sphere.
    lon_range : tuple[float, float]
        (lon_min, lon_max) in degrees for the periodic zonal extent.
    resolution_km : float
        Target cell spacing in km; sets the ghost-buffer width.
    radius : float
        Sphere radius in m.

    Returns
    -------
    triangles : ndarray, shape (M, 3)
        Triangle vertex indices into the original ``cell_xyz`` array.
    """
    N = len(cell_xyz)
    lon_min_rad = np.radians(lon_range[0])
    lon_max_rad = np.radians(lon_range[1])
    L_rad = lon_max_rad - lon_min_rad
    d_rad = resolution_km * 1000.0 / radius
    # Ghost ring width. Must be ≥ a few cells so the unrolled Delaunay
    # has enough overlap on each side to produce the correct seam
    # connectivity; 3.5 cells is comfortable.
    buffer_rad = 3.5 * d_rad

    lat = np.arcsin(np.clip(cell_xyz[:, 2], -1.0, 1.0))
    lon = np.arctan2(cell_xyz[:, 1], cell_xyz[:, 0])
    # Bring lon into [lon_min_rad, lon_min_rad + 2π)
    lon_wrapped = np.mod(lon - lon_min_rad, 2.0 * np.pi) + lon_min_rad
    u = lon_wrapped - lon_min_rad  # in [0, 2π); valid cells in [0, L_rad)
    # Generators sitting exactly on the west meridian (u = 0) can round-trip
    # through xyz → arctan2 to lon_min − ε (float error), so np.mod() wraps
    # them to u ≈ 2π instead of 0. Fold any value within a hair of the full
    # circle back onto the west seam so the sanity check below does not mistake
    # a seam generator for an out-of-extent one. The tolerance is far below any
    # real cell spacing, so a genuine out-of-extent seed (a true seeding bug),
    # which would land in (L_rad, 2π − tol), is still caught and raised.
    _seam_fold_tol = 1e-9
    u = np.where(u > 2.0 * np.pi - _seam_fold_tol, u - 2.0 * np.pi, u)

    # Sanity check — cells must lie within the periodic extent.  Allow a
    # small tolerance for rounding near the seam.
    if (u < -1e-6).any() or (u > L_rad + 1e-6).any():
        raise ValueError(
            "Some generators fall outside the periodic zonal extent "
            f"[lon_min, lon_max)={lon_range}. Check the seeding step."
        )
    u = np.clip(u, 0.0, L_rad - 1e-12)

    # Build unrolled 2D points: (u, lat) in radians. Scale u by
    # cos(lat_center) to roughly undo the meridional stretch of pure
    # (u, lat) so Delaunay sees near-isotropic distances. This only
    # affects triangulation quality (never metric quantities, which are
    # always computed on the sphere in _build_mesh_from_generators).
    lat_center = 0.5 * (lat.min() + lat.max())
    u_scale = max(np.cos(lat_center), 0.1)
    pts = np.column_stack([u * u_scale, lat])
    orig_idx = np.arange(N, dtype=np.int64)

    # Left-seam ghosts: cells with u < buffer → duplicate at u + L
    left_mask = u < buffer_rad
    if left_mask.any():
        ghost_u = (u[left_mask] + L_rad) * u_scale
        ghost_lat = lat[left_mask]
        pts = np.vstack([pts, np.column_stack([ghost_u, ghost_lat])])
        orig_idx = np.concatenate([orig_idx, np.arange(N)[left_mask]])

    # Right-seam ghosts: cells with u > L - buffer → duplicate at u - L
    right_mask = u > L_rad - buffer_rad
    if right_mask.any():
        ghost_u = (u[right_mask] - L_rad) * u_scale
        ghost_lat = lat[right_mask]
        pts = np.vstack([pts, np.column_stack([ghost_u, ghost_lat])])
        orig_idx = np.concatenate([orig_idx, np.arange(N)[right_mask]])

    tri = Delaunay(pts)
    mapped = orig_idx[tri.simplices]  # shape (M, 3) into original cells

    # Deduplicate and drop triangles that become degenerate after the
    # ghost→original remap (two vertices with the same original index).
    seen = set()
    unique_tris = []
    for t in mapped:
        a, b, c = int(t[0]), int(t[1]), int(t[2])
        if a == b or b == c or a == c:
            continue
        key = tuple(sorted((a, b, c)))
        if key in seen:
            continue
        seen.add(key)
        unique_tris.append((a, b, c))
    return np.array(unique_tris, dtype=np.int64)


def create_regional_voronoi_mesh(
    lon_range: tuple[float, float],
    lat_range: tuple[float, float],
    resolution_km: float = 300.0,
    radius: float = constants.R_earth,
    omega: float = constants.Omega,
    periodic_x: bool = False,
) -> VoronoiMesh:
    """Create a regional spherical Voronoi mesh for ocean dynamics testing.

    Generates a quasi-uniform hex mesh covering a lat/lon region + buffer,
    builds the Delaunay triangulation via stereographic projection, and
    constructs the full MPAS-compatible ``VoronoiMesh``. Boundary cells
    (outside the target domain) serve as buffer/land cells via the
    existing lat/lon land-mask mechanism.

    When ``periodic_x=True``, generators are seeded within
    ``lon_range`` and the east/west meridians are identified — topologically
    a cylindrical channel on the sphere.  When ``lon_range`` spans the
    full 360°, this is a zonal annular channel (no seam corrections
    needed).  When ``lon_range`` is sub-360°, an "unroll-and-ghost"
    Delaunay and seam-aware edge/triangle geometry are used so a
    regional channel of arbitrary zonal extent can be built — the
    east/west meridians wrap correctly and TRiSK operators see the
    intended through-the-seam distances, midpoints, and areas.  Use this
    for channel-like experiments (e.g. Eady baroclinic instability).

    Unlike the global ``create_voronoi_mesh``, this function:

    - Seeds generators only in the target region (+ buffer ring)
    - Uses uniform angular dlon spacing (same cell count per row) to
      avoid degenerate Voronoi edges at row boundaries
    - Uses Delaunay triangulation via stereographic projection (closed
      basin), via a stereographic annulus (full 360° periodic), or via
      an unroll-and-ghost 2D triangulation (sub-360° periodic)
    - Filters degenerate hull triangles (edge > 3x resolution)
    - Skips Lloyd relaxation (distorts boundary cells)
    - Sets safety floors on dvEdge and areaTriangle for boundary cells

    Parameters
    ----------
    lon_range : tuple[float, float]
        Longitude range in degrees [lon_min, lon_max]. When
        ``periodic_x=True``, this is also the periodic zonal extent: the
        east meridian at ``lon_max`` is identified with the west meridian
        at ``lon_min``.
    lat_range : tuple[float, float]
        Latitude range in degrees [lat_min, lat_max].
    resolution_km : float
        Target cell spacing in km. Default: 300 km.
    radius : float
        Sphere radius [m]. Default: Earth radius.
    omega : float
        Rotation rate [rad/s]. Default: Earth rotation.
    periodic_x : bool
        If True, the east/west meridians of ``lon_range`` are
        identified.  Sub-360° periodic-x is fully supported — see
        "unroll-and-ghost" note above.

    Returns
    -------
    VoronoiMesh
        Regional mesh ready for use with all TRiSK operators.

    Notes
    -----
    The motivation is that global MPAS meshes waste computation on land
    for regional tests, while lat-lon A-grid barotropic solvers suffer
    from checkerboard instability. This function provides a regional
    C-grid (TRiSK) mesh for stable ocean dynamics testing.

    References
    ----------
    - Issue #88: regional mesh for ocean dynamics testing
    - Ringler, T. D., et al. (2010). J. Comput. Phys., 229(9), 3065-3090.
    """
    # Compute the zonal-periodic extent (if any) so downstream steps know
    # how to handle seam edges / triangles.
    if periodic_x:
        L_rad = np.radians(lon_range[1] - lon_range[0])
        if L_rad <= 0 or L_rad > 2.0 * np.pi + 1e-10:
            raise ValueError(
                f"periodic_x=True requires 0 < L ≤ 360°, got lon_range={lon_range}"
            )
        periodic_L_rad = L_rad if abs(L_rad - 2.0 * np.pi) > 1e-6 else None
    else:
        periodic_L_rad = None

    # Step 1: Seed generators in the target region + buffer
    cell_xyz = _seed_regional_generators(lon_range, lat_range,
                                         resolution_km, radius,
                                         periodic_x=periodic_x)

    # Step 2: Delaunay triangulation (stereographic for closed,
    # stereographic-annulus for full 360° periodic, unroll-and-ghost for
    # sub-360° periodic).
    triangles = _regional_delaunay(cell_xyz, resolution_km, radius,
                                    periodic_x=periodic_x,
                                    lon_range=lon_range)

    # Step 3: Build complete mesh with seam-aware geometry when periodic.
    mesh = _build_mesh_from_generators(cell_xyz, radius, omega,
                                       triangles=triangles,
                                       periodic_L_rad=periodic_L_rad)

    # Step 4: Apply safety floors on dvEdge and areaTriangle.
    # Boundary edges may have only one adjacent triangle, giving
    # dvEdge = 0.  Set a floor to prevent NaN in TRiSK operators.
    d_rad = resolution_km * 1000.0 / radius
    dvEdge_floor = 0.1 * d_rad * radius  # 10% of resolution
    areaTriangle_floor = 0.01 * (d_rad * radius) ** 2  # 1% of cell area

    dvEdge_safe = jnp.maximum(mesh.dvEdge, dvEdge_floor)
    areaTriangle_safe = jnp.maximum(mesh.areaTriangle, areaTriangle_floor)

    # The TRiSK weights scale with dvEdge/dcEdge, so recompute them
    # using the floored dvEdge so the stored weightsOnEdge is
    # consistent with the final mesh geometry.  (The old LSQ weights
    # used only angleEdge and were blind to this inconsistency, which
    # masked baroclinic-instability amplification driven by stale
    # near-zero dvEdge values — see issue #211.)
    maxEdges2 = mesh.edgesOnEdge.shape[0]
    edgesOnEdge_new, weightsOnEdge_new, nEdgesOnEdge_new = (
        _compute_weights_on_edge(
            mesh.nEdges, maxEdges2, mesh.vertexDegree,
            np.asarray(mesh.nEdgesOnCell),
            np.asarray(mesh.cellsOnEdge),
            np.asarray(mesh.verticesOnEdge),
            np.asarray(mesh.edgesOnCell),
            np.asarray(mesh.kiteAreasOnVertex, dtype=np.float64),
            np.asarray(mesh.cellsOnVertex),
            np.asarray(mesh.areaCell, dtype=np.float64),
            np.asarray(dvEdge_safe, dtype=np.float64),
            np.asarray(mesh.dcEdge, dtype=np.float64),
        )
    )
    _w_dtype = mesh.weightsOnEdge.dtype
    _i_dtype = mesh.edgesOnEdge.dtype
    mesh = mesh._replace(
        dvEdge=dvEdge_safe,
        areaTriangle=areaTriangle_safe,
        edgesOnEdge=jnp.asarray(edgesOnEdge_new, dtype=_i_dtype),
        weightsOnEdge=jnp.asarray(weightsOnEdge_new, dtype=_w_dtype),
        nEdgesOnEdge=jnp.asarray(nEdgesOnEdge_new, dtype=_i_dtype),
    )

    return mesh


def load_mpas_mesh(path: str) -> VoronoiMesh:
    """Load an MPAS mesh from a NetCDF file.

    Parameters
    ----------
    path : str
        Path to MPAS mesh NetCDF file.

    Returns
    -------
    VoronoiMesh
    """
    import netCDF4 as nc

    ds = nc.Dataset(path, 'r')

    def read_var(name):
        return np.array(ds.variables[name][:])

    nCells = len(ds.dimensions['nCells'])
    nEdges = len(ds.dimensions['nEdges'])
    nVertices = len(ds.dimensions['nVertices'])
    maxEdges = len(ds.dimensions['maxEdges'])
    vertexDegree = len(ds.dimensions['vertexDegree'])

    # Read and convert from 1-indexed to 0-indexed
    def read_int_var(name):
        return np.array(ds.variables[name][:], dtype=np.int32) - 1

    radius = float(ds.sphere_radius) if hasattr(ds, 'sphere_radius') else constants.R_earth

    import jax
    try:
        from legoesm.core.precision import get_policy
        _fdtype = get_policy().storage
    except Exception:
        _fdtype = jnp.float64 if jax.config.jax_enable_x64 else jnp.float32

    mesh_data = {
        'nCells': nCells, 'nEdges': nEdges, 'nVertices': nVertices,
        'maxEdges': maxEdges, 'vertexDegree': vertexDegree, 'radius': radius,
    }

    # Coordinates
    for name in ['latCell', 'lonCell', 'latEdge', 'lonEdge',
                 'latVertex', 'lonVertex']:
        mesh_data[name] = jnp.array(read_var(name), dtype=_fdtype)

    for prefix in ['Cell', 'Edge', 'Vertex']:
        for coord in ['x', 'y', 'z']:
            name = f'{coord}{prefix}'
            mesh_data[name] = jnp.array(read_var(name), dtype=_fdtype)

    # Connectivity (transpose to match our (maxEdges, nCells) convention)
    conn_names = {
        'cellsOnEdge': (2, nEdges),
        'verticesOnEdge': (2, nEdges),
        'edgesOnCell': (maxEdges, nCells),
        'verticesOnCell': (maxEdges, nCells),
        'cellsOnVertex': (vertexDegree, nVertices),
        'edgesOnVertex': (vertexDegree, nVertices),
        'cellsOnCell': (maxEdges, nCells),
    }
    for name, shape in conn_names.items():
        data = read_int_var(name)
        if data.ndim == 2:
            data = data.T if data.shape[0] != shape[0] else data
        mesh_data[name] = jnp.array(data, dtype=jnp.int32)

    # Geometry
    for name in ['areaCell', 'areaTriangle', 'dcEdge', 'dvEdge', 'angleEdge',
                 'fEdge', 'fVertex', 'meshDensity']:
        if name in ds.variables:
            mesh_data[name] = jnp.array(read_var(name), dtype=_fdtype)

    # Weights
    maxEdges2 = 2 * maxEdges - 2
    if 'weightsOnEdge' in ds.variables:
        woe = read_var('weightsOnEdge')
        eoe = read_int_var('edgesOnEdge')
        if woe.ndim == 2:
            woe = woe.T if woe.shape[0] != maxEdges2 else woe
            eoe = eoe.T if eoe.shape[0] != maxEdges2 else eoe
        mesh_data['weightsOnEdge'] = jnp.array(woe, dtype=_fdtype)
        mesh_data['edgesOnEdge'] = jnp.array(eoe, dtype=jnp.int32)
    else:
        mesh_data['weightsOnEdge'] = jnp.zeros((maxEdges2, nEdges))
        mesh_data['edgesOnEdge'] = jnp.full((maxEdges2, nEdges), -1,
                                             dtype=jnp.int32)

    if 'kiteAreasOnVertex' in ds.variables:
        ka = read_var('kiteAreasOnVertex')
        if ka.ndim == 2:
            ka = ka.T if ka.shape[0] != vertexDegree else ka
        mesh_data['kiteAreasOnVertex'] = jnp.array(ka, dtype=_fdtype)
    else:
        mesh_data['kiteAreasOnVertex'] = jnp.zeros((vertexDegree, nVertices))

    if 'edgeSignOnCell' not in mesh_data:
        mesh_data['edgeSignOnCell'] = jnp.zeros((maxEdges, nCells))
    if 'edgeSignOnVertex' not in mesh_data:
        mesh_data['edgeSignOnVertex'] = jnp.zeros((vertexDegree, nVertices))

    mesh_data['nEdgesOnCell'] = jnp.array(
        read_var('nEdgesOnCell'), dtype=jnp.int32)
    if 'nEdgesOnEdge' in ds.variables:
        mesh_data['nEdgesOnEdge'] = jnp.array(
            read_var('nEdgesOnEdge'), dtype=jnp.int32)
    else:
        mesh_data['nEdgesOnEdge'] = jnp.zeros(nEdges, dtype=jnp.int32)

    ds.close()
    return VoronoiMesh(**mesh_data)


def reconstruct_cell_velocity(u_edge, mesh):
    """Reconstruct ``(u_east, v_north)`` at cell centers from edge normals.

    Implements the Perot (2000) area-weighted edge-to-cell reconstruction
    that MPAS uses everywhere it needs cell-centered winds (diagnostics,
    column physics, coupler exports).  Given the normal velocity
    ``u_edge`` at each edge and the per-edge angle ``angleEdge`` (the
    edge normal's azimuth measured from local east), each edge
    contributes ``(cos α · u_edge, sin α · u_edge)`` weighted by
    ``dvEdge · dcEdge / (2 · areaCell)``.  The formula is exact for
    uniform flow on any Voronoi mesh and smoothly differentiable, so it
    composes cleanly with ``jax.grad`` through column-physics bridges
    (turbulence, gravity-wave drag, etc.) that previously refused
    to dispatch on MPAS (audit 2026-05-12 MEDIUM #10).

    Parameters
    ----------
    u_edge : jax.Array, shape ``(nEdges,)`` or ``(nEdges, nlev)``
        Edge-normal velocity [m/s].
    mesh : VoronoiMesh
        The MPAS Voronoi mesh providing ``edgesOnCell``, ``dvEdge``,
        ``dcEdge``, ``angleEdge``, and ``areaCell``.

    Returns
    -------
    u_east, v_north : jax.Array
        Zonal and meridional cell-centered velocity, shape
        ``(nCells,)`` or ``(nCells, nlev)``.
    """
    is_3d = u_edge.ndim == 2

    eoc = mesh.edgesOnCell  # (maxEdges, nCells)
    mask = (eoc >= 0).astype(u_edge.dtype)
    eoc_safe = jnp.maximum(eoc, 0)

    dv = mesh.dvEdge[eoc_safe] * mask
    dc = mesh.dcEdge[eoc_safe] * mask
    angle = mesh.angleEdge[eoc_safe]
    weight = dv * dc / (2.0 * mesh.areaCell[jnp.newaxis, :])

    cos_a = jnp.cos(angle)
    sin_a = jnp.sin(angle)

    if is_3d:
        u_gathered = u_edge[eoc_safe] * mask[..., jnp.newaxis]
        w3d = weight[..., jnp.newaxis]
        contrib = u_gathered * w3d
        u_east = jnp.sum(contrib * cos_a[..., jnp.newaxis], axis=0)
        v_north = jnp.sum(contrib * sin_a[..., jnp.newaxis], axis=0)
    else:
        u_gathered = u_edge[eoc_safe] * mask
        contrib = u_gathered * weight
        u_east = jnp.sum(contrib * cos_a, axis=0)
        v_north = jnp.sum(contrib * sin_a, axis=0)

    return u_east, v_north
