"""Regenerate packages/atmosphere/legoesm/atmosphere/physics/turbulence/turbulence_les_tuned.yaml from the seed-uncertainty campaign.

Per scheme, selects the MEDIAN-score seed (a real, self-consistent parameter set,
not an average -- params do not compose linearly through the sigmoid transforms)
and writes its tuned coefficients as registry-qualified `scheme_key.field: value`.

Usage:
    python scripts/data/build_tuned_turbulence_yaml.py \
        --seeds results/scm_les_turbulence/seed_uncertainty \
                results/scm_les_turbulence/seed_uncertainty_clubb \
        --out packages/atmosphere/legoesm/atmosphere/physics/turbulence/turbulence_les_tuned.yaml
"""
import argparse
import collections
import glob
import json
from pathlib import Path


def collect(seed_dirs: list[str]) -> dict[str, list]:
    by_scheme: dict[str, list] = collections.defaultdict(list)
    for d in seed_dirs:
        for f in sorted(glob.glob(f"{d}/seed*/tuned_parameters.json")):
            rep = json.load(open(f))
            for s in rep.get("schemes", []):
                if s.get("status") != "tuned" or s.get("score_tuned") is None:
                    continue
                params = {p["name"]: p["tuned"] for p in s.get("parameters", [])
                          if p.get("trained") and p.get("tuned") is not None}
                if params:
                    by_scheme[s["scheme"]].append((float(s["score_tuned"]), params))
    return by_scheme


def median_params(by_scheme: dict[str, list], min_seeds: int) -> dict[str, float]:
    """Lower-median seed per scheme -> a REAL seed, never an average.

    A scheme with fewer than ``min_seeds`` tuned seeds is EXCLUDED: its median is
    not yet trustworthy, and silently emitting it (e.g. CLUBB at 2 seeds) would
    make the committed file non-reproducible the moment more seeds land.
    """
    canonical: dict[str, float] = {}
    for scheme, entries in sorted(by_scheme.items()):
        if len(entries) < min_seeds:
            print(f"  SKIP {scheme}: {len(entries)} < {min_seeds} tuned seeds")
            continue
        entries.sort(key=lambda e: e[0])
        mi = (len(entries) - 1) // 2
        canonical.update(entries[mi][1])
    return canonical


def write_yaml(canonical: dict[str, float], out: Path,
               by_scheme: dict[str, list]) -> None:
    grouped: dict[str, dict[str, float]] = collections.defaultdict(dict)
    for qual, val in sorted(canonical.items()):
        cls, field = qual.rsplit(".", 1)
        grouped[cls][field] = val
    counts = {sc: len(e) for sc, e in by_scheme.items()}
    lines = [
        "# LES-tuned turbulence parameters (median seed per scheme; "
        "10-seed sweep for the eight algebraic closures, 5-seed for CLUBB).",
        "# Registry-qualified `scheme_key.field: value`, spec-bounds-validated.",
        "# SCM applies these by DEFAULT (scm_turbulence_config les_tuned=True).",
        "# AMIP opt-in: this file holds ALL schemes; --params aborts on any",
        "# scheme not selected for the run, so pass only the ACTIVE scheme's",
        "# slice -- les_tuned.write_active_scheme_params(scheme, out) writes it.",
        "# Generated by scripts/data/build_tuned_turbulence_yaml.py (do not hand-edit).",
        "",
    ]
    for cls in sorted(grouped):
        lines.append(f"# --- {cls.rsplit('.', 1)[-1]} ---")
        for field, val in sorted(grouped[cls].items()):
            lines.append(f"{cls}.{field}: {val:.10g}")
        lines.append("")
    out.write_text("\n".join(lines))
    print(f"wrote {out} ({len(canonical)} params, "
          f"{len(grouped)} schemes; seed counts {counts})")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seeds", nargs="+", required=True)
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--min-seeds", type=int, default=5,
                    help="exclude a scheme with fewer tuned seeds "
                         "(default 5); keeps under-sampled schemes "
                         "like CLUBB out until their campaign fills.")
    args = ap.parse_args()
    by_scheme = collect(args.seeds)
    if not by_scheme:
        raise SystemExit("no tuned seeds found under the given dirs")
    write_yaml(median_params(by_scheme, args.min_seeds), args.out, by_scheme)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
