"""Fetch REAL RCEMIP community CRM output and convert it to a legoESM
``--reference-dir`` the SCM-RCE convection campaign can consume directly.

Why
---
``scripts/run/run_scm_rce_campaign.py`` scores convection schemes against a CRM
reference.  Until now that reference was generated by legoESM itself, so the
"CRM" shared its dycore, microphysics, radiation and grid with the schemes being
ranked — a self-consistency bias that flatters exactly the schemes we most want
to test honestly.  This script replaces it with output from the published
RCEMIP ensemble (Wing et al. 2018, GMD 11, 793-813; Wing et al. 2020, JAMES),
i.e. an INDEPENDENT CRM.

Source
------
DKRZ Swift object storage, public, no credentials:
  https://swiftbrowser.dkrz.de/public/dkrz_70a517a8-039d-4a1b-a30d-841923f8bc7a/RCEMIP/
Catalogue entry (WDCC): https://www.wdc-climate.de/ui/info?site=RCEMIP_DS

The RCEMIP site asks users to fill in a usage form and to read
``A-README-BEFORE-DOWNLOAD/`` first.  Those terms were NOT machine-verified by
this script — read them before publishing anything derived from the data, and
cite Wing et al. (2018) and the contributing model.

Cost
----
We pull only the **1D tier** (``f(z,t)`` hourly-mean profiles): ~760 KB per
variable, so a full fetch for one model/case is ~5 MB.  The 2D tier is ~3 GB and
the 3D tier ~4 GB per model/case; neither is needed, because the campaign's
reference reader immediately averages over the horizontal
(``run_scm_rce_campaign._reference_profiles`` does ``T.mean(axis=(0, 1))``), so
a domain-mean profile carries all the information it actually uses.  Run with
``--check-size`` to print the byte cost before downloading anything.

TLS note: Ginsburg's default CA bundle is missing the HARICA root that DKRZ
chains to.  ``--cacert`` defaults to the system bundle
(``/etc/pki/tls/certs/ca-bundle.crt``), which does verify.  We never disable
verification.

Output layout (what the campaign expects)
-----------------------------------------
``<dest>/snapshots3d/vol_XXXXXXXX.npz``  keys ``z, T, mse, cond, qcloud, w,
day, t_s, dx, Lx, Ly`` with the 3D fields shaped ``(1, 1, nz)`` — a domain-mean
column.  ``_reference_profiles`` means over axes (0, 1), so a singleton
horizontal dimension is exact, not an approximation.
``<dest>/snapshots/sfc_XXXXXXXX.npz`` carries the 4-height cross-check block
(``heights, T_levels, qv_levels, cond_levels``) used by ``_surface_cross_check``.

Humidity convention
-------------------
Default ``--humidity qv`` reads SAM's ``QV_avg``, the native water-vapour
MIXING RATIO in kg/kg, which is exactly what legoESM's ``q_v`` tracer holds —
so there is NO specific-vs-mixing-ratio conversion to get wrong.  The CMOR
``hus_avg`` (specific humidity) is available via ``--humidity hus`` but is 83%
fill for SAM_CRM/RCE_small300 (only 397 of 2400 times fully finite), which the
script reports and refuses rather than silently interpolating.

Two file conventions that WILL bite a naive reader, both handled here:
  * ``time`` carries ``units = "day"`` (0.02 .. 99.98), not seconds. Treating
    it as seconds collapses a 100-day run into 100 s and empties every
    equilibrium window. Units are read from the file and unknown units are
    fatal.
  * ``p`` carries ``units = "mb"``, not Pa.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

import numpy as np

from legoesm import constants

#: The OBJECT endpoint.  ``swiftbrowser.dkrz.de/public/...`` is the human
#: browser: it returns a 200 with an HTML page for a .nc path, so ``curl
#: --fail`` does NOT catch it and you silently get a 9 KB web page named
#: ``*.nc``.  The download link inside that page points here.  Every fetch is
#: additionally magic-byte checked (see _check_netcdf) so this can never
#: regress into "the tool exited 0, therefore we have data".
SWIFT_ROOT = ("https://swift.dkrz.de/v1/"
              "dkrz_70a517a8-039d-4a1b-a30d-841923f8bc7a/RCEMIP")
BROWSER_ROOT = ("https://swiftbrowser.dkrz.de/public/"
                "dkrz_70a517a8-039d-4a1b-a30d-841923f8bc7a/RCEMIP")
DEFAULT_CACERT = "/etc/pki/tls/certs/ca-bundle.crt"
SEC_PER_DAY = 86400.0
MSE_J_TO_KJ = 1.0e-3

#: 1D variables we need.  ``cond`` in legoESM is the sum of the condensate
#: tracers (q_c + q_r for the Kessler layout), so it maps to cloud liquid+ice
#: PLUS precipitating liquid+ice; ``qcloud`` is the cloud part alone.
CLOUD_VARS = ("clw_avg", "cli_avg")
PRECIP_COND_VARS = ("plw_avg", "pli_avg")
#: Humidity source.  ``QV_avg`` is SAM's native water-vapour MIXING RATIO
#: [kg/kg] -- directly comparable to legoESM's q_v tracer, so no specific-vs-
#: mixing-ratio conversion is needed at all.  ``hus_avg`` is the CMOR specific
#: humidity and, for SAM_CRM/RCE_small300, is 83% fill (only 397 of 2400 times
#: are fully finite), so it is a fallback, not the default.
HUMIDITY_VARS = {"qv": "QV_avg", "hus": "hus_avg"}
REQUIRED_VARS = ("ta_avg",) + CLOUD_VARS + PRECIP_COND_VARS


def _fatal(msg: str) -> None:
    print(f"FATAL: {msg}", file=sys.stderr)
    raise SystemExit(2)


def object_url(model: str, case: str, var: str) -> str:
    return f"{SWIFT_ROOT}/{model}/{case}/1D/{model}_{case}_1D_{var}.nc"


def _curl(url: str, cacert: str, out: Path | None, head: bool = False) -> str:
    cmd = ["curl", "-sS", "-L", "--fail", "--cacert", cacert]
    if head:
        cmd += ["-I", "-o", "/dev/null",
                "-w", "%{http_code} %{size_download} %{header_size}"]
        cmd += ["-w", "%{http_code} %{filename_effective}"]
    if out is not None:
        cmd += ["-o", str(out)]
    cmd.append(url)
    res = subprocess.run(cmd, capture_output=True, text=True, timeout=1800)
    if res.returncode != 0:
        _fatal(f"curl failed ({res.returncode}) for {url}\n{res.stderr}")
    return res.stdout


#: netCDF-3 ("CDF\x01/\x02") and netCDF-4/HDF5 ("\x89HDF") file signatures.
_NC_MAGIC = (b"CDF\x01", b"CDF\x02", b"CDF\x05", b"\x89HDF")


def _check_netcdf(path: Path, url: str) -> None:
    """A downloaded file that is not netCDF is FATAL, never a warning.

    The DKRZ browser host answers a .nc request with HTTP 200 and an HTML
    page, so neither the exit code nor ``curl --fail`` distinguishes data from
    a web page.  The magic bytes do.
    """
    if not path.exists() or path.stat().st_size == 0:
        _fatal(f"{path} is missing or empty after fetching {url}")
    with open(path, "rb") as fh:
        head = fh.read(8)
    if not any(head.startswith(m) for m in _NC_MAGIC):
        path.unlink(missing_ok=True)
        _fatal(
            f"{url} did not return netCDF (first bytes {head!r}). If this is "
            "HTML you are hitting the browser host, not the object store; the "
            "object endpoint is SWIFT_ROOT. Deleted the bad file so a rerun "
            "cannot use it from cache.")


def remote_size(url: str, cacert: str) -> int:
    """Content-Length via HEAD, in bytes.  -1 when the server does not say."""
    res = subprocess.run(
        ["curl", "-sSIL", "--fail", "--cacert", cacert, url],
        capture_output=True, text=True, timeout=300)
    if res.returncode != 0:
        return -1
    size = -1
    for line in res.stdout.splitlines():
        if line.lower().startswith("content-length:"):
            size = int(line.split(":", 1)[1].strip())
    return size


def _open_nc(path: Path):
    """Read a netCDF file, preferring xarray then netCDF4."""
    try:
        import xarray as xr
        return xr.open_dataset(path)
    except ImportError:
        pass
    try:
        import netCDF4  # noqa: F401
        import xarray as xr  # noqa: F811
        return xr.open_dataset(path, engine="netcdf4")
    except ImportError:
        _fatal("neither xarray nor netCDF4 is importable; cannot read the "
               "RCEMIP netCDF files. `pip install xarray netcdf4`.")


#: Recognised time units in the RCEMIP 1D files -> seconds.
_TIME_UNIT_SECONDS = {"day": SEC_PER_DAY, "days": SEC_PER_DAY,
                      "hour": 3600.0, "hours": 3600.0,
                      "s": 1.0, "sec": 1.0, "second": 1.0, "seconds": 1.0}


def time_to_seconds(ds) -> np.ndarray:
    """Time axis in SECONDS, from the file's own ``units`` attribute.

    SAM_CRM/RCE_small300 stores ``units = "day"`` running 0.02 .. 99.98, so
    treating the raw numbers as seconds silently collapses a 100-day run into
    100 seconds and makes every equilibrium window empty.  Unknown units are
    FATAL rather than assumed.
    """
    t = np.asarray(ds["time"].values, dtype=np.float64).reshape(-1)
    units = str(ds["time"].attrs.get("units", "")).strip().lower()
    if units not in _TIME_UNIT_SECONDS:
        _fatal(f"unrecognised time units {units!r}; refusing to guess. "
               f"Known: {sorted(_TIME_UNIT_SECONDS)}")
    return t * _TIME_UNIT_SECONDS[units]


def _pick(ds, names: tuple[str, ...]) -> str:
    for n in names:
        if n in ds.variables:
            return n
    _fatal(f"none of {names} found; file has {list(ds.variables)}")
    raise AssertionError  # unreachable


def build_reference(profiles: dict[str, np.ndarray], z_m: np.ndarray,
                    time_s: np.ndarray, dest: Path, *,
                    last_days: float, n_snapshots: int,
                    to_mixing_ratio: bool, source: str) -> None:
    """Write the campaign-format reference from domain-mean profiles.

    ``profiles`` holds ``T`` [K], ``qv`` [kg/kg specific], ``qcloud`` and
    ``cond`` [kg/kg], each shaped ``(nt, nz)``.
    """
    nt, nz = profiles["T"].shape
    if z_m.size != nz:
        _fatal(f"z has {z_m.size} levels but the profiles have {nz}.")
    t_end = float(time_s[-1])
    t_start = t_end - last_days * SEC_PER_DAY
    sel = np.nonzero(time_s >= t_start)[0]
    if sel.size < n_snapshots:
        _fatal(f"only {sel.size} times in the last {last_days} days; need "
               f"{n_snapshots}. Widen --last-days or lower --n-snapshots.")
    # Evenly spaced across the equilibrium window (INCLUDING its endpoints).
    take = sel[np.linspace(0, sel.size - 1, n_snapshots).round().astype(int)]
    print(f"\n  equilibrium window: t = {t_start/SEC_PER_DAY:.2f} .. "
          f"{t_end/SEC_PER_DAY:.2f} days ({sel.size} available times), "
          f"taking {n_snapshots} evenly spaced")

    qv_all = profiles["qv"]
    if to_mixing_ratio:
        qv_all = qv_all / (1.0 - qv_all)
    dq = float(np.max(np.abs(qv_all - profiles["qv"])))
    print(f"  humidity written: "
          + ("converted q -> r = q/(1-q); max |r - q| = %.3e kg/kg" % dq
             if to_mixing_ratio else
             "source values unchanged (QV_avg is ALREADY a mixing ratio, "
             "matching legoESM's q_v tracer; pass --humidity hus "
             "--to-mixing-ratio only if you switch source)"))

    vol_dir = dest / "snapshots3d"
    sfc_dir = dest / "snapshots"
    vol_dir.mkdir(parents=True, exist_ok=True)
    sfc_dir.mkdir(parents=True, exist_ok=True)

    # 4 cross-check heights, matching the plane driver's --snapshot-heights.
    want_h = np.array([1000.0, 5000.0, 9000.0, 12000.0])
    hidx = [int(np.argmin(np.abs(z_m - h))) for h in want_h]
    heights = z_m[hidx]

    for it in take:
        T = profiles["T"][it].astype(np.float64)
        qv = qv_all[it].astype(np.float64)
        cond = profiles["cond"][it].astype(np.float64)
        qcloud = profiles["qcloud"][it].astype(np.float64)
        for name, arr in (("T", T), ("qv", qv), ("cond", cond)):
            if not np.all(np.isfinite(arr)):
                _fatal(f"{name} at t index {it} has non-finite values.")
        # Reconstruct MSE so the campaign's mse->q_v inversion round-trips to
        # exactly the q_v we wrote (it recomputes
        # qv = (mse - c_pd T - g z)/L_v).
        mse_kJ = ((constants.c_pd * T + constants.g * z_m
                   + constants.L_v * qv) * MSE_J_TO_KJ)
        step = int(round(float(time_s[it])))
        col = lambda a: a.reshape(1, 1, -1)  # noqa: E731
        np.savez(
            vol_dir / f"vol_{step:08d}.npz",
            day=float(time_s[it]) / SEC_PER_DAY, t_s=float(time_s[it]),
            dx=np.nan, Lx=np.nan, Ly=np.nan,
            z=z_m, T=col(T), mse=col(mse_kJ), cond=col(cond),
            qcloud=col(qcloud), w=col(np.zeros_like(T)),
            source=source,
        )
        np.savez(
            sfc_dir / f"sfc_{step:08d}.npz",
            day=float(time_s[it]) / SEC_PER_DAY, t_s=float(time_s[it]),
            heights=heights,
            T_levels=T[hidx].reshape(-1, 1, 1),
            qv_levels=qv[hidx].reshape(-1, 1, 1),
            cond_levels=cond[hidx].reshape(-1, 1, 1),
            source=source,
        )
    print(f"  wrote {len(take)} vol_*.npz -> {vol_dir}")
    print(f"  wrote {len(take)} sfc_*.npz -> {sfc_dir}")
    (dest / "SOURCE.txt").write_text(
        f"{source}\n\nFetched by scripts/data/fetch_rcemip_reference.py from\n"
        f"{SWIFT_ROOT}\n\nCite: Wing et al. (2018), GMD 11, 793-813, "
        "doi:10.5194/gmd-11-793-2018, and the contributing model.\n"
        "Read A-README-BEFORE-DOWNLOAD/ in the archive before redistributing.\n")


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--model", default="SAM_CRM",
                   help="RCEMIP model directory, e.g. SAM_CRM, CM1, MicroHH, "
                        "ICON_LEM_CRM, UCLA-CRM, WRF-CRM, MESONH, SCALE.")
    p.add_argument("--case", default="RCE_small300",
                   choices=["RCE_small295", "RCE_small300", "RCE_small305",
                            "RCE_large295", "RCE_large300", "RCE_large305"])
    p.add_argument("--dest", type=Path,
                   default=Path("results/rcemip_reference"))
    p.add_argument("--cache", type=Path, default=Path("data/rcemip_raw"),
                   help="where the downloaded .nc files are kept")
    p.add_argument("--cacert", default=DEFAULT_CACERT)
    p.add_argument("--last-days", type=float, default=25.0,
                   help="equilibrium window at the END of the run; the RCEMIP "
                        "protocol suggests the last 25 days.")
    p.add_argument("--n-snapshots", type=int, default=10,
                   help="how many vol_*.npz to emit (campaign needs >= 5).")
    p.add_argument("--humidity", choices=sorted(HUMIDITY_VARS),
                   default="qv",
                   help="Humidity source: 'qv' = SAM QV_avg, the native MIXING "
                        "RATIO [kg/kg] that matches legoESM's q_v tracer "
                        "exactly (default); 'hus' = CMOR specific humidity, "
                        "which is 83%% fill for SAM_CRM/RCE_small300.")
    p.add_argument("--to-mixing-ratio", action="store_true",
                   help="convert specific humidity to mixing ratio r = q/(1-q). "
                        "Only meaningful with --humidity hus; QV_avg is "
                        "ALREADY a mixing ratio.")
    p.add_argument("--check-size", action="store_true",
                   help="print the download cost and exit without fetching.")
    args = p.parse_args(argv)

    if args.n_snapshots < 5:
        _fatal("--n-snapshots must be >= 5; run_scm_rce_campaign requires at "
               "least 5 vol_*.npz files.")

    wanted = REQUIRED_VARS + (HUMIDITY_VARS[args.humidity],)
    urls = {v: object_url(args.model, args.case, v) for v in wanted}
    print(f"model={args.model} case={args.case}")
    if args.check_size:
        total = 0
        for v, u in urls.items():
            n = remote_size(u, args.cacert)
            total += max(n, 0)
            print(f"  {v:12s} {n/1e6 if n > 0 else float('nan'):8.3f} MB  {u}")
        print(f"  TOTAL {total/1e6:.3f} MB (1D tier only). "
              "The 2D tier is ~3 GB and the 3D tier ~4 GB per model/case; "
              "neither is fetched.")
        return 0

    args.cache.mkdir(parents=True, exist_ok=True)
    local = {}
    for v, u in urls.items():
        dst = args.cache / f"{args.model}_{args.case}_1D_{v}.nc"
        if dst.exists() and dst.stat().st_size > 0:
            print(f"  cached  {v:12s} {dst.stat().st_size/1e6:7.3f} MB")
        else:
            print(f"  fetching {v:12s} ...", flush=True)
            _curl(u, args.cacert, dst)
            print(f"           {dst.stat().st_size/1e6:7.3f} MB")
        _check_netcdf(dst, u)          # magic bytes, cached files included
        local[v] = dst

    ds_T = _open_nc(local["ta_avg"])
    tname = _pick(ds_T, ("ta_avg", "ta", "tabs"))
    zname = _pick(ds_T, ("z", "height", "zg", "lev"))
    T = np.asarray(ds_T[tname].values, dtype=np.float64)
    z_m = np.asarray(ds_T[zname].values, dtype=np.float64).reshape(-1)
    time_s = time_to_seconds(ds_T)
    if T.ndim != 2:
        T = T.reshape(time_s.size, z_m.size)
    print(f"\n  grid: nz={z_m.size} levels, z = {z_m.min():.0f} .. "
          f"{z_m.max():.0f} m; nt={time_s.size} times, "
          f"t = {time_s.min()/SEC_PER_DAY:.2f} .. {time_s.max()/SEC_PER_DAY:.2f} d")
    print(f"  dz near surface = {np.diff(np.sort(z_m))[0]:.1f} m "
          "(legoESM plane CRM default is 1100 m UNIFORM -- see "
          "docs/science/specs/CRM_implementation.md F11)")

    def _load(var: str) -> np.ndarray:
        ds = _open_nc(local[var])
        nm = _pick(ds, (var, var.replace("_avg", "")))
        a = np.asarray(ds[nm].values, dtype=np.float64)
        return a.reshape(time_s.size, z_m.size)

    hvar = HUMIDITY_VARS[args.humidity]
    qv = _load(hvar)
    n_bad = int(np.sum(~np.isfinite(qv)))
    if n_bad:
        print(f"  WARNING: {hvar} has {n_bad}/{qv.size} non-finite entries "
              f"({100.0*n_bad/qv.size:.1f}%).")
        if args.humidity == "hus":
            _fatal(f"{hvar} is not usable; rerun with --humidity qv (SAM's "
                   "native mixing ratio, which is complete).")
        _fatal(f"{hvar} unexpectedly has gaps.")
    qcloud = sum(_load(v) for v in CLOUD_VARS)
    cond = qcloud + sum(_load(v) for v in PRECIP_COND_VARS)

    source = (f"RCEMIP {args.model} {args.case} 1D domain-mean profiles "
              f"(Wing et al. 2018, GMD 11, 793-813), fetched from DKRZ Swift")
    build_reference(
        {"T": T, "qv": qv, "qcloud": qcloud, "cond": cond},
        z_m, time_s, args.dest,
        last_days=args.last_days, n_snapshots=args.n_snapshots,
        to_mixing_ratio=args.to_mixing_ratio, source=source)
    print("\nFETCH_DONE")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
