"""legoESM-MITgcm recipe: barotropic wind-driven gyre (the beta-plane oracle).

A pure-config legoESM reproduction of MITgcm ``verification/tutorial_barotropic_gyre``
— the first MITgcm oracle case. Everything is selected from canonical legoESM
blocks; the ONLY new capability it needs is the Cartesian beta-plane C-grid
(``create_beta_plane_cgrid_geometry``), which is what lets a tendency-faithful
match to a non-spherical oracle exist at all.

MITgcm setup (``input/data`` + ``gendata.m``), reproduced field-for-field:

================  ===============================================================
grid              Cartesian beta-plane, 62 x 62 cells x 1 level, dx = dy = 20 km,
                  xgOrigin = ygOrigin = -20 km (so the wet interior is 60 x 60).
Coriolis          f0 = 1e-4, beta = 1e-11  ->  f = f0 + beta*y  (y from origin).
bathymetry        flat 5000 m, solid walls on all 4 boundary rows/cols
                  (``bathy.bin``: h([1 end],:)=0; h(:,[1 end])=0).
wind              tau_x(y) = -tauMax cos(pi Y), tauMax = 0.1 N/m^2,
                  Y = (j - 0.5)/(ny - 2)  (``windx_cosy.bin``). No meridional wind.
physics           homogeneous (tempStepping=saltStepping=.FALSE.) -> single layer,
                  constant density; viscAh = 400 (Laplacian); implicit free
                  surface; no bottom drag; rhoConst = 1000; gBaro = 9.81.
time              deltaT = 1200 s.
================  ===============================================================

Sign convention: MITgcm ``zonalWindFile`` IS the ocean-side stress (eastward +,
applied ``gU += tau_x/(rho dz)``). legoESM's external-forcing path treats
``OceanSurfaceForcing.tau_x`` as the ATMOSPHERIC stress and flips it internally,
so this recipe passes ``tau_x = +tauMax cos(pi Y)`` — after the flip that
reproduces MITgcm's ``-tauMax cos(pi Y)`` ocean stress (same negate the Veros
ACC recipe documents).

The MITgcm reference for tendency/statistics comparison is generated by
``scripts/data/generate_mitgcm_barotropic_gyre_reference.py`` and loaded via
``mitgcm_runner.load_mitgcm_reference("barotropic_gyre")``.
"""

from __future__ import annotations

from typing import NamedTuple

import jax.numpy as jnp
import numpy as np
from legoesm.grids.latlon import (
    LatLonCGridGeometry,
    create_beta_plane_cgrid_geometry,
)
from legoesm.ocean.eos import LinearEOSConfig
from legoesm.ocean.init_latlon_cgrid import rest_state_latlon_cgrid_ocean
from legoesm.ocean.state import (
    LatLonCGridOceanConfig,
    LatLonCGridOceanState,
    OceanSurfaceForcing,
)
from legoesm.ocean.vertical import create_ocean_z_star

# --- MITgcm tutorial_barotropic_gyre parameters (input/data + gendata.m). ----
NX = 62
NY = 62
DX_M = 20.0e3
DY_M = 20.0e3
F0 = 1.0e-4            # [s^-1]
BETA = 1.0e-11         # [m^-1 s^-1]
Y_ORIGIN_M = -20.0e3   # ygOrigin
X_ORIGIN_M = -20.0e3   # xgOrigin
H_DEPTH_M = 5000.0     # Ho
TAU_MAX = 0.1          # [N/m^2]
VISC_AH = 400.0        # [m^2/s]  viscAh
DT_S = 1200.0          # deltaT
RHO_CONST = 1000.0     # rhoConst
G_BARO = 9.81          # gBaro


class MitgcmGyreRecipe(NamedTuple):
    """Assembled legoESM reproduction of the MITgcm barotropic gyre."""

    geometry: LatLonCGridGeometry
    z_coord: object
    config: LatLonCGridOceanConfig
    state: LatLonCGridOceanState
    wind_forcing: OceanSurfaceForcing
    dt_s: float


def build_gyre_geometry() -> LatLonCGridGeometry:
    """Cartesian beta-plane C-grid matching MITgcm's grid + Coriolis."""
    return create_beta_plane_cgrid_geometry(
        NY, NX, dx_m=DX_M, dy_m=DY_M, f0=F0, beta=BETA,
        y_origin_m=Y_ORIGIN_M, x_origin_m=X_ORIGIN_M,
    )


def build_gyre_land_mask() -> jnp.ndarray:
    """Closed box: ocean interior, solid walls on every boundary row/col.

    Reproduces ``gendata.m`` ``h([1 end],:)=0; h(:,[1 end])=0`` exactly
    (1.0 = ocean, 0.0 = land).
    """
    mask = np.ones((NY, NX), dtype=np.float64)
    mask[0, :] = 0.0
    mask[-1, :] = 0.0
    mask[:, 0] = 0.0
    mask[:, -1] = 0.0
    return jnp.asarray(mask)


def gyre_taux_ocean_profile() -> np.ndarray:
    """MITgcm OCEAN-side zonal wind stress per row: ``-tauMax cos(pi Y)``.

    ``Y[j] = (j - 0.5)/(ny - 2)`` exactly as ``gendata.m`` (``y=((0:ny-1)-0.5)/
    (ny-2)``). Returns shape ``(NY,)`` [N/m^2].
    """
    j = np.arange(NY, dtype=np.float64)
    y_norm = (j - 0.5) / (NY - 2)
    return -TAU_MAX * np.cos(np.pi * y_norm)


def build_gyre_wind() -> OceanSurfaceForcing:
    """Wind as ``OceanSurfaceForcing``. Passes ``+tauMax cos(pi Y)`` so legoESM's
    internal atmospheric->ocean flip reproduces MITgcm's ``-tauMax cos(pi Y)``."""
    taux_ocean = gyre_taux_ocean_profile()           # (NY,) ocean-side
    tau_x = jnp.asarray(np.broadcast_to(-taux_ocean[:, None], (NY, NX)))  # negate
    tau_y = jnp.zeros((NY, NX), dtype=tau_x.dtype)
    return OceanSurfaceForcing(tau_x=tau_x, tau_y=tau_y)


def build_gyre_config(
    *, barotropic_solver: str = "implicit_cn", n_barotropic_substeps: int = 24,
) -> LatLonCGridOceanConfig:
    """Single-layer barotropic config: viscAh Laplacian, constant density, no
    GM / convection / vertical mixing / bottom drag — matching MITgcm.

    ``barotropic_solver="implicit"`` mirrors MITgcm's unconditionally-stable
    implicit free surface (the gravity-wave CFL at dt=1200 s, dx=20 km is ~13).
    """
    return LatLonCGridOceanConfig(
        g=G_BARO,
        rho_0=RHO_CONST,
        # Constant density (homogeneous): linear EOS with zero expansion.
        eos="linear",
        eos_linear=LinearEOSConfig(rho_ref=RHO_CONST, alpha_T=0.0, beta_S=0.0),
        # Laplacian lateral viscosity only (no cos-lat scaling on a Cartesian
        # grid); no biharmonic / Smagorinsky / Leith.
        A_h=VISC_AH,
        A_h_lat_scaling=False,
        B_h=0.0,
        C_smag=0.0,
        # No bottom drag, no eddy params, no vertical mixing (single layer).
        bottom_drag_r=0.0,
        gm_redi=None,
        K_h=0.0,
        barotropic_solver=barotropic_solver,
        n_barotropic_substeps=n_barotropic_substeps,
        differentiable_barotropic=True,
        use_conservation_fixer=False,
        enable_runtime_checks=False,
    )


def build_gyre_state(z_coord) -> LatLonCGridOceanState:
    """Rest state (u=v=eta=0, uniform T/S) on the closed-box beta-plane grid."""
    geom = build_gyre_geometry()
    return rest_state_latlon_cgrid_ocean(
        geom, z_coord,
        land_mask_override=build_gyre_land_mask(),
    )


def build_gyre_recipe(
    *, barotropic_solver: str = "implicit_cn", n_barotropic_substeps: int = 24,
) -> MitgcmGyreRecipe:
    """Assemble the full legoESM-MITgcm barotropic-gyre recipe."""
    geom = build_gyre_geometry()
    z_coord = create_ocean_z_star(1, H_max=H_DEPTH_M)
    config = build_gyre_config(
        barotropic_solver=barotropic_solver,
        n_barotropic_substeps=n_barotropic_substeps,
    )
    state = build_gyre_state(z_coord)
    wind = build_gyre_wind()
    return MitgcmGyreRecipe(
        geometry=geom, z_coord=z_coord, config=config,
        state=state, wind_forcing=wind, dt_s=DT_S,
    )
