"""legoESM-MITgcm recipe: barotropic wind-driven gyre (the beta-plane oracle).

A pure-config legoESM reproduction of MITgcm ``verification/tutorial_barotropic_gyre``
— the first MITgcm oracle case. Everything is selected from canonical legoESM
blocks; the ONLY new capability it needs is the Cartesian beta-plane C-grid
(``create_beta_plane_cgrid_geometry``), which is what lets a tendency-faithful
match to a non-spherical oracle exist at all.

MITgcm setup (``input/data`` + ``gendata.m``), reproduced field-for-field:

================  ===============================================================
grid              Cartesian beta-plane, 62 x 62 cells x 1 level, dx = dy = 20 km,
                  xgOrigin = ygOrigin = -20 km (so the wet interior is 60 x 60).
Coriolis          f0 = 1e-4, beta = 1e-11  ->  f = f0 + beta*y  (y from origin).
bathymetry        flat 5000 m, solid walls on all 4 boundary rows/cols
                  (``bathy.bin``: h([1 end],:)=0; h(:,[1 end])=0).
wind              tau_x(y) = -tauMax cos(pi Y), tauMax = 0.1 N/m^2,
                  Y = (j - 0.5)/(ny - 2)  (``windx_cosy.bin``). No meridional wind.
physics           homogeneous (tempStepping=saltStepping=.FALSE.) -> single layer,
                  constant density; viscAh = 400 (Laplacian); implicit free
                  surface; no bottom drag; rhoConst = 1000; gBaro = 9.81.
time              deltaT = 1200 s.
================  ===============================================================

Sign convention: MITgcm ``zonalWindFile`` IS the ocean-side stress (eastward +,
applied ``gU += tau_x/(rho dz)``). legoESM's external-forcing path treats
``OceanSurfaceForcing.tau_x`` as the ATMOSPHERIC stress and flips it internally,
so this recipe passes ``tau_x = +tauMax cos(pi Y)`` — after the flip that
reproduces MITgcm's ``-tauMax cos(pi Y)`` ocean stress (same negate the Veros
ACC recipe documents).

The MITgcm reference for tendency/statistics comparison is generated by
``scripts/data/generate_mitgcm_barotropic_gyre_reference.py`` and loaded via
``mitgcm_runner.load_mitgcm_reference("barotropic_gyre")``.
"""

from __future__ import annotations

from typing import NamedTuple

import jax.numpy as jnp
import numpy as np
from legoesm.grids.latlon import (
    LatLonCGridGeometry,
    create_beta_plane_cgrid_geometry,
)
from legoesm.ocean.eos import LinearEOSConfig
from legoesm.ocean.init_latlon_cgrid import rest_state_latlon_cgrid_ocean
from legoesm.ocean.state import (
    LatLonCGridOceanConfig,
    LatLonCGridOceanState,
    OceanSurfaceForcing,
)
from legoesm.ocean.vertical import create_ocean_z_star

# --- MITgcm tutorial_barotropic_gyre parameters (input/data + gendata.m). ----
NX = 62
NY = 62
DX_M = 20.0e3
DY_M = 20.0e3
F0 = 1.0e-4            # [s^-1]
BETA = 1.0e-11         # [m^-1 s^-1]
Y_ORIGIN_M = -20.0e3   # ygOrigin
X_ORIGIN_M = -20.0e3   # xgOrigin
H_DEPTH_M = 5000.0     # Ho
TAU_MAX = 0.1          # [N/m^2]
VISC_AH = 400.0        # [m^2/s]  viscAh
DT_S = 1200.0          # deltaT
RHO_CONST = 1000.0     # rhoConst
G_BARO = 9.81          # gBaro


class MitgcmGyreRecipe(NamedTuple):
    """Assembled legoESM reproduction of the MITgcm barotropic gyre."""

    geometry: LatLonCGridGeometry
    z_coord: object
    config: LatLonCGridOceanConfig
    state: LatLonCGridOceanState
    wind_forcing: OceanSurfaceForcing
    dt_s: float


def build_gyre_geometry() -> LatLonCGridGeometry:
    """Cartesian beta-plane C-grid matching MITgcm's grid + Coriolis."""
    return create_beta_plane_cgrid_geometry(
        NY, NX, dx_m=DX_M, dy_m=DY_M, f0=F0, beta=BETA,
        y_origin_m=Y_ORIGIN_M, x_origin_m=X_ORIGIN_M,
    )


def build_gyre_land_mask() -> jnp.ndarray:
    """Closed box: ocean interior, solid walls on every boundary row/col.

    Reproduces ``gendata.m`` ``h([1 end],:)=0; h(:,[1 end])=0`` exactly
    (1.0 = ocean, 0.0 = land).
    """
    mask = np.ones((NY, NX), dtype=np.float64)
    mask[0, :] = 0.0
    mask[-1, :] = 0.0
    mask[:, 0] = 0.0
    mask[:, -1] = 0.0
    return jnp.asarray(mask)


def gyre_taux_ocean_profile() -> np.ndarray:
    """MITgcm OCEAN-side zonal wind stress per row: ``-tauMax cos(pi Y)``.

    ``Y[j] = (j - 0.5)/(ny - 2)`` exactly as ``gendata.m`` (``y=((0:ny-1)-0.5)/
    (ny-2)``). Returns shape ``(NY,)`` [N/m^2].
    """
    j = np.arange(NY, dtype=np.float64)
    y_norm = (j - 0.5) / (NY - 2)
    return -TAU_MAX * np.cos(np.pi * y_norm)


def build_gyre_wind() -> OceanSurfaceForcing:
    """Wind as ``OceanSurfaceForcing``. Passes ``+tauMax cos(pi Y)`` so legoESM's
    internal atmospheric->ocean flip reproduces MITgcm's ``-tauMax cos(pi Y)``."""
    taux_ocean = gyre_taux_ocean_profile()           # (NY,) ocean-side
    tau_x = jnp.asarray(np.broadcast_to(-taux_ocean[:, None], (NY, NX)))  # negate
    tau_y = jnp.zeros((NY, NX), dtype=tau_x.dtype)
    return OceanSurfaceForcing(tau_x=tau_x, tau_y=tau_y)


def build_gyre_config(
    *, barotropic_solver: str = "implicit_cn",
) -> LatLonCGridOceanConfig:
    """Single-layer barotropic config matching MITgcm's DEFAULT core numerics.

    Settled by a direct MITgcm source audit (set_defaults.F / ini_parms.F) of the
    tutorial deck, not by trial-and-error:

    * ``barotropic_implicit_theta_{eta,pgf}=1.0`` — MITgcm's implicit free surface
      is FULLY backward-Euler (``implicSurfPress=implicDiv2DFlow=1.0``), not the
      legoESM default Crank-Nicolson 0.55. This is the dominant lever: it takes
      the 10-step eta pattern correlation from 0.975 to 0.9997 and the magnitude
      from +21% to within 8%.
    * ``momentum_advection="flux_form"`` — MITgcm default is flux-form
      (``vectorInvariantMomentum=.FALSE.``), not vector-invariant. (Negligible at
      spin-up where Ro~5e-7, but the faithful choice for the equilibrated gyre.)
    * ``lateral_viscosity_operator="flux_divergence"`` — MITgcm's component-wise
      ``div(A_h grad u)`` flux form, not the default vector-Laplacian.

    * ``lateral_side_bc="no_slip"`` — MITgcm ``no_slip_sides=.TRUE.``
      (``sideDragFactor=2``): the wall side-drag ``-(2/Δ)·A_h·u_tangential``
      (``mom_u_sidedrag``/``mom_v_sidedrag``). Sets the equilibrium Munk layer /
      gyre transport; inactive over a 10-step spin-up (the boundary layer has
      not yet formed) but required for the equilibrated (multi-year) run.
    """
    return LatLonCGridOceanConfig(
        g=G_BARO,
        rho_0=RHO_CONST,
        # Constant density (homogeneous): linear EOS with zero expansion.
        eos="linear",
        eos_linear=LinearEOSConfig(rho_ref=RHO_CONST, alpha_T=0.0, beta_S=0.0),
        # Laplacian lateral viscosity only (no cos-lat scaling on a Cartesian
        # grid); no biharmonic / Smagorinsky / Leith. MITgcm flux-form operator.
        A_h=VISC_AH,
        A_h_lat_scaling=False,
        lateral_viscosity_operator="flux_divergence",
        lateral_side_bc="no_slip",
        B_h=0.0,
        C_smag=0.0,
        # No bottom drag, no eddy params, no vertical mixing (single layer).
        bottom_drag_r=0.0,
        gm_redi=None,
        K_h=0.0,
        # MITgcm flux-form momentum advection (vs the vector-invariant default).
        momentum_advection="flux_form",
        # MITgcm fully-backward-Euler implicit free surface (audit: the lever).
        barotropic_solver=barotropic_solver,
        barotropic_implicit_theta_eta=1.0,
        barotropic_implicit_theta_pgf=1.0,
        # Sadourny energy-conserving (vertex-f) Coriolis: the face-f form leaks
        # energy on a β-plane (f_u != f_v) and runs the inviscid gyre turbulent;
        # the vertex-f form conserves KE+PE so the gyre stays laminar like MITgcm.
        coriolis_energy_conserving=True,
        differentiable_barotropic=True,
        use_conservation_fixer=False,
        enable_runtime_checks=False,
    )


def build_gyre_state(z_coord) -> LatLonCGridOceanState:
    """Rest state (u=v=eta=0, uniform T/S) on the closed-box beta-plane grid."""
    geom = build_gyre_geometry()
    return rest_state_latlon_cgrid_ocean(
        geom, z_coord,
        land_mask_override=build_gyre_land_mask(),
    )


def build_gyre_faithful_model(
    *, n: int = NX, dx_m: float = DX_M, dt_s: float = DT_S,
):
    """The MITgcm-faithful single-layer integrator for the EQUILIBRIUM oracle tier.

    Returns a ``GyreFaithfulModel`` (unsplit explicit-Coriolis → implicit free
    surface, every operator calibrated to MITgcm's momU/momV diagnostics) that
    reproduces MITgcm's laminar equilibrium ``|u|max≈0.031, |v|max≈0.084`` at 1×
    AND 2× resolution.  The canonical split ``LatLonCGridOceanModel`` matches the
    oracle at the 10-step / per-tendency tier (``build_gyre_recipe``) but runs the
    marginally-resolved (Munk δ≈1.7-cell) gyre turbulent at equilibrium because its
    barotropic/baroclinic split + forward-backward-Coriolis predictor sits on the
    unstable side of the western-boundary-current instability.  Use this stepper for
    the multi-year equilibrium comparison; see
    ``docs/ocean_fidelity/mitgcm_gyre_energy_conservation.md``.
    """
    from legoesm.ocean.fidelity.mitgcm_gyre_faithful import GyreFaithfulModel
    return GyreFaithfulModel(n=n, dx_m=dx_m, dt_s=dt_s)


def build_gyre_recipe(
    *, barotropic_solver: str = "implicit_cn",
) -> MitgcmGyreRecipe:
    """Assemble the full legoESM-MITgcm barotropic-gyre recipe."""
    geom = build_gyre_geometry()
    z_coord = create_ocean_z_star(1, H_max=H_DEPTH_M)
    config = build_gyre_config(barotropic_solver=barotropic_solver)
    state = build_gyre_state(z_coord)
    wind = build_gyre_wind()
    return MitgcmGyreRecipe(
        geometry=geom, z_coord=z_coord, config=config,
        state=state, wind_forcing=wind, dt_s=DT_S,
    )
