"""legoESM-MITgcm recipe: barotropic wind-driven gyre (the beta-plane oracle).

A pure-config legoESM reproduction of MITgcm ``verification/tutorial_barotropic_gyre``
— the first MITgcm oracle case. Everything is selected from canonical legoESM
blocks; the ONLY new capability it needs is the Cartesian beta-plane C-grid
(``create_beta_plane_cgrid_geometry``), which is what lets a tendency-faithful
match to a non-spherical oracle exist at all.

MITgcm setup (``input/data`` + ``gendata.m``), reproduced field-for-field:

================  ===============================================================
grid              Cartesian beta-plane, 62 x 62 cells x 1 level, dx = dy = 20 km,
                  xgOrigin = ygOrigin = -20 km (so the wet interior is 60 x 60).
Coriolis          f0 = 1e-4, beta = 1e-11  ->  f = f0 + beta*y  (y from origin).
bathymetry        flat 5000 m, solid walls on all 4 boundary rows/cols
                  (``bathy.bin``: h([1 end],:)=0; h(:,[1 end])=0).
wind              tau_x(y) = -tauMax cos(pi Y), tauMax = 0.1 N/m^2,
                  Y = (j - 0.5)/(ny - 2)  (``windx_cosy.bin``). No meridional wind.
physics           homogeneous (tempStepping=saltStepping=.FALSE.) -> single layer,
                  constant density; viscAh = 400 (Laplacian); implicit free
                  surface; no bottom drag; rhoConst = 1000; gBaro = 9.81.
time              deltaT = 1200 s.
================  ===============================================================

Sign convention: MITgcm ``zonalWindFile`` IS the ocean-side stress (eastward +,
applied ``gU += tau_x/(rho dz)``). legoESM's external-forcing path treats
``OceanSurfaceForcing.tau_x`` as the ATMOSPHERIC stress and flips it internally,
so this recipe passes ``tau_x = +tauMax cos(pi Y)`` — after the flip that
reproduces MITgcm's ``-tauMax cos(pi Y)`` ocean stress (same negate the Veros
ACC recipe documents).

The MITgcm reference for tendency/statistics comparison is generated by
``scripts/data/generate_mitgcm_barotropic_gyre_reference.py`` and loaded via
``mitgcm_runner.load_mitgcm_reference("barotropic_gyre")``.
"""

from __future__ import annotations

from typing import NamedTuple

import jax.numpy as jnp
import numpy as np
from legoesm.grids.latlon import (
    LatLonCGridGeometry,
    create_beta_plane_cgrid_geometry,
)
from legoesm.ocean.eos import LinearEOSConfig
from legoesm.ocean.fidelity.mitgcm_recipe import mitgcm_canonical_ocean_config
from legoesm.ocean.init_latlon_cgrid import rest_state_latlon_cgrid_ocean
from legoesm.ocean.state import (
    LatLonCGridOceanConfig,
    LatLonCGridOceanState,
    OceanSurfaceForcing,
)
from legoesm.ocean.vertical import create_ocean_z_star

# --- MITgcm tutorial_barotropic_gyre parameters (input/data + gendata.m). ----
NX = 62
NY = 62
DX_M = 20.0e3
DY_M = 20.0e3
F0 = 1.0e-4            # [s^-1]
BETA = 1.0e-11         # [m^-1 s^-1]
Y_ORIGIN_M = -20.0e3   # ygOrigin
X_ORIGIN_M = -20.0e3   # xgOrigin
H_DEPTH_M = 5000.0     # Ho
TAU_MAX = 0.1          # [N/m^2]
VISC_AH = 400.0        # [m^2/s]  viscAh
DT_S = 1200.0          # deltaT
RHO_CONST = 1000.0     # rhoConst
G_BARO = 9.81          # gBaro


class MitgcmGyreRecipe(NamedTuple):
    """Assembled legoESM reproduction of the MITgcm barotropic gyre."""

    geometry: LatLonCGridGeometry
    z_coord: object
    config: LatLonCGridOceanConfig
    state: LatLonCGridOceanState
    wind_forcing: OceanSurfaceForcing
    dt_s: float


def build_gyre_geometry() -> LatLonCGridGeometry:
    """Cartesian beta-plane C-grid matching MITgcm's grid + Coriolis."""
    return create_beta_plane_cgrid_geometry(
        NY, NX, dx_m=DX_M, dy_m=DY_M, f0=F0, beta=BETA,
        y_origin_m=Y_ORIGIN_M, x_origin_m=X_ORIGIN_M,
        # Post-#514 the C-grid operators READ the stored uniform dx_v (== dx_m)
        # rather than recomputing cos(grid.lat_v), so the natural nonzero
        # y/radius pseudo-lat no longer leaks into the implicit free-surface
        # metric — the cartesian_pseudo_lat=True workaround is obsolete and the
        # WBC stays laminar with the geometry's natural pseudo-lat.
        cartesian_pseudo_lat=False,
    )


def build_gyre_land_mask() -> jnp.ndarray:
    """Closed box: ocean interior, solid walls on every boundary row/col.

    Reproduces ``gendata.m`` ``h([1 end],:)=0; h(:,[1 end])=0`` exactly
    (1.0 = ocean, 0.0 = land).
    """
    mask = np.ones((NY, NX), dtype=np.float64)
    mask[0, :] = 0.0
    mask[-1, :] = 0.0
    mask[:, 0] = 0.0
    mask[:, -1] = 0.0
    return jnp.asarray(mask)


def gyre_taux_ocean_profile() -> np.ndarray:
    """MITgcm OCEAN-side zonal wind stress per row: ``-tauMax cos(pi Y)``.

    ``Y[j] = (j - 0.5)/(ny - 2)`` exactly as ``gendata.m`` (``y=((0:ny-1)-0.5)/
    (ny-2)``). Returns shape ``(NY,)`` [N/m^2].
    """
    j = np.arange(NY, dtype=np.float64)
    y_norm = (j - 0.5) / (NY - 2)
    return -TAU_MAX * np.cos(np.pi * y_norm)


def build_gyre_wind() -> OceanSurfaceForcing:
    """Wind as ``OceanSurfaceForcing``. Passes ``+tauMax cos(pi Y)`` so legoESM's
    internal atmospheric->ocean flip reproduces MITgcm's ``-tauMax cos(pi Y)``."""
    taux_ocean = gyre_taux_ocean_profile()           # (NY,) ocean-side
    tau_x = jnp.asarray(np.broadcast_to(-taux_ocean[:, None], (NY, NX)))  # negate
    tau_y = jnp.zeros((NY, NX), dtype=tau_x.dtype)
    return OceanSurfaceForcing(tau_x=tau_x, tau_y=tau_y)


def build_gyre_config(
    *, barotropic_solver: str = "implicit_cn",
) -> LatLonCGridOceanConfig:
    """Single-layer barotropic config matching MITgcm's DEFAULT core numerics.

    Settled by a direct MITgcm source audit (set_defaults.F / ini_parms.F) of the
    tutorial deck, not by trial-and-error:

    * ``barotropic_implicit_theta_{eta,pgf}=1.0`` — MITgcm's implicit free surface
      is FULLY backward-Euler (``implicSurfPress=implicDiv2DFlow=1.0``), not the
      legoESM default Crank-Nicolson 0.55. This is the dominant lever: it takes
      the 10-step eta pattern correlation from 0.975 to 0.9997 and the magnitude
      from +21% to within 8%.
    * ``momentum_advection="flux_form"`` — MITgcm default is flux-form
      (``vectorInvariantMomentum=.FALSE.``), not vector-invariant. (Negligible at
      spin-up where Ro~5e-7, but the faithful choice for the equilibrated gyre.)
    * ``lateral_viscosity_operator="flux_divergence"`` — MITgcm's component-wise
      ``div(A_h grad u)`` flux form, not the default vector-Laplacian.

    * ``lateral_side_bc="no_slip"`` — MITgcm ``no_slip_sides=.TRUE.``
      (``sideDragFactor=2``): the wall side-drag ``-(2/Δ)·A_h·u_tangential``
      (``mom_u_sidedrag``/``mom_v_sidedrag``). Sets the equilibrium Munk layer /
      gyre transport; inactive over a 10-step spin-up (the boundary layer has
      not yet formed) but required for the equilibrated (multi-year) run.

    * ``coriolis_scheme="explicit_ab2"`` + ``outer_integrator="ab2"`` +
      ``ab2_epsilon=0.01`` + ``momentum_flux_scheme="centered"`` — MITgcm's exact
      unsplit numerics: the planetary Coriolis enters the explicit momentum
      tendency and is Adams-Bashforth-2 extrapolated (``abEps=0.01``) alongside
      2nd-order centered flux-form advection, then the implicit free surface
      projects (the barotropic solver's own FB-Coriolis is gated off — Coriolis is
      already in ``F_slow``). The default ``coriolis_energy_conserving`` face-f
      Coriolis is used (NOT the Sadourny vertex-f override): an earlier version of
      this recipe set the vertex-f form to suppress a β-plane "Coriolis energy
      leak", but that leak was misdiagnosed — its true source was a cos(lat)
      metric inconsistency in the Cartesian beta-plane grid (the pseudo-``lat``
      was ``y_c/radius`` instead of 0, so ``divergence_cgrid`` and the flux-form
      advection recomputed an ~1.8%-short v-face length while the gradient used
      ``cos_lat=1``, breaking grad/div adjointness in the free-surface projection).
      With that grid fixed
      (``create_beta_plane_cgrid_geometry`` now pins ``lat=0``), the MITgcm-faithful
      face-f Coriolis runs the gyre LAMINAR to ``|u|max≈0.027`` / ``|v|max≈0.078``
      (within ~13% of MITgcm's 0.031/0.084), not the turbulent 0.066+ overshoot.
      See docs/ocean/fidelity/mitgcm_gyre_energy_conservation.md (iteration 7).

    Selects the SHARED MITgcm-faithful numerics block via
    :func:`mitgcm_canonical_ocean_config` (the MITgcm recipe card) and supplies
    the per-deck knobs: homogeneous linear EOS, single Laplacian ``viscAh=400``,
    no vertical mixing / physics (single layer), ``abEps=0.01``, and the
    ``barotropic_solver`` (the tutorial validates the per-tendency oracle tier on
    the split ``implicit_cn``; the retired equilibrium-tier GyreFaithfulModel
    stepper is documented in mitgcm_gyre_energy_conservation.md).
    """
    return mitgcm_canonical_ocean_config(
        g=G_BARO,
        rho_0=RHO_CONST,
        # Constant density (homogeneous): linear EOS with zero expansion.
        eos_linear=LinearEOSConfig(rho_ref=RHO_CONST, alpha_T=0.0, beta_S=0.0),
        # Single Laplacian lateral viscosity (MITgcm viscAh); no horizontal tracer
        # diffusion; no vertical mixing / physics block (single homogeneous layer).
        A_h=VISC_AH,
        K_h=0.0,
        # Homogeneous: no active tracer -> the tracer scheme is dynamically inert,
        # so pin it to the config default ('tvd', overriding the card's 'centered').
        tracer_advection="tvd",
        # MITgcm fully-backward-Euler implicit free surface (the card pins theta=1).
        # Solver is a parameter: the per-tendency oracle tier validates implicit_cn.
        barotropic_solver=barotropic_solver,
        # MITgcm abEps for this deck.
        ab2_epsilon=0.01,
    )


def build_gyre_state(z_coord) -> LatLonCGridOceanState:
    """Rest state (u=v=eta=0, uniform T/S) on the closed-box beta-plane grid."""
    geom = build_gyre_geometry()
    return rest_state_latlon_cgrid_ocean(
        geom, z_coord,
        land_mask_override=build_gyre_land_mask(),
    )


def build_gyre_recipe(
    *, barotropic_solver: str = "implicit_cn",
) -> MitgcmGyreRecipe:
    """Assemble the full legoESM-MITgcm barotropic-gyre recipe."""
    geom = build_gyre_geometry()
    z_coord = create_ocean_z_star(1, H_max=H_DEPTH_M)
    config = build_gyre_config(barotropic_solver=barotropic_solver)
    state = build_gyre_state(z_coord)
    wind = build_gyre_wind()
    return MitgcmGyreRecipe(
        geometry=geom, z_coord=z_coord, config=config,
        state=state, wind_forcing=wind, dt_s=DT_S,
    )
