"""Loader for the vendored official CMIP6 CMOR tables.

Why
---
The CMOR variable metadata that ``cmor_output.py`` stamps onto every
NetCDF variable used to live in ~9 hand-typed Python dicts.  Hand-typed
metadata drifts away from the official tables, and it did: an audit
against PCMDI/cmip6-cmor-tables found

* ``positive`` missing on all 15 flux variables,
* ``cell_methods`` wrong on 29 of 35 ``Amon`` variables
  (``"time: mean"`` where CMIP6 requires ``"area: time: mean"``),
* ``units`` wrong on ``cli``/``clw`` (``"1"`` instead of ``"kg kg-1"``),
* ``cell_measures`` missing everywhere,
* no ``type`` (CMIP6 wants ``real``, i.e. float32, not double).

Every one of those is mechanical if the metadata is READ from the table
rather than retyped.  This module is that reader.

The tables are vendored (trimmed, ~80 kB) under ``cmor_tables/`` and are
regenerated by ``scripts/data/build_cmor_table_subset.py``.  Nothing here
touches the network.

Public surface
--------------
``load_table(table_id)``       -> ``{var: entry}`` for one table
``CMOR_TABLES``                -> ``{table_id: {var: entry}}`` (all tables)
``load_cv()``                  -> vendored CMIP6 controlled-vocabulary subset
``table_header(table_id)``     -> the table's ``Header`` block
``coordinate_axis(name)``      -> one ``axis_entry`` (plev19, height2m, ...)

Each entry is the official table entry plus a normalized ``dimensions``
tuple in legoESM's internal axis names, e.g.
``"longitude latitude plev19 time"`` -> ``("time", "plev", "lat", "lon")``.
"""

from __future__ import annotations

import json
import re
from functools import lru_cache
from pathlib import Path
from typing import Any, Dict, Optional, Tuple

_TABLE_DIR = Path(__file__).resolve().parent / "cmor_tables"

# Official CMIP6 table IDs legoESM writes into.
CMIP6_TABLE_IDS: Tuple[str, ...] = (
    "Amon", "day", "CFday", "fx", "Lmon", "Omon", "Ofx", "SImon",
)

# Legacy table aliases kept so pre-existing callers/tests keep working.
# NONE of these is a valid CMIP6 table id for the variables it exposes:
#   ``Aday``  -- CMIP5 spelling; the CMIP6 CV value is ``day``.
#   ``Oyr``   -- a REAL CMIP6 table, but it holds ocean-biogeochemistry
#                annual fields, NOT thetao/so/uo/...; using it for those
#                is a legacy legoESM invention.
#   ``SIyr``  -- does not exist in CMIP6 at all (checked against all 48
#                official tables).
# Output written under these ids is NOT publishable; the compliance test
# refuses to certify them.
LEGACY_TABLE_ALIASES: Dict[str, str] = {
    "Aday": "day",
    "Oyr": "Omon",
    "SIyr": "SImon",
}

# Variables legoESM emits that exist in NO CMIP6 table (verified against
# all 48 official tables at the pinned ref).  They are kept so existing
# callers keep working, but they can never be published as CMIP6 and the
# compliance test refuses to certify them.  ``dimensions`` uses legoESM's
# internal axis names directly.
NON_CMIP6_VARIABLES: Dict[str, Dict[str, Dict[str, Any]]] = {
    "Lmon": {
        "nee": {
            "standard_name": (
                "surface_net_downward_mass_flux_of_carbon_dioxide_"
                "expressed_as_carbon"
            ),
            "long_name": "Net Ecosystem Exchange of Carbon",
            "units": "kg m-2 s-1",
            "cell_methods": "area: mean where land time: mean",
            "cell_measures": "area: areacella",
            "positive": "down",
            "type": "real",
            "dimensions": ("time", "lat", "lon"),
            "comment": "NOT a CMIP6 variable; legoESM diagnostic only.",
        },
    },
    "Omon": {
        "rhopoto": {
            "standard_name": "sea_water_potential_density",
            "long_name": "Sea Water Potential Density",
            "units": "kg m-3",
            "cell_methods": "area: mean where sea time: mean",
            "cell_measures": "area: areacello volume: volcello",
            "positive": "",
            "type": "real",
            "dimensions": ("time", "depth", "lat", "lon"),
            "comment": "NOT a CMIP6 variable; legoESM diagnostic only.",
        },
        "sic": {
            "standard_name": "sea_ice_area_fraction",
            "long_name": "Sea Ice Area Fraction",
            "units": "%",
            "cell_methods": "area: mean where sea time: mean",
            "cell_measures": "area: areacello",
            "positive": "",
            "type": "real",
            "dimensions": ("time", "lat", "lon"),
            "comment": (
                "CMIP5 name; the CMIP6 equivalent is SImon/siconc. "
                "NOT publishable as CMIP6."
            ),
        },
    },
}

# ---------------------------------------------------------------------------
# Dimension normalization: official CMOR axis token -> legoESM internal name
# ---------------------------------------------------------------------------
# ``None`` means the token carries no array dimension in legoESM output:
# scalar coordinates (height2m/height10m -> the ``height`` scalar coord
# built from ``_VAR_REFERENCE_HEIGHT``), single-layer soil (sdepth1) and
# type axes (typesi/typeland/...) are collapsed.
_DIM_TOKEN_MAP: Dict[str, Optional[str]] = {
    "longitude": "lon",
    "latitude": "lat",
    "gridlatitude": "lat",
    "time": "time",
    "time1": "time",
    "time2": "time",
    "time3": "time",
    "basin": "basin",
    "alevel": "lev",
    "alevhalf": "lev",
    "olevel": "depth",
    "olevhalf": "depth",
    "sdepth": "depth",
    "sdepth1": None,
    "height2m": None,
    "height10m": None,
    "typesi": None,
    "typeland": None,
    "typesea": None,
    "typec3pft": None,
    "typec4pft": None,
}
# Any ``plevNN`` / ``plevNNh`` token collapses to the ``plev`` axis.
_PLEV_RE = re.compile(r"^plev\d+h?$")

# Ordering of the internal dimension tuple.  Rank drives the sort so a
# reordering of the official token string cannot change our layout.
_DIM_ORDER = {"time": 0, "basin": 1, "plev": 2, "lev": 2, "depth": 2, "lat": 3, "lon": 4}

# KNOWN DEVIATIONS from the official table, kept because correcting them
# would change the DATA rather than the metadata.  Each one is a
# publication blocker for the affected variable and is asserted, by exact
# membership, in tests/unit/test_cmor_compliance.py so the list cannot
# grow silently.
#
# ``cli``/``clw``: CMIP6 ``Amon`` defines them on ``alevel`` (native model
# levels).  legoESM's CMOR pipeline interpolates all 3-D atmospheric
# fields to ``plev19`` before writing, so the emitted files carry a
# pressure axis.  Relabelling the axis would be a lie about the data and
# emitting model levels would require new diagnostics, so the deviation
# stands and is reported.
ALEVEL_EMITTED_ON_PLEV: Tuple[str, ...] = ("cli", "clw")

# UNITS DEVIATIONS -- variables where adopting the official ``units``
# string would MISREPRESENT the data currently produced, so the writer
# keeps emitting what the data actually is and the discrepancy is
# reported instead of silently relabelled.
#
# ``Omon/tos`` and ``Omon/tosga``: CMIP6 declares ``degC``.  The old
# hand-typed legoESM table declared ``K``, and the producing code was
# written to match it -- ``scripts/run/run_omip2_io_smoke.py:144`` does
# ``tos = T[..., 0] + constants.T_freeze  # surface T -> K for CMIP6 tos``
# even though the comment two lines above notes ``init_woa`` already
# returns degC.  Stamping ``degC`` on Kelvin data would make every value
# wrong by the freezing-point offset with no error anywhere.  Resolving
# this needs an ocean owner to decide whether the producer converts or
# the label changes; it is NOT a metadata-only fix, so it is out of scope
# here.  These two variables remain unpublishable until that lands.
#
# Keyed ``(table, var) -> units-as-emitted``.  Asserted by exact
# membership in tests/unit/test_cmor_compliance.py.
UNITS_DEVIATIONS: Dict[Tuple[str, str], str] = {
    ("Omon", "tos"): "K",
    ("Omon", "tosga"): "K",
}


def _normalize_dimensions(dim_string: str, var_name: str) -> Tuple[str, ...]:
    """Map an official CMOR ``dimensions`` string to internal axis names."""
    internal = []
    for token in dim_string.split():
        if _PLEV_RE.match(token):
            internal.append("plev")
            continue
        if token not in _DIM_TOKEN_MAP:
            raise KeyError(
                f"Unknown CMOR dimension token {token!r} in {dim_string!r} "
                f"for variable {var_name!r}. Add it to _DIM_TOKEN_MAP in "
                f"cmor_table_loader.py -- silently dropping it would write "
                f"the field on the wrong axes."
            )
        mapped = _DIM_TOKEN_MAP[token]
        if mapped is not None:
            internal.append(mapped)
    if var_name in ALEVEL_EMITTED_ON_PLEV:
        internal = ["plev" if d == "lev" else d for d in internal]
    # Stable ordering; unknown ranks would have raised above.
    internal.sort(key=lambda d: _DIM_ORDER[d])
    return tuple(internal)


@lru_cache(maxsize=None)
def _load_json(name: str) -> Dict[str, Any]:
    path = _TABLE_DIR / name
    if not path.exists():
        raise FileNotFoundError(
            f"Vendored CMOR table {path} is missing. Regenerate with "
            f"scripts/data/build_cmor_table_subset.py."
        )
    with path.open() as fh:
        return json.load(fh)


@lru_cache(maxsize=None)
def load_table(table_id: str) -> Dict[str, Dict[str, Any]]:
    """Return ``{var_name: entry}`` for *table_id*.

    Raises ``KeyError`` for a table id that is neither an official CMIP6
    table legoESM vendors nor a recognized legacy alias -- a silent
    fallback here would write a whole file under a bogus ``table_id``.
    """
    official = LEGACY_TABLE_ALIASES.get(table_id, table_id)
    if official not in CMIP6_TABLE_IDS:
        raise KeyError(
            f"Unknown CMOR table {table_id!r}. Known: "
            f"{sorted(CMIP6_TABLE_IDS) + sorted(LEGACY_TABLE_ALIASES)}"
        )
    raw = _load_json(f"CMIP6_{official}.json")
    out: Dict[str, Dict[str, Any]] = {}
    for var, entry in raw["variable_entry"].items():
        rec = dict(entry)
        rec["cmor_dimensions"] = entry["dimensions"]
        rec["dimensions"] = _normalize_dimensions(entry["dimensions"], var)
        deviated = UNITS_DEVIATIONS.get((official, var))
        if deviated is not None:
            rec["cmor_units"] = rec["units"]
            rec["units"] = deviated
        out[var] = rec
    # Legacy non-CMIP6 additions for the *official* table id.
    for var, entry in NON_CMIP6_VARIABLES.get(official, {}).items():
        rec = dict(entry)
        rec.setdefault("cmor_dimensions", "")
        out[var] = rec
    return out


def table_header(table_id: str) -> Dict[str, Any]:
    """Return the ``Header`` block of *table_id* (data_specs_version, ...)."""
    official = LEGACY_TABLE_ALIASES.get(table_id, table_id)
    if official not in CMIP6_TABLE_IDS:
        raise KeyError(f"Unknown CMOR table {table_id!r}")
    return _load_json(f"CMIP6_{official}.json")["Header"]


@lru_cache(maxsize=1)
def load_cv() -> Dict[str, Any]:
    """Return the vendored CMIP6 controlled-vocabulary subset."""
    return _load_json("CMIP6_CV.json")


def coordinate_axis(name: str) -> Dict[str, Any]:
    """Return one vendored ``axis_entry`` (``plev19``, ``height2m``, ...)."""
    axes = _load_json("CMIP6_coordinate.json")["axis_entry"]
    if name not in axes:
        raise KeyError(
            f"Coordinate axis {name!r} is not vendored. Add it to "
            f"WANTED_AXES in scripts/data/build_cmor_table_subset.py."
        )
    return axes[name]


def conventions_string() -> str:
    """Return a ``Conventions`` value that satisfies the CMIP6 CV regex.

    The CV stores a POSIX-BRE pattern such as
    ``^CF-1.7 CMIP-6.[0-2]\\( UGRID-1.0\\)\\{0,\\}$``.  We emit the value
    the official tables themselves declare in their ``Header``
    (``"CF-1.7 CMIP-6.2"``) and assert it matches, so a table refresh that
    moves either side is caught immediately rather than shipping the
    invalid ``"CF-1.8"`` the writer used to hard-code.
    """
    value = table_header("Amon")["Conventions"]
    if not re.match(cv_conventions_regex(), value):
        raise ValueError(
            f"Vendored Conventions {value!r} does not match the CMIP6 CV "
            f"pattern {cv_conventions_regex()!r}"
        )
    return value


def cv_conventions_regex() -> str:
    """Return the CV's ``Conventions`` pattern translated to Python ``re``."""
    raw = load_cv()["Conventions"]
    pattern = raw[0] if isinstance(raw, list) else raw
    # POSIX BRE -> Python: \( \) \{ \} are literals-escaped groups there.
    return pattern.replace("\\(", "(").replace("\\)", ")").replace(
        "\\{", "{"
    ).replace("\\}", "}")


def required_global_attributes() -> Tuple[str, ...]:
    """Return the CMIP6 CV ``required_global_attributes`` list."""
    return tuple(load_cv()["required_global_attributes"])


def experiment_title(experiment_id: str) -> str:
    """Return the CV's long ``experiment`` string for *experiment_id*.

    ``experiment`` is a REQUIRED CMIP6 global attribute that the old
    writer omitted entirely.  Unknown ids fall back to the id itself
    rather than raising: legoESM runs idealized experiments (``held_suarez``,
    ``aquaplanet``) that are legitimately outside the CMIP6 CV, and those
    outputs are not CMIP6 submissions anyway.
    """
    return load_cv()["experiment"].get(experiment_id, experiment_id)


def build_all_tables() -> Dict[str, Dict[str, Dict[str, Any]]]:
    """Return ``{table_id: {var: entry}}`` for every table incl. aliases."""
    tables = {t: load_table(t) for t in CMIP6_TABLE_IDS}
    for alias in LEGACY_TABLE_ALIASES:
        tables[alias] = load_table(alias)
    return tables
