"""Phase-4c — duo d2a2c_vect ROUTINE-TRANSLATION gate.

Certifies that ``fv3_native_duo_sw_core.d2a2c_vect_duo`` is a faithful
translation of the authoritative symmetryclean ``d2a2c_vect`` DUO branch
(``gridstruct%dg%is_initialized`` — interior 4th-order D->A->C over the full
domain, all panel-edge/cube-corner special-cases skipped): the port run on
the fixture's STORED inputs reproduces the authoritative Fortran ua/va/uc/
vc/ut/vt BIT-for-BIT (uint64) over each output's written region.

This closes the divergence_corner_duo oracle's scope caveat — that gate used
plain-``c_sw`` ua/va (d2a2c_vect's NON-duo branch); this certifies the real
duo ua/va source.  The extracted Fortran is byte-identical to
sw_core.F90:3361-3706 (SHA pinned below); ``input_sha256`` is enforced by
re-serialising the stored inputs.  Fixture (re)generated by
``scripts/cluster/d2a2c_oracle.sbatch``.
"""

import hashlib
import importlib.util
import os

import numpy as np
import pytest

FIX = os.path.join(os.path.dirname(__file__), "fixtures")
REPO = os.path.join(os.path.dirname(__file__), "..", "..")
RES, NG = 12, 3
LO = 1 - NG

# SHA-256 of the extracted d2a2c_vect block in fv3_d2a2c_duo_extract.F90,
# pinned as an in-repo drift guard; verified byte-identical to the
# authoritative symmetryclean sw_core.F90:3361-3706 at extraction time.
_EXTRACT_BLOCK_SHA256 = (
    "36ab66fa91643cfbc8fb321f9e39025e2f64ef87651365628ab4e320a1e474f0")

_PORT_INPUTS = ("cosa_s", "rsin2", "cosa_u", "rsin_u", "cosa_v", "rsin_v",
                "u", "v")
_ALL_INPUTS = ("cosa_s", "rsin2", "cosa_u", "rsin_u", "cosa_v", "rsin_v",
               "dxa", "dya", "sin_sg", "u", "v")


def _load_generator():
    path = os.path.join(REPO, "scripts", "validate", "fv3_native",
                        "gen_d2a2c_oracle.py")
    spec = importlib.util.spec_from_file_location("gen_d2a2c_oracle", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


@pytest.fixture(scope="module")
def oracle():
    return np.load(os.path.join(FIX, "d2a2c_oracle_c12.npz"))


def test_fixture_input_hash_enforced(oracle):
    """Re-serialise the fixture's STORED inputs through the generator's
    canonical writer and assert sha256 == the stored input_sha256 (+ a
    nextafter tamper check) — provenance ENFORCED, not merely recorded."""
    gen = _load_generator()
    fields = {k: np.asarray(oracle[k]) for k in _ALL_INPUTS}
    recomputed = hashlib.sha256(
        gen.serialize_d2a2c_inputs(fields, int(oracle["res"]),
                                   int(oracle["ng"]))).hexdigest()
    stored = str(oracle["input_sha256"])
    assert len(stored) == 64 and all(c in "0123456789abcdef" for c in stored)
    assert recomputed == stored
    tampered = dict(fields)
    tampered["u"] = fields["u"].copy()
    tampered["u"].flat[0] = np.nextafter(tampered["u"].flat[0], np.inf)
    bad = hashlib.sha256(
        gen.serialize_d2a2c_inputs(tampered, int(oracle["res"]),
                                   int(oracle["ng"]))).hexdigest()
    assert bad != stored


def test_extract_block_sha_pinned():
    """The extracted authoritative d2a2c_vect Fortran block is unchanged."""
    f = os.path.join(REPO, "scripts", "validate", "fv3_native",
                     "fv3_d2a2c_duo_extract.F90")
    txt = open(f, encoding="utf-8").read().split("\n")
    i0 = next(i for i, ln in enumerate(txt)
              if ln.strip().startswith("subroutine d2a2c_vect"))
    i1 = next(i for i, ln in enumerate(txt)
              if ln.strip() == "end subroutine d2a2c_vect")
    block = ("\n".join(txt[i0:i1 + 1]) + "\n").encode()
    assert hashlib.sha256(block).hexdigest() == _EXTRACT_BLOCK_SHA256


def test_d2a2c_vect_duo_bit_exact_on_stored_inputs(oracle):
    """Run the port on the fixture's STORED inputs; each of the six outputs
    must equal the authoritative Fortran BIT-for-BIT (uint64) over its
    written region (the port's non-sentinel cells)."""
    from legoesm.core.fv3_native_duo_sw_core import d2a2c_vect_duo
    from legoesm.core.fv3_native_sw_core import Bounds

    bd = Bounds.single_tile(RES, NG)
    gs = {k: np.asarray(oracle[k]) for k in
          ("cosa_s", "rsin2", "cosa_u", "rsin_u", "cosa_v", "rsin_v")}
    got = d2a2c_vect_duo(np.asarray(oracle["u"]), np.asarray(oracle["v"]),
                         gs, bd, RES + 1, RES + 1, dord4=True, grid_type=0)
    # expected written-node counts per output (geometry, non-vacuity guard).
    # ua/va: full domain (isd:ied)^2.  uc/ut: i in is-1..ie+2 (RES+3),
    # j in js-1..je+1 (RES+2).  vc/vt: i in is-1..ie+1 (RES+2),
    # j in js-1..je+2 (RES+3).  So uc=ut=vc=vt = (RES+3)*(RES+2) = 210 at C12.
    m_a = RES + 2 * NG
    expect = {"ua": m_a * m_a, "va": m_a * m_a,           # 324
              "uc": (RES + 3) * (RES + 2), "ut": (RES + 3) * (RES + 2),
              "vc": (RES + 2) * (RES + 3), "vt": (RES + 2) * (RES + 3)}
    total_diff = 0
    for key in ("ua", "va", "uc", "vc", "ut", "vt"):
        g = np.asarray(got[key], dtype=np.float64)
        w = np.asarray(oracle[key], dtype=np.float64)
        assert g.shape == w.shape, key
        mask = np.abs(g) < 1e29          # the port's written (non-sentinel) region
        n = int(mask.sum())
        assert n == expect[key], f"{key}: {n} written != {expect[key]}"
        assert np.isfinite(w[mask]).all(), f"{key}: Fortran sentinel in region"
        gd = int((g[mask].view(np.uint64) != w[mask].view(np.uint64)).sum())
        total_diff += gd
        assert gd == 0, f"{key}: {gd}/{n} nodes differ bitwise"
    assert total_diff == 0


def test_fixture_input_provenance(oracle):
    sha = str(oracle["input_sha256"])
    assert len(sha) == 64 and all(c in "0123456789abcdef" for c in sha)
    assert "d2a2c_vect" in str(oracle["input_lineage"])
    assert "divergence_corner_duo" in str(oracle["input_lineage"])
