"""Phase 4a — c_sw one-step oracle: field-by-field vs verbatim Fortran.

The fixture pair was generated by:

1. ``scripts/validate/fv3_native/export_swcore_inputs.py`` — builds the
   single-tile gridstruct (certified phase-1/2 compute domains + kinked
   mpp-equivalent halos) and the analytic rotated solid-body SW state,
   dumping every slot (``swcore_input.npz`` + text twin).
2. ``fv3_swcore_oracle_driver.F90`` + ``fv3_swcore_extract.F90`` — the
   VERBATIM ``c_sw``/``d2a2c_vect``/``divergence_corner``/fill extraction
   from GFDL_atmos_cubed_sphere @ 6f658bd0 (production branch, no
   SW_DYNAMICS), run for ONE step: nord=1, dt2=112.5, hydrostatic=T,
   dord4=T, grid_type=0 -> ``swcore_oracle_c12.npz``.

The python port must reproduce the Fortran outputs from the SAME input
bytes.  Compute-domain agreement is exact-to-roundoff; full-array
agreement (halo rings included) pins even the sentinel-propagation
behaviour, since both sides consume identical inputs.
"""

import os

import numpy as np
import pytest

FIX = os.path.join(os.path.dirname(__file__), "fixtures")


@pytest.fixture(scope="module")
def oracle():
    return np.load(os.path.join(FIX, "swcore_oracle_c12.npz"))


@pytest.fixture(scope="module")
def inputs():
    return np.load(os.path.join(FIX, "swcore_input.npz"))


@pytest.fixture(scope="module")
def csw_result(inputs):
    from legoesm.core.fv3_native_sw_core import Bounds, c_sw

    res = int(inputs["res"])
    ng = int(inputs["ng"])
    bd = Bounds.single_tile(res, ng)
    gs = {k: inputs[k] for k in inputs.files
          if k not in ("res", "ng", "dt2", "nord", "delp", "pt", "u", "v")}
    return c_sw(
        delp=inputs["delp"].copy(), pt=inputs["pt"].copy(),
        w=np.zeros_like(inputs["delp"]),
        u=inputs["u"].copy(), v=inputs["v"].copy(),
        gs=gs, bd=bd, npx=res + 1, npy=res + 1,
        dt2=float(inputs["dt2"]), nord=int(inputs["nord"]),
        hydrostatic=True, dord4=True, grid_type=0)


def _compute_slices(res, ng, shape):
    """Fortran compute-domain slices for a (cell|node)-shaped axis."""
    def sl(nlen):
        extra = nlen - (res + 2 * ng)   # 0 cell axis, 1 node axis
        return slice(ng, ng + res + extra)
    return tuple(sl(s) for s in shape)


# ---- input-side regeneration determinism (exporter is oracle-critical) ----

def test_gridstruct_regeneration_matches_fixture(inputs):
    from legoesm.grids.fv3_native_gridstruct import (
        FV3_OMEGA, FV3_RADIUS_M, analytic_swcore_state,
        build_fv3_native_gridstruct)

    gs = build_fv3_native_gridstruct(int(inputs["res"]), int(inputs["ng"]),
                                     radius=FV3_RADIUS_M, omega=FV3_OMEGA)
    st = analytic_swcore_state(gs)
    for key in ("dx", "dy", "dxa", "dya", "dxc", "dyc", "rdxc", "rdyc",
                "rarea", "rarea_c", "cosa_u", "sina_u", "rsin_u",
                "cosa_v", "sina_v", "rsin_v", "cosa_s", "rsin2",
                "sin_sg", "cos_sg", "fC"):
        assert np.array_equal(gs[key], inputs[key]), key
    for key in ("delp", "pt", "u", "v"):
        assert np.array_equal(st[key], inputs[key]), key


def test_gridstruct_halo_strips_are_real(inputs):
    """Side strips must carry real (non-sentinel) metric values."""
    res, ng = int(inputs["res"]), int(inputs["ng"])
    dxa = inputs["dxa"]
    sl = slice(ng, ng + res)
    for strip in (dxa[:ng, sl], dxa[-ng:, sl], dxa[sl, :ng], dxa[sl, -ng:]):
        assert (strip < 1.0e6).all()
    ssg = inputs["sin_sg"]
    for strip in (ssg[:ng, sl, :], ssg[-ng:, sl, :],
                  ssg[sl, :ng, :], ssg[sl, -ng:, :]):
        assert (np.abs(strip) <= 1.0).all()


def test_sin_sg_transport_patches_present(inputs):
    """The post-fill_ghost corner transport patches (verbatim v2 set)."""
    res, ng = int(inputs["res"]), int(inputs["ng"])
    npx = res + 1
    ssg = inputs["sin_sg"]
    lo = 1 - ng

    def at(i, j, k):
        return ssg[i - lo, j - lo, k - 1]

    csg = inputs["cos_sg"]

    def atc(i, j, k):
        return csg[i - lo, j - lo, k - 1]

    for i in range(0, -2 - 1, -1):   # sw corner strip
        assert at(0, i, 3) == at(i, 1, 2)
        assert at(i, 0, 4) == at(1, i, 1)
        assert atc(0, i, 3) == atc(i, 1, 2)
        assert atc(i, 0, 4) == atc(1, i, 1)
    for i in range(npx, npx + 2 + 1):    # nw (v2 source: npx - i)
        assert at(0, i, 3) == at(npx - i, npx - 1, 4)
        assert atc(0, i, 3) == atc(npx - i, npx - 1, 4)
    for i in range(0, -2 - 1, -1):
        assert at(i, npx, 2) == at(1, npx - i, 1)
        assert atc(i, npx, 2) == atc(1, npx - i, 1)
    for j in range(0, -2 - 1, -1):       # se
        assert at(npx, j, 1) == at(npx - j, 1, 2)
        assert atc(npx, j, 1) == atc(npx - j, 1, 2)
    for i in range(npx, npx + 2 + 1):
        assert at(i, 0, 4) == at(npx - 1, npx - i, 3)
        assert atc(i, 0, 4) == atc(npx - 1, npx - i, 3)
    for i in range(0, 2 + 1):        # ne corner strip
        assert at(npx, npx + i, 1) == at(npx + i, npx - 1, 4)
        assert at(npx + i, npx, 2) == at(npx - 1, npx + i, 3)
        assert atc(npx, npx + i, 1) == atc(npx + i, npx - 1, 4)
        assert atc(npx + i, npx, 2) == atc(npx - 1, npx + i, 3)


# ---- the phase-4a acceptance: field-by-field c_sw agreement ----

@pytest.mark.parametrize("field", ["delpc", "ptc", "uc", "vc",
                                   "ut", "vt", "ua", "va", "divg_d"])
def test_c_sw_matches_fortran_compute_domain(csw_result, oracle,
                                             inputs, field):
    got = csw_result[field]
    want = oracle[field]
    res, ng = int(inputs["res"]), int(inputs["ng"])
    sl = _compute_slices(res, ng, want.shape)
    g, w = got[sl], want[sl]
    assert np.isfinite(w).all()
    scale = np.maximum(np.abs(w).max(), 1e-30)
    err = np.abs(g - w).max() / scale
    assert err < 1e-13, f"{field}: rel err {err:.3e}"


@pytest.fixture(scope="module")
def perturbed_result(inputs):
    from legoesm.core.fv3_native_sw_core import Bounds, c_sw

    res = int(inputs["res"])
    ng = int(inputs["ng"])
    bd = Bounds.single_tile(res, ng)
    gs = {k: inputs[k] for k in inputs.files
          if k not in ("res", "ng", "dt2", "nord", "delp", "pt", "u", "v")}
    return c_sw(
        delp=inputs["delp"].copy(), pt=inputs["pt"].copy(),
        w=np.zeros_like(inputs["delp"]),
        u=inputs["u"].copy(), v=inputs["v"].copy(),
        gs=gs, bd=bd, npx=res + 1, npy=res + 1,
        dt2=float(inputs["dt2"]) * (1.0 + 1.0e-6),
        nord=int(inputs["nord"]),
        hydrostatic=True, dord4=True, grid_type=0)


@pytest.mark.parametrize("field", ["delpc", "ptc", "uc", "vc",
                                   "ut", "vt"])
def test_oracle_comparison_has_teeth(perturbed_result, oracle,
                                     inputs, field):
    """Synthetic violation: a perturbed step must FAIL every dt2-sensitive
    field's comparison (ua/va and divg_d are computed before the dt2
    scaling — legitimately dt2-blind).
    Guards against a vacuous gate (wrong slices, all-sentinel filters,
    fixture/key mixups silently comparing nothing)."""
    want = oracle[field]
    res, ng = int(inputs["res"]), int(inputs["ng"])
    sl = _compute_slices(res, ng, want.shape)
    scale = np.abs(want[sl]).max()
    err = np.abs(perturbed_result[field][sl] - want[sl]).max() / scale
    assert err > 1e-13, f"{field}: perturbed run still matches — vacuous gate"


@pytest.mark.parametrize("field", ["delpc", "ptc", "uc", "vc",
                                   "ut", "vt", "ua", "va", "divg_d"])
def test_c_sw_matches_fortran_full_arrays(csw_result, oracle,
                                          inputs, field):
    """Halo rings included: identical inputs -> identical garbage rings.

    The driver poisons unwritten slots with -9e9 while the python port
    leaves them at its own initial value; compare only slots the Fortran
    actually wrote (|x| < 8.9e8 or exact sentinel-free), which still spans
    every ring slot fed by real + big_number inputs.
    """
    got = np.asarray(csw_result[field], dtype=np.float64)
    want = np.asarray(oracle[field], dtype=np.float64)
    assert got.shape == want.shape
    res, ng = int(inputs["res"]), int(inputs["ng"])
    # SOURCE-DERIVED defined regions (codex r2 P1-3b): the driver dumps
    # only slots the c_sw/d2a2c write loops define; everything else is
    # NaN in the fixture.  Bounds mirror the driver's citations.
    npx = res + 1
    # Fortran index bounds (is=js=1, ie=je=npx-1):
    #   delpc/ptc [is-1..ie+1]^2 = [0..npx]; ua/va [is-2..ie+2]^2 =
    #   [-1..npx+1]; uc/ut i in [0..npx+1], j in [0..npx];
    #   vc/vt transposed; divg_d [1..npx]^2
    ring = {
        "delpc": (0, npx, 0, npx), "ptc": (0, npx, 0, npx),
        "ua": (-1, npx + 1, -1, npx + 1),
        "va": (-1, npx + 1, -1, npx + 1),
        "uc": (0, npx + 1, 0, npx), "ut": (0, npx + 1, 0, npx),
        "vc": (0, npx, 0, npx + 1), "vt": (0, npx, 0, npx + 1),
        "divg_d": (1, npx, 1, npx),
    }[field]
    lo = 1 - ng

    def rows(a, b):
        return slice(a - lo, b - lo + 1)

    expect = np.zeros(want.shape, dtype=bool)
    expect[rows(ring[0], ring[1]), rows(ring[2], ring[3])] = True
    written = np.isfinite(want)
    assert np.array_equal(written, expect), \
        f"{field}: fixture defined-region differs from the source bounds"
    g, w = got[written], want[written]
    denom = np.maximum(np.abs(w), 1.0)
    err = (np.abs(g - w) / denom).max()
    assert err < 1e-12, f"{field}: rel err {err:.3e} over defined slots"


def test_fortran_oracle_rebuild_matches_fixture(tmp_path, oracle):
    """Rebuild + rerun the VERBATIM Fortran oracle and compare against the
    committed fixture (codex r1 P1-3: CI otherwise never executes the
    extraction).  Skipped where no gfortran toolchain is available."""
    import shutil
    import subprocess

    if shutil.which("gfortran") is None:
        pytest.skip("no gfortran")
    import sys

    repo = os.path.join(os.path.dirname(__file__), "..", "..")
    script = os.path.join(repo, "scripts", "validate", "fv3_native",
                          "gen_swcore_oracle.sh")
    env = dict(os.environ, PYTHON=sys.executable)
    subprocess.run(["bash", script, str(tmp_path), "12", "3"],
                   check=True, env=env, capture_output=True, text=True)
    fresh = np.load(tmp_path / "swcore_oracle_c12.npz")
    for key in ("delpc", "ptc", "uc", "vc", "ut", "vt",
                "ua", "va", "divg_d"):
        assert np.array_equal(fresh[key], oracle[key], equal_nan=True), key


def test_rsin_override_sign_transfer_semantics():
    """Fortran SIGN(max(tiny,|s|), s) semantics incl BOTH signed zeros
    (gfortran default -fsign-zero; codex r2 P2-4)."""
    from legoesm.grids.fv3_native_gridstruct import rsin_border_override

    tiny = 1.0e-8
    s = np.array([0.0, -0.0, 0.5, -0.5, 1e-12, -1e-12])
    got = rsin_border_override(s)
    want = 1.0 / np.array([tiny, -tiny, 0.5, -0.5, tiny, -tiny])
    assert np.array_equal(got, want)
    assert got[1] < 0 and np.isfinite(got).all()


def test_area_c_halo_strips_match_neighbor_faces(inputs):
    """Six-face mpp map: every non-corner-region area_c halo slot must
    equal the neighbouring face's own stored value (codex r2 finding 1 —
    the outermost seam slots were generic quads instead of the x2
    specials)."""
    from legoesm.grids.fv3_native_gridstruct import (
        FV3_OMEGA, FV3_RADIUS_M, build_fv3_native_gridstruct)
    from legoesm.grids.fv3_native_halos import (
        ed_supergrid_lonlat_ref, neighbor_index, neighbor_tiles)
    from legoesm.grids.fv3_native_metrics import compute_fv3_native_metrics

    res, ng = int(inputs["res"]), int(inputs["ng"])
    npx = res + 1
    gs = build_fv3_native_gridstruct(res, ng,
                                     radius=FV3_RADIUS_M, omega=FV3_OMEGA)
    area_c = gs["rarea_c"]
    lon6, lat6 = ed_supergrid_lonlat_ref(res)
    sgc = 2 * np.arange(1, res + 2) - 1
    cert = compute_fv3_native_metrics(lon6[:, sgc - 1][:, :, sgc - 1],
                                      lat6[:, sgc - 1][:, :, sgc - 1],
                                      FV3_RADIUS_M)
    lo = 1 - ng
    sg_npx = 2 * res + 1
    nw, ne, ns, nn = neighbor_tiles(1)
    strips = ((nw, range(1 - ng, 0 + 1), range(1, npx + 1)),
              (ne, range(npx + 1, npx + ng + 1), range(1, npx + 1)),
              (ns, range(1, npx + 1), range(1 - ng, 0 + 1)),
              (nn, range(1, npx + 1), range(npx + 1, npx + ng + 1)))
    checked = 0
    for n_src, irange, jrange in strips:
        for fi in irange:
            for fj in jrange:
                # B node -> supergrid odd-odd -> neighbour B node
                si, sj = 2 * fi - 1, 2 * fj - 1
                ii, jj = neighbor_index(si, sj, 1, n_src, sg_npx, sg_npx)
                if ii % 2 == 0 or jj % 2 == 0:  # pragma: no cover
                    continue
                bi, bj = (ii + 1) // 2, (jj + 1) // 2
                assert 1 <= bi <= npx and 1 <= bj <= npx, (fi, fj)
                want = 1.0 / cert["area_c"][n_src - 1][bi - 1, bj - 1]
                got = area_c[fi - lo, fj - lo]
                assert abs(got - want) <= 1e-12 * abs(want), (fi, fj)
                checked += 1
    # EVERY strip slot must map and match — the 8 outermost seam slots
    # were exactly the ones a lenient count would have skipped (codex r3)
    assert checked == 4 * ng * npx
