"""Phase 4b — d_sw one-step oracle: field-by-field vs verbatim Fortran.

The fixture pair is generated by:

1. ``scripts/validate/fv3_native/export_dswcore_inputs.py`` — builds the
   single-tile gridstruct (all d_sw-consumed fields) + analytic SW state,
   runs the CERTIFIED python c_sw on all six faces and exchanges the
   time-centred uc/vc into tile-1's deep halos (CGRID_NE vector), dumping
   every slot (``dswcore_input.npz`` + text twin).
2. ``fv3_dswcore_oracle_driver.F90`` + ``fv3_dswcore_extract.F90`` — the
   VERBATIM d_sw call tree (tp_core PPM machinery, a2b_edge, d_sw/xtp_u/
   ytp_v/del6_vt_flux, fill_corners) from GFDL_atmos_cubed_sphere @
   6f658bd0 (production branch), run for ONE d_sw step: hord 6/8, nord=1,
   nord_v=1, dddmp=0.2, d4_bg=0.12, damp_v=0.2, hydrostatic, a2b damping
   path ON, dissipation-estimate OFF -> ``dswcore_oracle_c12.npz`` (each
   field stored on its python-return array's Fortran origin, NaN outside
   the source-defined region).

The loop-faithful python port (``legoesm.core.fv3_native_d_sw.d_sw``) must
reproduce the Fortran outputs from the SAME input bytes; agreement is
exact-to-roundoff on every dumped field.
"""

import os

import numpy as np
import pytest

FIX = os.path.join(os.path.dirname(__file__), "fixtures")

_CFG = dict(hord_tr=8, hord_mt=6, hord_vt=6, hord_tm=6, hord_dp=6,
            nord=1, nord_v=1, dddmp=0.2, d2_bg=0.0, d4_bg=0.12, damp_v=0.2,
            hydrostatic=True, do_diss_est=False)

# oracle fixture key == python d_sw return key (fixture is stored on the
# python array origin), so the comparison is a same-shape masked diff over
# the finite (== source-defined) region.  ``ptc`` is EXCLUDED: INTENT(OUT)
# scratch written only by the nord==0 circulation branch (skipped at
# nord=1) and the inline_q arm — genuinely undefined on this path, so the
# driver does not dump it.  ``delpc`` IS certified over its full 1..res+1
# write range; ``heat_source``/``diss_est`` verify the production zeroing;
# ``divg_d`` in is the REAL c_sw divergence (feeds the Smagorinsky
# sqrt(delpc**2 + a2b**2)), so a2b_ord4's output is discriminated.
_FIELDS = ["delp", "pt", "delpc", "u", "vc", "v", "uc", "ua", "va",
           "divg_d", "crx_adv", "xfx_adv", "cx", "cry_adv", "yfx_adv", "cy",
           "xflux", "yflux", "heat_source", "diss_est"]


@pytest.fixture(scope="module")
def oracle():
    return np.load(os.path.join(FIX, "dswcore_oracle_c12.npz"))


@pytest.fixture(scope="module")
def inputs():
    return np.load(os.path.join(FIX, "dswcore_input.npz"))


def _make_gs(inp):
    gs = {k: inp[k] for k in inp.files if k not in ("res", "ng", "dt")}
    gs.update(bounded_domain=False, grid_type=0, do_f3d=False,
              prevent_diss_cooling=False, stretched_grid=False,
              sw_corner=True, se_corner=True, ne_corner=True, nw_corner=True,
              da_min=float(inp["da_min"]), da_min_c=float(inp["da_min_c"]))
    return gs


def _run(inp, gs, dt_scale=1.0):
    from legoesm.core.fv3_native_d_sw import d_sw
    from legoesm.core.fv3_native_sw_core import Bounds

    res, ng = int(inp["res"]), int(inp["ng"])
    bd = Bounds.single_tile(res, ng)
    m_a = res + 2 * ng
    # divg_d in = the REAL c_sw divergence (exporter's DIVGD_IN); the
    # unread halo is NaN.  d_sw copies it into delpc and feeds the
    # Smagorinsky a2b term, so a2b_ord4 is discriminated (codex p4b P1-2).
    divg_in = np.array(inp["divg_d_in"], dtype=np.float64, copy=True)
    return d_sw(
        delp=inp["delp"], pt=inp["pt"], w=inp["w"], u=inp["u"], v=inp["v"],
        uc=inp["uc"], vc=inp["vc"], ua=inp["ua"], va=inp["va"],
        divg_d=divg_in,
        xflux=np.zeros((res + 1, res)), yflux=np.zeros((res, res + 1)),
        cx=np.zeros((res + 1, m_a)), cy=np.zeros((m_a, res + 1)),
        gs=gs, bd=bd, npx=res + 1, npy=res + 1,
        dt=float(inp["dt"]) * dt_scale, **_CFG)


@pytest.fixture(scope="module")
def result(inputs):
    return _run(inputs, _make_gs(inputs))


@pytest.mark.parametrize("field", _FIELDS)
def test_d_sw_matches_fortran(result, oracle, field):
    """Bit-exact (rel err < 1e-11) over the finite fixture region.  The
    Fortran driver dumps only the source-defined write-loop ranges of each
    field (documented per-field in the driver's dump_all); the builder
    stores them on the python array origin and leaves every other slot
    NaN, so the finite mask is exactly the compared region."""
    want = np.asarray(oracle[field], dtype=np.float64)
    got = np.asarray(result[field], dtype=np.float64)
    assert got.shape == want.shape, field
    finite = np.isfinite(want)
    assert int(finite.sum()) > 0, f"{field}: empty defined region"
    denom = np.maximum(np.abs(want[finite]), 1.0)
    err = (np.abs(got[finite] - want[finite]) / denom).max()
    assert err < 1e-11, f"{field}: max rel err {err:.3e}"


def test_oracle_comparison_has_teeth(inputs, oracle):
    """A perturbed dt must break the u update — guards against a vacuous
    gate (wrong shapes / all-NaN masks silently comparing nothing)."""
    perturbed = _run(inputs, _make_gs(inputs), dt_scale=1.01)
    want = np.asarray(oracle["u"], dtype=np.float64)
    got = np.asarray(perturbed["u"], dtype=np.float64)
    finite = np.isfinite(want)
    err = (np.abs(got[finite] - want[finite])
           / np.maximum(np.abs(want[finite]), 1.0)).max()
    assert err > 1e-6, "perturbed dt still matches — vacuous gate"


def test_a2b_ord4_is_discriminated(inputs, oracle, monkeypatch):
    """The Smagorinsky divergence damping actually depends on a2b_ord4's
    output — with the REAL c_sw divg_d fed in, zeroing a2b_ord4 must break
    the u update (codex p4b P1-2: a -9e9 divg_d left a2b's result dead)."""
    import legoesm.core.fv3_native_d_sw as mod

    def _a2b_zero(qin, qout, *a, **k):
        for i in range(qout.a.shape[0]):
            for j in range(qout.a.shape[1]):
                qout.a[i, j] = 0.0

    monkeypatch.setattr(mod, "a2b_ord4", _a2b_zero)
    out = _run(inputs, _make_gs(inputs))
    want = np.asarray(oracle["u"], dtype=np.float64)
    got = np.asarray(out["u"], dtype=np.float64)
    finite = np.isfinite(want)
    err = (np.abs(got[finite] - want[finite])
           / np.maximum(np.abs(want[finite]), 1.0)).max()
    assert err > 1e-8, "zeroing a2b_ord4 left u unchanged — a2b is dead"
