"""Phase 2 of the FV3-native cubed-sphere effort: exact FV3 metric construction.

Pins the phase-2 guarantees against the extended source-derived oracle
(``tests/grids/fixtures/fv3_gnomonic_ed_oracle.npz``, unit-sphere metric
fields regenerated by ``scripts/validate/fv3_native/gen_oracle.sh`` from the
verbatim ``fv_grid_tools``/``fv_grid_utils`` extraction):

1. ORACLE — the FV3-native metric builder reproduces the Fortran
   ``init_grid``+``grid_area`` FINAL state (spherical-excess areas, agrid
   distances, the ×2 half-dual edge overwrites in W,E,S,N order, cube-corner
   handling) field-by-field at C1/C8/C36, in create-layout via the
   deterministic face remap.

2. CLOSURE — spherical-excess cell areas tile 4πR² to machine precision.
   (``area_c`` deliberately has NO 4π assertion: FV3's own last-writer edge
   overwrites leave the 8 cube-vertex duals off the exact tiling — the
   oracle pins the real FV3 values, not an idealized closure.)

3. NO FALLBACK — an ED-provenance C/D grid must never silently take the
   legacy chord/supergrid approximations; the equiangular default must
   still take exactly the legacy path (byte-stability guarded by the
   pre-existing regression suite).
"""
from __future__ import annotations

import os
import pathlib

import numpy as np
import pytest

jax = pytest.importorskip("jax")
jax.config.update("jax_enable_x64", True)

from legoesm import constants  # noqa: E402
from legoesm.grids.cubed_sphere import (  # noqa: E402
    create_cubed_sphere,
    _GNOMONIC_ED_FACE_PERM,
    _GNOMONIC_ED_FACE_ROT,
)
from legoesm.grids.cubed_sphere_cdgrid import (  # noqa: E402
    create_cubed_sphere_cdgrid,
)

R = float(constants.R_earth)

_FIXTURE = pathlib.Path(__file__).parent / "fixtures" / "fv3_gnomonic_ed_oracle.npz"


def _rot_scalar(field: np.ndarray, k: int) -> np.ndarray:
    """rot90 an unstaggered or B-grid (square) per-face field."""
    return np.rot90(field, k)


def _remap_square(oracle_field: np.ndarray) -> np.ndarray:
    """Remap a square per-face oracle field (FV3 numbering) to create layout."""
    return np.stack([
        _rot_scalar(oracle_field[_GNOMONIC_ED_FACE_PERM[F]],
                    _GNOMONIC_ED_FACE_ROT[F])
        for F in range(6)
    ])


def _remap_staggered_pair(fx: np.ndarray, fy: np.ndarray):
    """Remap an (x-stagger, y-stagger) oracle field pair to create layout.

    rot90 by an odd k maps x-staggered positions onto y-staggered positions
    and vice versa, so the pair swaps; np.rot90 handles the index reversal.
    """
    out_x, out_y = [], []
    for F in range(6):
        g = _GNOMONIC_ED_FACE_PERM[F]
        k = _GNOMONIC_ED_FACE_ROT[F]
        if k % 2 == 0:
            out_x.append(np.rot90(fx[g], k))
            out_y.append(np.rot90(fy[g], k))
        else:
            out_x.append(np.rot90(fy[g], k))
            out_y.append(np.rot90(fx[g], k))
    return np.stack(out_x), np.stack(out_y)


def _load(im: int):
    d = np.load(_FIXTURE)
    return {
        "area": d[f"area_unit_c{im}"] * R**2,
        "dx": d[f"dx_unit_c{im}"] * R,
        "dy": d[f"dy_unit_c{im}"] * R,
        "dxa": d[f"dxa_unit_c{im}"] * R,
        "dya": d[f"dya_unit_c{im}"] * R,
        "dxc": d[f"dxc_unit_c{im}"] * R,
        "dyc": d[f"dyc_unit_c{im}"] * R,
        "area_c": d[f"area_c_unit_c{im}"] * R**2,
    }


# ---------------------------------------------------------------------------
# 1. Direct builder vs oracle (FV3 numbering — no remap needed)
# ---------------------------------------------------------------------------
class TestBuilderOracle:
    @pytest.mark.parametrize("im", [1, 8, 36])
    def test_builder_matches_fv3_metrics_fv3_layout(self, im):
        from legoesm.grids.fv3_native_metrics import (
            compute_fv3_native_metrics,
        )
        from legoesm.grids.cubed_sphere import make_fv3_native_grid

        ref = _load(im)
        lon6, lat6 = (np.asarray(a) for a in make_fv3_native_grid(im, 0))
        m = compute_fv3_native_metrics(lon6, lat6, radius=R)
        for name in ("area", "dx", "dy", "dxa", "dya", "dxc", "dyc",
                     "area_c"):
            got = np.asarray(m[name])
            assert got.shape == ref[name].shape, name
            rel = np.abs(got - ref[name]) / np.abs(ref[name]).max()
            # Spherical-excess fields (area, area_c) sit at the angle-ulp
            # floor: the excess is a cancellation of four angles ~pi/2, so a
            # single double-rounding difference between the oracle's true
            # quad (f_p) and numpy's 80-bit longdouble intermediates shows up
            # as ~8e-13 relative at C36.  5e-12 pins that floor; distances
            # have no cancellation and hold 1e-13.
            tol = 5e-12 if name in ("area", "area_c") else 1e-13
            assert rel.max() < tol, f"{name}: max rel dev {rel.max():.3e}"

    @pytest.mark.parametrize("im", [8, 36])
    def test_cell_areas_close_sphere(self, im):
        from legoesm.grids.fv3_native_metrics import (
            compute_fv3_native_metrics,
        )
        from legoesm.grids.cubed_sphere import make_fv3_native_grid

        lon6, lat6 = (np.asarray(a) for a in make_fv3_native_grid(im, 0))
        m = compute_fv3_native_metrics(lon6, lat6, radius=R)
        closure = float(np.sum(m["area"])) / (4.0 * np.pi * R**2) - 1.0
        assert abs(closure) < 1e-12


# ---------------------------------------------------------------------------
# 2. Factory-level: ED cdgrid carries the exact FV3 metrics (create layout)
# ---------------------------------------------------------------------------
class TestCDGridExactMetrics:
    @pytest.mark.parametrize("im", [8, 36])
    def test_ed_cdgrid_metrics_match_remapped_oracle(self, im):
        ref = _load(im)
        g = create_cubed_sphere(im, dtype=np.float64, gnomonic="ed")
        cd = create_cubed_sphere_cdgrid(g, metric_dtype=np.float64)

        area_c_ref = _remap_square(ref["area_c"])
        got = np.asarray(cd.area_corner)
        rel = np.abs(got - area_c_ref) / area_c_ref.max()
        # 5e-12: spherical-excess angle-ulp floor (see TestBuilderOracle)
        assert rel.max() < 5e-12, f"area_c: {rel.max():.3e}"

        dxc_ref, dyc_ref = _remap_staggered_pair(ref["dxc"], ref["dyc"])
        rel = np.abs(np.asarray(cd.dxc) - dxc_ref) / dxc_ref.max()
        assert rel.max() < 1e-13, f"dxc: {rel.max():.3e}"
        rel = np.abs(np.asarray(cd.dyc) - dyc_ref) / dyc_ref.max()
        assert rel.max() < 1e-13, f"dyc: {rel.max():.3e}"

        # CDGrid stores only the reciprocals rdxa/rdya — compare through them
        dxa_ref, dya_ref = _remap_staggered_pair(ref["dxa"], ref["dya"])
        got_dxa = 1.0 / np.asarray(cd.rdxa)
        rel = np.abs(got_dxa - dxa_ref) / dxa_ref.max()
        assert rel.max() < 1e-13, f"dxa (1/rdxa): {rel.max():.3e}"
        got_dya = 1.0 / np.asarray(cd.rdya)
        rel = np.abs(got_dya - dya_ref) / dya_ref.max()
        assert rel.max() < 1e-13, f"dya (1/rdya): {rel.max():.3e}"

    def test_ed_cdgrid_reciprocals_consistent(self):
        g = create_cubed_sphere(8, dtype=np.float64, gnomonic="ed")
        cd = create_cubed_sphere_cdgrid(g, metric_dtype=np.float64)
        assert np.allclose(
            np.asarray(cd.rdxc) * np.asarray(cd.dxc), 1.0, atol=1e-12)
        assert np.allclose(
            np.asarray(cd.rdyc) * np.asarray(cd.dyc), 1.0, atol=1e-12)
        assert np.allclose(
            np.asarray(cd.rarea_c) * np.asarray(cd.area_corner), 1.0, atol=1e-12)


# ---------------------------------------------------------------------------
# 3. Dispatch: no approximate fallback on the FV3-native path; legacy
#    equiangular still takes exactly the legacy builder
# ---------------------------------------------------------------------------
class TestRemapIndependence:
    def test_remap_table_pinned_to_derived_literals(self):
        # Breaks the shared-table circularity (codex P2): the production
        # PERM/ROT constants are pinned to the values derived independently
        # from the phase-1 old-layout invariance analysis.  A regression in
        # the production table now fails HERE even though the factory test
        # remaps oracle and builder through the same table.
        assert _GNOMONIC_ED_FACE_PERM == (0, 1, 3, 4, 2, 5)
        assert _GNOMONIC_ED_FACE_ROT == (0, 0, 3, 3, 1, 0)

    def test_remapped_oracle_faces_land_on_create_faces(self):
        # Independent orientation check: the remapped ORACLE agrid centres
        # must lie on the same cube face as create's EQUIANGULAR layout
        # (which shares no ED remap code).  Face-mean separation between the
        # two layouts is well under half a face width when the mapping is
        # right, and ~a full face width when any slot/rotation is wrong.
        d = np.load(_FIXTURE)
        lon_o = _remap_square(d["agrid_lon_c8"])
        lat_o = _remap_square(d["agrid_lat_c8"])
        g_eq = create_cubed_sphere(8, dtype=np.float64)
        lon_e, lat_e = np.asarray(g_eq.lon), np.asarray(g_eq.lat)

        def mean_xyz(lon, lat):
            v = np.stack([np.cos(lat) * np.cos(lon),
                          np.cos(lat) * np.sin(lon),
                          np.sin(lat)], -1).reshape(6, -1, 3).mean(axis=1)
            return v / np.linalg.norm(v, axis=-1, keepdims=True)

        vo, ve = mean_xyz(lon_o, lat_o), mean_xyz(lon_e, lat_e)
        sep = np.arccos(np.clip(np.sum(vo * ve, axis=-1), -1, 1))
        assert sep.max() < 0.35, f"face-slot mismatch: {np.degrees(sep)}"
        # rotation pin: the [0,0] corner cell of each remapped face must be
        # the corner nearest the equiangular layout's own [0,0] corner cell.
        for F in range(6):
            po = np.array([lon_o[F, 0, 0], lat_o[F, 0, 0]])
            corners = {
                (0, 0): (lon_e[F, 0, 0], lat_e[F, 0, 0]),
                (0, 1): (lon_e[F, 0, -1], lat_e[F, 0, -1]),
                (1, 0): (lon_e[F, -1, 0], lat_e[F, -1, 0]),
                (1, 1): (lon_e[F, -1, -1], lat_e[F, -1, -1]),
            }

            def gcd(a, b):
                return np.arccos(np.clip(
                    np.sin(a[1]) * np.sin(b[1])
                    + np.cos(a[1]) * np.cos(b[1]) * np.cos(a[0] - b[0]),
                    -1, 1))

            best = min(corners, key=lambda k: gcd(po, corners[k]))
            assert best == (0, 0), f"slot {F} rotated: [0,0] nearest {best}"


class TestFV3NativeGuards:
    def test_fp32_grid_construction_fails_closed(self):
        # codex P1: without x64 the ED grid is generated in fp32 — seam
        # nodes stop being bit-equal and 'exact' metrics would be a lie.
        # Must raise, never fall back to chord metrics.  Run in a clean
        # subprocess so this file's module-scope x64 enable can't mask it.
        import subprocess
        import sys

        code = (
            "import jax\n"
            "import numpy as np\n"
            "from legoesm.grids.cubed_sphere import create_cubed_sphere\n"
            "from legoesm.grids.cubed_sphere_cdgrid import "
            "create_cubed_sphere_cdgrid\n"
            "g = create_cubed_sphere(4, gnomonic='ed')\n"
            "try:\n"
            "    create_cubed_sphere_cdgrid(g)\n"
            "except ValueError as e:\n"
            "    assert 'float64' in str(e), e\n"
            "    print('FAILED_CLOSED_OK')\n"
            "else:\n"
            "    raise SystemExit('fp32 ED cdgrid did NOT fail closed')\n"
        )
        env = dict(os.environ)
        env.pop("JAX_ENABLE_X64", None)
        env["JAX_PLATFORMS"] = "cpu"
        out = subprocess.run(
            [sys.executable, "-c", code], env=env,
            capture_output=True, text=True, timeout=600)
        assert "FAILED_CLOSED_OK" in out.stdout, (out.stdout, out.stderr)

    def test_ed_panel_cdgrid_fails_closed(self):
        # codex p2-r2 P1: the ONE route to a regional ED C/D grid must not
        # silently reuse sliced GLOBAL metrics (cube-seam ×2 conventions
        # would be mislabeled as wall metrics).  A-grid ED panels stay fine.
        from legoesm.grids.cubed_sphere import create_cubed_sphere_panel

        with pytest.raises(NotImplementedError, match="walled panel"):
            create_cubed_sphere_panel(
                8, dtype=np.float64, gnomonic="ed", return_cdgrid=True)
        # equiangular panel cdgrid route unchanged
        panel, cd = create_cubed_sphere_panel(
            8, dtype=np.float64, return_cdgrid=True)
        assert panel.gnomonic_form == "equiangular"
        assert cd.base.gnomonic_form == "equiangular"

    def test_duogrid_global_cube_gets_same_global_metrics(self):
        # legoESM's bounded_domain flag is the duogrid OPERATOR shim, not
        # FV3's regional/nested flag — a global duogrid'd ED cube must get
        # byte-identical global FV3 metrics.
        g_plain = create_cubed_sphere(8, dtype=np.float64, gnomonic="ed")
        g_duo = create_cubed_sphere(
            8, dtype=np.float64, gnomonic="ed", use_duogrid=True)
        cd_plain = create_cubed_sphere_cdgrid(g_plain, metric_dtype=np.float64)
        cd_duo = create_cubed_sphere_cdgrid(g_duo, metric_dtype=np.float64)
        assert np.array_equal(np.asarray(cd_plain.area_corner),
                              np.asarray(cd_duo.area_corner))
        assert np.array_equal(np.asarray(cd_plain.dxc),
                              np.asarray(cd_duo.dxc))


class TestNoApproximateFallback:
    def test_ed_never_calls_chord_builder(self, monkeypatch):
        import legoesm.grids.cubed_sphere_cdgrid as cdg

        def _boom(*a, **k):  # pragma: no cover - guard
            raise AssertionError(
                "legacy chord/supergrid metric builder invoked on the "
                "FV3-native (ED) path")

        monkeypatch.setattr(cdg, "_compute_supergrid_metrics", _boom)
        g = create_cubed_sphere(4, dtype=np.float64, gnomonic="ed")
        cdg.create_cubed_sphere_cdgrid(g, metric_dtype=np.float64)

    def test_equiangular_still_uses_legacy_builder(self, monkeypatch):
        import legoesm.grids.cubed_sphere_cdgrid as cdg

        calls = {"n": 0}
        orig = cdg._compute_supergrid_metrics

        def _spy(*a, **k):
            calls["n"] += 1
            return orig(*a, **k)

        monkeypatch.setattr(cdg, "_compute_supergrid_metrics", _spy)
        g = create_cubed_sphere(4, dtype=np.float64)
        cdg.create_cubed_sphere_cdgrid(g, metric_dtype=np.float64)
        assert calls["n"] == 1
