"""Phase-4c — duo d2a2c_vect -> divergence_corner_duo CHAIN oracle.

CLOSES the divergence_corner_duo scope caveat end-to-end for the divergence
sub-pipeline: its own gate fed PLAIN-c_sw ua/va into divergence_corner_duo,
whereas the duo c_sw feeds ua/va from d2a2c_vect's dg-initialized branch
(different at panel edges/corners — 288 nodes).  Here the certified
``d2a2c_vect_duo`` produces the duo ua/va, which feed the certified
``divergence_corner_duo`` -> divg_d, and the composed result is bit-exact
(uint64) to the authoritative Fortran sub-chain (fv3_dchain_driver.F90:
duo d2a2c_vect -> divergence_corner_duo) over the 289 geometry-active
B-nodes.  Both leaves' extractions are SHA-pinned in their own gates; this
gate certifies their COMPOSITION on the real duo ua/va.

Fixture ``dchain_oracle_c12.npz`` (re)generated by
``scripts/cluster/dchain_oracle.sbatch``; ``input_sha256`` enforced.
"""

import hashlib
import importlib.util
import os

import numpy as np
import pytest

FIX = os.path.join(os.path.dirname(__file__), "fixtures")
REPO = os.path.join(os.path.dirname(__file__), "..", "..")
RES, NG = 12, 3
LO = 1 - NG
M_B = RES + 2 * NG + 1

_ALL_INPUTS = ("cosa_s", "rsin2", "cosa_u", "rsin_u", "cosa_v", "rsin_v",
               "dxa", "dya", "rarea_c", "dxc", "dyc", "sin_sg", "cos_sg",
               "u", "v")


def _load_generator():
    path = os.path.join(REPO, "scripts", "validate", "fv3_native",
                        "gen_dchain_oracle.py")
    spec = importlib.util.spec_from_file_location("gen_dchain_oracle", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


@pytest.fixture(scope="module")
def oracle():
    return np.load(os.path.join(FIX, "dchain_oracle_c12.npz"))


def _active_mask():
    """289-node divg_d active mask (isd+1..ied, jsd+1..jed), matching the
    divergence_corner_duo gate."""
    from legoesm.core.fv3_native_sw_core import Bounds
    bd = Bounds.single_tile(RES, NG)
    m = np.zeros((M_B, M_B), dtype=bool)
    m[bd.isd + 1 - LO:bd.ied - LO + 1, bd.jsd + 1 - LO:bd.jed - LO + 1] = True
    return m


def test_fixture_input_hash_enforced(oracle):
    gen = _load_generator()
    fields = {k: np.asarray(oracle[k]) for k in _ALL_INPUTS}
    recomputed = hashlib.sha256(
        gen.serialize_dchain_inputs(fields, int(oracle["res"]),
                                    int(oracle["ng"]))).hexdigest()
    stored = str(oracle["input_sha256"])
    assert len(stored) == 64 and all(c in "0123456789abcdef" for c in stored)
    assert recomputed == stored
    tampered = dict(fields)
    tampered["u"] = fields["u"].copy()
    tampered["u"].flat[0] = np.nextafter(tampered["u"].flat[0], np.inf)
    bad = hashlib.sha256(
        gen.serialize_dchain_inputs(tampered, int(oracle["res"]),
                                    int(oracle["ng"]))).hexdigest()
    assert bad != stored


def test_dchain_divg_d_bit_exact(oracle):
    """Compose the two certified leaves (d2a2c_vect_duo -> divergence_
    corner_duo) on the stored inputs; divg_d must equal the authoritative
    Fortran sub-chain BIT-for-BIT (uint64) over the 289 active B-nodes."""
    from legoesm.core.fv3_native_duo_sw_core import (
        d2a2c_vect_duo,
        divergence_corner_duo,
    )
    from legoesm.core.fv3_native_sw_core import Bounds

    assert (int(oracle["res"]), int(oracle["ng"])) == (RES, NG)
    bd = Bounds.single_tile(RES, NG)
    gs = {k: np.asarray(oracle[k]) for k in _ALL_INPUTS if k not in ("u", "v")}
    u, v = np.asarray(oracle["u"]), np.asarray(oracle["v"])
    duo = d2a2c_vect_duo(u, v, gs, bd, RES + 1, RES + 1, dord4=True,
                         grid_type=0)
    got = np.asarray(
        divergence_corner_duo(u, v, np.asarray(duo["ua"]),
                              np.asarray(duo["va"]), gs, bd, RES + 1, RES + 1,
                              grid_type=0), dtype=np.float64)
    want = np.asarray(oracle["divg_d"], dtype=np.float64)
    assert got.shape == want.shape == (M_B, M_B)
    active = _active_mask()
    assert int(active.sum()) == 289
    assert np.isfinite(want[active]).all()
    # non-vacuity: divg_d has real structure (not all-zero / constant), so
    # the bit-exact match is meaningful.  d2a2c_vect_duo's difference from
    # plain-c_sw ua/va (288 nodes) is certified in its own gate.
    assert np.ptp(want[active]) > 1e-12
    n_diff = int((got[active].view(np.uint64)
                  != want[active].view(np.uint64)).sum())
    assert n_diff == 0, f"{n_diff}/289 divg_d nodes differ bitwise"


def test_fixture_input_provenance(oracle):
    sha = str(oracle["input_sha256"])
    assert len(sha) == 64 and all(c in "0123456789abcdef" for c in sha)
    lin = str(oracle["input_lineage"])
    assert "d2a2c_vect" in lin and "divergence_corner_duo" in lin
