"""Phase 1 of the FV3-native cubed-sphere effort: explicit ED grid selection.

Pins the three phase-1 guarantees:

1. ORACLE — the Python ``gnomonic_grids(im, grid_type=0)`` face panel matches
   the verbatim-extracted FV3 Fortran ``gnomonic_grids`` output (quad-precision
   ENABLE_QUAD_PRECISION build) at C8 and C36 to near machine precision.
   Fixture: ``tests/grids/fixtures/fv3_gnomonic_ed_oracle.npz`` regenerated by
   ``scripts/validate/fv3_native/gen_oracle.sh`` from
   ``fv3_gnomonic_oracle.f90`` (source-derived, not hand-tuned).

2. PROVENANCE — ``CubedSphereGrid`` carries immutable, static grid provenance
   (``gnomonic_form``, ``fv3_grid_type``) as pytree aux_data (never a traced
   leaf, never inferred from dx/dy aspect ratios), the FV3-native factory
   ``create_fv3_native_cubed_sphere`` selects gnomonic_ed (FV3 grid_type=0),
   and ``create_cubed_sphere_cdgrid`` derives its metric family from that
   provenance — including at n=2 where the old aspect-ratio inference was
   provably blind.

3. LEGACY — the historic equiangular grid remains the untouched default of
   ``create_cubed_sphere`` and stays geometrically distinct from ED
   (~231 km max cell-centre separation at C36 per the fidelity audit).

Phase 1 does NOT claim full FV3 fidelity: metrics (phase 2), duogrid halos
(phase 3), and the forward-backward SW core (phase 4) remain non-native.
"""
from __future__ import annotations

import pathlib
import warnings

import numpy as np
import pytest

jax = pytest.importorskip("jax")
jax.config.update("jax_enable_x64", True)

from legoesm.grids.cubed_sphere import (  # noqa: E402
    CubedSphereGrid,
    create_cubed_sphere,
    gnomonic_grids,
)
from legoesm.grids.cubed_sphere_cdgrid import (  # noqa: E402
    create_cubed_sphere_cdgrid,
)
from legoesm import constants  # noqa: E402

R = float(constants.R_earth)

_FIXTURE = pathlib.Path(__file__).parent / "fixtures" / "fv3_gnomonic_ed_oracle.npz"


def _angdiff(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    """Angular difference |a-b| folded into [0, pi] (robust at the 0/2pi seam)."""
    d = np.abs(np.asarray(a) - np.asarray(b)) % (2.0 * np.pi)
    return np.minimum(d, 2.0 * np.pi - d)


# ---------------------------------------------------------------------------
# 1. Source-derived oracle: Python port == FV3 Fortran gnomonic_grids
# ---------------------------------------------------------------------------
class TestFV3SourceOracle:
    @pytest.mark.parametrize("im", [8, 36])
    def test_gnomonic_ed_matches_fv3_fortran(self, im):
        d = np.load(_FIXTURE)
        lon_ref = d[f"lon_c{im}"]
        lat_ref = d[f"lat_c{im}"]
        lon, lat = gnomonic_grids(im, grid_type=0)
        lon = np.asarray(lon)
        lat = np.asarray(lat)
        assert lon.shape == (im + 1, im + 1)
        assert _angdiff(lon, lon_ref).max() < 1e-13
        assert np.abs(lat - lat_ref).max() < 1e-13

    def test_gnomonic_ed_c1_degenerate_corners(self):
        # C1 exercises the empty-interior-loop edge of the construction.
        d = np.load(_FIXTURE)
        lon, lat = gnomonic_grids(1, grid_type=0)
        assert _angdiff(np.asarray(lon), d["lon_c1"]).max() < 1e-13
        assert np.abs(np.asarray(lat) - d["lat_c1"]).max() < 1e-13

    @pytest.mark.parametrize("im", [1, 8, 36])
    def test_make_fv3_native_grid_matches_fv3_mirror_grid(self, im):
        # The full 6-face assembly (gnomonic_grids + mirror_grid pipeline of
        # fv_grid_tools init_grid) — not just the face-1 panel — must match
        # the Fortran oracle in FV3 face numbering, face by face.  C1 (npx=2,
        # even) exercises the no-pole/dateline-forcing branch; C8/C36 (odd
        # npx) exercise the forcing masks.  Longitudes are compared RAW (not
        # mod 2π) away from the exact poles, pinning the FV3 [-π, π] atan2
        # range contract of mirror_grid_faces — an unintended renormalization
        # must fail here.
        from legoesm.grids.cubed_sphere import make_fv3_native_grid

        d = np.load(_FIXTURE)
        lon6, lat6 = make_fv3_native_grid(im, grid_type=0)
        lon6 = np.asarray(lon6)
        lat6 = np.asarray(lat6)
        assert lon6.shape == (6, im + 1, im + 1)
        # longitude is meaningless at the exact poles — mask |lat|=pi/2 nodes
        pole = np.abs(np.abs(d[f"lat6_c{im}"]) - np.pi / 2) < 1e-12
        dlon_raw = np.abs(lon6 - d[f"lon6_c{im}"])
        assert np.where(pole, 0.0, dlon_raw).max() < 1e-13
        assert np.abs(lat6 - d[f"lat6_c{im}"]).max() < 1e-13

    @pytest.mark.parametrize("im", [8, 36])
    def test_factory_centres_match_fv3_agrid_cloud(self, im):
        # End-to-end: the PUBLIC factory's cell centres must be the FV3
        # cell_center2 A-grid centres.  legoESM renumbers/rotates faces into
        # create_cubed_sphere's layout, so compare as a global point cloud
        # (bijective nearest-neighbour match on the unit sphere).
        from scipy.spatial import cKDTree

        from legoesm.grids.cubed_sphere import create_fv3_native_cubed_sphere

        d = np.load(_FIXTURE)
        g = create_fv3_native_cubed_sphere(im, dtype=np.float64)

        def cloud(lon, lat):
            lon = np.asarray(lon, dtype=np.float64).ravel()
            lat = np.asarray(lat, dtype=np.float64).ravel()
            return np.stack([
                np.cos(lat) * np.cos(lon),
                np.cos(lat) * np.sin(lon),
                np.sin(lat),
            ], axis=1)

        ours = cloud(g.lon, g.lat)
        ref = cloud(d[f"agrid_lon_c{im}"], d[f"agrid_lat_c{im}"])
        assert ours.shape == ref.shape
        dist_fwd, idx = cKDTree(ref).query(ours)
        assert dist_fwd.max() < 1e-12
        # bijection: every reference centre is hit exactly once
        assert len(np.unique(idx)) == len(ref)


# ---------------------------------------------------------------------------
# 2. Static provenance on the grid object
# ---------------------------------------------------------------------------
class TestGridProvenance:
    def test_default_grid_is_equiangular_with_provenance(self):
        g = create_cubed_sphere(8, dtype=np.float64)
        assert g.gnomonic_form == "equiangular"
        assert g.fv3_grid_type == 2

    def test_ed_grid_carries_fv3_grid_type_0(self):
        g = create_cubed_sphere(8, dtype=np.float64, gnomonic="ed")
        assert g.gnomonic_form == "ed"
        assert g.fv3_grid_type == 0

    def test_provenance_is_aux_data_not_leaf(self):
        g = create_cubed_sphere(8, dtype=np.float64, gnomonic="ed")
        leaves = jax.tree_util.tree_leaves(g)
        assert not any(isinstance(leaf, str) for leaf in leaves)
        # tree round-trip preserves provenance (aux_data path)
        g2 = jax.tree_util.tree_map(lambda x: x, g)
        assert g2.gnomonic_form == "ed"
        assert g2.fv3_grid_type == 0

    def test_provenance_participates_in_treedef(self):
        g_ed = create_cubed_sphere(8, dtype=np.float64, gnomonic="ed")
        g_eq = create_cubed_sphere(8, dtype=np.float64)
        td_ed = jax.tree_util.tree_structure(g_ed)
        td_eq = jax.tree_util.tree_structure(g_eq)
        assert td_ed != td_eq  # distinct static signature -> no silent mixing

    def test_replace_preserves_provenance(self):
        g = create_cubed_sphere(8, dtype=np.float64, gnomonic="ed")
        g2 = g._replace(radius=2.0 * g.radius)
        assert g2.gnomonic_form == "ed"
        assert g2.fv3_grid_type == 0

    def test_single_face_panel_forwards_ed_provenance(self):
        # ED request makes this non-vacuous: the field defaults would report
        # equiangular/2 if the panel builder failed to forward provenance.
        from legoesm.grids.cubed_sphere import create_cubed_sphere_panel

        panel = create_cubed_sphere_panel(8, dtype=np.float64, gnomonic="ed")
        assert panel.gnomonic_form == "ed"
        assert panel.fv3_grid_type == 0
        # legacy default unchanged
        panel_eq = create_cubed_sphere_panel(8, dtype=np.float64)
        assert panel_eq.gnomonic_form == "equiangular"

    def test_small_earth_scaling_preserves_ed_provenance(self):
        # codex P1: the small-Earth rebuild silently returned an equiangular
        # grid for an ED input (coordinates AND provenance both wrong).
        from legoesm.grids.cubed_sphere import apply_small_earth_scaling

        g_ed = create_cubed_sphere(8, dtype=np.float64, gnomonic="ed")
        g_small = apply_small_earth_scaling(g_ed, 10.0)
        assert g_small.gnomonic_form == "ed"
        assert g_small.fv3_grid_type == 0
        # ED node distribution actually survives (not just the label):
        # lon/lat are radius-independent, so they must match the unscaled grid.
        assert np.allclose(
            np.asarray(g_small.lat), np.asarray(g_ed.lat), atol=1e-12)


# ---------------------------------------------------------------------------
# 3. FV3-native factory entry point
# ---------------------------------------------------------------------------
class TestFV3NativeFactory:
    def test_factory_exists_and_selects_ed(self):
        from legoesm.grids.cubed_sphere import create_fv3_native_cubed_sphere

        g = create_fv3_native_cubed_sphere(8, dtype=np.float64)
        assert isinstance(g, CubedSphereGrid)
        assert g.gnomonic_form == "ed"
        assert g.fv3_grid_type == 0
        # identical coordinates to the explicit gated path
        g_ref = create_cubed_sphere(8, dtype=np.float64, gnomonic="ed")
        assert np.array_equal(np.asarray(g.lon), np.asarray(g_ref.lon))
        assert np.array_equal(np.asarray(g.lat), np.asarray(g_ref.lat))

    def test_factory_rejects_schmidt_stretch(self):
        # Schmidt/stretch args are deliberately NOT in the FV3-native factory
        # signature (unsupported on the ED path) — passing one fails loudly.
        from legoesm.grids.cubed_sphere import create_fv3_native_cubed_sphere

        with pytest.raises(TypeError):
            create_fv3_native_cubed_sphere(8, stretch_fac=3.0)

    def test_gated_path_still_rejects_schmidt_on_ed(self):
        with pytest.raises(ValueError):
            create_cubed_sphere(8, gnomonic="ed", stretch_fac=3.0)


# ---------------------------------------------------------------------------
# 4. CD-grid metric family follows provenance (no aspect-ratio inference)
# ---------------------------------------------------------------------------
class TestCDGridProvenance:
    def test_cdgrid_auto_follows_ed_provenance_at_n2(self):
        # n=2 is the case the old aspect-ratio inference could NOT distinguish
        # (both forms have aspect ~1.0 there) — provenance must decide.
        g_ed = create_cubed_sphere(2, dtype=np.float64, gnomonic="ed")
        cd_auto = create_cubed_sphere_cdgrid(g_ed, metric_dtype=np.float64)
        cd_expl = create_cubed_sphere_cdgrid(
            g_ed, metric_dtype=np.float64, gnomonic="ed")
        assert np.array_equal(
            np.asarray(cd_auto.dxc), np.asarray(cd_expl.dxc))
        assert np.array_equal(
            np.asarray(cd_auto.rarea_c), np.asarray(cd_expl.rarea_c))

    def test_cdgrid_auto_distinguishes_forms_at_n2(self):
        g_ed = create_cubed_sphere(2, dtype=np.float64, gnomonic="ed")
        g_eq = create_cubed_sphere(2, dtype=np.float64)
        cd_ed = create_cubed_sphere_cdgrid(g_ed, metric_dtype=np.float64)
        cd_eq = create_cubed_sphere_cdgrid(g_eq, metric_dtype=np.float64)
        assert not np.allclose(
            np.asarray(cd_ed.dxc), np.asarray(cd_eq.dxc), rtol=1e-12)

    def test_cdgrid_contradicting_request_raises(self):
        g_ed = create_cubed_sphere(4, dtype=np.float64, gnomonic="ed")
        g_eq = create_cubed_sphere(4, dtype=np.float64)
        with pytest.raises(ValueError, match="provenance"):
            create_cubed_sphere_cdgrid(g_ed, gnomonic="equiangular")
        with pytest.raises(ValueError, match="provenance"):
            create_cubed_sphere_cdgrid(g_eq, gnomonic="ed")


# ---------------------------------------------------------------------------
# 5. Legacy equiangular stays distinct and default
# ---------------------------------------------------------------------------
class TestLegacyDistinct:
    def test_c36_centres_differ_by_hundreds_of_km(self):
        g_eq = create_cubed_sphere(36, dtype=np.float64)
        g_ed = create_cubed_sphere(36, dtype=np.float64, gnomonic="ed")
        lon_a, lat_a = np.asarray(g_eq.lon), np.asarray(g_eq.lat)
        lon_b, lat_b = np.asarray(g_ed.lon), np.asarray(g_ed.lat)
        # great-circle separation of matching cell centres
        s = np.sin(lat_a) * np.sin(lat_b) + np.cos(lat_a) * np.cos(lat_b) * np.cos(lon_a - lon_b)
        sep_km = R * np.arccos(np.clip(s, -1.0, 1.0)) / 1e3
        # audit: up to ~231 km at C36; require the same order, not the exact value
        assert sep_km.max() > 100.0
        assert sep_km.max() < 400.0

    def test_c8_coordinates_distinct(self):
        g_eq = create_cubed_sphere(8, dtype=np.float64)
        g_ed = create_cubed_sphere(8, dtype=np.float64, gnomonic="ed")
        assert not np.allclose(np.asarray(g_eq.lat), np.asarray(g_ed.lat), atol=1e-6)


# ---------------------------------------------------------------------------
# 6. FV3-named models: compatibility migration warning on legacy grids
# ---------------------------------------------------------------------------
class TestFV3NamedModelMigration:
    def test_fv3_edge_sw_model_warns_on_equiangular(self):
        from legoesm.atmosphere.dynamics.gcm.shallow_water_fv3_cdgrid import (
            FV3EdgeShallowWaterModel,
        )

        g_eq = create_cubed_sphere(4, dtype=np.float64)
        with pytest.warns(FutureWarning, match="equiangular"):
            FV3EdgeShallowWaterModel(g_eq)

    def test_fv3_edge_sw_model_silent_on_ed(self):
        from legoesm.atmosphere.dynamics.gcm.shallow_water_fv3_cdgrid import (
            FV3EdgeShallowWaterModel,
        )

        g_ed = create_cubed_sphere(4, dtype=np.float64, gnomonic="ed")
        with warnings.catch_warnings():
            warnings.simplefilter("error", FutureWarning)
            FV3EdgeShallowWaterModel(g_ed)

    def test_fv3_fb_sw_model_warns_on_equiangular(self):
        from legoesm.atmosphere.dynamics.gcm.shallow_water_fv3_cdgrid import (
            FV3FBShallowWaterModel,
        )

        g_eq = create_cubed_sphere(4, dtype=np.float64)
        with pytest.warns(FutureWarning, match="equiangular"):
            FV3FBShallowWaterModel(g_eq)

    def test_fv3_fb_sw_model_silent_on_ed(self):
        from legoesm.atmosphere.dynamics.gcm.shallow_water_fv3_cdgrid import (
            FV3FBShallowWaterModel,
        )

        g_ed = create_cubed_sphere(4, dtype=np.float64, gnomonic="ed")
        with warnings.catch_warnings():
            warnings.simplefilter("error", FutureWarning)
            FV3FBShallowWaterModel(g_ed)
