"""Phase 4b — d_sw one-step oracle: field-by-field vs verbatim Fortran.

The fixture pair is generated by:

1. ``scripts/validate/fv3_native/export_dswcore_inputs.py`` — builds the
   single-tile gridstruct (all d_sw-consumed fields) + analytic SW state,
   runs the CERTIFIED python c_sw on all six faces and exchanges the
   time-centred uc/vc into tile-1's deep halos (CGRID_NE vector), dumping
   every slot (``dswcore_input.npz`` + text twin).
2. ``fv3_dswcore_oracle_driver.F90`` + ``fv3_dswcore_extract.F90`` — the
   VERBATIM d_sw call tree (tp_core PPM machinery, a2b_edge, d_sw/xtp_u/
   ytp_v/del6_vt_flux, fill_corners) from GFDL_atmos_cubed_sphere @
   6f658bd0 (production branch), run for ONE d_sw step: hord 6/8, nord=1,
   nord_v=1, dddmp=0.2, d4_bg=0.12, damp_v=0.2, hydrostatic, a2b damping
   path ON, dissipation-estimate OFF -> ``dswcore_oracle_c12.npz`` (each
   field stored on its python-return array's Fortran origin, NaN outside
   the source-defined region).

The loop-faithful python port (``legoesm.core.fv3_native_d_sw.d_sw``) must
reproduce the Fortran outputs from the SAME input bytes; agreement is
exact-to-roundoff on every dumped field.
"""

import os

import numpy as np
import pytest

FIX = os.path.join(os.path.dirname(__file__), "fixtures")

_CFG = dict(hord_tr=8, hord_mt=6, hord_vt=6, hord_tm=6, hord_dp=6,
            nord=1, nord_v=1, dddmp=0.2, d2_bg=0.0, d4_bg=0.12, damp_v=0.2,
            hydrostatic=True, do_diss_est=False)

# oracle fixture key == python d_sw return key (fixture is stored on the
# python array origin), so the comparison is a same-shape masked diff.
# ``ptc`` is EXCLUDED: it is INTENT(OUT) scratch written only by the
# nord==0 circulation branch (skipped at nord=1) — undefined in this
# config, and the Fortran driver merely dumps its -9e9 poison.  ``delpc``
# IS certified: the higher-order damping block writes delpc = divg_d.
_FIELDS = ["delpc", "u", "vc", "v", "uc", "ua", "va", "divg_d",
           "crx_adv", "xfx_adv", "cx", "cry_adv", "yfx_adv", "cy",
           "xflux", "yflux"]


@pytest.fixture(scope="module")
def oracle():
    return np.load(os.path.join(FIX, "dswcore_oracle_c12.npz"))


@pytest.fixture(scope="module")
def inputs():
    return np.load(os.path.join(FIX, "dswcore_input.npz"))


def _make_gs(inp):
    gs = {k: inp[k] for k in inp.files if k not in ("res", "ng", "dt")}
    gs.update(bounded_domain=False, grid_type=0, do_f3d=False,
              prevent_diss_cooling=False, stretched_grid=False,
              sw_corner=True, se_corner=True, ne_corner=True, nw_corner=True,
              da_min=float(inp["da_min"]), da_min_c=float(inp["da_min_c"]))
    return gs


def _run(inp, gs, dt_scale=1.0):
    from legoesm.core.fv3_native_d_sw import d_sw
    from legoesm.core.fv3_native_sw_core import Bounds

    res, ng = int(inp["res"]), int(inp["ng"])
    bd = Bounds.single_tile(res, ng)
    m_a, m_b = res + 2 * ng, res + 2 * ng + 1
    return d_sw(
        delp=inp["delp"], pt=inp["pt"], w=inp["w"], u=inp["u"], v=inp["v"],
        uc=inp["uc"], vc=inp["vc"], ua=inp["ua"], va=inp["va"],
        divg_d=np.full((m_b, m_b), -9.0e9),
        xflux=np.zeros((res + 1, res)), yflux=np.zeros((res, res + 1)),
        cx=np.zeros((res + 1, m_a)), cy=np.zeros((m_a, res + 1)),
        gs=gs, bd=bd, npx=res + 1, npy=res + 1,
        dt=float(inp["dt"]) * dt_scale, **_CFG)


@pytest.fixture(scope="module")
def result(inputs):
    return _run(inputs, _make_gs(inputs))


@pytest.mark.parametrize("field", _FIELDS)
def test_d_sw_matches_fortran(result, oracle, field):
    """Bit-exact (rel err < 1e-11) on the source-defined region.  The
    Fortran driver dumps only slots its write loops define; the fixture
    holds NaN elsewhere, so the finite mask IS the defined region."""
    want = np.asarray(oracle[field], dtype=np.float64)
    got = np.asarray(result[field], dtype=np.float64)
    assert got.shape == want.shape, field
    finite = np.isfinite(want)
    assert int(finite.sum()) > 0, f"{field}: empty defined region"
    denom = np.maximum(np.abs(want[finite]), 1.0)
    err = (np.abs(got[finite] - want[finite]) / denom).max()
    assert err < 1e-11, f"{field}: max rel err {err:.3e}"


def test_oracle_comparison_has_teeth(inputs, oracle):
    """A perturbed dt must break the u update — guards against a vacuous
    gate (wrong shapes / all-NaN masks silently comparing nothing)."""
    perturbed = _run(inputs, _make_gs(inputs), dt_scale=1.01)
    want = np.asarray(oracle["u"], dtype=np.float64)
    got = np.asarray(perturbed["u"], dtype=np.float64)
    finite = np.isfinite(want)
    err = (np.abs(got[finite] - want[finite])
           / np.maximum(np.abs(want[finite]), 1.0)).max()
    assert err > 1e-6, "perturbed dt still matches — vacuous gate"
