"""Phase-4c — DUO c_sw one-step oracle.

Certifies the port ``c_sw(..., duogrid=True)`` bit-exact (uint64) against the
authoritative symmetryclean c_sw DUO branch (flagstruct%duogrid +
dg%is_initialized; sw_core.F90:79-494) on identical inputs — the full duo
C-grid forward step (d2a2c_vect_duo + divergence_corner_duo + simple-upwind
KE/vorticity + interior vorticity transport, corner fills skipped).  The
plain branch (duogrid=False) is certified in test_fv3_native_swcore_phase4.

Fixture ``csw_oracle_c12.npz`` (re)generated by
``scripts/cluster/csw_oracle.sbatch``; ``input_sha256`` enforced; the
extracted Fortran c_sw block SHA is pinned.
"""

import hashlib
import importlib.util
import os

import numpy as np
import pytest

FIX = os.path.join(os.path.dirname(__file__), "fixtures")
REPO = os.path.join(os.path.dirname(__file__), "..", "..")
RES, NG = 12, 3

_EXTRACT_BLOCK_SHA256 = (
    "55f338356aee9f403a0c76880993b0a63ee2bce62883f964c624e6bc955fe744")

_METRIC_KEYS = ("cosa_s", "rsin2", "rarea", "dxa", "dya", "cosa_u", "sina_u",
                "rsin_u", "dy", "dxc", "rdxc", "cosa_v", "sina_v", "rsin_v",
                "dx", "dyc", "rdyc", "rarea_c", "fC", "sin_sg", "cos_sg")
_ALL_INPUTS = ("delp", "pt", "w", "u", "v") + _METRIC_KEYS
# order matters: [0] is bounded_domain, [1:] the four corner flags
_FLAG_KEYS = ("bounded_domain", "sw_corner", "se_corner", "ne_corner",
              "nw_corner")


def _load_generator():
    path = os.path.join(REPO, "scripts", "validate", "fv3_native",
                        "gen_csw_oracle.py")
    spec = importlib.util.spec_from_file_location("gen_csw_oracle", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


@pytest.fixture(scope="module")
def oracle():
    return np.load(os.path.join(FIX, "csw_oracle_c12.npz"))


def test_fixture_input_hash_enforced(oracle):
    gen = _load_generator()
    fields = {k: np.asarray(oracle[k]) for k in _ALL_INPUTS}
    # recompute over the STORED flags (flag_* keys) — the hash binds
    # metrics AND lane flags (km=1 migration, GLM r1 finding 4)
    flags = tuple((k, bool(oracle[f"flag_{k}"])) for k in _FLAG_KEYS)
    recomputed = hashlib.sha256(
        gen.serialize_csw_inputs(fields, int(oracle["res"]),
                                 int(oracle["ng"]), flags=flags)).hexdigest()
    stored = str(oracle["input_sha256"])
    assert len(stored) == 64 and all(c in "0123456789abcdef" for c in stored)
    assert recomputed == stored
    for k in _ALL_INPUTS:
        t = {kk: (v.copy() if kk == k else v) for kk, v in fields.items()}
        t[k].flat[0] = np.nextafter(t[k].flat[0], np.inf)
        bad = hashlib.sha256(
            gen.serialize_csw_inputs(t, int(oracle["res"]),
                                     int(oracle["ng"]),
                                     flags=flags)).hexdigest()
        assert bad != stored, k
    # flag-flip sensitivity: every lane flag is load-bearing in the hash
    for i, (fk, fv) in enumerate(flags):
        flipped = flags[:i] + ((fk, not fv),) + flags[i + 1:]
        bad = hashlib.sha256(
            gen.serialize_csw_inputs(fields, int(oracle["res"]),
                                     int(oracle["ng"]),
                                     flags=flipped)).hexdigest()
        assert bad != stored, fk


def test_extract_block_sha_pinned():
    f = os.path.join(REPO, "scripts", "validate", "fv3_native",
                     "fv3_csw_duo_extract.F90")
    txt = open(f, encoding="utf-8").read().split("\n")
    i0 = next(i for i, ln in enumerate(txt)
              if ln.strip().startswith("subroutine c_sw"))
    i1 = next(i for i, ln in enumerate(txt)
              if ln.strip() == "end subroutine c_sw")
    block = ("\n".join(txt[i0:i1 + 1]) + "\n").encode()
    assert hashlib.sha256(block).hexdigest() == _EXTRACT_BLOCK_SHA256


def _region(bd, key):
    """Geometry-derived (i_fort, j_fort) inclusive written region of each
    c_sw output on the duo branch (from the loop bounds), so the compare
    mask is BOUNDS-derived, not sentinel-preservation-dependent (codex p4c
    c_sw-oracle P2)."""
    if key in ("delpc", "ptc"):                        # transport update
        return bd.is_ - 1, bd.ie + 1, bd.js - 1, bd.je + 1
    if key == "uc":                                    # d2a2c uc region
        return bd.is_ - 1, bd.ie + 2, bd.js - 1, bd.je + 1
    if key == "vc":                                    # d2a2c vc region
        return bd.is_ - 1, bd.ie + 1, bd.js - 1, bd.je + 2
    return bd.isd + 1, bd.ied, bd.jsd + 1, bd.jed       # divg_d 289 B-nodes


def _mask(shape, i0, i1, j0, j1):
    lo = 1 - NG
    m = np.zeros(shape, dtype=bool)
    m[i0 - lo:i1 - lo + 1, j0 - lo:j1 - lo + 1] = True
    return m


def test_duo_c_sw_bit_exact(oracle):
    """Run the port c_sw(duogrid=True) on the STORED inputs; delpc/ptc/uc/vc
    AND divg_d (the divergence_corner_duo result — codex p4c c_sw-oracle P1)
    must equal the authoritative Fortran DUO c_sw BIT-for-BIT (uint64) over
    each output's BOUNDS-derived written region.  The port's finite
    non-sentinel region is asserted EQUAL to that bounds mask, so an omitted
    or extra write fails."""
    assert (int(oracle["res"]), int(oracle["ng"])) == (RES, NG)
    from legoesm.core.fv3_native_sw_core import Bounds, c_sw
    bd = Bounds.single_tile(RES, NG)
    gs = {k: np.asarray(oracle[k]) for k in _METRIC_KEYS}
    # BOUNDED lane flags (km=1 corpus migration, 2026-08-11), loaded
    # FROM the fixture (flag_* keys, hash-covered, and the same FLAG
    # records the Fortran driver consumed) — the port runs the exact
    # flags the oracle ran, no third hardcoding site.  The assert pins
    # them to the only pair upstream duo runs can reach
    # (fv_arrays.F90:1512 / fv_grid_utils.F90:224).
    for k in _FLAG_KEYS:
        gs[k] = bool(oracle[f"flag_{k}"])
    assert gs["bounded_domain"] is True
    assert not any(gs[k] for k in _FLAG_KEYS[1:])
    out = c_sw(delp=np.asarray(oracle["delp"]), pt=np.asarray(oracle["pt"]),
               w=np.asarray(oracle["w"]), u=np.asarray(oracle["u"]),
               v=np.asarray(oracle["v"]), gs=gs, bd=bd, npx=RES + 1,
               npy=RES + 1, dt2=112.5, nord=1, hydrostatic=True, dord4=True,
               grid_type=0, duogrid=True)
    for key in ("delpc", "ptc", "uc", "vc", "divg_d"):
        g = np.asarray(out[key], dtype=np.float64)
        w = np.asarray(oracle[key], dtype=np.float64)
        assert g.shape == w.shape, key
        exp = _mask(g.shape, *_region(bd, key))
        assert int(exp.sum()) >= 100, key
        port_region = (np.abs(g) < 1e24) & np.isfinite(g)
        assert np.array_equal(port_region, exp), (
            f"{key}: port wrote {int(port_region.sum())} != expected "
            f"{int(exp.sum())} (omitted/extra cell)")
        assert np.isfinite(w[exp]).all() and (np.abs(w[exp]) < 1e24).all(), key
        nd = int((g[exp].view(np.uint64) != w[exp].view(np.uint64)).sum())
        assert nd == 0, f"{key}: {nd}/{int(exp.sum())} cells differ bitwise"


def test_fixture_input_provenance(oracle):
    sha = str(oracle["input_sha256"])
    assert len(sha) == 64 and all(c in "0123456789abcdef" for c in sha)
    assert "duogrid" in str(oracle["input_lineage"])
    # soft label only — the REAL plain-metrics refusal is
    # test_fixture_metrics_are_the_bounded_gridstruct below
    assert "BOUNDED" in str(oracle["input_lineage"])


def test_fixture_metrics_are_the_bounded_gridstruct(oracle):
    """Genuine metric provenance (codex km=1 r2 finding 2): a lineage
    string is mutable metadata, so refusing a stale plain-metrics
    fixture on it alone is not provenance.  Rebuild the bounded C12
    gridstruct with the generator's own builder and require every
    serialized metric field to match the fixture EXACTLY (the
    generator stores the builder's float64 arrays unmodified, so
    bitwise equality is the correct bar) — a fixture carrying plain
    metrics under a relabelled lineage fails here on every angle/area
    field."""
    from legoesm.grids.fv3_native_gridstruct import (
        FV3_OMEGA,
        FV3_RADIUS_M,
        build_fv3_native_gridstruct_bounded,
    )

    gs = build_fv3_native_gridstruct_bounded(RES, NG, radius=FV3_RADIUS_M,
                                             omega=FV3_OMEGA)
    for k in _METRIC_KEYS:
        np.testing.assert_array_equal(
            np.asarray(oracle[k]), np.asarray(gs[k]),
            err_msg=f"{k}: fixture metric is not the bounded builder's")
