"""Phase 4a — c_sw one-step oracle: field-by-field vs verbatim Fortran.

The fixture pair was generated by:

1. ``scripts/validate/fv3_native/export_swcore_inputs.py`` — builds the
   single-tile gridstruct (certified phase-1/2 compute domains + kinked
   mpp-equivalent halos) and the analytic rotated solid-body SW state,
   dumping every slot (``swcore_input.npz`` + text twin).
2. ``fv3_swcore_oracle_driver.F90`` + ``fv3_swcore_extract.F90`` — the
   VERBATIM ``c_sw``/``d2a2c_vect``/``divergence_corner``/fill extraction
   from GFDL_atmos_cubed_sphere @ 6f658bd0 (production branch, no
   SW_DYNAMICS), run for ONE step: nord=1, dt2=112.5, hydrostatic=T,
   dord4=T, grid_type=0 -> ``swcore_oracle_c12.npz``.

The python port must reproduce the Fortran outputs from the SAME input
bytes.  Compute-domain agreement is exact-to-roundoff; full-array
agreement (halo rings included) pins even the sentinel-propagation
behaviour, since both sides consume identical inputs.
"""

import os

import numpy as np
import pytest

FIX = os.path.join(os.path.dirname(__file__), "fixtures")


@pytest.fixture(scope="module")
def oracle():
    return np.load(os.path.join(FIX, "swcore_oracle_c12.npz"))


@pytest.fixture(scope="module")
def inputs():
    return np.load(os.path.join(FIX, "swcore_input.npz"))


@pytest.fixture(scope="module")
def csw_result(inputs):
    from legoesm.core.fv3_native_sw_core import Bounds, c_sw

    res = int(inputs["res"])
    ng = int(inputs["ng"])
    bd = Bounds.single_tile(res, ng)
    gs = {k: inputs[k] for k in inputs.files
          if k not in ("res", "ng", "dt2", "nord", "delp", "pt", "u", "v")}
    return c_sw(
        delp=inputs["delp"].copy(), pt=inputs["pt"].copy(),
        w=np.zeros_like(inputs["delp"]),
        u=inputs["u"].copy(), v=inputs["v"].copy(),
        gs=gs, bd=bd, npx=res + 1, npy=res + 1,
        dt2=float(inputs["dt2"]), nord=int(inputs["nord"]),
        hydrostatic=True, dord4=True, grid_type=0)


def _compute_slices(res, ng, shape):
    """Fortran compute-domain slices for a (cell|node)-shaped axis."""
    def sl(nlen):
        extra = nlen - (res + 2 * ng)   # 0 cell axis, 1 node axis
        return slice(ng, ng + res + extra)
    return tuple(sl(s) for s in shape)


# ---- input-side regeneration determinism (exporter is oracle-critical) ----

def test_gridstruct_regeneration_matches_fixture(inputs):
    from legoesm.grids.fv3_native_gridstruct import (
        FV3_OMEGA, FV3_RADIUS_M, analytic_swcore_state,
        build_fv3_native_gridstruct)

    gs = build_fv3_native_gridstruct(int(inputs["res"]), int(inputs["ng"]),
                                     radius=FV3_RADIUS_M, omega=FV3_OMEGA)
    st = analytic_swcore_state(gs)
    for key in ("dx", "dy", "dxa", "dya", "dxc", "dyc", "rdxc", "rdyc",
                "rarea", "rarea_c", "cosa_u", "sina_u", "rsin_u",
                "cosa_v", "sina_v", "rsin_v", "cosa_s", "rsin2",
                "sin_sg", "cos_sg", "fC"):
        assert np.array_equal(gs[key], inputs[key]), key
    for key in ("delp", "pt", "u", "v"):
        assert np.array_equal(st[key], inputs[key]), key


def test_gridstruct_halo_strips_are_real(inputs):
    """Side strips must carry real (non-sentinel) metric values."""
    res, ng = int(inputs["res"]), int(inputs["ng"])
    dxa = inputs["dxa"]
    sl = slice(ng, ng + res)
    for strip in (dxa[:ng, sl], dxa[-ng:, sl], dxa[sl, :ng], dxa[sl, -ng:]):
        assert (strip < 1.0e6).all()
    ssg = inputs["sin_sg"]
    for strip in (ssg[:ng, sl, :], ssg[-ng:, sl, :],
                  ssg[sl, :ng, :], ssg[sl, -ng:, :]):
        assert (np.abs(strip) <= 1.0).all()


def test_sin_sg_transport_patches_present(inputs):
    """The post-fill_ghost corner transport patches (verbatim v2 set)."""
    res, ng = int(inputs["res"]), int(inputs["ng"])
    npx = res + 1
    ssg = inputs["sin_sg"]
    lo = 1 - ng

    def at(i, j, k):
        return ssg[i - lo, j - lo, k - 1]

    csg = inputs["cos_sg"]

    def atc(i, j, k):
        return csg[i - lo, j - lo, k - 1]

    for i in range(0, -2 - 1, -1):   # sw corner strip
        assert at(0, i, 3) == at(i, 1, 2)
        assert at(i, 0, 4) == at(1, i, 1)
        assert atc(0, i, 3) == atc(i, 1, 2)
        assert atc(i, 0, 4) == atc(1, i, 1)
    for i in range(npx, npx + 2 + 1):    # nw (v2 source: npx - i)
        assert at(0, i, 3) == at(npx - i, npx - 1, 4)
        assert atc(0, i, 3) == atc(npx - i, npx - 1, 4)
    for i in range(0, -2 - 1, -1):
        assert at(i, npx, 2) == at(1, npx - i, 1)
        assert atc(i, npx, 2) == atc(1, npx - i, 1)
    for j in range(0, -2 - 1, -1):       # se
        assert at(npx, j, 1) == at(npx - j, 1, 2)
        assert atc(npx, j, 1) == atc(npx - j, 1, 2)
    for i in range(npx, npx + 2 + 1):
        assert at(i, 0, 4) == at(npx - 1, npx - i, 3)
        assert atc(i, 0, 4) == atc(npx - 1, npx - i, 3)
    for i in range(0, 2 + 1):        # ne corner strip
        assert at(npx, npx + i, 1) == at(npx + i, npx - 1, 4)
        assert at(npx + i, npx, 2) == at(npx - 1, npx + i, 3)
        assert atc(npx, npx + i, 1) == atc(npx + i, npx - 1, 4)
        assert atc(npx + i, npx, 2) == atc(npx - 1, npx + i, 3)


# ---- the phase-4a acceptance: field-by-field c_sw agreement ----

@pytest.mark.parametrize("field", ["delpc", "ptc", "uc", "vc",
                                   "ut", "vt", "ua", "va", "divg_d"])
def test_c_sw_matches_fortran_compute_domain(csw_result, oracle,
                                             inputs, field):
    got = csw_result[field]
    want = oracle[field]
    res, ng = int(inputs["res"]), int(inputs["ng"])
    sl = _compute_slices(res, ng, want.shape)
    g, w = got[sl], want[sl]
    assert np.isfinite(w).all()
    scale = np.maximum(np.abs(w).max(), 1e-30)
    err = np.abs(g - w).max() / scale
    assert err < 1e-13, f"{field}: rel err {err:.3e}"


@pytest.fixture(scope="module")
def perturbed_result(inputs):
    from legoesm.core.fv3_native_sw_core import Bounds, c_sw

    res = int(inputs["res"])
    ng = int(inputs["ng"])
    bd = Bounds.single_tile(res, ng)
    gs = {k: inputs[k] for k in inputs.files
          if k not in ("res", "ng", "dt2", "nord", "delp", "pt", "u", "v")}
    return c_sw(
        delp=inputs["delp"].copy(), pt=inputs["pt"].copy(),
        w=np.zeros_like(inputs["delp"]),
        u=inputs["u"].copy(), v=inputs["v"].copy(),
        gs=gs, bd=bd, npx=res + 1, npy=res + 1,
        dt2=float(inputs["dt2"]) * (1.0 + 1.0e-6),
        nord=int(inputs["nord"]),
        hydrostatic=True, dord4=True, grid_type=0)


@pytest.mark.parametrize("field", ["delpc", "ptc", "uc", "vc",
                                   "ut", "vt"])
def test_oracle_comparison_has_teeth(perturbed_result, oracle,
                                     inputs, field):
    """Synthetic violation: a perturbed step must FAIL every dt2-sensitive
    field's comparison (ua/va and divg_d are computed before the dt2
    scaling — legitimately dt2-blind).
    Guards against a vacuous gate (wrong slices, all-sentinel filters,
    fixture/key mixups silently comparing nothing)."""
    want = oracle[field]
    res, ng = int(inputs["res"]), int(inputs["ng"])
    sl = _compute_slices(res, ng, want.shape)
    scale = np.abs(want[sl]).max()
    err = np.abs(perturbed_result[field][sl] - want[sl]).max() / scale
    assert err > 1e-13, f"{field}: perturbed run still matches — vacuous gate"


@pytest.mark.parametrize("field", ["delpc", "ptc", "uc", "vc",
                                   "ut", "vt", "ua", "va", "divg_d"])
def test_c_sw_matches_fortran_full_arrays(csw_result, oracle,
                                          inputs, field):
    """Halo rings included: identical inputs -> identical garbage rings.

    The driver poisons unwritten slots with -9e9 while the python port
    leaves them at its own initial value; compare only slots the Fortran
    actually wrote (|x| < 8.9e8 or exact sentinel-free), which still spans
    every ring slot fed by real + big_number inputs.
    """
    got = np.asarray(csw_result[field], dtype=np.float64)
    want = np.asarray(oracle[field], dtype=np.float64)
    assert got.shape == want.shape
    # exact driver sentinel: a slot is unwritten iff it still holds the
    # -9e9 poison (or a poison-scaled product for ut/vt, which c_sw scales
    # in place after d2a2c wrote them) — everything else must match
    written = want != -9.0e9
    res, ng = int(inputs["res"]), int(inputs["ng"])
    sl = _compute_slices(res, ng, want.shape)
    n_compute = want[sl].size
    # divergence_corner writes exactly the compute B nodes; every other
    # field's Fortran writes extend into the halo ring
    min_written = n_compute if field == "divg_d" else n_compute + 1
    assert int(written.sum()) >= min_written, \
        f"{field}: write-mask smaller than the compute domain"
    g, w = got[written], want[written]
    denom = np.maximum(np.abs(w), 1.0)
    err = (np.abs(g - w) / denom).max()
    assert err < 1e-12, f"{field}: rel err {err:.3e} over written slots"


def test_fortran_oracle_rebuild_matches_fixture(tmp_path, oracle):
    """Rebuild + rerun the VERBATIM Fortran oracle and compare against the
    committed fixture (codex r1 P1-3: CI otherwise never executes the
    extraction).  Skipped where no gfortran toolchain is available."""
    import shutil
    import subprocess

    if shutil.which("gfortran") is None:
        pytest.skip("no gfortran")
    import sys

    repo = os.path.join(os.path.dirname(__file__), "..", "..")
    script = os.path.join(repo, "scripts", "validate", "fv3_native",
                          "gen_swcore_oracle.sh")
    env = dict(os.environ, PYTHON=sys.executable)
    subprocess.run(["bash", script, str(tmp_path), "12", "3"],
                   check=True, env=env, capture_output=True, text=True)
    fresh = np.load(tmp_path / "swcore_oracle_c12.npz")
    for key in ("delpc", "ptc", "uc", "vc", "ut", "vt",
                "ua", "va", "divg_d"):
        assert np.array_equal(fresh[key], oracle[key]), key
