"""Phase 4c — DUO-GRID branch oracle: divergence_corner_duo vs authoritative FV3.

The plain-FV3 phase-4a extraction (GFDL @ 6f658bd0) calls
``divergence_corner``; the DUO-GRID FV3 (Mouallem/Xi-Chen, Zenodo 8327578,
``atmos_cubed_sphere-symmetryclean``) calls ``divergence_corner_duo`` under
``flagstruct%duogrid`` — the branch legoESM's production solver runs.  This
gate certifies the loop-faithful python port
(``fv3_native_duo_sw_core.divergence_corner_duo``) field-by-field against
the VERBATIM authoritative Fortran, on the phase-4a certified single-tile
gridstruct + analytic state.

Fixture ``divduo_oracle_c12.npz`` is (re)generated by
``scripts/cluster/divduo_oracle.sbatch`` (gen_divduo_oracle.py builds the
inputs + runs the port; fv3_divduo_driver.F90 runs the authoritative
divergence_corner_duo).  All 361 B-nodes matched bit-exactly on generation.
"""

import os

import numpy as np
import pytest

FIX = os.path.join(os.path.dirname(__file__), "fixtures")


@pytest.fixture(scope="module")
def oracle():
    return np.load(os.path.join(FIX, "divduo_oracle_c12.npz"))


def _port_output():
    from legoesm.core.fv3_native_duo_sw_core import divergence_corner_duo
    from legoesm.core.fv3_native_sw_core import Bounds, c_sw
    from legoesm.grids.fv3_native_gridstruct import (
        FV3_OMEGA,
        FV3_RADIUS_M,
        analytic_swcore_state,
        build_fv3_native_gridstruct,
    )

    res, ng = 12, 3
    gs = build_fv3_native_gridstruct(res, ng, radius=FV3_RADIUS_M,
                                     omega=FV3_OMEGA)
    st = analytic_swcore_state(gs)
    bd = Bounds.single_tile(res, ng)
    csw = c_sw(delp=st["delp"], pt=st["pt"], w=np.zeros_like(st["delp"]),
               u=st["u"], v=st["v"], gs=gs, bd=bd, npx=res + 1, npy=res + 1,
               dt2=112.5, nord=1, hydrostatic=True, dord4=True, grid_type=0)
    ua = np.nan_to_num(np.asarray(csw["ua"], float), nan=0.0)
    va = np.nan_to_num(np.asarray(csw["va"], float), nan=0.0)
    u = np.nan_to_num(np.asarray(st["u"], float), nan=0.0)
    v = np.nan_to_num(np.asarray(st["v"], float), nan=0.0)
    return divergence_corner_duo(u, v, ua, va, gs, bd, res + 1, res + 1,
                                 grid_type=0)


def test_divergence_corner_duo_matches_authoritative(oracle):
    """Bit-exact vs the authoritative Mouallem divergence_corner_duo over
    every dumped B-node (compute + halo the Fortran writes)."""
    want = np.asarray(oracle["divg_d"], dtype=np.float64)
    got = np.asarray(_port_output(), dtype=np.float64)
    assert got.shape == want.shape
    finite = np.isfinite(want)
    assert int(finite.sum()) == 361
    err = (np.abs(got[finite] - want[finite])
           / np.maximum(np.abs(want[finite]), 1.0)).max()
    assert err < 1e-11, f"divergence_corner_duo: max rel err {err:.3e}"


def test_duo_panel_edge_zeroing_present():
    """The duo-specific seam zeroing/quartering must fire — the interior
    B-nodes at the panel seam (i==1, i==npx, j==1, j==npy) are zeroed,
    distinguishing divergence_corner_duo from divergence_corner_nest."""
    out = np.asarray(_port_output(), dtype=np.float64)
    res, ng = 12, 3
    lo = 1 - ng
    npx = res + 1

    def at(i, j):
        return out[i - lo, j - lo]

    # seam B-nodes zeroed
    for j in range(2, npx):
        assert at(1, j) == 0.0
        assert at(npx, j) == 0.0
    for i in range(2, npx):
        assert at(i, 1) == 0.0
        assert at(i, npx) == 0.0
