"""Phase-4c — DUO c_sw one-step oracle.

Certifies the port ``c_sw(..., duogrid=True)`` bit-exact (uint64) against the
authoritative symmetryclean c_sw DUO branch (flagstruct%duogrid +
dg%is_initialized; sw_core.F90:79-494) on identical inputs — the full duo
C-grid forward step (d2a2c_vect_duo + divergence_corner_duo + simple-upwind
KE/vorticity + interior vorticity transport, corner fills skipped).  The
plain branch (duogrid=False) is certified in test_fv3_native_swcore_phase4.

Fixture ``csw_oracle_c12.npz`` (re)generated by
``scripts/cluster/csw_oracle.sbatch``; ``input_sha256`` enforced; the
extracted Fortran c_sw block SHA is pinned.
"""

import hashlib
import importlib.util
import os

import numpy as np
import pytest

FIX = os.path.join(os.path.dirname(__file__), "fixtures")
REPO = os.path.join(os.path.dirname(__file__), "..", "..")
RES, NG = 12, 3

_EXTRACT_BLOCK_SHA256 = (
    "55f338356aee9f403a0c76880993b0a63ee2bce62883f964c624e6bc955fe744")

_METRIC_KEYS = ("cosa_s", "rsin2", "rarea", "dxa", "dya", "cosa_u", "sina_u",
                "rsin_u", "dy", "dxc", "rdxc", "cosa_v", "sina_v", "rsin_v",
                "dx", "dyc", "rdyc", "rarea_c", "fC", "sin_sg", "cos_sg")
_ALL_INPUTS = ("delp", "pt", "w", "u", "v") + _METRIC_KEYS


def _load_generator():
    path = os.path.join(REPO, "scripts", "validate", "fv3_native",
                        "gen_csw_oracle.py")
    spec = importlib.util.spec_from_file_location("gen_csw_oracle", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


@pytest.fixture(scope="module")
def oracle():
    return np.load(os.path.join(FIX, "csw_oracle_c12.npz"))


def test_fixture_input_hash_enforced(oracle):
    gen = _load_generator()
    fields = {k: np.asarray(oracle[k]) for k in _ALL_INPUTS}
    recomputed = hashlib.sha256(
        gen.serialize_csw_inputs(fields, int(oracle["res"]),
                                 int(oracle["ng"]))).hexdigest()
    stored = str(oracle["input_sha256"])
    assert len(stored) == 64 and all(c in "0123456789abcdef" for c in stored)
    assert recomputed == stored
    for k in _ALL_INPUTS:
        t = {kk: (v.copy() if kk == k else v) for kk, v in fields.items()}
        t[k].flat[0] = np.nextafter(t[k].flat[0], np.inf)
        bad = hashlib.sha256(
            gen.serialize_csw_inputs(t, int(oracle["res"]),
                                     int(oracle["ng"]))).hexdigest()
        assert bad != stored, k


def test_extract_block_sha_pinned():
    f = os.path.join(REPO, "scripts", "validate", "fv3_native",
                     "fv3_csw_duo_extract.F90")
    txt = open(f, encoding="utf-8").read().split("\n")
    i0 = next(i for i, ln in enumerate(txt)
              if ln.strip().startswith("subroutine c_sw"))
    i1 = next(i for i, ln in enumerate(txt)
              if ln.strip() == "end subroutine c_sw")
    block = ("\n".join(txt[i0:i1 + 1]) + "\n").encode()
    assert hashlib.sha256(block).hexdigest() == _EXTRACT_BLOCK_SHA256


def test_duo_c_sw_bit_exact(oracle):
    """Run the port c_sw(duogrid=True) on the STORED inputs; delpc/ptc/uc/vc
    must equal the authoritative Fortran DUO c_sw BIT-for-BIT (uint64) over
    each output's computed region.  The mask is the finite non-sentinel
    region of BOTH sides asserted EQUAL, so an omitted or extra write fails
    (codex-sound)."""
    assert (int(oracle["res"]), int(oracle["ng"])) == (RES, NG)
    from legoesm.core.fv3_native_sw_core import Bounds, c_sw
    bd = Bounds.single_tile(RES, NG)
    gs = {k: np.asarray(oracle[k]) for k in _METRIC_KEYS}
    out = c_sw(delp=np.asarray(oracle["delp"]), pt=np.asarray(oracle["pt"]),
               w=np.asarray(oracle["w"]), u=np.asarray(oracle["u"]),
               v=np.asarray(oracle["v"]), gs=gs, bd=bd, npx=RES + 1,
               npy=RES + 1, dt2=112.5, nord=1, hydrostatic=True, dord4=True,
               grid_type=0, duogrid=True)
    for key in ("delpc", "ptc", "uc", "vc"):
        g = np.asarray(out[key], dtype=np.float64)
        w = np.asarray(oracle[key], dtype=np.float64)
        assert g.shape == w.shape, key
        mg = (np.abs(g) < 1e24) & np.isfinite(g)
        mw = (np.abs(w) < 1e24) & np.isfinite(w)
        assert np.array_equal(mg, mw), f"{key}: computed region differs"
        assert int(mw.sum()) >= 100, f"{key}: too few computed cells"
        nd = int((g[mw].view(np.uint64) != w[mw].view(np.uint64)).sum())
        assert nd == 0, f"{key}: {nd}/{int(mw.sum())} cells differ bitwise"


def test_fixture_input_provenance(oracle):
    sha = str(oracle["input_sha256"])
    assert len(sha) == 64 and all(c in "0123456789abcdef" for c in sha)
    assert "duogrid" in str(oracle["input_lineage"])
