"""Canonical NeuralGCM slab-ocean S2S namespace."""

from legoesm.ml.s2s.neuralgcm_slab.campaign import (
    campaign_dir_for_year,
    campaign_dir_name,
    case_dir_for_start,
    center_compare_dir,
    center_compare_dir_name,
    checkpoint_tag,
    filter_start_times_to_year,
    generate_semimonthly_start_times,
    surface_forcing_filename,
)
from legoesm.ml.s2s.neuralgcm_slab.ensemble import (
    HEADLINE_FIELDS,
    HeadlineField,
    PerturbationConfig,
    aggregate_daily_series,
    apply_initial_perturbations,
    build_ensemble_daily_crps_table,
    build_ensemble_mean_daily_mae_table,
    build_ensemble_mean_daily_rmse_table,
    build_member_daily_mae_table,
    build_member_daily_rmse_table,
    generate_correlated_gaussian_noise,
    member_name,
    member_seed,
    open_member_forecasts,
    save_long_records_csv,
)
from legoesm.ml.s2s.neuralgcm_slab.evaluation import (
    DEFAULT_S2S_WINDOWS,
    LeadTimeWindow,
    aggregate_long_records,
    aggregate_metric_table,
    load_long_record_csv,
    load_metric_csv,
    save_metric_summary_csv,
    summarize_metric_csv,
)
from legoesm.ml.s2s.neuralgcm_slab.metrics import (
    DEFAULT_FIELD_SPECS,
    DEFAULT_METRICS,
    DEFAULT_METRIC_SPECS,
    FieldSpec,
    MetricSpec,
    align_truth_to_forecast,
    build_daily_metric_table,
    resolve_metric_specs,
    save_metric_table_csv,
    weighted_mae,
    weighted_rmse,
)
from legoesm.ml.s2s.neuralgcm_slab.neuralgcm_backend import (
    DEFAULT_NEURALGCM_CHECKPOINT,
    NeuralGCMBackend,
    NeuralGCMBackendConfig,
    neuralgcm_available,
    patch_checkpoint_for_surface_pressure,
)
from legoesm.ml.s2s.neuralgcm_slab.preparation import (
    DEFAULT_ARCO_ERA5_STORE,
    DEFAULT_PREP_CHECKPOINT,
    PreparationConfig,
    prepare_neuralgcm_case,
)
from legoesm.ml.s2s.neuralgcm_slab.slab_coupling import (
    CoupledFieldNames,
    SlabCouplingConfig,
    advance_slab_ocean_one_day,
    apply_sea_ice_mask,
    extract_surface_forcing_from_dataset,
    init_slab_state_from_field,
    rollout_coupled_daily,
)


_POSTPROCESS_NAMES = {
    "BOX_COLORS",
    "EXPERIMENTS",
    "FIELD_LABELS",
    "postprocess_campaign",
    "postprocess_campaign_center_crps",
    "postprocess_case",
    "postprocess_case_dirs_center_crps",
    "postprocess_case_dirs_center_crps",
}


def __getattr__(name):
    if name in _POSTPROCESS_NAMES:
        from legoesm.ml.s2s.neuralgcm_slab import postprocess
        return getattr(postprocess, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = [
    "DEFAULT_ARCO_ERA5_STORE",
    "DEFAULT_FIELD_SPECS",
    "DEFAULT_METRICS",
    "DEFAULT_METRIC_SPECS",
    "DEFAULT_NEURALGCM_CHECKPOINT",
    "DEFAULT_PREP_CHECKPOINT",
    "DEFAULT_S2S_WINDOWS",
    "CoupledFieldNames",
    "FieldSpec",
    "HEADLINE_FIELDS",
    "HeadlineField",
    "LeadTimeWindow",
    "MetricSpec",
    "NeuralGCMBackend",
    "NeuralGCMBackendConfig",
    "PerturbationConfig",
    "PreparationConfig",
    "SlabCouplingConfig",
    "advance_slab_ocean_one_day",
    "aggregate_daily_series",
    "aggregate_long_records",
    "aggregate_metric_table",
    "align_truth_to_forecast",
    "apply_initial_perturbations",
    "apply_sea_ice_mask",
    "build_daily_metric_table",
    "build_ensemble_daily_crps_table",
    "build_ensemble_mean_daily_mae_table",
    "build_ensemble_mean_daily_rmse_table",
    "build_member_daily_mae_table",
    "build_member_daily_rmse_table",
    "campaign_dir_for_year",
    "campaign_dir_name",
    "case_dir_for_start",
    "center_compare_dir",
    "center_compare_dir_name",
    "checkpoint_tag",
    "extract_surface_forcing_from_dataset",
    "filter_start_times_to_year",
    "generate_correlated_gaussian_noise",
    "generate_semimonthly_start_times",
    "init_slab_state_from_field",
    "load_long_record_csv",
    "load_metric_csv",
    "member_name",
    "member_seed",
    "neuralgcm_available",
    "open_member_forecasts",
    "patch_checkpoint_for_surface_pressure",
    "postprocess_campaign",
    "postprocess_campaign_center_crps",
    "postprocess_case",
    "prepare_neuralgcm_case",
    "resolve_metric_specs",
    "surface_forcing_filename",
    "rollout_coupled_daily",
    "save_long_records_csv",
    "save_metric_summary_csv",
    "save_metric_table_csv",
    "summarize_metric_csv",
    "weighted_mae",
    "weighted_rmse",
]
