"""Air-sea bulk-flux parity vs the frozen AeroBulk oracle baseline.

Oracle
------
``tests/unit/baselines/aerobulk_noskin_v1.npz`` holds inputs + outputs of
the AeroBulk Fortran reference (Brodeau et al. 2017 — the lineage ancestor
of NEMO's ``sbcblk``), noskin variants, generated by
``scripts/data/generate_aerobulk_reference.py`` via aerobulk-python.
aerobulk-python itself was validated against the independent NumPy NEMO
5.0.1 mirror of ``test_ncar_bulk.py`` (ncar fluxes agree to <=2e-2 rel,
tau/evap to <=7e-4) before freezing — see the PR notes.

What is compared
----------------
1. ``bulk_flux_omip.air_sea_fluxes(algo='ncar')`` vs aerobulk ``ncar``.
2. ``compute_most_fluxes(scheme='large_yeager')`` vs aerobulk ``ncar``
   (same LY09 physics), at 10/10 m and the OMIP-style 2/10 m height split.
3. ``compute_most_fluxes(scheme='coare3')`` vs aerobulk ``coare3p0``
   (scheme-native gustiness default: COARE 3.0 includes it; zi=600 m,
   beta=1.25 — the kernel default matches aerobulk).

Convention alignment (harness glue, per the fidelity doctrine this lives
in the TEST, not the model): NEMO-style Exner potential temperature, 0.98
saline Goff q_sat, moist air density from ``bulk_flux_omip`` helpers;
SST-dependent L_vap passed via ``L_latent`` so the constant-L_v convention
does not masquerade as a MOST error; sign mapping aerobulk->legoESM
(stress along-wind -> ocean-reaction, heat positive-down -> positive-up).

Gate design (three tiers, tolerances = measured-at-freeze x ~2-3 margin)
------------------------------------------------------------------------
- MEDIAN over all points: tight.  A formulation bug moves medians by
  orders of magnitude (the LY09 psi(10/L) bug moved the stress median
  from 1.7e-4 to 1.6e-2 — 100x).
- P95 over all points: moderate.
- MAX over the regime where the schemes are well-posed:
  * LY09's 18/32.7e-3 Stanton switch is BISTABLE where the Obukhov-length
    numerator changes sign between the two branches (warm-but-dry air):
    the NEMO/aerobulk fixed-point iteration flip-flops in a limit cycle
    and its answer is an artifact of iteration parity.  Such points (and
    near-calm winds, where wind-floor conventions differ) are excluded
    from the MAX gate only — they still count in median/p95.
  * COARE max is gated on the core physical regime (3 < W < 28 m/s,
    |dtheta| < 5 K); outside it, zeta-clip and calm-floor conventions
    dominate (absolute differences stay small, O(10 W/m^2)).
"""
from __future__ import annotations

from pathlib import Path

import jax
import numpy as np
import pytest

jax.config.update("jax_enable_x64", True)

import jax.numpy as jnp  # noqa: E402
from legoesm.core.bulk_flux import compute_most_fluxes  # noqa: E402
from legoesm.ocean.bulk_flux_omip import (  # noqa: E402
    air_sea_fluxes,
    exner_potential_temperature,
    latent_heat_vaporization_sst,
    pressure_at_height,
    rho_air_moist,
    seawater_q_sat,
)

from legoesm import constants  # noqa: E402

_BASE = Path(__file__).parent / "baselines" / "aerobulk_noskin_v1.npz"

# Floors for relative error (avoid near-zero-flux blowups)
_FLOOR_TAU = 1e-3   # [N/m^2]
_FLOOR_HEAT = 1.0   # [W/m^2]

# LY09 10-m Stanton numbers (stable/unstable) and Dalton number — used ONLY
# to detect the bistable branch region, mirrors LY09 Table 4 / NEMO.
_LY_STANTON_STABLE = 18.0e-3
_LY_STANTON_UNSTABLE = 32.7e-3
_LY_DALTON = 34.6e-3


@pytest.fixture(scope="module")
def oracle():
    d = np.load(_BASE)
    inp = {k[3:]: d[k] for k in d.files if k.startswith("in_")}
    sst, t_air, q_air = inp["sst"], inp["t_air"], inp["q_air"]
    slp = inp["slp"]
    W = np.hypot(inp["u"], inp["v"])  # noqa: N806 - wind-speed notation

    ssq = np.asarray(seawater_q_sat(jnp.asarray(sst), jnp.asarray(slp)))

    def prep(z):
        p = pressure_at_height(jnp.asarray(q_air), jnp.asarray(slp), z,
                               jnp.asarray(t_air))
        theta = np.asarray(
            exner_potential_temperature(jnp.asarray(t_air), p))
        rho = np.asarray(rho_air_moist(jnp.asarray(t_air),
                                       jnp.asarray(q_air), p))
        return theta, rho

    theta10, rho10 = prep(10.0)
    theta2, rho2 = prep(2.0)
    theta_s = np.asarray(
        exner_potential_temperature(jnp.asarray(sst), jnp.asarray(slp)))
    L_sst = np.asarray(  # noqa: N806 - latent-heat notation
        latent_heat_vaporization_sst(jnp.asarray(theta_s)))

    # LY09 Stanton-branch bistability discriminator: sign of the Obukhov
    # numerator evaluated with each branch's Stanton number.  Different
    # signs => neither branch is a self-consistent fixed point => the
    # oracle's own iteration limit-cycles there.
    c = 1.0 / constants.epsilon - 1.0
    dth = theta10 - theta_s
    dq = q_air - ssq
    zqa = 1.0 + c * q_air
    n_stab = _LY_STANTON_STABLE * dth * zqa + c * theta10 * _LY_DALTON * dq
    n_unst = _LY_STANTON_UNSTABLE * dth * zqa + c * theta10 * _LY_DALTON * dq
    # Near-cancellation guard: even with consistent signs, a numerator
    # within ~10% of perfect cancellation converges to zeta ~ 0 where the
    # discontinuous 18/32.7 Stanton jump makes the scheme's own answer
    # implementation-fragile (measured offenders sat at <= 5% clearance).
    scale = (np.abs(_LY_STANTON_STABLE * dth * zqa)
             + np.abs(c * theta10 * _LY_DALTON * dq))
    clear = np.minimum(np.abs(n_stab), np.abs(n_unst)) > 0.1 * scale
    ly_unambiguous = (np.sign(n_stab) == np.sign(n_unst)) & clear

    core_regime = (W > 3.0) & (W < 28.0) & (np.abs(dth) < 5.0)

    return dict(d=d, inp=inp, W=W, ssq=ssq, theta10=theta10, rho10=rho10,
                theta2=theta2, rho2=rho2, theta_s=theta_s, L_sst=L_sst,
                ly_mask=ly_unambiguous & (W > 1.0) & core_regime,
                core_mask=core_regime)


def _rel_err(ours, ref, floor):
    ours = np.asarray(ours)
    ref = np.asarray(ref)
    return np.abs(ours - ref) / np.maximum(np.abs(ref), floor)


def _gate(name, ours, ref, floor, med_tol, p95_tol, max_tol, max_mask):
    """Assert the three-tier tolerance gates for one output field.

    Median is over ALL points; p95 and max are over ``max_mask`` (the
    regime where the scheme is well-posed — see module docstring).
    """
    rel = _rel_err(ours, ref, floor)
    med, p95 = np.median(rel), np.quantile(rel[max_mask], 0.95)
    mx = rel[max_mask].max()
    msg = (f"{name}: median={med:.3e} (tol {med_tol}), "
           f"p95={p95:.3e} (tol {p95_tol}), "
           f"masked-max={mx:.3e} (tol {max_tol})")
    print(msg)  # visible with pytest -s; aids tolerance recalibration
    assert med < med_tol and p95 < p95_tol and mx < max_tol, msg


# ---------------------------------------------------------------------------
# 1. OMIP NEMO-port ncar vs aerobulk ncar
# ---------------------------------------------------------------------------

def test_omip_ncar_matches_aerobulk(oracle):
    d, inp = oracle["d"], oracle["inp"]
    out = air_sea_fluxes(
        u10=jnp.asarray(inp["u"]), v10=jnp.asarray(inp["v"]),
        T_air_K=jnp.asarray(inp["t_air"]), q_air=jnp.asarray(inp["q_air"]),
        T_sfc_K=jnp.asarray(inp["sst"]), slp_Pa=jnp.asarray(inp["slp"]))
    allpts = np.ones_like(oracle["W"], dtype=bool)
    # OMIP port keeps NEMO conventions: heat positive-down (= aerobulk),
    # stress = ocean reaction (-aerobulk), evap positive when evaporating
    # (aerobulk negative).
    _gate("omip tau_x", out[0], -d["ncar_zt10_zu10_taux"], _FLOOR_TAU,
          1e-3, 1e-3, 5e-2, allpts)
    _gate("omip tau_y", out[1], -d["ncar_zt10_zu10_tauy"], _FLOOR_TAU,
          1e-3, 1e-3, 5e-2, allpts)
    _gate("omip sh", out[2], d["ncar_zt10_zu10_qh"], _FLOOR_HEAT,
          2e-2, 3e-2, 6e-2, allpts)
    _gate("omip lh", out[3], d["ncar_zt10_zu10_ql"], _FLOOR_HEAT,
          5e-3, 1e-2, 4e-2, allpts)
    _gate("omip evap", out[4], -d["ncar_zt10_zu10_evap"], 1e-6,
          1e-3, 1e-3, 3e-2, allpts)


# ---------------------------------------------------------------------------
# 2. core MOST kernel, large_yeager vs aerobulk ncar
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("heights", ["zt10_zu10", "zt2_zu10"])
def test_core_large_yeager_matches_aerobulk_ncar(oracle, heights):
    d, inp = oracle["d"], oracle["inp"]
    if heights == "zt10_zu10":
        theta, rho, kw = oracle["theta10"], oracle["rho10"], {}
    else:
        theta, rho = oracle["theta2"], oracle["rho2"]
        kw = dict(z_t=2.0, z_q=2.0)
    tau_x, tau_y, sh, lh, _ = compute_most_fluxes(
        jnp.asarray(inp["u"]), jnp.asarray(inp["v"]), jnp.asarray(theta),
        jnp.asarray(inp["q_air"]), jnp.asarray(oracle["theta_s"]),
        jnp.asarray(oracle["ssq"]), jnp.asarray(rho), z_ref=10.0,
        scheme="large_yeager", n_iter=5,
        L_latent=jnp.asarray(oracle["L_sst"]), **kw)
    tag = f"ncar_{heights}"
    m = oracle["ly_mask"]
    # legoESM core convention: heat positive-up => compare to -aerobulk.
    _gate(f"ly {heights} tau_x", tau_x, -d[f"{tag}_taux"], _FLOOR_TAU,
          5e-3, 2e-2, 1e-1, m)
    _gate(f"ly {heights} tau_y", tau_y, -d[f"{tag}_tauy"], _FLOOR_TAU,
          5e-3, 2e-2, 1e-1, m)
    _gate(f"ly {heights} sh", sh, -d[f"{tag}_qh"], _FLOOR_HEAT,
          3e-2, 6e-2, 1e-1, m)
    _gate(f"ly {heights} lh", lh, -d[f"{tag}_ql"], _FLOOR_HEAT,
          1e-2, 7e-2, 2e-1, m)


# ---------------------------------------------------------------------------
# 3. core MOST kernel, coare3 vs aerobulk coare3p0
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("heights", ["zt10_zu10", "zt2_zu10"])
def test_core_coare3_matches_aerobulk_coare3p0(oracle, heights):
    d, inp = oracle["d"], oracle["inp"]
    if heights == "zt10_zu10":
        theta, rho, kw = oracle["theta10"], oracle["rho10"], {}
    else:
        theta, rho = oracle["theta2"], oracle["rho2"]
        kw = dict(z_t=2.0, z_q=2.0)
    tau_x, tau_y, sh, lh, _ = compute_most_fluxes(
        jnp.asarray(inp["u"]), jnp.asarray(inp["v"]), jnp.asarray(theta),
        jnp.asarray(inp["q_air"]), jnp.asarray(oracle["theta_s"]),
        jnp.asarray(oracle["ssq"]), jnp.asarray(rho), z_ref=10.0,
        # gustiness_w_zi left at None: the scheme-native coare3 default
        # (600 m, beta 1.25) IS the aerobulk coare3p0 convention under test.
        scheme="coare3", n_iter=5, L_latent=jnp.asarray(oracle["L_sst"]), **kw)
    tag = f"coare3p0_{heights}"
    m = oracle["core_mask"]
    _gate(f"coare3 {heights} tau_x", tau_x, -d[f"{tag}_taux"], _FLOOR_TAU,
          5e-3, 3e-2, 1e-1, m)
    _gate(f"coare3 {heights} tau_y", tau_y, -d[f"{tag}_tauy"], _FLOOR_TAU,
          5e-3, 3e-2, 1e-1, m)
    _gate(f"coare3 {heights} sh", sh, -d[f"{tag}_qh"], _FLOOR_HEAT,
          3e-2, 7e-2, 1e-1, m)
    _gate(f"coare3 {heights} lh", lh, -d[f"{tag}_ql"], _FLOOR_HEAT,
          1e-2, 2e-2, 1e-1, m)


# ---------------------------------------------------------------------------
# 4. Non-vacuity self-test (guardrail doctrine: every gate ships a
#    synthetic-violation check proving it can actually fail).
# ---------------------------------------------------------------------------

def test_gate_fails_on_synthetic_violation(oracle):
    d = oracle["d"]
    ref = -d["coare3p0_zt10_zu10_taux"]
    corrupted = ref * 1.10  # a 10% systematic bias must trip the median gate
    with pytest.raises(AssertionError):
        _gate("synthetic", corrupted, ref, _FLOOR_TAU,
              5e-3, 3e-2, 1e-1, np.ones_like(ref, dtype=bool))


def test_baseline_metadata_present():
    meta = _BASE.with_suffix(".json")
    assert meta.exists(), "aerobulk baseline metadata json missing"
    import json
    m = json.loads(meta.read_text())
    assert m["skin_correction"] is False
    assert set(m["algos"]) == {"ncar", "coare3p0"}


# ---------------------------------------------------------------------------
# 5. Thermodynamic-convention lever (#762): thermo_convention="aerobulk"
#    resolves the SAME SST-dependent L the oracle injects explicitly, and
#    the moist-cp sensible flux moves TOWARD the aerobulk truth.
# ---------------------------------------------------------------------------

def test_aerobulk_convention_L_matches_explicit_injection(oracle):
    """convention="aerobulk" with NO explicit L_latent must equal the
    L_latent=L_sst injection bitwise on the latent flux (same formula,
    same inputs) — pins that the lever resolves L internally exactly as
    the oracle fixture does."""
    inp = oracle["inp"]
    common = dict(
        u_rel=jnp.asarray(inp["u"]), v_rel=jnp.asarray(inp["v"]),
        T_atm=jnp.asarray(oracle["theta10"]),
        q_atm=jnp.asarray(inp["q_air"]),
        T_sfc=jnp.asarray(oracle["theta_s"]),
        q_sfc=jnp.asarray(oracle["ssq"]),
        rho=jnp.asarray(oracle["rho10"]), z_ref=10.0,
        scheme="coare3", n_iter=5,
    )
    out_conv = compute_most_fluxes(**common, thermo_convention="aerobulk")
    out_inj = compute_most_fluxes(
        **common, L_latent=jnp.asarray(oracle["L_sst"]))
    # Latent: bitwise-equal L resolution (formula + inputs identical).
    np.testing.assert_array_equal(np.asarray(out_conv[3]),
                                  np.asarray(out_inj[3]))
    # Momentum: convention must not touch stress at all.
    np.testing.assert_array_equal(np.asarray(out_conv[0]),
                                  np.asarray(out_inj[0]))


def test_aerobulk_convention_sh_closes_gap_to_oracle(oracle):
    """Moist cp_air(q) moves the sensible flux TOWARD the aerobulk truth
    (median relative error must not degrade; it improves wherever q is
    large).  Non-vacuity: the two conventions must actually differ."""
    d, inp = oracle["d"], oracle["inp"]
    m = oracle["core_mask"]
    common = dict(
        u_rel=jnp.asarray(inp["u"]), v_rel=jnp.asarray(inp["v"]),
        T_atm=jnp.asarray(oracle["theta10"]),
        q_atm=jnp.asarray(inp["q_air"]),
        T_sfc=jnp.asarray(oracle["theta_s"]),
        q_sfc=jnp.asarray(oracle["ssq"]),
        rho=jnp.asarray(oracle["rho10"]), z_ref=10.0,
        scheme="coare3", n_iter=5,
        L_latent=jnp.asarray(oracle["L_sst"]),
    )
    sh_legacy = np.asarray(compute_most_fluxes(
        **common, thermo_convention="legoesm")[2])
    sh_moist = np.asarray(compute_most_fluxes(
        **common, thermo_convention="aerobulk")[2])
    ref = -d["coare3p0_zt10_zu10_qh"]
    assert not np.allclose(sh_legacy, sh_moist), "lever is a no-op"
    def _med_rel(x):
        e = np.abs(x - ref) / np.maximum(np.abs(ref), _FLOOR_HEAT)
        return float(np.median(e[m]))
    assert _med_rel(sh_moist) <= _med_rel(sh_legacy) + 1e-12, (
        f"moist cp moved SH AWAY from aerobulk: "
        f"{_med_rel(sh_moist):.4f} vs {_med_rel(sh_legacy):.4f}")


def test_thermo_convention_dispatch_hardening():
    """A typo'd convention must raise, never silently run the other set."""
    one = jnp.ones((2,))
    with pytest.raises(ValueError, match="thermo_convention"):
        compute_most_fluxes(one, one, one * 290.0, one * 0.01,
                            one * 291.0, one * 0.012, one * 1.2,
                            thermo_convention="aerobulk_typo")


def test_legoesm_default_unchanged(oracle):
    """Omitting thermo_convention == passing "legoesm" bitwise (the
    default flip-guard: production paths are byte-identical)."""
    inp = oracle["inp"]
    common = dict(
        u_rel=jnp.asarray(inp["u"]), v_rel=jnp.asarray(inp["v"]),
        T_atm=jnp.asarray(oracle["theta10"]),
        q_atm=jnp.asarray(inp["q_air"]),
        T_sfc=jnp.asarray(oracle["theta_s"]),
        q_sfc=jnp.asarray(oracle["ssq"]),
        rho=jnp.asarray(oracle["rho10"]), z_ref=10.0,
        scheme="large_yeager", n_iter=5,
    )
    a = compute_most_fluxes(**common)
    b = compute_most_fluxes(**common, thermo_convention="legoesm")
    for x, y in zip(a, b):
        np.testing.assert_array_equal(np.asarray(x), np.asarray(y))


def test_ocean_surface_q_sat_convention_symmetry():
    """The shared air-sea q_sfc helper (#762): Goff only under aerobulk on a
    MOST scheme; Tetens (byte-identical) for the default legoesm convention,
    the 'constant' closure, and aerobulk on a non-MOST scheme.  This is the
    single source coupler + slab-ocean + tiled surface layer share so the
    interface q_sfc is never split between conventions."""
    import jax.numpy as jnp
    from legoesm.core.bulk_flux import ocean_surface_q_sat
    from legoesm.thermo import (
        saturation_mixing_ratio as _tet,
        saturation_mixing_ratio_goff as _goff,
    )
    T = jnp.array([275.0, 290.0, 302.0])
    p = jnp.array([1.01e5, 1.01e5, 1.01e5])
    # Default + legoesm + non-MOST + aerobulk-on-constant -> Tetens.
    for conv, sch in [("legoesm", "constant"), ("legoesm", "coare3"),
                      ("aerobulk", "constant")]:
        np.testing.assert_array_equal(
            np.asarray(ocean_surface_q_sat(
                T, p, thermo_convention=conv, bulk_scheme=sch)),
            np.asarray(_tet(T, p)))
    # aerobulk on a MOST scheme -> Goff, and it actually differs from Tetens.
    for sch in ("most", "coare3", "large_yeager"):
        got = ocean_surface_q_sat(
            T, p, thermo_convention="aerobulk", bulk_scheme=sch)
        np.testing.assert_array_equal(np.asarray(got), np.asarray(_goff(T, p)))
    assert not np.allclose(np.asarray(_goff(T, p)), np.asarray(_tet(T, p)))
    # Salinity factor scales linearly.
    np.testing.assert_allclose(
        np.asarray(ocean_surface_q_sat(T, p, saline_factor=0.98)),
        0.98 * np.asarray(_tet(T, p)), rtol=1e-12)
