"""Divergence-SELECTIVE biharmonic damping on the MPAS hydrostatic lane
(CAM-FV's ``ldiv4``, ``fv_div24del2flag=4`` -- the CAM6 physics default).

The dycore's existing ``nu_del2``/``nu_del4`` are VECTOR Laplacians: they damp
the rotational and divergent modes together.  This lever damps only the
curl-free part, which is what CAM applies at every level and what a hybrid
table with pure-pressure (B=0) top layers needs, since a fixed-mass layer
cannot absorb divergence and continuity turns it into vertical mass flux.

Off state (scale 0.0) must be byte-identical so every existing run is unchanged.
"""
from __future__ import annotations

import importlib.util
import os
import pathlib
import sys

import jax

jax.config.update("jax_enable_x64", True)
import jax.numpy as jnp
import numpy as np
import pytest

from legoesm.atmosphere.dynamics.gcm.primitive_eq_mpas import (
    MPASPrimitiveEquationConfig, mpas_hydrostatic_tendencies)
from legoesm.core.operators_voronoi import (
    curl_vertex_3d, div_damp_del4_3d, divergence_cell_3d)
from legoesm.driver.component_factory import compute_diffusion
from legoesm.driver.config import DycoreConfig, ExperimentConfig, GridConfig
from legoesm.grids.vertical import (create_sigma_coordinate,
                                    make_cam6_l32_levels as create_cam6_l32)

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                os.pardir, os.pardir, "scripts", "run"))
from run_amip import build_arg_parser, build_config_from_args  # noqa: E402


def _helpers():
    path = pathlib.Path(__file__).with_name("test_mpas_atmosphere.py")
    spec = importlib.util.spec_from_file_location("_mpas_atm_helpers", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_operator_damps_only_the_divergent_mode():
    """The whole point of the lever: a discretely non-divergent wind is left
    alone, and whatever the operator returns carries no curl of its own."""
    mesh = _helpers()._make_mesh(level=2)
    nlev = 4
    rng = np.random.default_rng(0)
    u = jnp.asarray(rng.standard_normal((mesh.dvEdge.shape[0], nlev)))

    # Tangential gradient of a vertex streamfunction: discretely divergence-free.
    psi = jnp.asarray(rng.standard_normal((mesh.fVertex.shape[0], nlev)))
    v0, v1 = mesh.verticesOnEdge[0], mesh.verticesOnEdge[1]
    u_rot = (psi[v1] - psi[v0]) / mesh.dvEdge[:, None]

    out, out_rot = div_damp_del4_3d(u, mesh), div_damp_del4_3d(u_rot, mesh)
    scale = float(jnp.abs(out).max())
    assert scale > 0.0                                            # non-vacuous
    assert float(jnp.abs(divergence_cell_3d(u_rot, mesh)).max()) < \
        1e-12 * float(jnp.abs(divergence_cell_3d(u, mesh)).max())  # the premise
    # Rotational flow untouched, and the damping tendency is itself curl-free,
    # so balanced flow neither feeds it nor is generated by it.
    assert float(jnp.abs(out_rot).max()) < 1e-12 * scale
    assert float(jnp.abs(curl_vertex_3d(out, mesh)).max()) < 1e-12 * scale


def test_the_term_dissipates_rather_than_amplifies():
    """Both reviewers planted a sign reversal and watched the whole suite pass:
    nullspace, curl-freeness and linearity in nu are all sign-invariant, so a
    flipped sign would ship a 20%-per-step grid-scale INSTABILITY.  The
    discriminating quantity is the work the term does on the wind, under the
    C-grid's own edge weights ``dcEdge*dvEdge``: writing A = grad.div, the
    operator is A^2 and A is self-adjoint in those weights, so
    <u, -nu A^2 u> = -nu ||A u||^2 <= 0 for every wind, strictly < 0 whenever
    the flow is not purely rotational."""
    mesh = _helpers()._make_mesh(level=2)
    nlev = 4
    rng = np.random.default_rng(1)
    u = jnp.asarray(rng.standard_normal((mesh.dvEdge.shape[0], nlev)))
    w = (mesh.dcEdge * mesh.dvEdge)[:, None]                  # C-grid edge weight

    tendency = -1.0 * div_damp_del4_3d(u, mesh)               # nu = 1, as applied
    work = float(jnp.sum(w * u * tendency))
    assert work < 0.0, f"the term does positive work ({work:+.6e}): it amplifies"
    # A flipped sign is exactly this number with the opposite sign, so the
    # assertion above is the planted-failure guard.
    assert float(jnp.sum(w * u * (+1.0 * div_damp_del4_3d(u, mesh)))) > 0.0

    # And it dissipates in the only sense that matters for the run: repeated
    # explicit application at the production coefficient shrinks the divergent
    # part of the wind monotonically while leaving the rotational part alone.
    psi = jnp.asarray(rng.standard_normal((mesh.fVertex.shape[0], nlev)))
    v0, v1 = mesh.verticesOnEdge[0], mesh.verticesOnEdge[1]
    u_rot = (psi[v1] - psi[v0]) / mesh.dvEdge[:, None]
    area = float(jnp.min(jnp.asarray(mesh.areaCell)))
    dt = 112.5
    nu = 0.01 * area ** 2 / dt
    x, div0 = u + u_rot, float(jnp.linalg.norm(divergence_cell_3d(u + u_rot, mesh)))
    rot0 = float(jnp.linalg.norm(curl_vertex_3d(u + u_rot, mesh)))
    prev = div0
    for _ in range(5):
        x = x - dt * nu * div_damp_del4_3d(x, mesh)
        now = float(jnp.linalg.norm(divergence_cell_3d(x, mesh)))
        assert now < prev, "divergent part grew: the term is unstable or anti-damping"
        prev = now
    assert prev < div0
    np.testing.assert_allclose(float(jnp.linalg.norm(curl_vertex_3d(x, mesh))),
                               rot0, rtol=1e-9)   # rotational part untouched


def test_off_state_is_byte_identical_and_on_state_moves_only_the_wind():
    h = _helpers()
    mesh, nlev = h._make_mesh(level=2), 8
    sig = create_sigma_coordinate(nlev, dtype=jnp.float64)
    state = h._add_perturbation_hydro(h._make_hydrostatic_state(mesh, nlev), mesh, nlev)
    base = MPASPrimitiveEquationConfig(nu_del2=1.0e5, nu_del4=1.0e17)

    def tend(cfg):
        return mpas_hydrostatic_tendencies(state, mesh, sig, cfg)

    off, on = tend(base), tend(base._replace(nu_div4=1.0e16))
    assert MPASPrimitiveEquationConfig().nu_div4 == 0.0
    assert np.array_equal(np.asarray(tend(base._replace(nu_div4=0.0)).du_dt.data),
                          np.asarray(off.du_dt.data))            # off = identical
    increment = np.asarray(on.du_dt.data) - np.asarray(off.du_dt.data)
    assert np.abs(increment).max() > 0.0                         # non-vacuous
    # Momentum-only: the thermodynamic and surface-pressure tendencies of this
    # call are untouched (the wind feeds them on the NEXT step, not this one).
    np.testing.assert_array_equal(np.asarray(on.dT_dt.data), np.asarray(off.dT_dt.data))
    # Linear in the coefficient, so the config value is the coefficient.
    half = np.asarray(tend(base._replace(nu_div4=0.5e16)).du_dt.data) - np.asarray(off.du_dt.data)
    np.testing.assert_allclose(half, 0.5 * increment, rtol=1e-9, atol=1e-30)


def test_coefficient_matches_cam_ldiv4_and_reaches_the_dycore():
    """``0.01 * cell_area**2 / dt`` is CAM's tau4*L**4 (cd_core.F90:655-683)."""
    mesh = _helpers()._make_mesh(level=2)
    dc = DycoreConfig(discretization="mpas", dt=112.5, mpas_div_damp4_scale=1.0)
    diff = compute_diffusion(mesh, dc)
    expected = 0.01 * float(jnp.min(jnp.asarray(mesh.areaCell))) ** 2 / 112.5
    np.testing.assert_allclose(diff.div_damp4, expected, rtol=1e-12)
    assert compute_diffusion(mesh, dc._replace(mpas_div_damp4_scale=0.0)).div_damp4 == 0.0
    np.testing.assert_allclose(
        compute_diffusion(mesh, dc._replace(mpas_div_damp4_scale=0.5)).div_damp4,
        0.5 * expected, rtol=1e-12)


def test_config_default_off_guards_and_cli_round_trip():
    assert DycoreConfig().mpas_div_damp4_scale == 0.0
    grid = GridConfig(grid_type="mpas", vertical_coord="sigma", nlev=36, resolution=6)
    mpas = dict(discretization="mpas")
    ExperimentConfig(dycore=DycoreConfig(mpas_div_damp4_scale=1.0, **mpas),
                     grid=grid).validate_strict()
    # NaN/inf must be refused at config time: the scale reaches a momentum
    # tendency, where a non-finite value raises nothing and just turns the
    # whole wind field non-finite on the first step.
    for bad in (dict(mpas_div_damp4_scale=-1.0), dict(mpas_div_damp4_scale="1.0"),
                dict(mpas_div_damp4_scale=True),
                dict(mpas_div_damp4_scale=float("nan")),
                dict(mpas_div_damp4_scale=float("inf")),
                dict(mpas_div_damp4_scale=float("-inf"))):
        with pytest.raises(ValueError, match="mpas_div_damp4_scale"):
            ExperimentConfig(dycore=DycoreConfig(**mpas, **bad), grid=grid).validate_strict()
    # Silently-inert refusal on every lane that does not consume it.
    for bad in (dict(discretization="cdgrid"), dict(**mpas, model_type="nonhydrostatic")):
        with pytest.raises(ValueError, match="mpas_div_damp4_scale"):
            ExperimentConfig(dycore=DycoreConfig(mpas_div_damp4_scale=1.0, **bad),
                             grid=grid).validate_strict()
    args = build_arg_parser().parse_args(["--mpas-div-damp4-scale", "1.0"])
    assert build_config_from_args(args).dycore.mpas_div_damp4_scale == 1.0
    assert build_config_from_args(
        build_arg_parser().parse_args([])).dycore.mpas_div_damp4_scale == 0.0


def test_cam6_deck_reaches_the_dycore_end_to_end():
    """RULE: a new knob ships with a committed config that selects it -- and
    both reviewers pointed out that reading the YAML text proves nothing about
    whether the value survives the deck loader, the config builder and the
    factory.  This walks the whole path to the constructed dycore, which is the
    only thing that would have caught a deck key silently dropped on the way.
    """
    from legoesm.driver.run_config_yaml import load_yaml_config
    deck = pathlib.Path(__file__).parents[2] / "config" / "amip" / "amip_production.yaml"
    parser = build_arg_parser()
    keys = load_yaml_config(str(deck), parser)
    assert keys["mpas_div_damp4_scale"] == 1.0                  # deck -> loader
    parser.set_defaults(**keys)
    cfg = build_config_from_args(parser.parse_args([]))
    assert cfg.dycore.mpas_div_damp4_scale == 1.0               # loader -> config
    mesh = _helpers()._make_mesh(level=2)
    diff = compute_diffusion(mesh, cfg.dycore)
    assert diff.div_damp4 > 0.0                                 # config -> coefficient
    # coefficient -> the dycore object the run actually steps
    from legoesm.driver.component_factory import create_atmosphere_dycore
    model = create_atmosphere_dycore(cfg, mesh, create_cam6_l32())
    assert model.config.nu_div4 == diff.div_damp4 > 0.0
    # and the same path with the lever off leaves the dycore at zero
    off = cfg._replace(dycore=cfg.dycore._replace(mpas_div_damp4_scale=0.0))
    assert create_atmosphere_dycore(off, mesh, create_cam6_l32()).config.nu_div4 == 0.0


def test_conservative_hybrid_transport_is_selectable_and_conserves():
    """The hybrid lane's theta transport is advective upwind, which violates
    the discrete product rule; the conservative Simmons-Burridge flux form the
    spectral lane already selects satisfies it to round-off.  'sb' makes that
    operator reachable here.  Measured on the CAM 32-level table: column
    residual 3.8e-2 of the interfacial exchange advective, 6.7e-16 conservative.
    """
    from legoesm.grids.vertical import (
        dp_from_hybrid, vertical_advection_hybrid, vertical_advection_hybrid_sb)
    coord = create_cam6_l32()
    p_s = jnp.asarray([1.0e5])
    dp = dp_from_hybrid(coord, p_s)
    nlev = dp.shape[-1]
    z = np.arange(nlev)
    f = jnp.asarray((250.0 + 40.0 * np.sin(2 * np.pi * z / nlev))[None, :])
    F = np.zeros(nlev + 1)
    F[1:-1] = 0.05 * np.sin(np.pi * np.arange(1, nlev) / nlev)   # zero at both ends
    F = jnp.asarray(F[None, :])
    dF = F[..., 1:] - F[..., :-1]
    exch = float(jnp.sum(jnp.abs(F[..., 1:-1] * jnp.diff(f, axis=-1))))

    def product_rule_residual(op):
        return abs(float(jnp.sum(dp * op(f, F, p_s, coord) - f * dF))) / exch

    assert product_rule_residual(vertical_advection_hybrid_sb) < 1e-12
    assert product_rule_residual(vertical_advection_hybrid) > 1e-3   # non-vacuous

    # Reachable from the MPAS hybrid lane, and it changes the temperature
    # tendency there; sigma refuses it rather than running it inert.
    h = _helpers()
    mesh = h._make_mesh(level=2)
    state = h._add_perturbation_hydro(h._make_hydrostatic_state(mesh, nlev), mesh, nlev)
    base = MPASPrimitiveEquationConfig(nu_del2=1.0e5)

    def dT(scheme, crd):
        cfg = base._replace(vert_advection_scheme=scheme)
        return np.asarray(mpas_hydrostatic_tendencies(state, mesh, crd, cfg).dT_dt.data)

    assert not np.array_equal(dT("upwind", coord), dT("sb", coord))
    assert MPASPrimitiveEquationConfig().vert_advection_scheme == "upwind"
    with pytest.raises(ValueError, match="sb"):
        s8 = h._add_perturbation_hydro(h._make_hydrostatic_state(mesh, 8), mesh, 8)
        mpas_hydrostatic_tendencies(
            s8, mesh, create_sigma_coordinate(8, dtype=jnp.float64),
            base._replace(vert_advection_scheme="sb"))


def test_production_deck_selects_both_levers_and_no_other_deck_does():
    """The user approved both levers on 2026-09-23 after the three-arm
    physics-off A/B, and on the same day made the CAM6 suite the production
    default, so the levers now live in amip_production.yaml.  This pins that
    decision: the production deck carries both, every other committed deck
    carries neither, and the CODE defaults stay off -- the deck selects them,
    a default is not a record.  It goes red if a lever leaks into another deck
    or into a default.

    The outgoing Sundqvist/L36 deck is named explicitly rather than matched by
    exclusion, because it is the paired baseline of the run-1 comparison and
    the whole point of keeping it is that it carries NEITHER lever."""
    from legoesm.driver.run_config_yaml import read_yaml_with_includes
    cfgdir = pathlib.Path(__file__).parents[2] / "config"
    doc = read_yaml_with_includes(cfgdir / "amip" / "amip_production.yaml")
    assert doc["mpas_div_damp4_scale"] == 1.0
    assert doc["mpas_vert_advection_scheme"] == "sb"
    assert DycoreConfig().mpas_div_damp4_scale == 0.0
    assert DycoreConfig().mpas_vert_advection_scheme == "upwind"
    base = read_yaml_with_includes(cfgdir / "amip" / "amip_sundqvist_l36.yaml")
    assert base.get("mpas_div_damp4_scale", 0.0) == 0.0   # silent -> code default
    assert base["mpas_vert_advection_scheme"] == "van_leer"
    # Walk the RESOLVED decks, not the raw files: a deck that inherits a lever
    # through `include:` carries it just as surely as one that spells it out,
    # and a raw-key walk cannot see that (GLM review 2026-09-23).
    _assert_no_other_deck_carries_a_lever(cfgdir)


def _assert_no_other_deck_carries_a_lever(cfgdir):
    """The walk itself, taking its config root as an argument.

    Split out so the negative control below can run it against a COPY in a
    temporary directory instead of planting a file in the real checkout: the
    genuine gate walks the same tree, so a shared impostor would make it fail
    spuriously under pytest-xdist and would survive a crash (GLM round 3).
    """
    from legoesm.driver.run_config_yaml import read_yaml_with_includes
    production = (cfgdir / "amip" / "amip_production.yaml").resolve()
    for deck in sorted(cfgdir.rglob("*.yaml")):
        # Exempt the canonical PATH, not the basename: a file named
        # amip_production.yaml anywhere else under config/ would otherwise be
        # skipped, and codex proved that bypass runnable -- an in-memory
        # config/review/amip_production.yaml inheriting production passed both
        # this walk and strict validation carrying 1.0/sb (round-2 review).
        if deck.resolve() == production:
            continue
        # No catch: measured 2026-09-23, all 313 config/**/*.yaml resolve
        # without raising, so a swallowed error here would only be an escape
        # hatch for a deck that stopped resolving (GLM round-2 review).
        other = read_yaml_with_includes(deck) or {}
        if not isinstance(other, dict):
            continue
        assert other.get("mpas_div_damp4_scale", 0.0) == 0.0, deck
        assert other.get("mpas_vert_advection_scheme", "upwind") != "sb", deck


def test_the_lever_walk_exempts_a_path_not_a_basename(tmp_path):
    """Negative control for the exemption, from codex round 2.

    A deck named amip_production.yaml somewhere OTHER than config/amip/ is not
    the production deck and must be walked like any other.  Before the fix it
    was skipped by basename, so a deck inheriting the levers could reach a run
    with the gate green.

    Runs against a COPY of config/ under tmp_path, so it plants nothing in the
    checkout, cannot collide with a parallel run of the real gate, and leaves
    nothing behind if it dies mid-test.
    """
    import shutil
    import pytest
    real = pathlib.Path(__file__).parents[2] / "config"
    cfgdir = tmp_path / "config"
    shutil.copytree(real, cfgdir)
    # sanity: the copy passes before the impostor is planted, so a failure
    # below is the impostor and not the copying.
    _assert_no_other_deck_carries_a_lever(cfgdir)
    impostor = cfgdir / "review" / "amip_production.yaml"
    impostor.parent.mkdir(parents=True)
    impostor.write_text("include: ../amip/amip_production.yaml\n")
    with pytest.raises(AssertionError):
        _assert_no_other_deck_carries_a_lever(cfgdir)
