"""Divergence-SELECTIVE biharmonic damping on the MPAS hydrostatic lane
(CAM-FV's ``ldiv4``, ``fv_div24del2flag=4`` -- the CAM6 physics default).

The dycore's existing ``nu_del2``/``nu_del4`` are VECTOR Laplacians: they damp
the rotational and divergent modes together.  This lever damps only the
curl-free part, which is what CAM applies at every level and what a hybrid
table with pure-pressure (B=0) top layers needs, since a fixed-mass layer
cannot absorb divergence and continuity turns it into vertical mass flux.

Off state (scale 0.0) must be byte-identical so every existing run is unchanged.
"""
from __future__ import annotations

import importlib.util
import os
import pathlib
import sys

import jax

jax.config.update("jax_enable_x64", True)
import jax.numpy as jnp
import numpy as np
import pytest

from legoesm.atmosphere.dynamics.gcm.primitive_eq_mpas import (
    MPASPrimitiveEquationConfig, mpas_hydrostatic_tendencies)
from legoesm.core.operators_voronoi import (
    curl_vertex_3d, div_damp_del4_3d, divergence_cell_3d)
from legoesm.driver.component_factory import compute_diffusion
from legoesm.driver.config import DycoreConfig, ExperimentConfig, GridConfig
from legoesm.grids.vertical import create_sigma_coordinate

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                os.pardir, os.pardir, "scripts", "run"))
from run_amip import build_arg_parser, build_config_from_args  # noqa: E402


def _helpers():
    path = pathlib.Path(__file__).with_name("test_mpas_atmosphere.py")
    spec = importlib.util.spec_from_file_location("_mpas_atm_helpers", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_operator_damps_only_the_divergent_mode():
    """The whole point of the lever: a discretely non-divergent wind is left
    alone, and whatever the operator returns carries no curl of its own."""
    mesh = _helpers()._make_mesh(level=2)
    nlev = 4
    rng = np.random.default_rng(0)
    u = jnp.asarray(rng.standard_normal((mesh.dvEdge.shape[0], nlev)))

    # Tangential gradient of a vertex streamfunction: discretely divergence-free.
    psi = jnp.asarray(rng.standard_normal((mesh.fVertex.shape[0], nlev)))
    v0, v1 = mesh.verticesOnEdge[0], mesh.verticesOnEdge[1]
    u_rot = (psi[v1] - psi[v0]) / mesh.dvEdge[:, None]

    out, out_rot = div_damp_del4_3d(u, mesh), div_damp_del4_3d(u_rot, mesh)
    scale = float(jnp.abs(out).max())
    assert scale > 0.0                                            # non-vacuous
    assert float(jnp.abs(divergence_cell_3d(u_rot, mesh)).max()) < \
        1e-12 * float(jnp.abs(divergence_cell_3d(u, mesh)).max())  # the premise
    # Rotational flow untouched, and the damping tendency is itself curl-free,
    # so balanced flow neither feeds it nor is generated by it.
    assert float(jnp.abs(out_rot).max()) < 1e-12 * scale
    assert float(jnp.abs(curl_vertex_3d(out, mesh)).max()) < 1e-12 * scale


def test_off_state_is_byte_identical_and_on_state_moves_only_the_wind():
    h = _helpers()
    mesh, nlev = h._make_mesh(level=2), 8
    sig = create_sigma_coordinate(nlev, dtype=jnp.float64)
    state = h._add_perturbation_hydro(h._make_hydrostatic_state(mesh, nlev), mesh, nlev)
    base = MPASPrimitiveEquationConfig(nu_del2=1.0e5, nu_del4=1.0e17)

    def tend(cfg):
        return mpas_hydrostatic_tendencies(state, mesh, sig, cfg)

    off, on = tend(base), tend(base._replace(nu_div4=1.0e16))
    assert MPASPrimitiveEquationConfig().nu_div4 == 0.0
    assert np.array_equal(np.asarray(tend(base._replace(nu_div4=0.0)).du_dt.data),
                          np.asarray(off.du_dt.data))            # off = identical
    increment = np.asarray(on.du_dt.data) - np.asarray(off.du_dt.data)
    assert np.abs(increment).max() > 0.0                         # non-vacuous
    # Momentum-only: the thermodynamic and surface-pressure tendencies of this
    # call are untouched (the wind feeds them on the NEXT step, not this one).
    np.testing.assert_array_equal(np.asarray(on.dT_dt.data), np.asarray(off.dT_dt.data))
    # Linear in the coefficient, so the config value is the coefficient.
    half = np.asarray(tend(base._replace(nu_div4=0.5e16)).du_dt.data) - np.asarray(off.du_dt.data)
    np.testing.assert_allclose(half, 0.5 * increment, rtol=1e-9, atol=1e-30)


def test_coefficient_matches_cam_ldiv4_and_reaches_the_dycore():
    """``0.01 * cell_area**2 / dt`` is CAM's tau4*L**4 (cd_core.F90:655-683)."""
    mesh = _helpers()._make_mesh(level=2)
    dc = DycoreConfig(discretization="mpas", dt=112.5, mpas_div_damp4_scale=1.0)
    diff = compute_diffusion(mesh, dc)
    expected = 0.01 * float(jnp.min(jnp.asarray(mesh.areaCell))) ** 2 / 112.5
    np.testing.assert_allclose(diff.div_damp4, expected, rtol=1e-12)
    assert compute_diffusion(mesh, dc._replace(mpas_div_damp4_scale=0.0)).div_damp4 == 0.0
    np.testing.assert_allclose(
        compute_diffusion(mesh, dc._replace(mpas_div_damp4_scale=0.5)).div_damp4,
        0.5 * expected, rtol=1e-12)


def test_config_default_off_guards_and_cli_round_trip():
    assert DycoreConfig().mpas_div_damp4_scale == 0.0
    grid = GridConfig(grid_type="mpas", vertical_coord="sigma", nlev=36, resolution=6)
    mpas = dict(discretization="mpas")
    ExperimentConfig(dycore=DycoreConfig(mpas_div_damp4_scale=1.0, **mpas),
                     grid=grid).validate_strict()
    for bad in (dict(mpas_div_damp4_scale=-1.0), dict(mpas_div_damp4_scale="1.0"),
                dict(mpas_div_damp4_scale=True)):
        with pytest.raises(ValueError, match="mpas_div_damp4_scale"):
            ExperimentConfig(dycore=DycoreConfig(**mpas, **bad), grid=grid).validate_strict()
    # Silently-inert refusal on every lane that does not consume it.
    for bad in (dict(discretization="cdgrid"), dict(**mpas, model_type="nonhydrostatic")):
        with pytest.raises(ValueError, match="mpas_div_damp4_scale"):
            ExperimentConfig(dycore=DycoreConfig(mpas_div_damp4_scale=1.0, **bad),
                             grid=grid).validate_strict()
    args = build_arg_parser().parse_args(["--mpas-div-damp4-scale", "1.0"])
    assert build_config_from_args(args).dycore.mpas_div_damp4_scale == 1.0
    assert build_config_from_args(
        build_arg_parser().parse_args([])).dycore.mpas_div_damp4_scale == 0.0


def test_cam6_deck_selects_cam_strength():
    """RULE: a new knob ships with a committed config that selects it."""
    import yaml
    deck = pathlib.Path(__file__).parents[2] / "config" / "amip" / "amip_cam6.yaml"
    assert yaml.safe_load(deck.read_text())["mpas_div_damp4_scale"] == 1.0
