#!/usr/bin/env python
"""Generate ONE verification scorecard (#388 Ask#4).

Answers, as of the current commit's run artifacts, *which (component × case ×
grid) combinations are verified, to which tier, and whether the oracle-match
tiers are trustworthy under truth-tier precedence*.

It aggregates the artifacts that already exist — no new instrumentation:

* every ``results/<component>/summary.json`` (written by the shared
  ``MatrixRunner``) → one row per (component, case, grid) with its tier +
  status + maturity;
* an optional fidelity pass/fail dump (a JSON list of records with ``tier`` +
  ``passed``, e.g. :class:`legoesm.ocean.fidelity.diff.PassFailRecord`) → the
  truth-tier-precedence verdict (oracle tiers ≥3 are LOCKED if any truth tier
  0–2 failed), via :mod:`legoesm.ocean.fidelity.precedence`.

This is the lightweight "doc generated from existing summary.json's" the issue
asks for (NOT a queryable DB — an explicit non-goal) and the surface on which
the otherwise-documented-only truth-tier precedence rule is now machine-checked
and reported.  Output is a generated artifact under ``results/`` (gitignored),
regenerated on demand; it is a snapshot of the latest runs, not a CI golden.

Usage::

    python scripts/validate/ocean_fidelity/build_fidelity_scorecard.py
    python scripts/validate/ocean_fidelity/build_fidelity_scorecard.py \\
        --results-root results --fidelity-results results/ocean/fidelity_records.json \\
        --output results/scorecard.md
"""
from __future__ import annotations

import argparse
import json
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any

# scripts/validate/ocean_fidelity/<this> -> repo root is parents[3]
_REPO_ROOT = Path(__file__).resolve().parents[3]


@dataclass(frozen=True)
class MatrixRow:
    component: str
    case: str
    grid: str
    resolution: str
    tier: Any
    status: str
    maturity: str


def _git_sha() -> str:
    try:
        return subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=_REPO_ROOT, capture_output=True, text=True, check=True,
        ).stdout.strip()
    except Exception:  # noqa: BLE001 — best-effort provenance stamp
        return "unknown"


def load_matrix_rows(results_root: Path) -> list[MatrixRow]:
    """Flatten every ``results/<component>/summary.json`` into scorecard rows.

    The component is taken from the parent directory name (the per-result dict
    does not always carry it).  Missing keys degrade gracefully so a partial /
    older summary still contributes what it has.
    """
    rows: list[MatrixRow] = []
    if not results_root.is_dir():
        return rows
    for summary in sorted(results_root.glob("*/summary.json")):
        component = summary.parent.name
        try:
            doc = json.loads(summary.read_text())
        except (OSError, json.JSONDecodeError):
            continue
        # Schema varies across runners: most write {"results": [...], ...} but
        # some write a bare list of result dicts.  Tolerate both.
        if isinstance(doc, dict):
            results = doc.get("results", [])
        elif isinstance(doc, list):
            results = doc
        else:
            results = []
        for r in results:
            if not isinstance(r, dict):
                continue
            rows.append(MatrixRow(
                component=str(r.get("component", component)),
                case=str(r.get("test", r.get("case", "?"))),
                grid=str(r.get("grid", "?")),
                resolution=str(r.get("resolution", "")),
                tier=r.get("tier", "?"),
                status=str(r.get("status", "?")),
                maturity=str(r.get("maturity", "")),
            ))
    return rows


def load_fidelity_records(path: Path | None) -> list[dict]:
    """Load a JSON list of fidelity pass/fail records (``tier`` + ``passed``)."""
    if path is None or not path.is_file():
        return []
    doc = json.loads(path.read_text())
    # Accept either a bare list or {"records": [...]}; tolerate junk.
    records = doc.get("records") if isinstance(doc, dict) else doc
    if not isinstance(records, list):
        return []
    return [r for r in records
            if isinstance(r, dict) and "tier" in r and "passed" in r]


def render_scorecard_md(rows: list[MatrixRow], verdict, *, sha: str) -> str:
    lines = [
        "# legoESM verification scorecard",
        "",
        f"Commit `{sha}`. Auto-generated by "
        "`scripts/validate/ocean_fidelity/build_fidelity_scorecard.py` — a "
        "snapshot of the latest run artifacts, not a CI golden.",
        "",
        "## Matrix coverage — (component × case × grid) → tier / status",
        "",
    ]
    if rows:
        lines += [
            "| Component | Case | Grid | Res | Tier | Status | Maturity |",
            "|---|---|---|---|---|---|---|",
        ]
        for r in sorted(rows, key=lambda x: (x.component, str(x.tier), x.case, x.grid)):
            lines.append(
                f"| {r.component} | {r.case} | {r.grid} | {r.resolution} | "
                f"{r.tier} | {r.status} | {r.maturity} |"
            )
        n_pass = sum(1 for r in rows if r.status == "PASS")
        lines += ["", f"**{n_pass}/{len(rows)} matrix cases PASS.**", ""]
    else:
        lines += [
            "_No `results/<component>/summary.json` found — run a matrix "
            "(`scripts/matrix/run_*_test_matrix.py`) first._", "",
        ]

    lines += ["## Truth-tier precedence (ocean fidelity)", ""]
    if verdict is None:
        lines += [
            "_No fidelity records supplied (`--fidelity-results`); precedence "
            "gate not evaluated._", "",
        ]
    else:
        gate = {
            "trusted": "TRUSTED", "locked": "LOCKED", "mismatch": "MISMATCH",
            "incomplete": "INCOMPLETE", "not_engaged": "N/A",
        }.get(verdict.status, verdict.status.upper())
        lines += [
            f"**Oracle tiers (≥3): {gate}.** {verdict.reason}",
            "",
            "| Tier | Pass | Fail | Green | Kind |",
            "|---|---|---|---|---|",
        ]
        from legoesm.ocean.fidelity.precedence import ORACLE_TIER_FLOOR
        for t, st in sorted(verdict.tiers.items()):
            kind = "truth" if t < ORACLE_TIER_FLOOR else "oracle"
            mark = "✅" if st.green else "❌"
            lines.append(
                f"| {t} | {st.n_pass} | {st.n_fail} | {mark} | {kind} |")
        lines.append("")
    return "\n".join(lines)


def build_scorecard(results_root: Path, fidelity_results: Path | None) -> dict:
    from legoesm.ocean.fidelity.precedence import evaluate_precedence

    rows = load_matrix_rows(results_root)
    records = load_fidelity_records(fidelity_results)
    verdict = evaluate_precedence(records) if records else None
    sha = _git_sha()
    md = render_scorecard_md(rows, verdict, sha=sha)
    payload: dict = {
        "commit": sha,
        "matrix": [r.__dict__ for r in rows],
    }
    if verdict is not None:
        payload["fidelity_precedence"] = {
            "status": verdict.status,
            "oracle_trusted": verdict.oracle_trusted,
            "oracle_locked": verdict.oracle_locked,
            "truth_failed": list(verdict.truth_failed),
            "truth_missing": list(verdict.truth_missing),
            "oracle_failed": list(verdict.oracle_failed),
            "reason": verdict.reason,
            "tiers": {str(t): {"n_pass": s.n_pass, "n_fail": s.n_fail,
                               "green": s.green}
                      for t, s in verdict.tiers.items()},
        }
    return {"markdown": md, "json": payload, "verdict": verdict}


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--results-root", default=str(_REPO_ROOT / "results"),
                   help="directory holding <component>/summary.json files")
    p.add_argument("--fidelity-results", default=None,
                   help="optional JSON list of fidelity pass/fail records "
                        "(tier + passed) for the precedence gate")
    p.add_argument("--output", default=str(_REPO_ROOT / "results" / "scorecard.md"),
                   help="markdown output path (.json written alongside)")
    args = p.parse_args(argv)

    out = build_scorecard(
        Path(args.results_root),
        Path(args.fidelity_results) if args.fidelity_results else None,
    )
    md_path = Path(args.output)
    md_path.parent.mkdir(parents=True, exist_ok=True)
    md_path.write_text(out["markdown"] + "\n")
    json_path = md_path.with_suffix(".json")
    json_path.write_text(json.dumps(out["json"], indent=2, sort_keys=True) + "\n")

    print(out["markdown"])
    print(f"\n  Wrote {md_path}\n  Wrote {json_path}")
    # Exit non-zero ONLY on a hard precedence violation (oracle tiers present +
    # a truth-tier FAILURE locks them) so this can gate a fidelity CI job.  An
    # "incomplete" verdict (missing truth coverage, no failures) is advisory and
    # exits 0.
    v = out["verdict"]
    if v is not None and v.oracle_locked:
        print("\n  PRECEDENCE VIOLATION: oracle tiers LOCKED by a truth-tier "
              "failure.")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
