"""legoESM vs Oceananigans barotropic-gyre fidelity comparison.

Builds a legoESM reproduction of the Oceananigans ``barotropic_gyre`` validation
case (regional spherical box lon[-30,30] x lat[15,75], 60x60x1, reduced gravity
g=0.1, cos wind stress, linear bottom drag, horizontal viscosity, vector-invariant
momentum, implicit free surface), spins it up from rest with the SAME forcing for
the same wall-clock as the oracle reference, and compares the surface velocity
pattern to the real Oceananigans output via the shared
``fidelity.compare.compare_field`` (pattern correlation + RMSE).

This is the first end-to-end legoESM<->Oceananigans fidelity number (the barotropic
solver + spherical-gyre dynamics). The Oceananigans reference is generated by
``scripts/data/generate_oceananigans_barotropic_gyre_reference.jl`` and loaded via
``oceananigans_runner.load_oceananigans_reference`` (point the runner at it with
``LEGOESM_OCEAN_FIDELITY_OCEANANIGANS_REF``).

Run::

    LEGOESM_OCEAN_FIDELITY_OCEANANIGANS_REF=/tmp/ocn_fidelity_ref \
      JAX_ENABLE_X64=1 .venv/bin/python \
      scripts/validate/ocean_fidelity/compare_oceananigans_barotropic_gyre.py [days] [dt_s]
"""

from __future__ import annotations

import os
import sys

os.environ.setdefault("JAX_ENABLE_X64", "1")
os.environ.setdefault("JAX_PLATFORMS", "cpu")

import numpy as np
import jax
import jax.numpy as jnp

from legoesm.grids.latlon import create_regional_latlon_grid
from legoesm.ocean.dynamics.ocean_model_latlon_cgrid import LatLonCGridOceanModel
from legoesm.ocean.eos import LinearEOSConfig
from legoesm.ocean.fidelity.compare import compare_field
from legoesm.ocean.fidelity.oceananigans_recipe import (
    oceananigans_canonical_ocean_config,
)
from legoesm.ocean.fidelity.oceananigans_runner import load_oceananigans_reference
from legoesm.ocean.init_latlon_cgrid import rest_state_latlon_cgrid_ocean
from legoesm.ocean.state import OceanSurfaceForcing
from legoesm.ocean.vertical import create_ocean_z_star

# --- Oceananigans barotropic_gyre parameters (validation/barotropic_gyre.jl) ---
NX = 60
NY = 60
LON_W, LON_E = -30.0, 30.0
LAT_S, LAT_N = 15.0, 75.0
H_DEPTH = 4000.0
G_REDUCED = 0.1
TAU0 = 1.0e-2                      # wind-stress amplitude [N/m^2]
PHI0 = 15.0
LPHI = LAT_N - LAT_S              # 60 deg
A_H = 5.0e3 * (60.0 / NX) ** 2   # nu_h0
MU_DRAG = 1.0 / (60.0 * 86400.0)  # linear bottom drag [1/s]
RHO0 = 1000.0                     # reference density [kg/m^3] (cfg.rho_0)


def build_gyre():
    grid, wall_mask = create_regional_latlon_grid(
        NY, NX, LAT_S, LAT_N, lon_west=LON_W, lon_east=LON_E, periodic_x=False)
    z_coord = create_ocean_z_star(n_levels=1, H_max=H_DEPTH)
    baro = os.environ.get("BARO_SOLVER", "implicit_cn")
    mom = os.environ.get("MOM_ADV", "vector_invariant")
    extra = {}
    if baro == "explicit_substep":
        # split-explicit free surface (closer to Oceananigans ImplicitFreeSurface
        # spin-up than implicit_cn); alpha=0 = no SSH-diffusion backstop.
        extra["barotropic_diffusion_alpha"] = float(
            os.environ.get("BARO_ALPHA", "0.0"))
        extra["barotropic_time_filter"] = os.environ.get("BARO_FILTER", "cosine")
        extra["n_barotropic_substeps"] = int(os.environ.get("BARO_SUBSTEPS", "30"))
    g_use = float(os.environ.get("G_OVERRIDE", str(G_REDUCED)))
    cfg = oceananigans_canonical_ocean_config(
        eos_linear=LinearEOSConfig(alpha_T=2.0e-4, beta_S=0.0),
        g=g_use, rho_0=1000.0,
        A_h=A_H, K_h=0.0,
        momentum_advection=mom,
        barotropic_solver=baro,
        bottom_drag_r=MU_DRAG,
        tracer_advection="centered",   # homogeneous: tracer inert
        **extra,
    )
    print(f"[cfg] baro={baro} mom={mom} extra={extra}", flush=True)
    state = rest_state_latlon_cgrid_ocean(grid, z_coord, land_mask_override=wall_mask)
    model = LatLonCGridOceanModel(grid, z_coord, cfg)
    return grid, wall_mask, state, model


def build_wind(grid):
    """cos wind stress tau_x(phi) = TAU0 cos(2pi (phi-PHI0)/LPHI).

    UNIT CONVENTION (the bridge's job): Oceananigans applies the wind as a
    ``FluxBoundaryCondition`` on the velocity field u, so its TAU0=1e-2 is a
    KINEMATIC stress [m^2/s^2] = tau_dynamic / rho_0 (the velocity equation is
    per-unit-mass; there is no rho in it).  legoESM's ``OceanSurfaceForcing.tau_x``
    is a DYNAMIC stress [N/m^2] that the model divides by rho_0 internally.  To
    deliver the IDENTICAL top-cell acceleration tau/(rho_0*H) we must pass the
    dynamic stress rho_0 * tau_kinematic.  Omitting this factor under-forces the
    gyre by exactly rho_0 (=1000x) -> a laminar ~3e-4 m/s flow instead of the
    oracle's O(1 m/s) western boundary current.

    Sign convention VALIDATED against the oracle: passing +ocean_stress (NOT the
    MITgcm-recipe negation) makes legoESM spin up the SAME gyre pattern as
    Oceananigans.  WIND_SIGN env overrides for re-checking the convention.
    """
    lat_deg = np.degrees(np.asarray(grid.lat))           # (n_lat+2,) incl wall rows
    tau_kin = TAU0 * np.cos(2 * np.pi * (lat_deg - PHI0) / LPHI)   # kinematic [m^2/s^2]
    ocean_tau = RHO0 * tau_kin                                     # -> dynamic [N/m^2]
    sign = float(os.environ.get("WIND_SIGN", "-1"))
    tau_x = jnp.asarray(np.broadcast_to(
        -sign * ocean_tau[:, None], lat_deg.shape + (NX + 2,)))
    return OceanSurfaceForcing(tau_x=tau_x, tau_y=jnp.zeros_like(tau_x))


def main():
    days = float(sys.argv[1]) if len(sys.argv) > 1 else 30.0
    dt = float(sys.argv[2]) if len(sys.argv) > 2 else 1800.0
    nsteps = int(round(days * 86400.0 / dt))

    grid, wall_mask, state, model = build_gyre()
    # Seed F_slow_{u,v}_prev: the canonical factory now defaults
    # barotropic_slow_forcing_ab2=True for the effective explicit_ab2 x
    # implicit_cn x ab2 combo (FE-Coriolis fix); the step raises on an
    # unseeded prev. No-op when the flag is off.
    state = model.seed_scan_carry(state, dt)
    wind = build_wind(grid)
    print(f"[legoESM gyre] {NY}x{NX}, g={G_REDUCED}, A_h={A_H:.0f}, "
          f"run {days}d @ dt={dt}s ({nsteps} steps)", flush=True)

    res = load_oceananigans_reference("barotropic_gyre")
    o_days = np.asarray(res.times_s) / 86400.0                # oracle snapshot days
    steps_per_day = max(1, int(round(86400.0 / dt)))

    step = jax.jit(lambda s: model.step(s, dt, surface_forcing=wind))
    # Run day-by-day; snapshot legoESM u at each oracle snapshot day; stop on NaN.
    lego_u_at_day: dict[int, np.ndarray] = {}
    last_finite_day = 0
    for day in range(1, int(days) + 1):
        for _ in range(steps_per_day):
            state = step(state)
        jax.block_until_ready(state.u.data)
        umax = float(jnp.max(jnp.abs(state.u.data)))
        etamax = float(jnp.max(jnp.abs(state.eta.data)))
        finite = bool(jnp.all(jnp.isfinite(state.u.data)))
        print(f"  day {day:3d}  max|u|={umax:.4e}  max|eta|={etamax:.4e}  "
              f"finite={finite}", flush=True)
        if not finite:
            print(f"  >>> legoESM blew at day {day}", flush=True)
            break
        last_finite_day = day
        if any(abs(day - od) < 0.5 for od in o_days):
            lego_u_at_day[day] = np.asarray(state.u.data)[1:NY + 1, 1:NX + 1, 0]

    # Compare at EVERY oracle-snapshot day legoESM reached (pattern corr is
    # amplitude-independent, so it tests whether legoESM spins up the SAME gyre
    # PATTERN even while its amplitude lags / before any late grid instability).
    common = sorted(d for d in lego_u_at_day
                    if any(abs(d - od) < 0.5 for od in o_days))
    if not common:
        print(f"\n>>> NO stable common snapshot (legoESM finite only to day "
              f"{last_finite_day}; oracle snapshots at {list(o_days)}).")
        return
    print("\n=== legoESM vs Oceananigans barotropic_gyre (surface u) ===")
    print("  day | pattern_corr |  nrmse  | lego max|u| | oracle max|u|")
    for d in common:
        o_idx = int(np.argmin([abs(d - od) for od in o_days]))
        u_l = lego_u_at_day[d]
        u_o = np.asarray(res.variables["u"])[o_idx][0][:, :NX]
        m = compare_field(u_l, u_o)
        print(f"  {d:3d} |   {m.pattern_corr:+.4f}    | {m.nrmse:.4f} | "
              f"{np.max(np.abs(u_l)):.3e}  |  {np.max(np.abs(u_o)):.3e}", flush=True)


if __name__ == "__main__":
    main()
