"""legoESM vs Oceananigans bickley_jet fidelity comparison (deterministic twin).

Both codes start from the IDENTICAL Bickley jet IC (U=sech^2 jet + a fixed
vortical perturbation) on a lat-lon periodic channel (unit sphere, rotation=1,
single free-surface layer), evolve with WENO-9 vector-invariant momentum, and
the relative vorticity field zeta is compared at matched times. This directly
tests the eddy-regime momentum advection (PR #559) -- the §5 residual's home --
without the wind/boundary-current/reduced-gravity pathologies of the gyre.

The Oceananigans reference is generated by
scripts/data/generate_oceananigans_bickley_jet_reference.jl. Point the runner at
it with $LEGOESM_OCEAN_FIDELITY_OCEANANIGANS_REF.
"""

from __future__ import annotations

import os
import sys

os.environ.setdefault("JAX_ENABLE_X64", "1")
os.environ.setdefault("JAX_PLATFORMS", "cpu")

import numpy as np
import jax
import jax.numpy as jnp

from legoesm.grids.latlon import create_regional_latlon_grid
from legoesm.ocean.dynamics.ocean_model_latlon_cgrid import LatLonCGridOceanModel
from legoesm.ocean.eos import LinearEOSConfig
from legoesm.ocean.fidelity.compare import compare_field
from legoesm.ocean.fidelity.oceananigans_recipe import (
    oceananigans_canonical_ocean_config,
)
from legoesm.ocean.fidelity.oceananigans_runner import load_oceananigans_reference
from legoesm.ocean.init_latlon_cgrid import rest_state_latlon_cgrid_ocean
from legoesm.ocean.vertical import create_ocean_z_star

NH = 64
NPHI = 32
RADIUS = 1.0
OMEGA = 1.0
G = 1.0
EPS, ELL, KK = 0.1, 0.5, 0.5


def _sech(x):
    return 1.0 / np.cosh(x)


def _U(y):
    return _sech(y) ** 2


def _psitilde(x, y):
    return np.exp(-(y + ELL / 10.0) ** 2 / (2 * ELL ** 2)) * np.cos(KK * x) * np.cos(KK * y)


def _utilde(x, y):
    return +_psitilde(x, y) * (KK * np.tan(KK * y) + y / ELL ** 2)


def _vtilde(x, y):
    return -_psitilde(x, y) * KK * np.tan(KK * x)


def _u_ic(lon_deg, lat_deg):
    x = np.radians(lon_deg) * 2.0
    y8 = np.radians(lat_deg) * 8.0
    return _U(y8) + EPS * _utilde(x, y8)


def _v_ic(lon_deg, lat_deg):
    x = np.radians(lon_deg) * 2.0
    y4 = np.radians(lat_deg) * 4.0
    return EPS * _vtilde(x, y4)


def build_bickley():
    grid, wall_mask = create_regional_latlon_grid(
        NPHI, NH, -80.0, 80.0, lon_west=-180.0, lon_east=180.0,
        periodic_x=True, radius=RADIUS, omega=OMEGA)
    z_coord = create_ocean_z_star(n_levels=1, H_max=1.0)
    cfg = oceananigans_canonical_ocean_config(
        eos_linear=LinearEOSConfig(alpha_T=2.0e-4, beta_S=0.0),
        g=G, rho_0=1000.0, A_h=0.0, K_h=0.0,
        momentum_advection=os.environ.get("MOM_ADV", "weno9"),
        # FAITHFUL eddy-regime config (matches Oceananigans' scheme TYPES):
        #  - coriolis_scheme="matsuno_split" = the MATCHED vertex-f Coriolis
        #    (closest to Oceananigans HydrostaticSphericalCoriolis EnstrophyConserving,
        #    f & zeta co-located at the FF vertex). The default explicit_ab2 4-point
        #    FACE-f average supports a rotational 2dx null mode that drives a
        #    SPURIOUS late-time enstrophy GROWTH; the matched form suppresses it
        #    (under-dissipation t12 4511->2992, bounce pushed t24->t30).
        #  - barotropic_solver="implicit_cn" = the ImplicitFreeSurface analog
        #    (backward-Euler theta=1.0 below); explicit_substep under-dissipates
        #    the roll-up. These are FAITHFUL scheme-type choices, NOT tuning.
        coriolis_scheme=os.environ.get("CORIOLIS_SCHEME", "matsuno_split"),
        barotropic_solver=os.environ.get("BARO_SOLVER", "implicit_cn"),
        bottom_drag_r=0.0, tracer_advection="weno7",
        weno_smoothness="split",
    )
    # ImplicitFreeSurface is fully implicit (backward Euler) -> theta=1.0.
    cfg = cfg._replace(barotropic=cfg.barotropic._replace(barotropic_implicit_theta_eta=1.0,
                       barotropic_implicit_theta_pgf=1.0),
                       vortcor_enstrophy_metric=os.environ.get("VORTCOR_METRIC", "0") == "1",
                       vortcor_reconstruct_zeta=os.environ.get("VORTCOR_ZETA", "0") == "1",
                       weno_divergence_smoothness=os.environ.get("WENO_DIV_SMOOTH") or None)
    # CRITICAL: match the Oceananigans z=(0,1) domain depth (H=1). The rest-state
    # bathymetry defaults to H_max=5500 m; leaving it would give a barotropic depth
    # H~5500 (gravity-wave speed sqrt(gH)~74 instead of 1) -> the free surface is
    # over-damped + explicit_substep is CFL-unstable. (Enstrophy is H-insensitive
    # so the eddy comparison didn't expose this; the geostrophic-adjustment test did.)
    state = rest_state_latlon_cgrid_ocean(grid, z_coord, land_mask_override=wall_mask,
                                          H_max=1.0)
    model = LatLonCGridOceanModel(grid, z_coord, cfg)
    return grid, wall_mask, z_coord, state, model


def set_bickley_ic(grid, state):
    """Set u (lon-face, lat-centre) and v (lon-centre, lat-face) to the IC."""
    lat_c = np.degrees(np.asarray(grid.lat))            # (n_lat,) cell centres
    lon_c = np.degrees(np.asarray(grid.lon))            # (n_lon,) cell centres
    dlon = lon_c[1] - lon_c[0]
    dlat = lat_c[1] - lat_c[0]
    lon_f = lon_c - dlon / 2.0                          # west faces
    lat_f = lat_c - dlat / 2.0                          # south faces
    u = np.asarray(state.u.data)                        # (n_lat, n_lon+1, 1)
    v = np.asarray(state.v.data)                        # (n_lat+1, n_lon, 1)
    nlat, nlonp1 = u.shape[0], u.shape[1]
    nlatp1, nlon = v.shape[0], v.shape[1]
    # u at (lat_c[i], lon_f[j])
    LATu, LONu = np.meshgrid(lat_c[:nlat], np.r_[lon_f, lon_f[:1] + 360.0][:nlonp1],
                             indexing="ij")
    u_new = _u_ic(LONu, LATu)[:, :, None]
    # v at (lat_f[i], lon_c[j])
    lat_f_ext = np.r_[lat_f, lat_f[-1:] + dlat][:nlatp1]
    LATv, LONv = np.meshgrid(lat_f_ext, lon_c[:nlon], indexing="ij")
    v_new = _v_ic(LONv, LATv)[:, :, None]
    return state._replace(
        u=state.u.replace(data=jnp.asarray(u_new)),
        v=state.v.replace(data=jnp.asarray(v_new)))


def main():
    stop = float(sys.argv[1]) if len(sys.argv) > 1 else 60.0
    grid, wall_mask, z_coord, state, model = build_bickley()
    state = set_bickley_ic(grid, state)
    # dt from the oracle CFL: 0.1 * dx_min / sqrt(g)
    dx_min = float(RADIUS * np.cos(np.radians(80.0)) * np.radians(360.0 / NH))
    dt = 0.1 * dx_min / np.sqrt(G)
    # Seed F_slow prev pair (factory defaults barotropic_slow_forcing_ab2 on
    # for the explicit_ab2 x implicit_cn x ab2 combo; no-op otherwise).
    state = model.seed_scan_carry(state, dt)
    nsteps = int(round(stop / dt))
    spd = max(1, nsteps // int(stop) if stop >= 1 else nsteps)
    print(f"[bickley] {NPHI}x{NH}, weno9, dt={dt:.4f}, stop={stop} ({nsteps} steps); "
          f"IC max|u|={float(jnp.max(jnp.abs(state.u.data))):.3f}", flush=True)

    res = load_oceananigans_reference("bickley_jet")
    o_times = np.asarray(res.times_s)
    print(f"[oracle] times={o_times}, zeta shape={res.variables['zeta'].shape}", flush=True)

    from legoesm.ocean.dynamics.latlon_cgrid_operators import curl_vertex_cgrid

    def lego_zeta_interior():
        z = np.asarray(curl_vertex_cgrid(state.u.data, state.v.data, grid))
        # zeta at vertices (n_lat+1, n_lon+1[,1]); match the oracle's (nlat_f, nlon_f).
        z = z[..., 0] if z.ndim == 3 else z
        return z

    o_zeta = np.asarray(res.variables["zeta"])          # (time, z, lat_f, lon_f)
    o_nlat_f, o_nlon_f = o_zeta.shape[2], o_zeta.shape[3]

    def enstrophy(z):
        return float(np.sum(z.astype(np.float64) ** 2))

    # Oracle enstrophy trajectory (statistical fidelity: does legoESM DECAY at
    # the same rate? pointwise pattern MUST decorrelate for chaotic turbulence).
    o_ens = {float(res.times_s[i]): enstrophy(o_zeta[i, 0]) for i in range(len(res.times_s))}

    step = jax.jit(lambda s: model.step(s, dt, surface_forcing=None))
    print("\n  t_oracle | corr(zeta) | lego_enstrophy | oracle_enstrophy | "
          "ens_ratio(lego/oracle)", flush=True)
    t = 0.0
    targets = [ot for ot in o_times if 0 < ot <= stop + 1e-9]
    ti = 0
    for it in range(1, nsteps + 1):
        state = step(state)
        t += dt
        if ti < len(targets) and t >= targets[ti] - dt / 2:
            if not bool(jnp.all(jnp.isfinite(state.u.data))):
                print(f"  t={t:.1f}  >>> legoESM blew", flush=True)
                break
            zl = lego_zeta_interior()
            # Alignment validated against the t=0 IC (corr 0.9999): legoESM
            # interior lat-vertices start at row 1 (skip the 1 wall row); lon
            # vertices 0:nlon_f match the oracle's periodic faces.
            o_idx = int(np.argmin([abs(targets[ti] - ot) for ot in o_times]))
            zo = o_zeta[o_idx, 0]
            zl_a = zl[1:1 + o_nlat_f, :o_nlon_f]
            m = compare_field(zl_a, zo)
            el = enstrophy(zl_a)
            eo = o_ens[float(o_times[o_idx])]
            print(f"   {targets[ti]:6.1f}  |  {m.pattern_corr:+.4f}   | "
                  f"{el:12.2f} | {eo:14.2f} | {el / eo:.3f}", flush=True)
            ti += 1
        if ti >= len(targets):
            break


if __name__ == "__main__":
    main()
